import type { Questao } from "@/domain/content/types";

type Row = [string, string, string, string, string, string, string];
const make = (disciplina: string, fonte: string, rows: Row[]): Questao[] => rows.map(([id, subtemaId, enunciado, correta, d1, d2, d3], n) => {
  const alvo = n % 4; const opcoes = [d1, d2, d3]; opcoes.splice(alvo, 0, correta);
  return { id, subtemaId, disciplinaId: disciplina, enunciado, alternativas: opcoes.map((texto, i) => ({ letra: String.fromCharCode(65 + i), texto, correta: i === alvo, comentario: i === alvo ? `Correta: ${correta}. A decisão deve ser integrada ao risco, à apresentação clínica e à diretriz aplicável.` : `Distrator: ${texto}. Essa alternativa não explica adequadamente o cenário descrito.` })), dificuldade: "intermediaria", estilo: "omed", tags: [disciplina, "omed-alto-rendimento", "lote-02"], fonte };
});

const FC = "SBC/ESC — diretrizes de cardiologia e emergências cardiovasculares; lote OMED revisado em 2026-08-03.";
export const QUESTOES_CARDIO_LOTE_02 = make("cardio", FC, [
  ["cardio-lote02-001", "cardio--sindrome-coronariana-aguda-sca-iam--diagnostico-e-conduta", "Após ECG com supra de ST e dor persistente, qual é a prioridade?", "Ativar estratégia de reperfusão imediata, preferindo angioplastia primária quando disponível em tempo adequado.", "Aguardar troponina para decidir", "Solicitar teste ergométrico", "Dar alta se a dor diminuir"],
  ["cardio-lote02-002", "cardio--sindrome-coronariana-aguda-sca-iam--diagnostico-e-conduta", "Na SCA sem supra, a estratificação de risco orienta:", "Tempo de estratégia invasiva, antitrombóticos e monitorização conforme risco isquêmico e hemorrágico.", "Repouso domiciliar universal", "Trombólise para todos", "Suspensão de estatina"],
  ["cardio-lote02-003", "cardio--insuficiencia-cardiaca-icfer-e-icfep--diagnostico-e-conduta", "Paciente com ICFEr sintomática deve receber terapia quádrupla quando elegível, incluindo:", "Bloqueio neuro-hormonal baseado em evidências e inibidor de SGLT2, com titulação e monitorização.", "Apenas digoxina", "Antibiótico contínuo", "Restrição hídrica isolada"],
  ["cardio-lote02-004", "cardio--insuficiencia-cardiaca-icfer-e-icfep--diagnostico-e-conduta", "Na descompensação congestiva, o diurético de alça serve principalmente para:", "Aliviar congestão e sintomas, sem substituir terapias prognósticas após estabilização.", "Curar a etiologia em todos", "Aumentar a volemia", "Tratar arritmia isoladamente"],
  ["cardio-lote02-005", "cardio--fibrilacao-atrial-bradiarritmias-e-leitura-de-ecg--diagnostico-e-conduta", "Em fibrilação atrial com instabilidade hemodinâmica, a conduta é:", "Cardioversão elétrica sincronizada imediata, com suporte e avaliação de anticoagulação.", "Somente betabloqueador oral", "Aguardar ecocardiograma", "Alta com aspirina"],
  ["cardio-lote02-006", "cardio--fibrilacao-atrial-bradiarritmias-e-leitura-de-ecg--diagnostico-e-conduta", "Em FA estável, a prevenção de AVC depende principalmente de:", "Escore de risco tromboembólico e decisão compartilhada sobre anticoagulação.", "Frequência cardíaca isolada", "Tamanho do átrio apenas", "Uso obrigatório de antiagregante"],
  ["cardio-lote02-007", "cardio--taquiarritmias-e-manejo-acls--diagnostico-e-conduta", "Taquicardia regular de QRS estreito e paciente estável pode ser tratada inicialmente com:", "Manobras vagais e adenosina quando não houver contraindicação e o ritmo for compatível.", "Desfibrilação não sincronizada", "Atropina", "Sulfato de magnésio em todos"],
  ["cardio-lote02-008", "cardio--taquiarritmias-e-manejo-acls--diagnostico-e-conduta", "Taquicardia ventricular sem pulso exige:", "RCP de alta qualidade e desfibrilação precoce conforme algoritmo de parada.", "Cardioversão sincronizada sem RCP", "Apenas verapamil", "Observação"],
  ["cardio-lote02-009", "cardio--pericardite-aguda-e-tamponamento--diagnostico-e-conduta", "O achado mais característico da pericardite aguda é:", "Dor pleurítica que melhora sentado e inclinado para frente, com possível atrito e alterações difusas no ECG.", "Dor que piora ao inclinar-se", "Supra localizado sempre", "Edema unilateral de perna"],
  ["cardio-lote02-010", "cardio--pericardite-aguda-e-tamponamento--diagnostico-e-conduta", "Tamponamento cardíaco com choque requer:", "Drenagem pericárdica urgente e suporte hemodinâmico, tratando a causa.", "Diurese agressiva", "Anticoagulação plena sempre", "Alta após analgesia"],
  ["cardio-lote02-011", "cardio--disseccao-aortica--diagnostico-e-conduta", "Dor torácica abrupta irradiada para dorso e assimetria de pulsos sugere:", "Síndrome aórtica aguda, com controle imediato de frequência/pressão e angioimagem adequada.", "Refluxo gastroesofágico simples", "Pneumonia sem avaliação", "Pericardite viral obrigatória"],
  ["cardio-lote02-012", "cardio--disseccao-aortica--diagnostico-e-conduta", "Na dissecção aórtica tipo A, a prioridade definitiva é:", "Avaliação cirúrgica emergente após estabilização inicial com betabloqueio quando possível.", "Trombólise sistêmica", "Teste ergométrico", "Alta com AINE"],
  ["cardio-lote02-013", "cardio--hipertensao-secundaria--diagnostico-e-conduta", "Hipertensão resistente com hipocalemia espontânea deve levantar suspeita de:", "Hiperaldosteronismo primário, com investigação hormonal após revisar medicamentos e condições do teste.", "Hipotireoidismo obrigatório", "Anemia ferropriva", "Arritmia isolada"],
  ["cardio-lote02-014", "cardio--dislipidemia-e-estatinas--diagnostico-e-conduta", "Após evento aterosclerótico, a estatina deve ser:", "De alta intensidade, com adesão e resposta lipídica monitoradas.", "Suspensa se o LDL cair", "Usada apenas em baixa dose", "Substituída por vitamina"],
  ["cardio-lote02-015", "cardio--doenca-arterial-periferica-e-claudicacao-intermitente--diagnostico-e-conduta", "Na claudicação intermitente, a abordagem inicial inclui:", "Cessação do tabagismo, exercício estruturado, controle de risco e antiagregação quando indicada.", "Repouso absoluto", "Corticoide crônico", "Antibiótico profilático"],
  ["cardio-lote02-016", "cardio--morte-subita-cardiaca-em-atletas-e-commotio-cordis--diagnostico-e-conduta", "Na parada cardíaca presenciada em atleta, a medida que mais aumenta sobrevida é:", "RCP imediata e desfibrilação precoce quando ritmo chocável.", "Aguardar equipe sem tocar no paciente", "Dar água", "Realizar ECG após 30 minutos"],
  ["cardio-lote02-017", "cardio--febre-reumatica-e-cardiopatia-reumatica-cronica--diagnostico-e-conduta", "A profilaxia secundária da febre reumática tem como objetivo:", "Prevenir novas infecções estreptocócicas e recorrência de lesão valvar.", "Tratar apenas dor articular", "Substituir ecocardiograma", "Suspender após uma dose"],
  ["cardio-lote02-018", "cardio--hipertensao-resistente-e-refrataria--diagnostico-e-conduta", "Antes de rotular hipertensão resistente, deve-se conferir:", "Adesão, técnica de medida, efeito do avental branco, substâncias e esquema farmacológico adequado.", "Apenas uma medida isolada", "Somente idade", "Dieta sem revisar medicamentos"],
  ["cardio-lote02-019", "cardio--fibrilacao-atrial-bradiarritmias-e-leitura-de-ecg--diagnostico-e-conduta", "Bradicardia sintomática com instabilidade pode exigir:", "Atropina e, se refratária, estimulação transcutânea/transvenosa conforme ACLS.", "Apenas adenosina", "Trombólise", "Diurético"],
  ["cardio-lote02-020", "cardio--sindrome-coronariana-aguda-sca-iam--diagnostico-e-conduta", "A troponina de alta sensibilidade deve ser interpretada:", "Com valores seriados, delta e contexto clínico, distinguindo lesão de infarto.", "Como diagnóstico isolado", "Sem considerar função renal", "Apenas pelo valor máximo"],
]);

const FN = "Academia Brasileira de Neurologia/AHA-ASA/ILAE — diretrizes de neurologia e emergências neurológicas; lote OMED revisado em 2026-08-03.";
export const QUESTOES_NEURO_LOTE_02 = make("neuro", FN, [
  ["neuro-lote02-001", "neuro--avc-isquemico--diagnostico-e-conduta", "No AVC isquêmico agudo, a TC sem contraste tem como objetivo imediato:", "Excluir hemorragia e avaliar extensão inicial antes de reperfusão.", "Confirmar sempre a área isquêmica", "Medir pressão intracraniana diretamente", "Substituir exame neurológico"],
  ["neuro-lote02-002", "neuro--avc-isquemico--diagnostico-e-conduta", "A trombólise intravenosa é considerada após:", "Confirmar elegibilidade clínica, janela temporal, ausência de hemorragia e contraindicações.", "Qualquer déficit com mais de 48 horas", "TC mostrando hemorragia", "Uso recente de anticoagulante sem checagem"],
  ["neuro-lote02-003", "neuro--avc-isquemico--diagnostico-e-conduta", "Na oclusão de grande vaso, a trombectomia:", "Pode beneficiar pacientes selecionados por imagem e janela clínica ampliada.", "É proibida após seis horas em todos", "Substitui suporte básico", "É indicada sem angioimagem"],
  ["neuro-lote02-004", "neuro--avc-hemorragico-hsa-e-hemorragia-intraparenquimatosa--diagnostico-e-conduta", "Na HSA aneurismática, a prioridade é:", "Identificar e tratar o aneurisma, controlar complicações e prevenir vasoespasmo/isquemia tardia.", "Trombólise", "Alta sem angiografia", "Apenas analgésico"],
  ["neuro-lote02-005", "neuro--avc-hemorragico-hsa-e-hemorragia-intraparenquimatosa--diagnostico-e-conduta", "Em hemorragia intracerebral associada à varfarina, deve-se:", "Suspender e reverter anticoagulação rapidamente conforme protocolo e gravidade.", "Administrar mais varfarina", "Trombólise", "Aguardar normalização espontânea"],
  ["neuro-lote02-006", "neuro--crise-convulsiva-e-status-epilepticus--diagnostico-e-conduta", "No status epiléptico, glicemia capilar deve ser verificada:", "Imediatamente, corrigindo hipoglicemia sem atrasar anticonvulsivante quando indicado.", "Somente após EEG", "Apenas no dia seguinte", "Nunca em adulto"],
  ["neuro-lote02-007", "neuro--crise-convulsiva-e-status-epilepticus--diagnostico-e-conduta", "Crise focal com alteração da consciência persistente deve ser:", "Tratada como emergência quando prolongada, com benzodiazepínico e segunda linha se necessário.", "Observada sem monitorização", "Tratada com antibiótico", "Encerrada com contenção física"],
  ["neuro-lote02-008", "neuro--cefaleias-primarias-e-sinais-de-alarme--diagnostico-e-conduta", "Cefaleia em trovoada exige:", "Investigação urgente para HSA e outras causas secundárias, mesmo se o exame inicial for normal.", "Diagnóstico automático de enxaqueca", "Apenas hidratação domiciliar", "Nenhum exame"],
  ["neuro-lote02-009", "neuro--cefaleias-primarias-e-sinais-de-alarme--diagnostico-e-conduta", "Enxaqueca com aura típica apresenta:", "Sintomas neurológicos reversíveis, graduais e seguidos por cefaleia em parte dos episódios.", "Déficit fixo progressivo", "Febre e rigidez de nuca", "Perda de consciência prolongada"],
  ["neuro-lote02-010", "neuro--hipertensao-intracraniana-e-delirium--diagnostico-e-conduta", "Papiledema bilateral sugere:", "Aumento da pressão intracraniana e necessidade de investigar causa antes de punção lombar.", "Desidratação isolada", "Enxaqueca simples obrigatória", "Doença ocular externa"],
  ["neuro-lote02-011", "neuro--sindrome-de-guillain-barre--diagnostico-e-conduta", "Na síndrome de Guillain-Barré, o risco imediato mais importante é:", "Falência respiratória e disautonomia, exigindo monitorização seriada.", "Hiperglicemia isolada", "Icterícia", "Artrite periférica"],
  ["neuro-lote02-012", "neuro--sindrome-de-guillain-barre--diagnostico-e-conduta", "Tratamentos com benefício comprovado no Guillain-Barré incluem:", "Imunoglobulina intravenosa ou plasmaférese, sem associação rotineira entre ambas.", "Corticoide isolado", "Antibiótico de amplo espectro", "Repouso sem suporte"],
  ["neuro-lote02-013", "neuro--miastenia-gravis--diagnostico-e-conduta", "Na crise miastênica, a prioridade é:", "Avaliar e proteger ventilação, tratar precipitante e iniciar terapia específica em ambiente monitorado.", "Aumentar sedativos", "Proibir avaliação respiratória", "Dar apenas analgésico"],
  ["neuro-lote02-014", "neuro--miastenia-gravis--diagnostico-e-conduta", "Ptose flutuante e fatigabilidade sugerem:", "Miastenia gravis, devendo procurar fraqueza ocular/bulbar e sinais de crise.", "AVC hemorrágico obrigatório", "Neuropatia sensitiva pura", "Meningite sempre"],
  ["neuro-lote02-015", "neuro--compressao-medular-aguda-e-sindrome-de-cauda-equina--diagnostico-e-conduta", "Dor lombar com anestesia em sela e retenção urinária exige:", "Avaliação emergente para síndrome da cauda equina e descompressão quando indicada.", "Apenas fisioterapia", "Alta com AINE", "Ressonância após meses"],
  ["neuro-lote02-016", "neuro--encefalopatia-de-wernicke-korsakoff--diagnostico-e-conduta", "Em paciente desnutrido com confusão, ataxia e oftalmoparesia, deve-se:", "Administrar tiamina antes de glicose quando possível e tratar como emergência.", "Dar glicose isolada primeiro sempre", "Aguardar ressonância", "Usar somente antipsicótico"],
  ["neuro-lote02-017", "neuro--sindromes-vestibulares--diagnostico-e-conduta", "Vertigem aguda contínua com déficit neurológico focal sugere:", "Evento central, exigindo investigação de circulação posterior e não apenas manobra periférica.", "VPPB simples obrigatória", "Otite externa", "Ansiedade sem exame"],
  ["neuro-lote02-018", "neuro--neurossifilis--diagnostico-e-conduta", "Suspeita de neurossífilis depende de:", "Manifestações neurológicas/oculares e avaliação sérica e liquórica integrada.", "VDRL sérico isolado sempre", "Apenas lesão cutânea", "Nenhum exame do líquor"],
  ["neuro-lote02-019", "neuro--amnesias-e-sindromes-demenciais--diagnostico-e-conduta", "Avaliação inicial de declínio cognitivo inclui:", "História funcional, exame cognitivo, medicamentos, causas reversíveis e exame neurológico.", "Somente ressonância", "Apenas teste de memória", "Diagnóstico sem informante"],
  ["neuro-lote02-020", "neuro--hipertensao-intracraniana-e-delirium--diagnostico-e-conduta", "Delirium é definido por:", "Alteração aguda e flutuante da atenção e consciência, geralmente por causa médica subjacente.", "Declínio estável de anos", "Psicose primária obrigatória", "Apenas tristeza"],
]);

const FP = "SBPT/ERS/ATS — diretrizes de pneumologia, infecções respiratórias e ventilação; lote OMED revisado em 2026-08-03.";
export const QUESTOES_PNEUMO_LOTE_02 = make("pneumo", FP, [
  ["pneumo-lote02-001", "pneumo--pneumonia-adquirida-na-comunidade-pac--diagnostico-e-conduta", "Na PAC, a gravidade deve ser estimada para decidir:", "Local de cuidado, necessidade de suporte e esquema antimicrobiano adequado.", "Somente pelo agente isolado", "Apenas pela idade", "Sem examinar sinais vitais"],
  ["pneumo-lote02-002", "pneumo--pneumonia-adquirida-na-comunidade-pac--diagnostico-e-conduta", "Em PAC grave com choque, antibiótico deve ser:", "Iniciado precocemente após culturas quando isso não causar atraso relevante.", "Adiado até cultura final", "Substituído por corticoide", "Oral em dose mínima sempre"],
  ["pneumo-lote02-003", "pneumo--asma-cronica-e-crise-aguda--diagnostico-e-conduta", "Na crise asmática grave, o tratamento inicial inclui:", "Broncodilatador inalatório repetido, corticoide sistêmico precoce e oxigênio titulado.", "Apenas antibiótico", "Sedação profunda de rotina", "Suspender monitorização"],
  ["pneumo-lote02-004", "pneumo--asma-cronica-e-crise-aguda--diagnostico-e-conduta", "Uso frequente de broncodilatador de resgate indica:", "Controle inadequado e necessidade de revisar adesão, técnica, gatilhos e terapia controladora.", "Boa estabilidade sempre", "Cura da asma", "Indicação de suspender corticoide inalatório"],
  ["pneumo-lote02-005", "pneumo--dpoc-cronico-e-exacerbado--diagnostico-e-conduta", "Na exacerbação de DPOC, o oxigênio deve ser:", "Titulado para evitar hiperóxia e manter alvo individualizado, frequentemente 88–92%.", "Administrado no fluxo máximo", "Evitado sempre", "Substituído por nitrogênio"],
  ["pneumo-lote02-006", "pneumo--dpoc-cronico-e-exacerbado--diagnostico-e-conduta", "Ventilação não invasiva na DPOC é especialmente útil em:", "Acidose respiratória hipercápnica com esforço, se não houver contraindicação.", "Todo paciente assintomático", "Hemoptise maciça", "Parada cardiorrespiratória"],
  ["pneumo-lote02-007", "pneumo--tromboembolismo-pulmonar-tep--diagnostico-e-conduta", "D-dímero é mais útil quando:", "A probabilidade pré-teste é baixa ou intermediária e um resultado negativo pode excluir TEP.", "O paciente está em choque", "A probabilidade é alta e a imagem é impossível", "Para monitorar resposta à heparina"],
  ["pneumo-lote02-008", "pneumo--tromboembolismo-pulmonar-tep--diagnostico-e-conduta", "TEP com choque obstrutivo pode exigir:", "Reperfusão sistêmica ou intervenção dirigida, além de suporte e anticoagulação quando possível.", "Apenas observação", "Diurético isolado", "Antibiótico sem anticoagulação"],
  ["pneumo-lote02-009", "pneumo--pneumotorax-espontaneo-e-hipertensivo--diagnostico-e-conduta", "Pneumotórax hipertensivo com instabilidade deve ser tratado por:", "Descompressão imediata, seguida de drenagem torácica, sem aguardar radiografia.", "Tomografia antes de intervir", "Apenas oxigênio", "Punção lombar"],
  ["pneumo-lote02-010", "pneumo--pneumotorax-espontaneo-e-hipertensivo--diagnostico-e-conduta", "No pneumotórax espontâneo primário pequeno e estável, pode-se:", "Considerar observação/oxigênio e seguimento conforme tamanho, sintomas e protocolo local.", "Drenar todos obrigatoriamente", "Intubar sempre", "Dar antibiótico por 30 dias"],
  ["pneumo-lote02-011", "pneumo--derrame-pleural--diagnostico-e-conduta", "Derrame pleural com pH baixo e loculações sugere:", "Complicação infecciosa com necessidade de drenagem e avaliação de controle de foco.", "Transudato simples", "Apenas observação", "Diurese como única medida"],
  ["pneumo-lote02-012", "pneumo--tuberculose-pulmonar-com-hiv--diagnostico-e-conduta", "Em TB pulmonar com HIV, o diagnóstico deve usar:", "Teste rápido molecular/cultura e avaliação de resistência, sem esquecer formas extrapulmonares.", "Apenas radiografia normal", "Sorologia isolada", "Antibiótico comum"],
  ["pneumo-lote02-013", "pneumo--tuberculose-pulmonar-com-hiv--diagnostico-e-conduta", "Em TB/HIV, o início da terapia antirretroviral:", "É planejado durante o tratamento da TB conforme gravidade e risco de síndrome inflamatória de reconstituição.", "É sempre proibido", "Substitui esquema antituberculoso", "Deve ocorrer antes de qualquer avaliação"],
  ["pneumo-lote02-014", "pneumo--disturbios-acido-base-e-interpretacao-de-gasometria--diagnostico-e-conduta", "Gasometria com pH baixo e PaCO2 alto indica:", "Acidose respiratória, cuja compensação e tempo de instalação devem ser avaliados.", "Alcalose respiratória pura", "Acidose metabólica isolada", "Resultado impossível"],
  ["pneumo-lote02-015", "pneumo--disturbios-acido-base-e-interpretacao-de-gasometria--diagnostico-e-conduta", "Na acidose metabólica com ânion gap elevado, deve-se:", "Buscar causas como lactato, cetoácidos, insuficiência renal e toxinas, além de tratar o gatilho.", "Dar bicarbonato a todos", "Ignorar glicemia", "Diagnosticar DPOC"],
  ["pneumo-lote02-016", "pneumo--tosse-cronica-e-tosse-por-ieca--diagnostico-e-conduta", "Tosse crônica em adulto deve ser investigada inicialmente com:", "História de tabaco/medicações, exame físico e radiografia, direcionando causas comuns.", "Tomografia para todos sem avaliação", "Antibiótico indefinido", "Corticoide sem diagnóstico"],
  ["pneumo-lote02-017", "pneumo--asma-e-pneumopatia-ocupacional--diagnostico-e-conduta", "Asma relacionada ao trabalho exige:", "Comparar sintomas e função pulmonar nos dias de trabalho e afastamento, além de controlar exposição.", "Manter exposição sem proteção", "Diagnosticar por IgE isolada", "Ignorar ambiente ocupacional"],
  ["pneumo-lote02-018", "pneumo--dpoc-cronico-e-exacerbado--diagnostico-e-conduta", "Reabilitação pulmonar na DPOC melhora:", "Capacidade funcional, dispneia e qualidade de vida, integrando cessação do tabagismo.", "Apenas radiografia", "Somente PaCO2", "Risco infeccioso necessariamente"],
  ["pneumo-lote02-019", "pneumo--pneumonia-adquirida-na-comunidade-pac--diagnostico-e-conduta", "Na pneumonia aspirativa, a escolha antimicrobiana depende de:", "Gravidade, contexto de aspiração, flora provável e risco de patógenos resistentes.", "Cobertura anaeróbia máxima em todos", "Nenhum antibiótico em choque", "Somente antifúngico"],
  ["pneumo-lote02-020", "pneumo--tromboembolismo-pulmonar-tep--diagnostico-e-conduta", "Anticoagulação no TEP deve considerar:", "Probabilidade diagnóstica, risco de sangramento, função renal, gravidez e possibilidade de procedimento.", "Apenas peso corporal", "Somente saturação", "Sempre aspirina"],
]);
