import type { Questao } from "@/domain/content/types";

/**
 * Questões inéditas — hematologia.
 * Gerado por scripts/gerar-conteudo.mts. Cada alternativa tem comentário próprio:
 * a errada explica por que está errada, não repete a justificativa da certa.
 */
export const QUESTOES_HEMATO: Questao[] = [
  {
    id: "hemato-001",
    subtemaId: "hemato--anemias--investigacao-e-classificacao",
    disciplinaId: "hemato",
    enunciado: "Mulher de 54 anos, com artrite reumatoide em atividade, refere fadiga progressiva. Exames: Hb 9,6 g/dL, VCM 77 fL, RDW 17,4%, contagem de hemácias 3,6 milhões/µL, ferritina 88 ng/mL, ferro sérico 22 µg/dL, saturação de transferrina 8%, TIBC no limite inferior da normalidade, receptor solúvel de transferrina elevado, PCR e VHS elevadas. Qual a interpretação mais adequada do quadro?",
    alternativas: [
      { letra: "A", texto: "Anemia de doença crônica isolada, sem necessidade de investigar ferropenia", correta: false, comentario: "Na doença crônica pura o RDW tende a ser normal e, sobretudo, o receptor solúvel de transferrina permanece NORMAL, porque não é reagente de fase aguda e reflete a real carência de ferro nas células. Aqui ele está elevado, junto de RDW de 17,4% e saturação de apenas 8% — achados que não se explicam apenas pelo sequestro de ferro mediado por hepcidina." },
      { letra: "B", texto: "Deficiência de ferro associada à anemia de doença crônica, apesar da ferritina aparentemente normal", correta: true, comentario: "Correta. A ferritina é proteína de fase aguda e, na inflamação ativa, valores de até cerca de 100 ng/mL não excluem ferropenia. O conjunto microcitose com RDW elevado, saturação de transferrina de 8% e, decisivamente, receptor solúvel de transferrina elevado (marcador não influenciado pela fase aguda) caracteriza deficiência de ferro sobreposta à anemia inflamatória — cenário que exige reposição de ferro e busca da fonte de perda, além de controlar a doença de base." },
      { letra: "C", texto: "Traço beta-talassêmico, sugerido pela microcitose desproporcional à anemia", correta: false, comentario: "O traço talassêmico cursa com RDW NORMAL (população eritrocitária homogênea) e contagem de hemácias normal ou aumentada, com índice de Mentzer menor que 13. Nesta paciente o RDW é de 17,4% e as hemácias estão em 3,6 milhões/µL, resultando em Mentzer acima de 13 — padrão oposto ao da talassemia. Além disso, a talassemia não altera a saturação de transferrina, que aqui está em 8%." },
      { letra: "D", texto: "Anemia sideroblástica, justificada pela microcitose com ferritina preservada", correta: false, comentario: "A anemia sideroblástica cursa com ferro sérico ALTO, saturação de transferrina ALTA e ferritina francamente elevada, porque o ferro chega à célula mas não é incorporado à protoporfirina, acumulando-se nas mitocôndrias perinucleares (sideroblastos em anel). O achado de ferro sérico 22 µg/dL com saturação de 8% é exatamente o inverso desse perfil e afasta a hipótese." },
    ],
    dificuldade: "avancada",
    estilo: "caso",
    tags: ["anemia ferropriva", "anemia de doenca cronica", "receptor soluvel de transferrina", "cinetica do ferro", "ferritina"],
  },
  {
    id: "hemato-002",
    subtemaId: "hemato--anemias--investigacao-e-classificacao",
    disciplinaId: "hemato",
    enunciado: "Homem de 68 anos, com gastrite atrófica conhecida e uso crônico de metformina, apresenta parestesias simétricas em pés há três meses, marcha instável e perda de sensibilidade vibratória. Hemograma: Hb 9,4 g/dL, VCM 116 fL, plaquetas e leucócitos no limite inferior; esfregaço com neutrófilos hipersegmentados. Vitamina B12 = 210 pg/mL e ácido fólico sérico normal. Está hemodinamicamente estável. Qual a conduta mais adequada?",
    alternativas: [
      { letra: "A", texto: "Iniciar ácido fólico 5 mg/dia e reavaliar o hemograma em 30 dias", correta: false, comentario: "É justamente a conduta mais perigosa neste caso. O folato restaura a síntese de DNA e corrige a anemia e a macrocitose, dando falsa impressão de sucesso, mas não corrige o bloqueio da via da metilmalonil-CoA: a degeneração combinada subaguda da medula espinhal continua progredindo e pode se tornar irreversível. Em macrocitose com sintomas neurológicos, folato isolado nunca é a resposta." },
      { letra: "B", texto: "Iniciar reposição de cobalamina imediatamente e solicitar ácido metilmalônico e homocisteína para confirmação, além de anticorpo anti-fator intrínseco", correta: true, comentario: "Correta. Com B12 na faixa indeterminada (200–300 pg/mL) mas quadro clínico e hematológico altamente sugestivo, não se posterga o tratamento: a lesão neurológica é tempo-dependente. O ácido metilmalônico eleva-se apenas na deficiência de B12 (a homocisteína sobe nas duas deficiências), confirmando o diagnóstico mesmo com dosagem sérica limítrofe, e o anti-fator intrínseco é o marcador específico da anemia perniciosa, contexto coerente com a gastrite atrófica. Deve-se ainda monitorar potássio nos primeiros dias da resposta eritropoética." },
      { letra: "C", texto: "Transfundir concentrado de hemácias para correção rápida da anemia antes de qualquer investigação", correta: false, comentario: "A anemia é crônica, com Hb de 9,4 g/dL e paciente hemodinamicamente estável, muito acima do gatilho transfusional restritivo de 7 g/dL (8 g/dL em contextos cardiovasculares selecionados). Transfundir aqui não traz benefício, expõe a riscos de sobrecarga volêmica e reação transfusional e ainda pode dificultar a interpretação dos exames diagnósticos subsequentes." },
      { letra: "D", texto: "Solicitar mielograma com biópsia de medula óssea antes de iniciar qualquer reposição", correta: false, comentario: "O exame medular na anemia megaloblástica mostraria alterações compatíveis, mas é dispensável quando o quadro clínico, o esfregaço com neutrófilos hipersegmentados e a dosagem vitamínica já direcionam o diagnóstico. Ele fica reservado para citopenias inexplicadas, suspeita de mielodisplasia ou infiltração medular, e sua realização atrasaria uma reposição cujo retardo custa função neurológica definitiva." },
    ],
    dificuldade: "avancada",
    estilo: "conduta",
    tags: ["anemia megaloblastica", "vitamina B12", "acido metilmalonico", "anemia perniciosa", "degeneracao combinada subaguda"],
  },
  {
    id: "hemato-003",
    subtemaId: "hemato--anemias--investigacao-e-classificacao",
    disciplinaId: "hemato",
    enunciado: "Adolescente de 15 anos com icterícia intermitente desde a infância, esplenomegalia e colecistectomia por litíase aos 13 anos. Pai com história semelhante. Exames: Hb 10,2 g/dL, VCM 84 fL, CHCM 37,2 g/dL, reticulócitos 8% (IPR elevado), LDH elevada, bilirrubina indireta elevada, haptoglobina indetectável; esfregaço com numerosos esferócitos; teste de antiglobulina direta (Coombs direto) NEGATIVO. Qual exame confirma melhor a hipótese diagnóstica?",
    alternativas: [
      { letra: "A", texto: "Citometria de fluxo com ligação de eosina-5-maleimida (EMA)", correta: true, comentario: "Correta. O conjunto hemólise crônica familiar, esferócitos, CHCM acima de 36 g/dL e Coombs direto negativo define esferocitose hereditária. As diretrizes hematológicas atuais recomendam como triagem preferencial a citometria de fluxo com ligação de eosina-5-maleimida, que avalia as proteínas de membrana eritrocitária, isolada ou combinada ao teste de lise em glicerol acidificado, por apresentarem melhor acurácia que os métodos clássicos." },
      { letra: "B", texto: "Teste de fragilidade osmótica em solução salina hipotônica", correta: false, comentario: "É o exame classicamente citado em materiais antigos, e de fato está alterado na doença, mas foi deslocado da primeira linha por sensibilidade e especificidade inferiores: pode ser normal em formas leves e falso-positivo em outras condições com esferócitos, como a hemólise autoimune. Não é hoje o exame que melhor confirma o diagnóstico, embora ainda seja usado onde os métodos preferenciais não estão disponíveis." },
      { letra: "C", texto: "Eletroforese de hemoglobinas com quantificação de HbA2 e HbF", correta: false, comentario: "A eletroforese investiga hemoglobinopatias qualitativas e quantitativas, como as talassemias e a doença falciforme, cujo esfregaço mostraria células em alvo ou drepanócitos e cuja microcitose seria desproporcional à anemia. Nada disso ocorre aqui: o VCM é normal, o CHCM está elevado e a alteração morfológica é o esferócito, que traduz defeito de membrana, não de síntese de globina." },
      { letra: "D", texto: "Teste de antiglobulina indireta (Coombs indireto) e pesquisa de crioaglutininas", correta: false, comentario: "Esses exames pesquisam anticorpos livres no plasma e aglutininas frias, úteis quando se suspeita de hemólise imune ou em incompatibilidade transfusional. O Coombs direto já veio negativo, o que afasta anticorpos ou complemento fixados à superfície da hemácia e, portanto, torna improvável a origem imune; a história familiar de longa data reforça um defeito corpuscular hereditário, e não um processo autoimune adquirido." },
    ],
    dificuldade: "intermediaria",
    estilo: "exame",
    tags: ["esferocitose hereditaria", "anemia hemolitica", "coombs direto", "CHCM", "eosina-5-maleimida"],
  },
  {
    id: "hemato-004",
    subtemaId: "hemato--leucemias--agudas-e-cronicas",
    disciplinaId: "hemato",
    enunciado: "Mulher de 34 anos procura o pronto-socorro com equimoses extensas, gengivorragia e epistaxe há 4 dias, além de astenia progressiva. Exame: palidez, petéquias em membros inferiores, sem adenomegalia ou esplenomegalia. Hemograma: Hb 7,8 g/dL, leucócitos 2.100/mm³ com 38% de células granulares atípicas de núcleo irregular, algumas contendo feixes de bastonetes de Auer, plaquetas 18.000/mm³. Coagulograma: fibrinogênio 88 mg/dL, INR 1,8, D-dímero muito elevado. Cariótipo e FISH foram solicitados e o resultado sairá em 48 horas. Qual a conduta mais adequada neste momento?",
    alternativas: [
      { letra: "A", texto: "Aguardar o resultado do FISH para t(15;17) antes de iniciar qualquer terapia antileucêmica específica, mantendo apenas suporte transfusional.", correta: false, comentario: "É exatamente a conduta que mata esta paciente. A mortalidade precoce na leucemia promielocítica aguda é hemorrágica e ocorre nas primeiras horas a dias; esperar 48 horas por um exame genético em quem já tem morfologia sugestiva, fibrinogênio de 88 mg/dL e sangramento ativo é retardo injustificável. O ATRA é seguro o bastante para ser iniciado na suspeita e suspenso depois, caso a hipótese não se confirme." },
      { letra: "B", texto: "Iniciar imediatamente ATRA (ácido all-trans-retinoico) associado a suporte transfusional agressivo com crioprecipitado/fibrinogênio e plaquetas, sem aguardar a confirmação genética.", correta: true, comentario: "Conduta correta. O conjunto sangramento desproporcional à plaquetometria, promielócitos atípicos com feixes de bastonetes de Auer, fibrinogênio baixo, INR alargado e D-dímero elevado configura leucemia promielocítica aguda com CIVD e hiperfibrinólise, a única emergência hematológica em que se inicia a terapia-alvo antes do diagnóstico genético. O ATRA reverte rapidamente a coagulopatia ao induzir diferenciação, e o suporte deve manter fibrinogênio acima de 100 a 150 mg/dL e plaquetas acima de 30.000 a 50.000/mm³, reavaliados ao menos diariamente." },
      { letra: "C", texto: "Indicar leucaférese de urgência para citorredução antes de qualquer terapia específica, pelo risco de leucostase.", correta: false, comentario: "Duplamente equivocada neste caso. A paciente tem leucócitos de 2.100/mm³, ou seja, leucopenia, e não há qualquer substrato para leucostase, que exige hiperleucocitose com sintomas neurológicos ou respiratórios. Além disso, a leucaférese é especificamente contraindicada na leucemia promielocítica aguda, mesmo quando a leucometria é alta, porque agrava a coagulopatia e aumenta a mortalidade hemorrágica." },
      { letra: "D", texto: "Iniciar quimioterapia de indução padrão no esquema 7+3 com citarabina e daunorrubicina, como em qualquer leucemia mieloide aguda.", correta: false, comentario: "Trata a promielocítica como se fosse uma LMA comum e desperdiça o que há de mais eficaz nesta doença. A LPA é a exceção terapêutica dentro das LMA: o tratamento se organiza em torno de ATRA e trióxido de arsênio, sendo possível curar a maioria dos casos de risco não alto sem quimioterapia citotóxica. O antracíclico só é acrescentado no alto risco, definido por leucócitos acima de 10.000/mm³, o que não é o caso aqui." },
    ],
    dificuldade: "avancada",
    estilo: "conduta",
    tags: ["leucemia promielocítica aguda", "LPA", "t(15;17)", "PML-RARA", "ATRA", "CIVD", "emergência hematológica"],
  },
  {
    id: "hemato-005",
    subtemaId: "hemato--leucemias--agudas-e-cronicas",
    disciplinaId: "hemato",
    enunciado: "Homem de 68 anos, hipertenso controlado, assintomático, realiza exames de rotina. Hemograma: Hb 13,8 g/dL, leucócitos 82.000/mm³ com 88% de linfócitos de aspecto pequeno e maduro, plaquetas 214.000/mm³. O esfregaço mostra numerosas manchas de Gumprecht. Ao exame físico há linfonodos cervicais e axilares móveis, indolores, de até 1,5 cm, sem esplenomegalia. Não há febre, sudorese noturna nem perda de peso. A imunofenotipagem do sangue periférico revela população B monoclonal CD5+, CD19+, CD23+, com CD20 e imunoglobulina de superfície fracos e restrição de cadeia leve kappa. Qual a conduta?",
    alternativas: [
      { letra: "A", texto: "Iniciar imediatamente quimioimunoterapia com fludarabina, ciclofosfamida e rituximabe, pois a leucometria acima de 50.000/mm³ configura doença de alto risco.", correta: false, comentario: "Parte de uma premissa falsa: na leucemia linfocítica crônica a contagem absoluta de linfócitos, isoladamente e por mais alta que seja, não é critério de tratamento. Diferente da leucemia mieloide crônica ou da LMA, aqui não há risco relevante de leucostase mesmo com valores elevados. Além disso, o esquema FCR deixou de ser a primeira linha preferencial, tendo sido substituído por terapia-alvo na maioria dos cenários." },
      { letra: "B", texto: "Manter observação vigilante, com exame físico e hemograma seriados, reservando tratamento para quando surgirem critérios do iwCLL.", correta: true, comentario: "Conduta correta. O paciente preenche os critérios diagnósticos de LLC, mas está em estádio inicial (Rai 0 a I, Binet A), sem anemia, plaquetopenia, massa sintomática, sintomas B ou citopenia autoimune. Estudos consistentes mostram que tratar a LLC assintomática precocemente não prolonga a sobrevida e expõe o paciente à toxicidade, de modo que a estratégia estabelecida é a observação vigilante até que se cumpra alguma indicação formal, como falência medular progressiva, adenomegalia ou esplenomegalia sintomática ou tempo de duplicação linfocitária inferior a 6 meses." },
      { letra: "C", texto: "Iniciar acalabrutinibe de forma imediata para reduzir o risco de transformação de Richter.", correta: false, comentario: "A intenção é boa, mas a premissa não se sustenta: não existe evidência de que iniciar terapia-alvo em paciente assintomático previna a transformação de Richter, que ocorre em uma minoria dos casos e não tem profilaxia farmacológica estabelecida. Antecipar o inibidor de BTK apenas expõe o paciente a fibrilação atrial, sangramento, hipertensão e custo, sem ganho demonstrado enquanto não houver indicação formal de tratar." },
      { letra: "D", texto: "Solicitar biópsia de medula óssea para confirmar o diagnóstico antes de definir qualquer conduta, pois a citometria de fluxo periférica é insuficiente.", correta: false, comentario: "Erra no método diagnóstico. A LLC é uma das poucas neoplasias hematológicas que se diagnostica sem punção medular: bastam linfócitos B clonais em número igual ou superior a 5.000/mm³ no sangue periférico com o imunofenótipo característico, exatamente o que já está documentado aqui. O estudo medular fica reservado a situações específicas, como esclarecer a origem de uma citopenia, e não muda a decisão de observar este paciente." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["leucemia linfocítica crônica", "LLC", "smudge cells", "iwCLL", "observação vigilante", "CD5 CD23"],
  },
  {
    id: "hemato-006",
    subtemaId: "hemato--leucemias--agudas-e-cronicas",
    disciplinaId: "hemato",
    enunciado: "Adolescente de 16 anos com diagnóstico recente de leucemia linfoblástica aguda de células B, leucometria inicial de 190.000/mm³, LDH muito elevado e hepatoesplenomegalia, inicia quimioterapia de indução. Quarenta e oito horas depois evolui com oligúria e náuseas. Exames: creatinina 2,6 mg/dL (basal 0,9), potássio 6,4 mEq/L, fósforo 7,2 mg/dL, cálcio corrigido 6,7 mg/dL (assintomático, sem alterações eletrocardiográficas de hipocalcemia), ácido úrico 12,4 mg/dL. Qual a conduta mais adequada?",
    alternativas: [
      { letra: "A", texto: "Hidratação endovenosa vigorosa, rasburicase para reduzir o ácido úrico já formado, tratamento da hipercalemia e não reposição de cálcio na hipocalcemia assintomática.", correta: true, comentario: "Conduta correta. O quadro preenche critérios de síndrome de lise tumoral clínica de Cairo-Bishop, com hiperuricemia, hipercalemia, hiperfosfatemia, hipocalcemia e lesão renal aguda instaladas após a quimioterapia em paciente de altíssimo risco. Na lise já estabelecida, a droga de escolha é a rasburicase, que converte o urato existente em alantoína hidrossolúvel, associada a hidratação vigorosa e manejo agressivo da hipercalemia; a hipocalcemia assintomática não deve ser corrigida, pois a reposição de cálcio em ambiente de hiperfosfatemia precipita fosfato de cálcio e agrava a lesão renal. Lembrar de checar deficiência de G6PD, que contraindica a rasburicase." },
      { letra: "B", texto: "Manter apenas alopurinol em dose plena como droga de escolha para reduzir rapidamente o ácido úrico já circulante.", correta: false, comentario: "Confunde profilaxia com tratamento. O alopurinol inibe a xantina oxidase e portanto impede a formação de novo urato, mas não degrada o urato que já está no sangue, de modo que sua ação é lenta demais para uma lise instalada com ácido úrico de 12,4 mg/dL e rim já lesado. Há ainda o inconveniente do acúmulo de xantina e hipoxantina, com risco de nefropatia por xantina. O alopurinol tem lugar na profilaxia de risco baixo a intermediário, não neste cenário." },
      { letra: "C", texto: "Alcalinizar a urina com bicarbonato de sódio em infusão contínua para todos os pacientes, buscando pH urinário acima de 7,0.", correta: false, comentario: "Reproduz uma prática abandonada. A alcalinização urinária aumenta a solubilidade do ácido úrico, mas reduz a do fosfato de cálcio, favorecendo sua precipitação tubular justamente em um paciente que já tem fósforo de 7,2 mg/dL, além de piorar a hipocalcemia. Por isso deixou de ser recomendada de rotina, e o pilar do manejo passou a ser hidratação abundante com solução isotônica somada à redução farmacológica do urato." },
      { letra: "D", texto: "Repor gluconato de cálcio endovenoso para normalizar o cálcio sérico antes de qualquer outra medida.", correta: false, comentario: "Trata um número em vez do paciente e cria dano. A hipocalcemia da lise tumoral é consequência da quelação pelo fósforo elevado, e repor cálcio em quem está assintomático e sem repercussão eletrocardiográfica aumenta o produto cálcio-fósforo e a deposição de fosfato de cálcio nos túbulos renais e em outros tecidos. A reposição só se justifica diante de tetania, convulsão ou arritmia, e a correção real vem do controle da hiperfosfatemia e da própria lise." },
    ],
    dificuldade: "avancada",
    estilo: "caso",
    tags: ["síndrome de lise tumoral", "Cairo-Bishop", "rasburicase", "hipercalemia", "LLA", "lesão renal aguda"],
  },
  {
    id: "hemato-007",
    subtemaId: "hemato--linfomas--hodgkin-e-nao-hodgkin",
    disciplinaId: "hemato",
    enunciado: "Mulher de 28 anos procura atendimento por linfonodomegalia cervical indolor há 2 meses, associada a febre vespertina, sudorese noturna profusa e perda de 6 kg (cerca de 12% do peso corporal) em 4 meses. Relata dor no local do linfonodo minutos após ingerir bebida alcoólica. Foi realizada punção aspirativa por agulha fina (PAAF) do linfonodo cervical, cujo laudo descreve \"células atípicas sugestivas de neoplasia linfoproliferativa\", sem definição diagnóstica precisa. Qual a conduta mais adequada neste momento?",
    alternativas: [
      { letra: "A", texto: "Repetir a PAAF em outro linfonodo cervical para tentar confirmar o achado citológico.", correta: false, comentario: "Mesmo repetida, a PAAF fornece apenas material citológico disperso e não reproduz a arquitetura linfonodal necessária para subtipar o linfoma, então repeti-la não resolve a limitação do método." },
      { letra: "B", texto: "Solicitar biópsia excisional do linfonodo acometido para histopatologia e imuno-histoquímica.", correta: true, comentario: "A biópsia excisional preserva a arquitetura nodal, permite identificar a célula neoplásica em seu microambiente e realizar o painel imuno-histoquímico completo, sendo o método padrão-ouro para diagnóstico definitivo de linfoma." },
      { letra: "C", texto: "Iniciar empiricamente o esquema ABVD com base no quadro clínico sugestivo de linfoma de Hodgkin.", correta: false, comentario: "Tratamento quimioterápico nunca deve ser iniciado sem confirmação histopatológica do subtipo de linfoma, mesmo diante de um quadro clínico clássico, pois o esquema terapêutico depende diretamente do diagnóstico histológico." },
      { letra: "D", texto: "Solicitar PET-CT para estadiamento da doença antes de qualquer procedimento de biópsia.", correta: false, comentario: "O estadiamento com PET-CT pressupõe diagnóstico histológico já confirmado; realizá-lo antes da biópsia inverte a sequência lógica de investigação e não substitui a necessidade de tecido para diagnóstico." },
    ],
    dificuldade: "intermediaria",
    estilo: "diagnostico",
    tags: ["linfoma de Hodgkin", "biópsia excisional", "PAAF", "diagnóstico"],
  },
  {
    id: "hemato-008",
    subtemaId: "hemato--linfomas--hodgkin-e-nao-hodgkin",
    disciplinaId: "hemato",
    enunciado: "Menino de 9 anos é levado ao pronto-socorro com massa abdominal volumosa e dor em região de fossa ilíaca direita, de crescimento rápido nas últimas duas semanas. Biópsia excisional de linfonodo mesentérico revela lençol difuso de células neoplásicas de tamanho médio intercaladas por macrófagos de citoplasma claro, conferindo padrão de \"céu estrelado\", com índice de proliferação Ki-67 próximo de 100%. Antes de iniciar a quimioterapia, qual é a medida mais importante a ser adotada?",
    alternativas: [
      { letra: "A", texto: "Solicitar sorologia para HTLV-1, já que a positividade contraindicaria o uso de rituximabe no esquema terapêutico.", correta: false, comentario: "HTLV-1 está associado à leucemia/linfoma de células T do adulto, não ao linfoma de Burkitt descrito no caso, e não é essa a prioridade imediata antes de iniciar o tratamento." },
      { letra: "B", texto: "Iniciar hidratação vigorosa e agente hipouricemiante (como rasburicase) para profilaxia de síndrome de lise tumoral.", correta: true, comentario: "O linfoma de Burkitt tem a maior taxa proliferativa entre as neoplasias humanas, podendo desencadear lise tumoral espontânea mesmo antes da quimioterapia; a profilaxia com hidratação e hipouricemiante é obrigatória e deve preceder o início do tratamento citotóxico." },
      { letra: "C", texto: "Aguardar o resultado do mielograma para excluir infiltração medular antes de iniciar qualquer medida terapêutica.", correta: false, comentario: "Investigação complementar de estadiamento não deve atrasar a profilaxia de lise tumoral, que é uma medida emergencial diante de um tumor de duplicação extremamente rápida e alto risco metabólico imediato." },
      { letra: "D", texto: "Iniciar corticoterapia isolada em altas doses por sete dias, reservando a poliquimioterapia definitiva para depois.", correta: false, comentario: "Essa não é a conduta padrão para linfoma de Burkitt; atrasar a poliquimioterapia definitiva em um tumor de crescimento tão acelerado aumenta o risco de complicações e não substitui a profilaxia específica de lise tumoral." },
    ],
    dificuldade: "avancada",
    estilo: "conduta",
    tags: ["linfoma de Burkitt", "síndrome de lise tumoral", "t(8;14)", "MYC", "emergência oncológica"],
  },
  {
    id: "hemato-009",
    subtemaId: "hemato--linfomas--hodgkin-e-nao-hodgkin",
    disciplinaId: "hemato",
    enunciado: "Homem de 65 anos, com linfonodomegalias cervicais e axilares de crescimento lento há 3 anos, encontra-se em observação vigilante (\"watch and wait\") por linfoma folicular assintomático de baixa carga tumoral. Há 2 semanas, nota crescimento rápido e assimétrico de um linfonodo cervical, acompanhado de elevação importante do LDH sérico, sem outros sintomas. Esse quadro sugere qual evento?",
    alternativas: [
      { letra: "A", texto: "Progressão esperada do linfoma folicular para a fase leucêmica típica de sua evolução natural.", correta: false, comentario: "O linfoma folicular não costuma evoluir com fase leucêmica típica como parte de sua história natural indolente; crescimento assimétrico rápido com LDH elevado não se explica por essa progressão esperada." },
      { letra: "B", texto: "Transformação histológica do linfoma folicular indolente para um linfoma agressivo, tipicamente difuso de grandes células B.", correta: true, comentario: "Crescimento nodal assimétrico e rápido associado a elevação importante do LDH em paciente com linfoma folicular previamente estável é o padrão clássico de transformação histológica para um linfoma agressivo, exigindo nova biópsia para confirmação." },
      { letra: "C", texto: "Reação linfonodal reacional a um processo infeccioso viral concomitante, sem relação com o linfoma de base.", correta: false, comentario: "Embora infecções causem linfadenopatia reacional, a associação com LDH marcadamente elevado e crescimento assimétrico em paciente com linfoma prévio aponta para evento neoplásico, não para um simples quadro infeccioso." },
      { letra: "D", texto: "Recidiva do mesmo linfoma folicular indolente, sem qualquer mudança no comportamento biológico da doença.", correta: false, comentario: "Uma simples recidiva indolente não costuma cursar com crescimento assimétrico rápido nem elevação importante do LDH; esses achados indicam mudança no comportamento biológico da doença, não apenas recidiva do padrão indolente prévio." },
    ],
    dificuldade: "avancada",
    estilo: "caso",
    tags: ["linfoma folicular", "transformação histológica", "LDGCB", "LDH", "watch and wait"],
  },
  {
    id: "hemato-010",
    subtemaId: "hemato--mieloma-multiplo-e-neoplasias-mieloproliferativas--diagnostico-e-conduta",
    disciplinaId: "hemato",
    enunciado: "Paciente de 68 anos com lombalgia mecânica leve, sem história de trauma ou fratura. Exames: cálcio sérico 9,5 mg/dL, creatinina 0,9 mg/dL, hemoglobina 13 g/dL, radiografia do esqueleto sem lesões líticas. O mielograma mostra 15% de plasmócitos clonais. A dosagem de cadeias leves livres séricas revela kappa 800 mg/L e lambda 5 mg/L, com razão kappa/lambda de 160. Qual é o diagnóstico mais provável e a conduta adequada?",
    alternativas: [
      { letra: "A", texto: "Gamopatia monoclonal de significado indeterminado (MGUS); manter apenas observação clínica periódica.", correta: false, comentario: "A plasmocitose clonal medular de 15% já ultrapassa o limite de 10% que define MGUS, independentemente da ausência de critérios CRAB; por definição, MGUS exige plasmócitos clonais abaixo desse corte, o que não é o caso deste paciente." },
      { letra: "B", texto: "Mieloma múltiplo ativo (sintomático), pois a razão de cadeias leves livres igual a 160 (≥ 100) configura um evento definidor de mieloma pelo biomarcador SLiM, mesmo sem qualquer critério CRAB; está indicado iniciar tratamento sistêmico.", correta: true, comentario: "Conduta correta. O paciente tem plasmocitose clonal ≥ 10% e uma razão de cadeias leves livres envolvida:não envolvida ≥ 100 com a cadeia envolvida acima de 100 mg/L, que é exatamente o biomarcador Li do critério SLiM. Isso torna a doença ativa e indica tratamento mesmo na ausência de cálcio elevado, insuficiência renal, anemia ou lesão óssea." },
      { letra: "C", texto: "Mieloma múltiplo indolente (smoldering); manter apenas seguimento sem iniciar tratamento oncológico.", correta: false, comentario: "A razão de cadeias leves livres ≥ 100, com a cadeia envolvida acima de 100 mg/L, é por definição um dos três biomarcadores SLiM que tornam a doença ativa, retirando-a da categoria smoldering mesmo havendo plasmócitos entre 10 e 60% e ausência de CRAB." },
      { letra: "D", texto: "Macroglobulinemia de Waldenström; solicitar eletroforese de proteínas em busca de pico de IgM.", correta: false, comentario: "A macroglobulinemia de Waldenström decorre de proliferação linfoplasmocitária secretora de IgM pentamérica, e não de plasmocitose clonal medular com predomínio isolado de cadeia leve kappa como no caso descrito, que é o padrão típico do mieloma." },
    ],
    dificuldade: "avancada",
    estilo: "diagnostico",
    tags: ["mieloma múltiplo", "SLiM-CRAB", "cadeias leves livres", "IMWG"],
  },
  {
    id: "hemato-011",
    subtemaId: "hemato--mieloma-multiplo-e-neoplasias-mieloproliferativas--diagnostico-e-conduta",
    disciplinaId: "hemato",
    enunciado: "Paciente com mieloma múltiplo confirmado apresenta dor óssea persistente. Foi solicitada cintilografia óssea com tecnécio-99m, que resultou normal, gerando dúvida diagnóstica sobre a real extensão da doença óssea. Qual a explicação mais correta para esse resultado e qual a conduta de imagem adequada?",
    alternativas: [
      { letra: "A", texto: "A cintilografia é normal porque, nesse estágio, o mieloma ainda não causa lesão óssea significativa; deve-se repetir o exame em 6 meses.", correta: false, comentario: "Essa alternativa ignora o mecanismo real: o mieloma pode causar destruição óssea extensa e clinicamente significativa mesmo com cintilografia normal, já que o exame não detecta esse tipo de lesão, e não porque a doença óssea esteja ausente." },
      { letra: "B", texto: "A cintilografia com tecnécio-99m depende de atividade osteoblástica reacional, que está ausente nas lesões puramente líticas do mieloma; deve-se solicitar radiografia de corpo inteiro/TC de baixa dose, RM ou PET-CT.", correta: true, comentario: "Conduta correta. O radiofármaco da cintilografia é captado por osteoblastos em atividade de reparo, e no mieloma os osteoblastos estão inibidos enquanto os osteoclastos são hiperativados, gerando lesões puramente osteolíticas sem reação reparadora — por isso o exame é classicamente falso-negativo, e os métodos indicados são TC de baixa dose de corpo inteiro, RM ou PET-CT." },
      { letra: "C", texto: "O exame está tecnicamente inadequado; deve-se repetir a cintilografia com maior dose do radiofármaco.", correta: false, comentario: "O problema não é dose nem técnica de aquisição; é a ausência biológica de reação osteoblástica que o próprio método precisa captar para gerar sinal, de modo que repetir o exame com mais radiofármaco não resolve a limitação intrínseca do método nesse contexto." },
      { letra: "D", texto: "A cintilografia óssea é o exame de escolha para avaliação óssea no mieloma múltiplo, e o resultado normal exclui doença óssea significativa.", correta: false, comentario: "A cintilografia não é o exame de escolha no mieloma justamente por sua alta taxa de falso-negativo diante de lesões osteolíticas puras, e um resultado normal não deve ser usado para excluir doença óssea nesse contexto." },
    ],
    dificuldade: "intermediaria",
    estilo: "exame",
    tags: ["mieloma múltiplo", "lesão lítica", "cintilografia óssea", "imagem óssea"],
  },
  {
    id: "hemato-012",
    subtemaId: "hemato--mieloma-multiplo-e-neoplasias-mieloproliferativas--diagnostico-e-conduta",
    disciplinaId: "hemato",
    enunciado: "Mulher de 72 anos é investigada por anemia macrocítica persistente (VCM 108 fL), com contagem de plaquetas normal-alta e leucócitos normais. O mielograma revela medula hipercelular, com displasia eritroide isolada e ausência de excesso de blastos. O cariótipo evidencia deleção isolada do braço longo do cromossomo 5 (del5q). Qual é o diagnóstico e a conduta farmacológica mais indicada?",
    alternativas: [
      { letra: "A", texto: "Anemia ferropriva; iniciar reposição de ferro por via oral.", correta: false, comentario: "A anemia ferropriva cursa com microcitose e medula normocelular com hiperplasia eritroide sem displasia clonal, achados incompatíveis com a anemia macrocítica, a medula hipercelular displásica e a alteração citogenética clonal descritas neste caso." },
      { letra: "B", texto: "Síndrome mielodisplásica com deleção isolada do 5q; iniciar lenalidomida, que induz resposta hematológica e citogenética duradoura nesse subtipo específico.", correta: true, comentario: "Conduta correta. O quadro de citopenia (aqui, anemia macrocítica) com medula hipercelular e displásica, blastos não aumentados e deleção isolada do 5q define a síndrome 5q-, um subtipo de SMD que responde de forma marcante à lenalidomida, com resposta hematológica e citogenética sustentada nessa população, tipicamente mulheres idosas." },
      { letra: "C", texto: "Leucemia mieloide aguda; iniciar quimioterapia de indução imediatamente.", correta: false, comentario: "O mielograma não descreve excesso de blastos, e o corte obrigatório para definir leucemia mieloide aguda é blastos medulares iguais ou superiores a 20%; sem esse achado, o quadro permanece classificado como síndrome mielodisplásica." },
      { letra: "D", texto: "Mielofibrose primária; iniciar ruxolitinibe.", correta: false, comentario: "A mielofibrose primária cursa com fibrose medular, esplenomegalia maciça e leucoeritroblastose com dacrócitos no sangue periférico, e não com medula hipercelular displásica sem fibrose como a descrita no caso, o que afasta esse diagnóstico." },
    ],
    dificuldade: "avancada",
    estilo: "caso",
    tags: ["síndrome mielodisplásica", "del5q", "lenalidomida", "sideroblastos"],
  },
  {
    id: "hemato-013",
    subtemaId: "hemato--medicina-transfusional--indicacoes-de-hemocomponentes",
    disciplinaId: "hemato",
    enunciado: "Homem de 44 anos, no segundo dia de pós-operatório de laparotomia por perfuração intestinal, recebe 2 unidades de plasma fresco congelado. Cerca de 2 horas após o término da infusão, evolui com dispneia intensa e SpO2 de 84% em ar ambiente. Ao exame: temperatura 38,3 °C, PA 88/54 mmHg, FC 118 bpm, estertores difusos, ausência de turgência jugular e ausência de terceira bulha. A radiografia de tórax mostra infiltrado alveolar bilateral difuso. NT-proBNP dentro da faixa de referência e balanço hídrico das últimas 24 horas próximo do neutro. Foi administrada furosemida endovenosa, sem melhora da oxigenação. Qual é o diagnóstico e a conduta adequada?",
    alternativas: [
      { letra: "A", texto: "Sobrecarga circulatória associada à transfusão (TACO) — repetir furosemida e reduzir a velocidade de infusão nas próximas transfusões.", correta: false, comentario: "A TACO cursa com HIPERTENSÃO, turgência jugular, terceira bulha, NT-proBNP ELEVADO e balanço hídrico positivo, e melhora rapidamente com diurético. Este paciente está hipotenso, febril, com BNP normal, balanço neutro e sem resposta à furosemida — todos os pontos apontam na direção oposta." },
      { letra: "B", texto: "Lesão pulmonar aguda relacionada à transfusão (TRALI) — suspender definitivamente a transfusão, instituir suporte ventilatório com estratégia protetora e notificar a hemovigilância; diurético não está indicado.", correta: true, comentario: "Quadro típico de TRALI: hipoxemia de início em até 6 horas do término de componente rico em plasma, infiltrado bilateral, HIPOTENSÃO, febre, NT-proBNP normal e ausência de resposta a diurético. O tratamento é exclusivamente de suporte (ventilação protetora); diurese forçada pode agravar a hipoperfusão. A notificação ao serviço de hemoterapia é obrigatória para bloqueio dos demais componentes do doador." },
      { letra: "C", texto: "Reação anafilática por deficiência de IgA — adrenalina intramuscular e uso de hemocomponentes lavados nas próximas transfusões.", correta: false, comentario: "A anafilaxia transfusional se instala em MINUTOS do início da infusão e é dominada por urticária, angioedema, broncoespasmo e colapso, sem febre e sem infiltrado alveolar bilateral à radiografia. Aqui o quadro começou 2 horas após o término, cursa com febre e tem imagem de edema pulmonar difuso, o que não corresponde a reação alérgica." },
      { letra: "D", texto: "Reação hemolítica transfusional aguda por incompatibilidade ABO — hidratação vigorosa e manutenção do débito urinário.", correta: false, comentario: "A hemólise aguda ABO surge nos primeiros minutos, com pequenos volumes, e se manifesta por dor lombar e no trajeto venoso, hemoglobinúria, Coombs direto positivo, CIVD e insuficiência renal — nada disso descrito. Além do mais, o componente infundido foi PLASMA, e o achado dominante é insuficiência respiratória hipoxêmica com infiltrado bilateral, não hemólise." },
    ],
    dificuldade: "intermediaria",
    estilo: "caso",
    tags: ["TRALI", "TACO", "reação transfusional", "hemocomponentes", "plasma fresco congelado"],
  },
  {
    id: "hemato-014",
    subtemaId: "hemato--medicina-transfusional--indicacoes-de-hemocomponentes",
    disciplinaId: "hemato",
    enunciado: "Mulher de 34 anos, previamente hígida, chega ao pronto-socorro com astenia, icterícia e episódio de desorientação. Exames: hemoglobina 7,4 g/dL, plaquetas 9.000/mm³, esquizócitos ao esfregaço, LDH 1.850 U/L, bilirrubina indireta elevada, haptoglobina indetectável, creatinina 1,4 mg/dL, TP e TTPa normais, fibrinogênio 320 mg/dL e teste de Coombs direto negativo. Qual é a conduta transfusional inicial mais adequada?",
    alternativas: [
      { letra: "A", texto: "Transfundir concentrado de plaquetas imediatamente, já que a contagem está abaixo do gatilho profilático de 10.000/mm³, e depois iniciar corticoterapia.", correta: false, comentario: "O gatilho profilático de 10.000/mm³ vale para plaquetopenia HIPOPROLIFERATIVA (pós-quimioterapia, aplasia), e não para plaquetopenia de consumo por microangiopatia. Na púrpura trombocitopênica trombótica a transfusão de plaquetas fornece substrato para a microtrombose e pode precipitar eventos isquêmicos, sendo reservada apenas a hemorragia com risco iminente de morte." },
      { letra: "B", texto: "Iniciar plasmaférese terapêutica com reposição de plasma fresco congelado, sem transfusão profilática de plaquetas.", correta: true, comentario: "O conjunto anemia hemolítica microangiopática com esquizócitos, Coombs direto negativo, plaquetopenia intensa, LDH muito elevado, alteração neurológica e coagulograma/fibrinogênio normais define púrpura trombocitopênica trombótica. O tratamento é a plasmaférese de urgência, que remove o autoanticorpo anti-ADAMTS13 e repõe a enzima presente no plasma fresco congelado; a plaqueta profilática é formalmente evitada." },
      { letra: "C", texto: "Infundir plasma fresco congelado 15 mL/kg como terapia definitiva, sem necessidade de plasmaférese.", correta: false, comentario: "A infusão isolada de plasma repõe ADAMTS13, mas NÃO remove o autoanticorpo inibitório e é insuficiente como tratamento definitivo. Ela funciona apenas como ponte quando a plasmaférese não pode ser iniciada de imediato, e não substitui a troca plasmática, que é o procedimento que reduz mortalidade nessa doença." },
      { letra: "D", texto: "Transfundir crioprecipitado para corrigir o consumo de fibrinogênio associado ao quadro.", correta: false, comentario: "O fibrinogênio está normal (320 mg/dL) e o TP/TTPa também, o que justamente afasta coagulação intravascular disseminada e torna o crioprecipitado desnecessário. O crioprecipitado só entra quando há hipofibrinogenemia (classicamente abaixo de 150 mg/dL) acompanhada de sangramento, cenário ausente neste caso." },
    ],
    dificuldade: "avancada",
    estilo: "conduta",
    tags: ["PTT", "microangiopatia trombótica", "plaquetas", "plasmaférese", "contraindicação transfusional"],
  },
  {
    id: "hemato-015",
    subtemaId: "hemato--medicina-transfusional--indicacoes-de-hemocomponentes",
    disciplinaId: "hemato",
    enunciado: "Homem de 58 anos com cirrose hepática por doença hepática relacionada ao álcool, Child-Pugh B, internado com ascite volumosa e febre baixa, será submetido a paracentese diagnóstica para pesquisa de peritonite bacteriana espontânea. Exames: INR 1,8, TTPa discretamente alargado, plaquetas 62.000/mm³, hemoglobina 9,6 g/dL, fibrinogênio 190 mg/dL. Não há sangramento ativo nem equimoses. Qual é a conduta adequada antes do procedimento?",
    alternativas: [
      { letra: "A", texto: "Transfundir plasma fresco congelado 15 mL/kg para reduzir o INR abaixo de 1,5 antes de puncionar.", correta: false, comentario: "O INR foi validado para monitorizar antagonistas da vitamina K e reflete mal a hemostasia do cirrótico, que apresenta rebalanceamento com queda simultânea de fatores pró e anticoagulantes. Transfundir plasma nesse cenário não reduz sangramento, expõe a TACO e TRALI e ainda pode elevar a pressão portal pela sobrecarga de volume." },
      { letra: "B", texto: "Transfundir concentrado de plaquetas até ultrapassar 50.000/mm³, pois toda punção de cavidade exige esse limiar.", correta: false, comentario: "O limiar de 50.000/mm³ se aplica a procedimentos invasivos de médio e alto risco, como punção lombar, biópsias e endoscopia terapêutica. A paracentese e a toracocentese são classificadas como procedimentos de BAIXO risco hemorrágico e o paciente já está com 62.000/mm³, acima do limiar citado — a transfusão seria desnecessária mesmo se a regra invocada fosse a correta." },
      { letra: "C", texto: "Realizar a paracentese sem transfusão prévia de hemocomponentes, com técnica cuidadosa e preferencialmente guiada por ultrassonografia.", correta: true, comentario: "Paracentese é procedimento de baixo risco hemorrágico e as diretrizes atuais recomendam NÃO corrigir rotineiramente INR nem plaquetas do cirrótico antes de realizá-la. Adiar a punção diagnóstica em paciente com suspeita de peritonite bacteriana espontânea é mais perigoso que o risco de sangramento, pois retarda o diagnóstico e o início do antibiótico." },
      { letra: "D", texto: "Administrar vitamina K endovenosa e adiar o procedimento por 48 horas para reavaliação do coagulograma.", correta: false, comentario: "A vitamina K corrige apenas o componente de deficiência ou má absorção do complexo protrombínico e tem efeito limitado na coagulopatia da insuficiência hepatocelular, em que o problema é a falência de síntese. Adiar 48 horas uma paracentese diagnóstica em paciente febril com ascite retarda o reconhecimento da peritonite bacteriana espontânea, condição de alta mortalidade quando o antibiótico é postergado." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["plasma fresco congelado", "cirrose", "INR", "indicação inadequada", "paracentese"],
  },
];
