import type { Questao } from "@/domain/content/types";

/**
 * Banco de questões — Infectologia (OMED VI).
 * Extraídas do "Infectologia OMED · Simulado 160 Questões (Gabarito
 * Comentado)" do usuário, via scripts/extract-pdf.mts. Conferidas com o
 * material e com as diretrizes do MS.
 *
 * Lote 1: Temas 01–04 (Tuberculose, Meningites, Sífilis, HIV/AIDS) — Q1–Q24.
 */

const SUB = {
  tbDx: "inf--tuberculose--diagnostico-e-tratamento",
  tbLatente: "inf--tuberculose--tb-latente",
  meningite: "inf--meningites--bacteriana-vs-viral",
  sifilis: "inf--infeccoes-sexualmente-transmissiveis--sifilis",
  hiv: "inf--hiv-aids--diagnostico-e-tarv",
  dengue: "inf--arboviroses--dengue-classificacao-e-manejo",
  sepse: "inf--sepse--reconhecimento-e-surviving-sepsis",
  storch: "inf--infeccoes-congenitas--storch-visao-infectologica",
} as const;

const FONTE = "Simulado OMED Infectologia — 160 questões comentadas (material do usuário)";
const FONTE_CONGENITA = "Google Drive — 'Exame Nacional de Infectologia Perinatal e Medicina Fetal' (material do usuário)";

export const QUESTOES_INF: Questao[] = [
  // ── TUBERCULOSE ─────────────────────────────────────────────────
  {
    id: "inf-tb-001",
    subtemaId: SUB.tbDx,
    disciplinaId: "inf",
    enunciado:
      "O foco de Ghon, associado à linfadenopatia hilar satélite, constitui o complexo primário de Ranke na tuberculose. Esse achado é típico de qual forma da doença?",
    alternativas: [
      { letra: "A", texto: "TB pós-primária (reativação), tipicamente em ápices pulmonares.", correta: false, comentario: "A reativação cursa com cavitações apicais, sem complexo primário." },
      { letra: "B", texto: "TB primária, mais comum em crianças, após o primeiro contato com o bacilo.", correta: true, comentario: "Foco de Ghon (lesão parenquimatosa) + linfonodo hilar = complexo de Ranke, marca da primoinfecção." },
      { letra: "C", texto: "TB miliar, por disseminação hematogênica maciça.", correta: false, comentario: "A miliar mostra micronódulos difusos ('grão de milho'), não complexo primário." },
      { letra: "D", texto: "TB pleural, por contiguidade de um foco subpleural.", correta: false, comentario: "Cursa com derrame pleural exsudativo, não com esse complexo." },
    ],
    dificuldade: "fixacao",
    estilo: "fixacao",
    tags: ["tuberculose", "complexo de Ranke", "TB primária"],
    fonte: FONTE,
  },
  {
    id: "inf-tb-002",
    subtemaId: SUB.tbDx,
    disciplinaId: "inf",
    enunciado:
      "Segundo o Ministério da Saúde, qual exame é preconizado como teste de escolha inicial para todo sintomático respiratório, substituindo a baciloscopia como primeira linha onde disponível?",
    alternativas: [
      { letra: "A", texto: "Cultura em meio líquido (MGIT).", correta: false, comentario: "É o padrão-ouro, mas demorada — não serve como triagem inicial." },
      { letra: "B", texto: "PPD (prova tuberculínica).", correta: false, comentario: "Avalia infecção latente, não doença ativa." },
      { letra: "C", texto: "TRM-TB (teste rápido molecular, GeneXpert).", correta: true, comentario: "O MS preconiza o TRM-TB como primeira linha: detecta o DNA do bacilo em ~2h e ainda identifica resistência à rifampicina." },
      { letra: "D", texto: "IGRA (interferon-gamma release assay).", correta: false, comentario: "Também avalia infecção latente, não doença ativa." },
    ],
    dificuldade: "fixacao",
    estilo: "conduta",
    tags: ["tuberculose", "TRM-TB", "GeneXpert"],
    fonte: FONTE,
  },
  {
    id: "inf-tb-003",
    subtemaId: SUB.tbDx,
    disciplinaId: "inf",
    enunciado:
      "Qual a duração total recomendada do tratamento da tuberculose meningoencefálica e osteoarticular com o esquema básico (RHZE/RH)?",
    alternativas: [
      { letra: "A", texto: "6 meses, igual à forma pulmonar.", correta: false, comentario: "6 meses é a duração da TB pulmonar; essas formas exigem tratamento mais longo." },
      { letra: "B", texto: "9 meses.", correta: false, comentario: "Não é a duração preconizada pelo MS para essas formas." },
      { letra: "C", texto: "12 meses, com fase de manutenção estendida.", correta: true, comentario: "TB meningoencefálica e osteoarticular: 12 meses (2 RHZE + 10 RH). Na meníngea associa-se corticoide." },
      { letra: "D", texto: "18 meses, exigindo fármacos de segunda linha.", correta: false, comentario: "Segunda linha só na resistência; o esquema básico é mantido." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["tuberculose", "TB meningoencefálica", "duração"],
    fonte: FONTE,
  },
  {
    id: "inf-tb-004",
    subtemaId: SUB.tbDx,
    disciplinaId: "inf",
    enunciado:
      "Paciente em uso do esquema RHZE evolui com discromatopsia (perda da percepção vermelho-verde) e redução da acuidade visual. Qual fármaco é o responsável mais provável?",
    alternativas: [
      { letra: "A", texto: "Rifampicina.", correta: false, comentario: "Causa coloração alaranjada de secreções e hepatotoxicidade, não neurite óptica." },
      { letra: "B", texto: "Isoniazida.", correta: false, comentario: "Classicamente causa neuropatia PERIFÉRICA (prevenida com piridoxina)." },
      { letra: "C", texto: "Pirazinamida.", correta: false, comentario: "Associa-se a hiperuricemia/artralgia e hepatotoxicidade." },
      { letra: "D", texto: "Etambutol.", correta: true, comentario: "O etambutol causa neurite óptica dose-dependente: discromatopsia vermelho-verde e queda da acuidade visual." },
    ],
    dificuldade: "fixacao",
    estilo: "diagnostico",
    tags: ["tuberculose", "etambutol", "neurite óptica"],
    fonte: FONTE,
  },
  {
    id: "inf-tb-005",
    subtemaId: SUB.tbLatente,
    disciplinaId: "inf",
    enunciado:
      "No tratamento da infecção latente pelo M. tuberculosis (ILTB/TPT), qual esquema é hoje considerado preferencial por melhor adesão?",
    alternativas: [
      { letra: "A", texto: "Isoniazida isolada por 6–9 meses.", correta: false, comentario: "Esquema clássico, mas longo — adesão bem pior." },
      { letra: "B", texto: "Rifampicina isolada por 4 meses.", correta: false, comentario: "É alternativa válida, porém o 3HP é o preferencial pela posologia semanal." },
      { letra: "C", texto: "3HP: isoniazida + rifapentina semanal, por 3 meses.", correta: true, comentario: "Apenas 12 doses semanais — curso curto com adesão muito superior, hoje preferencial." },
      { letra: "D", texto: "RHZE por 2 meses seguido de RH por 1 mês.", correta: false, comentario: "Esse é esquema de doença ATIVA, não de infecção latente." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["ILTB", "3HP", "rifapentina"],
    fonte: FONTE,
  },
  {
    id: "inf-tb-006",
    subtemaId: SUB.tbDx,
    disciplinaId: "inf",
    enunciado:
      "Paciente em tratamento de TB pulmonar apresenta urina e suor com coloração alaranjada após início do RHZE. Qual a conduta?",
    alternativas: [
      { letra: "A", texto: "Suspender o esquema e investigar hepatotoxicidade.", correta: false, comentario: "Não há relação com hepatotoxicidade; suspender por isso comprometeria o tratamento." },
      { letra: "B", texto: "Reduzir a dose de rifampicina pela metade.", correta: false, comentario: "Reduzir dose favorece resistência, sem qualquer benefício." },
      { letra: "C", texto: "Tranquilizar o paciente: é efeito benigno da rifampicina, sem necessidade de suspender.", correta: true, comentario: "A rifampicina cora secreções de laranja-avermelhado — efeito esperado e inofensivo; orientar evita abandono." },
      { letra: "D", texto: "Substituir a rifampicina por uma quinolona.", correta: false, comentario: "Trocar droga de primeira linha por efeito benigno é inadequado." },
    ],
    dificuldade: "fixacao",
    estilo: "conduta",
    tags: ["rifampicina", "efeito adverso", "adesão"],
    fonte: FONTE,
  },

  // ── MENINGITES ──────────────────────────────────────────────────
  {
    id: "inf-men-007",
    subtemaId: SUB.meningite,
    disciplinaId: "inf",
    enunciado:
      "Qual a principal indicação de tomografia de crânio ANTES da punção lombar na suspeita de meningite bacteriana?",
    alternativas: [
      { letra: "A", texto: "Todo paciente, sem exceção.", correta: false, comentario: "TC universal atrasa o antibiótico e piora o desfecho — não se faz de rotina." },
      { letra: "B", texto: "Apenas em pacientes acima de 60 anos.", correta: false, comentario: "A idade isolada não é o critério." },
      { letra: "C", texto: "Imunossupressão, lesão de SNC prévia, convulsão recente, papiledema, déficit focal ou rebaixamento importante da consciência.", correta: true, comentario: "São os preditores de lesão com efeito de massa (risco de herniação). Fora deles, punciona-se direto. Se a TC for necessária, colher hemocultura e iniciar ATB ANTES do exame." },
      { letra: "D", texto: "Apenas quando há suspeita de meningite viral.", correta: false, comentario: "A TC não diferencia meningite viral de bacteriana." },
    ],
    dificuldade: "avancada",
    estilo: "conduta",
    tags: ["meningite", "punção lombar", "TC de crânio"],
    fonte: FONTE,
  },
  {
    id: "inf-men-008",
    subtemaId: SUB.meningite,
    disciplinaId: "inf",
    enunciado:
      "Em qual situação a Listeria monocytogenes deve ser obrigatoriamente coberta no esquema empírico da meningite bacteriana?",
    alternativas: [
      { letra: "A", texto: "Crianças entre 1 e 5 anos.", correta: false, comentario: "Nessa faixa predominam meningococo e pneumococo." },
      { letra: "B", texto: "Pacientes acima de 50 anos, gestantes, etilistas ou imunossuprimidos.", correta: true, comentario: "São os grupos de risco para Listeria → acrescentar AMPICILINA ao esquema (a cefalosporina de 3ª geração não cobre Listeria)." },
      { letra: "C", texto: "Apenas em recém-nascidos.", correta: false, comentario: "O RN é grupo de risco, mas não o único — a cobertura vai além dele." },
      { letra: "D", texto: "Não é necessário cobrir Listeria em nenhuma faixa etária.", correta: false, comentario: "Deixar Listeria descoberta nos grupos de risco é erro grave." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["meningite", "Listeria", "ampicilina"],
    fonte: FONTE,
  },
  {
    id: "inf-men-009",
    subtemaId: SUB.meningite,
    disciplinaId: "inf",
    enunciado:
      "A dexametasona reduz sequelas neurológicas (especialmente perda auditiva) na meningite bacteriana. Qual o momento ideal de administração?",
    alternativas: [
      { letra: "A", texto: "Apenas após a cultura do líquor identificar o agente.", correta: false, comentario: "Esperar a cultura perde completamente a janela terapêutica." },
      { letra: "B", texto: "24 horas após o antibiótico, quando a lise bacteriana já ocorreu.", correta: false, comentario: "Tarde demais: o objetivo é justamente conter a inflamação DA lise." },
      { letra: "C", texto: "Junto ou pouco antes da primeira dose do antibiótico.", correta: true, comentario: "O corticoide precisa estar presente quando a lise bacteriana liberar componentes inflamatórios — depois disso perde o benefício." },
      { letra: "D", texto: "Somente na meningite meningocócica confirmada.", correta: false, comentario: "O maior benefício é justamente na pneumocócica." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["meningite", "dexametasona"],
    fonte: FONTE,
  },
  {
    id: "inf-men-010",
    subtemaId: SUB.meningite,
    disciplinaId: "inf",
    enunciado: "Sobre a quimioprofilaxia de contatos próximos na meningite bacteriana, assinale a correta:",
    alternativas: [
      { letra: "A", texto: "É indicada de rotina tanto para meningococo quanto para pneumococo.", correta: false, comentario: "Não há indicação de rotina no pneumococo." },
      { letra: "B", texto: "Indicada na doença meningocócica (rifampicina 600 mg 12/12h por 2 dias no adulto) e seletivamente no Hib, mas não é rotina no pneumococo.", correta: true, comentario: "Meningococo e Hib têm transmissão por contato próximo prolongado; o pneumococo não justifica quimioprofilaxia de contatos." },
      { letra: "C", texto: "Indicada apenas se o caso índice evoluir para óbito.", correta: false, comentario: "A indicação independe do desfecho do caso índice." },
      { letra: "D", texto: "Feita exclusivamente com ceftriaxona IM em todos os contatos.", correta: false, comentario: "A ceftriaxona é alternativa (ex.: gestantes); a rifampicina é a opção padrão." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["meningite", "quimioprofilaxia", "rifampicina"],
    fonte: FONTE,
  },
  {
    id: "inf-men-011",
    subtemaId: SUB.meningite,
    disciplinaId: "inf",
    enunciado:
      "Qual a principal sequela da meningite bacteriana (sobretudo pneumocócica) que justifica audiometria após a alta?",
    alternativas: [
      { letra: "A", texto: "Perda auditiva neurossensorial.", correta: true, comentario: "É a sequela mais frequente (inflamação coclear/VIII par) — daí a audiometria de rotina após a alta e o uso precoce de dexametasona." },
      { letra: "B", texto: "Cegueira cortical.", correta: false, comentario: "Possível, porém rara." },
      { letra: "C", texto: "Paralisia facial periférica bilateral.", correta: false, comentario: "Não é a sequela característica." },
      { letra: "D", texto: "Anosmia permanente.", correta: false, comentario: "Não é sequela típica de meningite bacteriana." },
    ],
    dificuldade: "fixacao",
    estilo: "diagnostico",
    tags: ["meningite", "sequela", "perda auditiva"],
    fonte: FONTE,
  },
  {
    id: "inf-men-012",
    subtemaId: SUB.meningite,
    disciplinaId: "inf",
    enunciado: "Sobre os sinais de Kernig e Brudzinski na suspeita de meningite, qual afirmativa está correta?",
    alternativas: [
      { letra: "A", texto: "Têm alta sensibilidade isolada; a ausência de ambos exclui meningite com segurança.", correta: false, comentario: "Perigoso: a ausência NÃO exclui meningite." },
      { letra: "B", texto: "Têm sensibilidade baixa isoladamente; a ausência não exclui meningite.", correta: true, comentario: "A sensibilidade é baixa (~5–30%) — a suspeita clínica manda puncionar mesmo com esses sinais negativos." },
      { letra: "C", texto: "São específicos apenas para meningite viral.", correta: false, comentario: "Refletem irritação meníngea de qualquer etiologia." },
      { letra: "D", texto: "Devem substituir a punção lombar quando positivos.", correta: false, comentario: "Nada substitui a punção — é ela que define etiologia e conduta." },
    ],
    dificuldade: "intermediaria",
    estilo: "diagnostico",
    tags: ["meningite", "Kernig", "Brudzinski", "semiologia"],
    fonte: FONTE,
  },

  // ── SÍFILIS ─────────────────────────────────────────────────────
  {
    id: "inf-sif-013",
    subtemaId: SUB.sifilis,
    disciplinaId: "inf",
    enunciado: "Qual característica diferencia classicamente o cancro duro (sífilis primária) do cancro mole (H. ducreyi)?",
    alternativas: [
      { letra: "A", texto: "O cancro duro é doloroso e o cancro mole é indolor.", correta: false, comentario: "Está invertido." },
      { letra: "B", texto: "O cancro duro é indolor e o cancro mole é doloroso.", correta: true, comentario: "Cancro duro (T. pallidum): úlcera única, indolor, base endurecida, fundo limpo. Cancro mole (H. ducreyi): múltiplas, dolorosas, fundo sujo." },
      { letra: "C", texto: "Apenas o cancro mole apresenta adenopatia satélite.", correta: false, comentario: "Ambos cursam com adenopatia; no cancro mole ela supura (bubão)." },
      { letra: "D", texto: "O cancro duro é sempre múltiplo.", correta: false, comentario: "Classicamente é lesão ÚNICA." },
    ],
    dificuldade: "fixacao",
    estilo: "diagnostico",
    tags: ["sífilis", "cancro duro", "cancro mole"],
    fonte: FONTE,
  },
  {
    id: "inf-sif-014",
    subtemaId: SUB.sifilis,
    disciplinaId: "inf",
    enunciado: "Sobre os testes sorológicos para sífilis, qual afirmativa está correta?",
    alternativas: [
      { letra: "A", texto: "Os testes não-treponêmicos (VDRL/RPR) permanecem reagentes para sempre, mesmo após o tratamento.", correta: false, comentario: "É o oposto: os testes NÃO-treponêmicos caem com o tratamento; são os treponêmicos que permanecem reagentes pela vida toda." },
      { letra: "B", texto: "Os testes treponêmicos (FTA-Abs) servem para seguimento de cura, pois seus títulos caem com o tratamento.", correta: false, comentario: "Os treponêmicos não são usados para seguimento — permanecem reagentes mesmo após cura." },
      { letra: "C", texto: "O VDRL é usado para diagnóstico de atividade e seguimento de resposta terapêutica, sendo quantificável em títulos.", correta: true, comentario: "VDRL/RPR são quantificáveis; queda de pelo menos 2 diluições em 3 meses indica sucesso terapêutico." },
      { letra: "D", texto: "Testes treponêmicos não podem apresentar falso-positivo em nenhuma situação clínica.", correta: false, comentario: "Nenhum teste é infalível; a afirmativa absoluta já a torna incorreta." },
    ],
    dificuldade: "intermediaria",
    estilo: "diagnostico",
    tags: ["sífilis", "VDRL", "sorologia"],
    fonte: FONTE,
  },
  {
    id: "inf-sif-015",
    subtemaId: SUB.sifilis,
    disciplinaId: "inf",
    enunciado: "Qual é o tratamento de escolha para neurossífilis, em qualquer fase da doença?",
    alternativas: [
      { letra: "A", texto: "Penicilina G benzatina 2,4 milhões UI IM, dose única.", correta: false, comentario: "A benzatina não atinge concentrações liquóricas adequadas — não trata neurossífilis." },
      { letra: "B", texto: "Penicilina G benzatina 2,4 milhões UI IM, semanal por 3 semanas.", correta: false, comentario: "Esse é o esquema para sífilis latente tardia, não para neurossífilis." },
      { letra: "C", texto: "Penicilina G cristalina EV, 18–24 milhões UI/dia, por 10–14 dias.", correta: true, comentario: "A via endovenosa fracionada a cada 4h é necessária para atingir concentração liquórica terapêutica." },
      { letra: "D", texto: "Doxiciclina 100 mg 12/12h por 28 dias.", correta: false, comentario: "Não é o tratamento de escolha para neurossífilis; penicilina cristalina EV é insubstituível nesse contexto." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["sífilis", "neurossífilis", "penicilina"],
    fonte: FONTE,
  },
  {
    id: "inf-sif-016",
    subtemaId: SUB.sifilis,
    disciplinaId: "inf",
    enunciado:
      "A reação de Jarisch-Herxheimer, que pode ocorrer nas primeiras 24 horas após a primeira dose de penicilina no tratamento da sífilis, caracteriza-se por:",
    alternativas: [
      { letra: "A", texto: "Reação alérgica grave que contraindica a continuidade do tratamento com penicilina.", correta: false, comentario: "Não é reação alérgica — é causada pela lise maciça de espiroquetas." },
      { letra: "B", texto: "Reação febril aguda por lise maciça de espiroquetas, que não contraindica a continuidade do tratamento.", correta: true, comentario: "Febre, mialgia, cefaleia e piora transitória das lesões; manejo é sintomático, sem suspender a penicilina." },
      { letra: "C", texto: "Sinal de resistência bacteriana à penicilina, exigindo troca imediata para doxiciclina.", correta: false, comentario: "Não indica resistência — o T. pallidum não desenvolveu resistência documentada à penicilina." },
      { letra: "D", texto: "Evento exclusivo da sífilis terciária, nunca observado em fases mais precoces.", correta: false, comentario: "Pode ocorrer em qualquer fase tratada, não é exclusivo da terciária." },
    ],
    dificuldade: "intermediaria",
    estilo: "diagnostico",
    tags: ["sífilis", "Jarisch-Herxheimer"],
    fonte: FONTE,
  },
  {
    id: "inf-sif-017",
    subtemaId: SUB.sifilis,
    disciplinaId: "inf",
    enunciado: "Qual dos seguintes é um achado clássico de sífilis congênita na radiografia de ossos longos?",
    alternativas: [
      { letra: "A", texto: "Sinal de Wimberger (rarefação da metáfise proximal da tíbia).", correta: true, comentario: "Junto à pseudoparalisia de Parrot, reflete periostite/metafisite da sífilis congênita." },
      { letra: "B", texto: "Sinal do duplo contorno.", correta: false, comentario: "Não é achado de sífilis congênita — é descrito em outros contextos radiológicos." },
      { letra: "C", texto: "Sinal de Codman.", correta: false, comentario: "Achado clássico de osteossarcoma, não de sífilis congênita." },
      { letra: "D", texto: "Triângulo de Codman com reação periosteal em 'casca de cebola'.", correta: false, comentario: "Padrão de sarcoma de Ewing, não de sífilis congênita." },
    ],
    dificuldade: "avancada",
    estilo: "diagnostico",
    tags: ["sífilis congênita", "radiografia", "sinal de Wimberger"],
    fonte: FONTE,
  },
  {
    id: "inf-sif-018",
    subtemaId: SUB.sifilis,
    disciplinaId: "inf",
    enunciado:
      "Para que o tratamento da sífilis na gestação seja considerado adequado, evitando a notificação da criança como sífilis congênita, quais critérios devem ser cumpridos simultaneamente?",
    alternativas: [
      { letra: "A", texto: "Apenas o uso de penicilina benzatina, independentemente do momento da gestação.", correta: false, comentario: "O momento importa: precisa ser iniciado até 30 dias antes do parto." },
      { letra: "B", texto: "Esquema completo com penicilina benzatina para o estágio, iniciado até 30 dias antes do parto, com queda documentada de titulação e parceiro tratado.", correta: true, comentario: "Todos os critérios devem ser cumpridos simultaneamente; a falta de qualquer um leva à notificação da criança como sífilis congênita." },
      { letra: "C", texto: "Uso de doxiciclina como alternativa válida em qualquer trimestre, desde que o parceiro seja tratado.", correta: false, comentario: "Doxiciclina é contraindicada na gestação — não atravessa a placenta de forma eficaz para proteger o feto." },
      { letra: "D", texto: "Apenas a queda do título de VDRL, independentemente do tratamento do parceiro.", correta: false, comentario: "O tratamento do parceiro é critério obrigatório, não dispensável." },
    ],
    dificuldade: "avancada",
    estilo: "conduta",
    tags: ["sífilis gestacional", "sífilis congênita", "tratamento adequado"],
    fonte: FONTE,
  },

  // ── HIV/AIDS ─────────────────────────────────────────────────────
  {
    id: "inf-hiv-019",
    subtemaId: SUB.hiv,
    disciplinaId: "inf",
    enunciado: "Segundo a estratégia 'treat all' atualmente recomendada, qual é o critério de CD4 para indicação de início de TARV?",
    alternativas: [
      { letra: "A", texto: "CD4 < 500 células/mm³.", correta: false, comentario: "Não há mais corte de CD4 para indicar TARV." },
      { letra: "B", texto: "CD4 < 350 células/mm³.", correta: false, comentario: "Critério de estratégias antigas, superado pelo 'treat all'." },
      { letra: "C", texto: "TARV indicada para todo paciente HIV positivo, independentemente do valor de CD4 ou carga viral.", correta: true, comentario: "O 'treat all' recomenda início o mais precocemente possível para todo HIV+, reduzindo transmissibilidade e morbimortalidade." },
      { letra: "D", texto: "CD4 < 200 células/mm³, correspondendo à definição de AIDS.", correta: false, comentario: "Esse é o corte para definição de AIDS, não o critério de início de TARV hoje." },
    ],
    dificuldade: "fixacao",
    estilo: "fixacao",
    tags: ["HIV", "TARV", "treat all"],
    fonte: FONTE,
  },
  {
    id: "inf-hiv-020",
    subtemaId: SUB.hiv,
    disciplinaId: "inf",
    enunciado: "Qual é o esquema antirretroviral preferencial de primeira linha para adultos virgens de tratamento no Brasil atualmente?",
    alternativas: [
      { letra: "A", texto: "Zidovudina + lamivudina + efavirenz.", correta: false, comentario: "Esquema antigo, substituído pelo esquema com dolutegravir." },
      { letra: "B", texto: "Tenofovir + lamivudina + dolutegravir (TDF+3TC+DTG).", correta: true, comentario: "Comprimido de dose fixa combinada, 1x/dia; dolutegravir tem alta barreira genética à resistência." },
      { letra: "C", texto: "Tenofovir + entricitabina + ritonavir.", correta: false, comentario: "Ritonavir é usado como booster de inibidores de protease, não faz parte do esquema preferencial atual." },
      { letra: "D", texto: "Abacavir + lamivudina + darunavir.", correta: false, comentario: "Não é o esquema de primeira linha preferencial no Brasil." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["HIV", "TARV", "dolutegravir"],
    fonte: FONTE,
  },
  {
    id: "inf-hiv-021",
    subtemaId: SUB.hiv,
    disciplinaId: "inf",
    enunciado: "Em relação à coinfecção TB-HIV, qual o momento correto para início da TARV conforme o valor de CD4?",
    alternativas: [
      { letra: "A", texto: "CD4 < 50: iniciar TARV em até 2 semanas do início do tratamento de TB; CD4 ≥ 50: iniciar entre 8-12 semanas.", correta: true, comentario: "Quanto mais imunossuprimido, mais precoce a TARV, apesar do risco de síndrome de reconstituição imune (SIRI) — o benefício supera o risco." },
      { letra: "B", texto: "TARV deve sempre ser iniciada no mesmo dia do diagnóstico de TB, independentemente do CD4.", correta: false, comentario: "Início simultâneo aumenta muito o risco de SIRI grave; o momento depende do CD4." },
      { letra: "C", texto: "TARV deve ser postergada até o término completo do tratamento de TB, para evitar SIRI.", correta: false, comentario: "Postergar tanto aumenta a mortalidade, especialmente em CD4 baixo." },
      { letra: "D", texto: "CD4 < 50: iniciar TARV apenas após 8 semanas; CD4 ≥ 50: iniciar imediatamente.", correta: false, comentario: "Está invertido — quanto menor o CD4, mais precoce deve ser o início." },
    ],
    dificuldade: "avancada",
    estilo: "conduta",
    tags: ["HIV", "tuberculose", "coinfecção", "SIRI"],
    fonte: FONTE,
  },
  {
    id: "inf-hiv-022",
    subtemaId: SUB.hiv,
    disciplinaId: "inf",
    enunciado: "Qual profilaxia primária é indicada para pneumocistose em pacientes HIV positivos com CD4 < 200 células/mm³?",
    alternativas: [
      { letra: "A", texto: "Azitromicina semanal.", correta: false, comentario: "Azitromicina é usada na profilaxia de complexo Mycobacterium avium, não de pneumocistose." },
      { letra: "B", texto: "Sulfametoxazol-trimetoprima (SMX-TMP).", correta: true, comentario: "Mesma droga também previne neurotoxoplasmose (indicada se CD4 < 100 e IgG antitoxoplasma reagente)." },
      { letra: "C", texto: "Fluconazol diário.", correta: false, comentario: "Fluconazol é usado no tratamento/profilaxia de candidíase e criptococose, não de pneumocistose." },
      { letra: "D", texto: "Ganciclovir profilático.", correta: false, comentario: "Ganciclovir é usado para citomegalovírus, não para pneumocistose." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["HIV", "pneumocistose", "profilaxia"],
    fonte: FONTE,
  },
  {
    id: "inf-hiv-023",
    subtemaId: SUB.hiv,
    disciplinaId: "inf",
    enunciado: "Sobre o conceito 'Indetectável = Intransmissível (I=I)', assinale a alternativa correta.",
    alternativas: [
      { letra: "A", texto: "Elimina o risco de transmissão sexual quando a carga viral está indetectável de forma sustentada, mas não altera a contraindicação absoluta de amamentação em mães HIV positivas no Brasil.", correta: true, comentario: "I=I vale para transmissão sexual; a amamentação continua contraindicada no Brasil independentemente da carga viral materna, substituída por fórmula." },
      { letra: "B", texto: "Permite a amamentação segura em mães HIV positivas com carga viral indetectável.", correta: false, comentario: "A contraindicação à amamentação é absoluta no Brasil, mesmo com carga viral indetectável." },
      { letra: "C", texto: "Aplica-se apenas à transmissão vertical, não à transmissão sexual.", correta: false, comentario: "É o oposto: I=I refere-se especificamente à transmissão sexual." },
      { letra: "D", texto: "É válido apenas para pacientes em uso de inibidores de protease.", correta: false, comentario: "O conceito vale para qualquer esquema TARV eficaz, não é específico de classe de fármaco." },
    ],
    dificuldade: "avancada",
    estilo: "diagnostico",
    tags: ["HIV", "I=I", "amamentação", "transmissão"],
    fonte: FONTE,
  },
  {
    id: "inf-hiv-024",
    subtemaId: SUB.hiv,
    disciplinaId: "inf",
    enunciado:
      "Qual é o prazo máximo recomendado para início da profilaxia pós-exposição (PEP) ao HIV após exposição sexual desprotegida ou acidente biológico?",
    alternativas: [
      { letra: "A", texto: "24 horas, idealmente na primeira hora.", correta: false, comentario: "O prazo máximo é maior que 24h." },
      { letra: "B", texto: "72 horas, idealmente nas primeiras 2 horas.", correta: true, comentario: "PEP mantida por 28 dias, com o mesmo esquema TARV preferencial do tratamento — quanto mais precoce, maior a eficácia." },
      { letra: "C", texto: "7 dias, sem necessidade de pressa.", correta: false, comentario: "Prazo muito além do recomendado — a eficácia cai com o atraso." },
      { letra: "D", texto: "48 horas, apenas em caso de violência sexual.", correta: false, comentario: "O prazo de 72h vale para qualquer exposição de risco, não só violência sexual." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["HIV", "PEP", "profilaxia pós-exposição"],
    fonte: FONTE,
  },

  // ── DENGUE E ARBOVIROSES ────────────────────────────────────────
  {
    id: "inf-den-025",
    subtemaId: SUB.dengue,
    disciplinaId: "inf",
    enunciado: "Qual é o principal fator de risco para o desenvolvimento de dengue grave?",
    alternativas: [
      { letra: "A", texto: "Primeira infecção por qualquer sorotipo.", correta: false, comentario: "A primoinfecção costuma ser mais branda; o risco de gravidade aumenta na reinfecção por outro sorotipo." },
      { letra: "B", texto: "Infecção secundária por sorotipo diferente do da infecção prévia (mecanismo de ADE).", correta: true, comentario: "Anticorpos heterotípicos não neutralizantes facilitam a entrada viral em macrófagos (amplificação dependente de anticorpos), aumentando a resposta inflamatória e o extravasamento plasmático." },
      { letra: "C", texto: "Uso prévio de vacina, independentemente de infecção prévia.", correta: false, comentario: "Não é o fator clássico de gravidade; a vacina tem indicações específicas conforme sorostatus." },
      { letra: "D", texto: "Idade entre 20 e 30 anos.", correta: false, comentario: "Extremos de idade e comorbidades pesam mais; a faixa citada não é fator de risco por si." },
    ],
    dificuldade: "intermediaria",
    estilo: "fixacao",
    tags: ["dengue", "ADE", "dengue grave"],
    fonte: FONTE,
  },
  {
    id: "inf-den-026",
    subtemaId: SUB.dengue,
    disciplinaId: "inf",
    enunciado: "Em qual momento da evolução da dengue costumam surgir os sinais de alarme?",
    alternativas: [
      { letra: "A", texto: "Nos primeiros dois dias de febre alta.", correta: false, comentario: "A fase febril inicial raramente traz os sinais de alarme." },
      { letra: "B", texto: "Tipicamente quando a febre cede (defervescência), entre o 3º e o 7º dia.", correta: true, comentario: "A defervescência marca a entrada na fase crítica: é quando ocorre o extravasamento plasmático. A queda da febre NÃO é melhora." },
      { letra: "C", texto: "Apenas na convalescença.", correta: false, comentario: "A convalescença é fase de recuperação (risco de hipervolemia), não de surgimento de alarme." },
      { letra: "D", texto: "Sem relação temporal com a febre.", correta: false, comentario: "Há relação clara: a fase crítica gira em torno da defervescência." },
    ],
    dificuldade: "fixacao",
    estilo: "fixacao",
    tags: ["dengue", "sinais de alarme", "fase crítica"],
    fonte: FONTE,
  },
  {
    id: "inf-den-027",
    subtemaId: SUB.dengue,
    disciplinaId: "inf",
    enunciado: "Qual classe de analgésico/antitérmico é formalmente contraindicada enquanto houver suspeita de dengue?",
    alternativas: [
      { letra: "A", texto: "Paracetamol.", correta: false, comentario: "É a primeira escolha sintomática na dengue." },
      { letra: "B", texto: "Dipirona.", correta: false, comentario: "Também é opção aceita para febre/dor na dengue." },
      { letra: "C", texto: "AAS e AINEs, pelo risco hemorrágico.", correta: true, comentario: "AAS e anti-inflamatórios aumentam o risco de sangramento (e AAS traz risco de síndrome de Reye em crianças) — proibidos na suspeita de dengue." },
      { letra: "D", texto: "Todos os antitérmicos até confirmação laboratorial.", correta: false, comentario: "Paracetamol e dipirona são liberados; não se espera exame para controlar a febre." },
    ],
    dificuldade: "fixacao",
    estilo: "conduta",
    tags: ["dengue", "AAS", "AINE", "contraindicação"],
    fonte: FONTE,
  },
  {
    id: "inf-den-028",
    subtemaId: SUB.dengue,
    disciplinaId: "inf",
    enunciado: "Qual manifestação é mais sugestiva de zika em comparação com dengue e chikungunya?",
    alternativas: [
      { letra: "A", texto: "Febre alta com artralgia intensa e simétrica.", correta: false, comentario: "Artralgia intensa e incapacitante aponta para chikungunya." },
      { letra: "B", texto: "Exantema pruriginoso precoce (1º–2º dia) com conjuntivite não purulenta e febre baixa ou ausente.", correta: true, comentario: "É o padrão típico da zika — além do risco de microcefalia (vertical) e Guillain-Barré." },
      { letra: "C", texto: "Plaquetopenia progressiva com hemoconcentração.", correta: false, comentario: "Marca do extravasamento na dengue, não da zika." },
      { letra: "D", texto: "Dor retro-orbitária intensa com febre de 39–40 °C.", correta: false, comentario: "Mais característico da dengue." },
    ],
    dificuldade: "intermediaria",
    estilo: "diagnostico",
    tags: ["zika", "arboviroses", "diagnóstico diferencial"],
    fonte: FONTE,
  },
  {
    id: "inf-den-029",
    subtemaId: SUB.dengue,
    disciplinaId: "inf",
    enunciado: "Segundo a classificação de risco do MS para dengue, qual a conduta no Grupo D (choque)?",
    alternativas: [
      { letra: "A", texto: "Hidratação oral abundante e retorno se sinal de alarme.", correta: false, comentario: "Conduta do Grupo A (sem alarme), inadequada no choque." },
      { letra: "B", texto: "Soro fisiológico 0,9% 10 mL/kg em 1 hora.", correta: false, comentario: "É a expansão do Grupo C (com sinais de alarme), não do choque." },
      { letra: "C", texto: "SF 0,9% 20 mL/kg em até 20 minutos, repetindo até 3 vezes, com internação em UTI.", correta: true, comentario: "Grupo D = choque: expansão rápida e vigorosa, reavaliando após cada bolus, em ambiente de terapia intensiva." },
      { letra: "D", texto: "Observação ambulatorial com hemograma seriado.", correta: false, comentario: "Inaceitável no choque, que exige expansão imediata." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["dengue", "grupo D", "choque", "expansão"],
    fonte: FONTE,
  },

  // ── SEPSE E CHOQUE SÉPTICO ──────────────────────────────────────
  {
    id: "inf-sep-030",
    subtemaId: SUB.sepse,
    disciplinaId: "inf",
    enunciado: "Segundo o consenso Sepsis-3, qual afirmativa está correta sobre o qSOFA?",
    alternativas: [
      { letra: "A", texto: "É critério diagnóstico definitivo de sepse, dispensando o SOFA.", correta: false, comentario: "O qSOFA não fecha diagnóstico — é ferramenta de alerta." },
      { letra: "B", texto: "É triagem rápida à beira do leito, não critério diagnóstico definitivo — o diagnóstico exige SOFA ≥ 2.", correta: true, comentario: "qSOFA (FR ≥ 22, PAS ≤ 100, Glasgow < 15) sinaliza risco; sepse = infecção + aumento do SOFA ≥ 2. A Surviving Sepsis desaconselha usá-lo como triagem única." },
      { letra: "C", texto: "Deve ser calculado apenas em pacientes já em UTI.", correta: false, comentario: "É justamente uma ferramenta de beira de leito, fora da UTI." },
      { letra: "D", texto: "Substitui a coleta de lactato.", correta: false, comentario: "O lactato é parte da avaliação e da ressuscitação; o qSOFA não o substitui." },
    ],
    dificuldade: "intermediaria",
    estilo: "fixacao",
    tags: ["sepse", "qSOFA", "Sepsis-3"],
    fonte: FONTE,
  },
  {
    id: "inf-sep-031",
    subtemaId: SUB.sepse,
    disciplinaId: "inf",
    enunciado: "Como é definido o choque séptico segundo o Sepsis-3?",
    alternativas: [
      { letra: "A", texto: "Qualquer séptico com PAS < 90 mmHg em algum momento.", correta: false, comentario: "Hipotensão transitória não define choque séptico." },
      { letra: "B", texto: "Necessidade de vasopressor para PAM ≥ 65 mmHg + lactato > 2 mmol/L, apesar de reposição volêmica adequada.", correta: true, comentario: "É a definição do Sepsis-3 — a combinação de vasoplegia refratária a volume e hiperlactatemia, com mortalidade > 40%." },
      { letra: "C", texto: "SOFA ≥ 4, independentemente de vasopressor.", correta: false, comentario: "O SOFA gradua disfunção, mas não define choque isoladamente." },
      { letra: "D", texto: "Febre + hipotensão transitória responsiva a volume.", correta: false, comentario: "Se responde a volume, não é choque séptico estabelecido." },
    ],
    dificuldade: "avancada",
    estilo: "fixacao",
    tags: ["choque séptico", "lactato", "Sepsis-3"],
    fonte: FONTE,
  },
  {
    id: "inf-sep-032",
    subtemaId: SUB.sepse,
    disciplinaId: "inf",
    enunciado: "Quais ações compõem o pacote da primeira hora (Hour-1 Bundle) da Surviving Sepsis Campaign?",
    alternativas: [
      { letra: "A", texto: "Lactato, 2 hemoculturas antes do ATB, antibiótico empírico amplo, cristaloide 30 mL/kg se indicado, vasopressor se PAM < 65 apesar de volume.", correta: true, comentario: "São as 5 ações iniciadas simultaneamente na 1ª hora. A hemocultura não deve atrasar o antibiótico." },
      { letra: "B", texto: "Apenas antibiótico e hemocultura.", correta: false, comentario: "Faltam lactato, reposição volêmica e vasopressor." },
      { letra: "C", texto: "TC de abdome, hemocultura, ATB, drenagem cirúrgica imediata e vasopressor.", correta: false, comentario: "TC e cirurgia não fazem parte do bundle de 1h (o controle do foco é conduzido à parte)." },
      { letra: "D", texto: "Sequência obrigatória em 3h/6h do protocolo antigo.", correta: false, comentario: "O modelo atual é o Hour-1 Bundle, simultâneo, não a divisão 3h/6h." },
    ],
    dificuldade: "avancada",
    estilo: "conduta",
    tags: ["sepse", "Hour-1 Bundle", "Surviving Sepsis"],
    fonte: FONTE,
  },
  {
    id: "inf-sep-033",
    subtemaId: SUB.sepse,
    disciplinaId: "inf",
    enunciado: "Qual é o vasopressor de primeira escolha no choque séptico?",
    alternativas: [
      { letra: "A", texto: "Dopamina.", correta: false, comentario: "Associa-se a mais arritmias; deixou de ser primeira escolha." },
      { letra: "B", texto: "Noradrenalina.", correta: true, comentario: "É o vasopressor de 1ª escolha; a vasopressina entra como 2ª droga (poupadora de catecolamina)." },
      { letra: "C", texto: "Adrenalina com hidrocortisona de rotina.", correta: false, comentario: "Hidrocortisona só no choque refratário; adrenalina não é a 1ª escolha." },
      { letra: "D", texto: "Vasopressina isolada.", correta: false, comentario: "A vasopressina é adjuvante, não usada isoladamente como 1ª droga." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["sepse", "noradrenalina", "vasopressor"],
    fonte: FONTE,
  },

  // ── INFECÇÕES CONGÊNITAS (STORCH — visão infectológica) ──────────
  {
    id: "inf-cong-01",
    subtemaId: SUB.storch,
    disciplinaId: "inf",
    enunciado:
      "Gestante, 14 semanas, sorologia para toxoplasmose com IgG (+) e IgM (+). Teste de avidez de IgG = 25% (baixa avidez). Qual a conduta imediata e o seguimento diagnóstico?",
    alternativas: [
      { letra: "A", texto: "Espiramicina 1g de 8/8h e amniocentese para PCR de T. gondii após 18 semanas.", correta: true, comentario: "Baixa avidez em gestante < 16 semanas indica infecção recente (dentro dos últimos ~4 meses) — alto risco. Espiramicina reduz a transmissão vertical; a PCR no líquido amniótico só tem boa sensibilidade após 18 semanas E ≥4 semanas da soroconversão." },
      { letra: "B", texto: "Sulfadiazina, pirimetamina e ácido folínico imediatamente até o fim da gestação.", correta: false, comentario: "O esquema tríplice é reservado para infecção FETAL confirmada, não para a suspeita de infecção materna isolada." },
      { letra: "C", texto: "Espiramicina e repetir sorologia em 3 semanas para observar a curva de IgG.", correta: false, comentario: "O seguimento correto é a investigação da infecção fetal (PCR no líquido amniótico), não apenas repetir sorologia materna." },
      { letra: "D", texto: "Tranquilizar a paciente, pois IgG indica imunidade prévia e o IgM é residual.", correta: false, comentario: "A baixa avidez de IgG afasta essa hipótese — indica infecção adquirida recentemente, não antiga." },
      { letra: "E", texto: "Cordocentese imediata para IgM fetal e esquema tríplice se positivo.", correta: false, comentario: "Cordocentese tem mais risco que a amniocentese e não é o primeiro exame; a investigação fetal padrão é a PCR no líquido amniótico." },
    ],
    dificuldade: "avancada",
    estilo: "conduta",
    tags: ["toxoplasmose", "avidez de IgG", "gestação"],
    fonte: FONTE_CONGENITA,
  },
  {
    id: "inf-cong-02",
    subtemaId: SUB.storch,
    disciplinaId: "inf",
    enunciado:
      "RN de termo com petéquias, hepatoesplenomegalia e icterícia às custas de bilirrubina direta. USG transfontanela mostra calcificações periventriculares; teste da orelhinha \"falha\" bilateral. Diagnóstico e tratamento mais prováveis?",
    alternativas: [
      { letra: "A", texto: "Toxoplasmose congênita; sulfadiazina, pirimetamina e ácido folínico por 1 ano.", correta: false, comentario: "A calcificação da toxoplasmose é difusa pelo parênquima, não periventricular." },
      { letra: "B", texto: "CMV congênito; valganciclovir oral por 6 meses.", correta: true, comentario: "Calcificação periventricular + surdez neurossensorial (falha na triagem auditiva) é o padrão clássico do CMV; valganciclovir VO por 6 meses reduz a progressão da surdez." },
      { letra: "C", texto: "Sífilis congênita; penicilina G cristalina IV por 10 dias.", correta: false, comentario: "Sífilis não costuma cursar com calcificação periventricular nem falha na triagem auditiva como achado central." },
      { letra: "D", texto: "Rubéola congênita; isolamento respiratório e suporte para malformações.", correta: false, comentario: "A calcificação periventricular não é típica da rubéola; a tríade de Gregg é catarata + cardiopatia + surdez." },
      { letra: "E", texto: "Infecção por Zika; estimulação precoce para microcefalia.", correta: false, comentario: "A calcificação do Zika é cortical/subcortical, associada a microcefalia grave com colapso craniano, não periventricular isolada." },
    ],
    dificuldade: "avancada",
    estilo: "diagnostico",
    tags: ["CMV", "calcificação periventricular", "surdez"],
    fonte: FONTE_CONGENITA,
  },
  {
    id: "inf-cong-03",
    subtemaId: SUB.storch,
    disciplinaId: "inf",
    enunciado:
      "Gestante de 20 semanas com exantema, artralgia e febre baixa. USG morfológica mostra feto hidrópico (ascite e derrame pleural); Doppler de ACM com PVS > 1,5 MoM. Agente e fisiopatologia?",
    alternativas: [
      { letra: "A", texto: "Citomegalovírus; vasculite cerebral obliterante.", correta: false, comentario: "CMV não é a causa clássica de hidropisia com PVS de ACM elevado; seu dano principal é neurológico/auditivo." },
      { letra: "B", texto: "Parvovírus B19; aplasia eritrocitária e anemia fetal grave.", correta: true, comentario: "O parvovírus B19 tem tropismo pelos precursores eritroides — a aplasia leva a anemia grave, insuficiência cardíaca de alto débito e hidropisia; o PVS de ACM elevado reflete a anemia fetal." },
      { letra: "C", texto: "Toxoplasma gondii; obstrução do aqueduto de Sylvius.", correta: false, comentario: "A toxoplasmose causa hidrocefalia por obstrução liquórica, não hidropisia com anemia/PVS elevado." },
      { letra: "D", texto: "Listeria monocytogenes; sepse fetal com microabscessos hepáticos.", correta: false, comentario: "A listeriose causa sepse neonatal disseminada (granulomatosis infantiseptica), não esse padrão de hidropisia anêmica." },
      { letra: "E", texto: "Treponema pallidum; periostite de ossos longos.", correta: false, comentario: "A periostite é achado ósseo da sífilis, não explica hidropisia por anemia com PVS de ACM elevado." },
    ],
    dificuldade: "avancada",
    estilo: "diagnostico",
    tags: ["parvovírus B19", "hidropisia fetal", "Doppler ACM"],
    fonte: FONTE_CONGENITA,
  },
  {
    id: "inf-cong-04",
    subtemaId: SUB.storch,
    disciplinaId: "inf",
    enunciado:
      "Gestante no 1º trimestre, VDRL 1:4 e teste treponêmico rápido positivo, sem registro de tratamento prévio. Qual a conduta correta segundo o Ministério da Saúde?",
    alternativas: [
      { letra: "A", texto: "Tratar como sífilis latente tardia/de duração ignorada: penicilina benzatina 2,4 milhões UI IM semanal, 3 semanas.", correta: true, comentario: "Sem informação que permita estadiar a infecção (assintomática, achado de rastreio), trata-se como duração ignorada — esquema de 3 doses (7,2 milhões UI totais) para cobrir também a possibilidade de infecção mais antiga." },
      { letra: "B", texto: "Aguardar novo VDRL em 15 dias para confirmar aumento de títulos antes de tratar.", correta: false, comentario: "Sífilis na gestação nunca deve aguardar confirmação por cinética de títulos — tratamento é imediato após teste treponêmico + não treponêmico reagentes." },
      { letra: "C", texto: "Penicilina G Benzatina 2,4 milhões UI em dose única.", correta: false, comentario: "Dose única é para sífilis recente (primária/secundária/latente precoce) comprovada — não é o caso de duração ignorada." },
      { letra: "D", texto: "Solicitar radiografia de ossos longos e líquor da gestante antes de tratar.", correta: false, comentario: "Esses exames são para o RN exposto, não pré-requisito para iniciar o tratamento materno." },
      { letra: "E", texto: "Tratar com ceftriaxona se a paciente relatar alergia não confirmada à penicilina.", correta: false, comentario: "Alergia não confirmada exige investigação/dessensibilização — a penicilina é insubstituível na gestação." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["sífilis", "gestação", "penicilina"],
    fonte: FONTE_CONGENITA,
  },
  {
    id: "inf-cong-05",
    subtemaId: SUB.storch,
    disciplinaId: "inf",
    enunciado:
      "A tríade clássica da Síndrome da Rubéola Congênita (infecção precoce na gestação) é composta por:",
    alternativas: [
      { letra: "A", texto: "Microcefalia, calcificações difusas e coriorretinite.", correta: false, comentario: "Esse é um padrão mais associado à toxoplasmose." },
      { letra: "B", texto: "Catarata, cardiopatia congênita (PCA) e surdez neurossensorial.", correta: true, comentario: "Tríade de Gregg: catarata + cardiopatia (classicamente persistência do canal arterial) + surdez neurossensorial." },
      { letra: "C", texto: "Hidropisia fetal, anemia e óbito intrauterino.", correta: false, comentario: "Padrão mais associado ao parvovírus B19." },
      { letra: "D", texto: "Lesões cutâneas cicatriciais, hipoplasia de membros e coriorretinite.", correta: false, comentario: "Padrão da síndrome da varicela congênita." },
      { letra: "E", texto: "Hepatoesplenomegalia, rinite serossanguinolenta e osteocondrite.", correta: false, comentario: "Padrão da sífilis congênita precoce." },
    ],
    dificuldade: "fixacao",
    estilo: "fixacao",
    tags: ["rubéola congênita", "tríade de Gregg"],
    fonte: FONTE_CONGENITA,
  },
  {
    id: "inf-cong-06",
    subtemaId: SUB.storch,
    disciplinaId: "inf",
    enunciado:
      "Secundigesta, 28 semanas, febre/mialgia/cefaleia há 4 dias, contato com sobrinho com exantema há 1 semana. Sorologia: IgG negativo, IgM positivo para varicela. Conduta quanto ao risco de varicela congênita/neonatal?",
    alternativas: [
      { letra: "A", texto: "Imunoglobulina específica (VZIG) imediatamente.", correta: false, comentario: "A VZIG previne/atenua a doença quando dada antes ou logo após a exposição, antes da soroconversão — como o IgM já está positivo, a paciente já está infectada e a VZIG perde a utilidade." },
      { letra: "B", texto: "Cesárea de urgência para evitar transmissão no canal de parto.", correta: false, comentario: "Não há indicação de parto de urgência; o risco relevante nesta fase é a síndrome da varicela congênita, não a transmissão intraparto (que preocupa perto do termo)." },
      { letra: "C", texto: "Aciclovir oral para a gestante e monitorização fetal com USG seriada.", correta: true, comentario: "Gestante sintomática com varicela confirmada: aciclovir oral (reduz gravidade materna) + USG seriada para rastrear sinais de síndrome da varicela congênita (o risco existe até a 20ª semana)." },
      { letra: "D", texto: "Tranquilizar, pois o risco de varicela congênita só existe no 1º trimestre.", correta: false, comentario: "A janela de maior risco é 13–20 semanas, não restrita ao 1º trimestre; aos 28 semanas ainda cabe vigilância, embora o risco maior já tenha passado." },
      { letra: "E", texto: "Amniocentese para DNA viral e interrupção da gestação se positivo.", correta: false, comentario: "PCR positivo no líquido amniótico não indica interrupção da gestação — a conduta é acompanhamento por imagem." },
    ],
    dificuldade: "avancada",
    estilo: "conduta",
    tags: ["varicela", "gestação", "aciclovir"],
    fonte: FONTE_CONGENITA,
  },
  {
    id: "inf-cong-07",
    subtemaId: SUB.storch,
    disciplinaId: "inf",
    enunciado:
      "Feto de 32 semanas com microcefalia e colapso do crânio, calcificações subcorticais grosseiras, artrogripose e microftalmia; mãe em área endêmica de arboviroses. Diagnóstico mais provável?",
    alternativas: [
      { letra: "A", texto: "Vírus Chikungunya.", correta: false, comentario: "A infecção periparto por chikungunya causa febre/exantema/edema no RN, não essa síndrome malformativa." },
      { letra: "B", texto: "Vírus Zika.", correta: true, comentario: "Microcefalia com colapso craniano, calcificações subcorticais e artrogripose são o padrão clássico da síndrome congênita do Zika." },
      { letra: "C", texto: "Vírus da dengue.", correta: false, comentario: "A dengue perinatal manifesta-se como plaquetopenia/sangramento no RN, não malformação estrutural fetal." },
      { letra: "D", texto: "Citomegalovírus.", correta: false, comentario: "A calcificação do CMV é periventricular, e não costuma cursar com colapso craniano/artrogripose." },
      { letra: "E", texto: "Toxoplasmose.", correta: false, comentario: "A calcificação da toxoplasmose é difusa e não associada a colapso craniano/artrogripose." },
    ],
    dificuldade: "intermediaria",
    estilo: "diagnostico",
    tags: ["Zika", "microcefalia", "calcificação subcortical"],
    fonte: FONTE_CONGENITA,
  },
  {
    id: "inf-cong-08",
    subtemaId: SUB.storch,
    disciplinaId: "inf",
    enunciado: "Qual a estratégia mais eficaz para reduzir o risco de cronificação da hepatite B no RN de mãe HBsAg reagente?",
    alternativas: [
      { letra: "A", texto: "Cesárea eletiva em todas as gestantes HBsAg (+).", correta: false, comentario: "A via de parto não altera significativamente o risco quando a imunoprofilaxia neonatal é feita corretamente." },
      { letra: "B", texto: "Vacina contra HBV + imunoglobulina específica (HBIG) nas primeiras 12–24h de vida.", correta: true, comentario: "A combinação vacina + HBIG logo após o nascimento é a estratégia com maior eficácia comprovada na prevenção da transmissão vertical/cronificação." },
      { letra: "C", texto: "Interferon peguilado na gestante no 3º trimestre.", correta: false, comentario: "Não é a estratégia padrão; antivirais orais (tenofovir) em alta carga viral podem ser usados, não o interferon." },
      { letra: "D", texto: "Proibição estrita do aleitamento materno.", correta: false, comentario: "O aleitamento materno é permitido em mãe HBsAg+ quando o RN recebeu a imunoprofilaxia adequada." },
      { letra: "E", texto: "Lamivudina pela gestante desde o 1º trimestre, independente da carga viral.", correta: false, comentario: "O uso de antiviral na gestante é reservado a alta carga viral no 3º trimestre, não rotina desde o 1º trimestre." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["hepatite B", "HBIG", "transmissão vertical"],
    fonte: FONTE_CONGENITA,
  },
  {
    id: "inf-cong-09",
    subtemaId: SUB.storch,
    disciplinaId: "inf",
    enunciado:
      "Gestante de 38 semanas em trabalho de parto ativo apresenta lesões vesiculosas agrupadas, dolorosas, em vulva, há 24h — primeiro episódio de herpes genital. Conduta obstétrica mais adequada?",
    alternativas: [
      { letra: "A", texto: "Parto vaginal com proteção das lesões com gaze vaselinada.", correta: false, comentario: "Não protege o RN do contato com secreções infectadas no canal de parto." },
      { letra: "B", texto: "Parto cesáreo, preferencialmente com bolsas íntegras.", correta: true, comentario: "Primoinfecção herpética próxima ao parto tem o maior risco de transmissão neonatal (30–50%, sem tempo de transferência de anticorpos maternos) — cesárea, idealmente antes da rotura de membranas, reduz esse risco." },
      { letra: "C", texto: "Parto vaginal e aciclovir EV para o RN imediatamente.", correta: false, comentario: "A prevenção primária (evitar exposição) é preferível a tratar depois da exposição já ocorrida." },
      { letra: "D", texto: "Aciclovir tópico nas lesões e aguardar evolução do parto vaginal.", correta: false, comentario: "Aciclovir tópico não reduz o risco de transmissão perinatal o suficiente para justificar via vaginal na primoinfecção." },
      { letra: "E", texto: "Curetagem das lesões antes do desprendimento fetal.", correta: false, comentario: "Não é uma conduta indicada nem segura em trabalho de parto." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["herpes genital", "parto", "cesárea"],
    fonte: FONTE_CONGENITA,
  },
  {
    id: "inf-cong-10",
    subtemaId: SUB.storch,
    disciplinaId: "inf",
    enunciado: "A profilaxia intraparto para Streptococcus do grupo B (GBS) é indicada, independentemente do resultado do swab, quando:",
    alternativas: [
      { letra: "A", texto: "Cultura negativa para GBS há 4 semanas.", correta: false, comentario: "Cultura negativa recente não indica profilaxia." },
      { letra: "B", texto: "Bacteriúria por GBS na gestação atual.", correta: true, comentario: "Bacteriúria por GBS em qualquer momento da gestação indica alta colonização e profilaxia intraparto, independentemente do swab de 35-37 semanas." },
      { letra: "C", texto: "Cesárea eletiva com membranas íntegras.", correta: false, comentario: "Cesárea eletiva fora de trabalho de parto e com bolsa íntegra não requer profilaxia." },
      { letra: "D", texto: "Histórico de GBS em gestação anterior, sem doença no RN.", correta: false, comentario: "O antecedente que indica profilaxia obrigatória é RN anterior com doença invasiva por GBS, não apenas swab positivo prévio." },
      { letra: "E", texto: "Trabalho de parto a termo com bolsa rota há 2 horas.", correta: false, comentario: "Isoladamente não indica profilaxia obrigatória sem outro fator de risco ou swab positivo." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["GBS", "profilaxia intraparto"],
    fonte: FONTE_CONGENITA,
  },
  {
    id: "inf-cong-11",
    subtemaId: SUB.storch,
    disciplinaId: "inf",
    enunciado:
      "\"Sinal de duplo contorno\" em ossos longos à USG + rinite muco-sanguinolenta ao nascimento são achados altamente sugestivos de:",
    alternativas: [
      { letra: "A", texto: "Sífilis congênita.", correta: true, comentario: "Periostite/osteocondrite (duplo contorno ósseo) e rinite serossanguinolenta são achados clássicos da sífilis congênita precoce." },
      { letra: "B", texto: "Rubéola congênita.", correta: false, comentario: "A rubéola cursa com cardiopatia, catarata e surdez — não com esse padrão ósseo/nasal." },
      { letra: "C", texto: "Toxoplasmose congênita.", correta: false, comentario: "A toxoplasmose não costuma causar achados ósseos ou rinite." },
      { letra: "D", texto: "Osteogênese imperfeita.", correta: false, comentario: "É uma doença genética do colágeno, não infecção congênita." },
      { letra: "E", texto: "Doença de Chagas congênita.", correta: false, comentario: "Não é um achado característico do Chagas congênito." },
    ],
    dificuldade: "intermediaria",
    estilo: "diagnostico",
    tags: ["sífilis congênita", "duplo contorno", "periostite"],
    fonte: FONTE_CONGENITA,
  },
  {
    id: "inf-cong-12",
    subtemaId: SUB.storch,
    disciplinaId: "inf",
    enunciado: "Sobre a doença de Chagas congênita, assinale a alternativa correta:",
    alternativas: [
      { letra: "A", texto: "A transmissão vertical ocorre exclusivamente no parto vaginal.", correta: false, comentario: "A transmissão é transplacentária e pode ocorrer em qualquer momento da gestação, independentemente da via de parto." },
      { letra: "B", texto: "A maioria dos RN infectados é sintomática, com a \"tríade de Romaña\".", correta: false, comentario: "A maioria dos RN infectados é ASSINTOMÁTICA; o sinal de Romaña é da forma aguda por inoculação ocular, não faz parte de uma tríade congênita." },
      { letra: "C", texto: "O diagnóstico no período neonatal precoce deve ser feito preferencialmente por métodos parasitológicos diretos (ex.: micro-hematócrito).", correta: true, comentario: "A sorologia (IgG) não é confiável no RN pequeno pela transferência passiva materna — só é interpretável após 9–12 meses. No período neonatal, o método direto (parasitológico) é o indicado." },
      { letra: "D", texto: "O benzonidazol é contraindicado em menores de 1 ano.", correta: false, comentario: "Ao contrário — o benzonidazol é indicado e tem as melhores taxas de cura justamente nessa faixa etária." },
      { letra: "E", texto: "O rastreamento sorológico para Chagas é obrigatório em todas as gestantes brasileiras no 1º trimestre.", correta: false, comentario: "Não é rastreio universal obrigatório em todo o Brasil como é o VDRL — a recomendação varia por região de endemicidade." },
    ],
    dificuldade: "avancada",
    estilo: "diagnostico",
    tags: ["Chagas congênito", "diagnóstico parasitológico"],
    fonte: FONTE_CONGENITA,
  },
  {
    id: "inf-cong-13",
    subtemaId: SUB.storch,
    disciplinaId: "inf",
    enunciado: "\"Dentes de Hutchinson\" e \"tíbia em sabre\" são sequelas tardias classicamente associadas a qual infecção congênita?",
    alternativas: [
      { letra: "A", texto: "Citomegalovírus.", correta: false, comentario: "Não é achado do CMV." },
      { letra: "B", texto: "Toxoplasmose.", correta: false, comentario: "Não é achado da toxoplasmose." },
      { letra: "C", texto: "Sífilis.", correta: true, comentario: "São estigmas da sífilis congênita tardia (> 2 anos), junto com nariz em sela e a tríade de Hutchinson (ceratite intersticial, surdez, dentes de Hutchinson)." },
      { letra: "D", texto: "Rubéola.", correta: false, comentario: "Não é achado da rubéola congênita." },
      { letra: "E", texto: "Parvovírus B19.", correta: false, comentario: "Não é achado do parvovírus B19." },
    ],
    dificuldade: "fixacao",
    estilo: "fixacao",
    tags: ["sífilis congênita tardia", "dentes de Hutchinson"],
    fonte: FONTE_CONGENITA,
  },
  {
    id: "inf-cong-14",
    subtemaId: SUB.storch,
    disciplinaId: "inf",
    enunciado: "A \"tétrade de Sabin\" (coriorretinite + calcificações cerebrais difusas + hidrocefalia + retardo mental) é patognomônica de:",
    alternativas: [
      { letra: "A", texto: "Citomegalovírus congênito.", correta: false, comentario: "O CMV causa calcificação periventricular, não a tétrade de Sabin." },
      { letra: "B", texto: "Toxoplasmose congênita.", correta: true, comentario: "A tétrade de Sabin é a descrição clássica e mais cobrada da toxoplasmose congênita grave." },
      { letra: "C", texto: "Síndrome de Zika congênita.", correta: false, comentario: "Zika causa calcificação subcortical com microcefalia e colapso craniano, não a tétrade de Sabin." },
      { letra: "D", texto: "Herpes simples disseminado.", correta: false, comentario: "Não é a apresentação típica do herpes neonatal." },
      { letra: "E", texto: "Rubéola congênita.", correta: false, comentario: "A rubéola manifesta-se pela tríade de Gregg, não pela tétrade de Sabin." },
    ],
    dificuldade: "fixacao",
    estilo: "fixacao",
    tags: ["toxoplasmose congênita", "tétrade de Sabin"],
    fonte: FONTE_CONGENITA,
  },
  {
    id: "inf-cong-15",
    subtemaId: SUB.storch,
    disciplinaId: "inf",
    enunciado: "Sobre a infecção por CMV na gestação, assinale a afirmativa correta:",
    alternativas: [
      { letra: "A", texto: "A transmissão vertical só ocorre em infecção primária materna.", correta: false, comentario: "Também pode ocorrer em infecção não primária (reativação/reinfecção por nova cepa), embora com risco menor." },
      { letra: "B", texto: "O uso de ganciclovir na gestante é o tratamento padrão para prevenir a transmissão fetal.", correta: false, comentario: "Não há tratamento antiviral materno consagrado como padrão para prevenir transmissão; o tratamento pós-natal (valganciclovir) é para o RN sintomático." },
      { letra: "C", texto: "A taxa de transmissão vertical aumenta com o avançar da idade gestacional, mas a gravidade das lesões é maior no 1º trimestre.", correta: true, comentario: "Segue o padrão geral: mais transmissão tardia (maior contato placentário), porém lesões mais graves quando a infecção é precoce (organogênese)." },
      { letra: "D", texto: "O diagnóstico fetal por PCR no líquido amniótico deve ser feito antes de 16 semanas.", correta: false, comentario: "Ao contrário — deve-se aguardar pelo menos 21 semanas e um intervalo mínimo após a infecção materna, para evitar falso-negativo." },
      { letra: "E", texto: "IgG materno garante proteção total contra reinfecção por novas cepas.", correta: false, comentario: "A imunidade prévia reduz mas não elimina o risco de reinfecção por cepa diferente." },
    ],
    dificuldade: "avancada",
    estilo: "diagnostico",
    tags: ["CMV", "transmissão vertical", "PCR líquido amniótico"],
    fonte: FONTE_CONGENITA,
  },
  {
    id: "inf-cong-16",
    subtemaId: SUB.storch,
    disciplinaId: "inf",
    enunciado: "Qual fator está mais fortemente associado ao aumento do risco de transmissão vertical do vírus da hepatite C (HCV)?",
    alternativas: [
      { letra: "A", texto: "Tipo de parto (vaginal vs. cesárea).", correta: false, comentario: "A via de parto não tem impacto consistente comprovado na transmissão do HCV." },
      { letra: "B", texto: "Coinfecção com o vírus HIV.", correta: true, comentario: "A coinfecção HIV/HCV aumenta significativamente a taxa de transmissão vertical do HCV (por elevar a carga viral e a inflamação placentária)." },
      { letra: "C", texto: "Aleitamento materno.", correta: false, comentario: "O aleitamento não é contraindicado na hepatite C isolada (sem fissura mamária/sangramento ativo)." },
      { letra: "D", texto: "Uso de procedimentos invasivos como amniocentese.", correta: false, comentario: "Pode aumentar discretamente o risco, mas não é o fator mais fortemente associado." },
      { letra: "E", texto: "Presença de anticorpos anti-HCV, independentemente da carga viral.", correta: false, comentario: "O que importa é a viremia (RNA viral detectável), não apenas a sorologia." },
    ],
    dificuldade: "intermediaria",
    estilo: "diagnostico",
    tags: ["hepatite C", "transmissão vertical", "coinfecção HIV"],
    fonte: FONTE_CONGENITA,
  },
  {
    id: "inf-cong-17",
    subtemaId: SUB.storch,
    disciplinaId: "inf",
    enunciado:
      "A forma neonatal precoce da listeriose, caracterizada por abscessos disseminados e granulomas em múltiplos órgãos, é denominada:",
    alternativas: [
      { letra: "A", texto: "Síndrome de Lyell.", correta: false, comentario: "É uma dermatose grave (necrólise epidérmica tóxica), não relacionada à listeriose." },
      { letra: "B", texto: "Granulomatosis infantiseptica.", correta: true, comentario: "É o termo clássico para a sepse neonatal disseminada por Listeria monocytogenes, com microabscessos/granulomas multiorgânicos." },
      { letra: "C", texto: "Pênfigo sifilítico.", correta: false, comentario: "É achado cutâneo da sífilis congênita (bolhas palmoplantares), não da listeriose." },
      { letra: "D", texto: "Eritema infeccioso neonatal.", correta: false, comentario: "Não é um termo relacionado à listeriose congênita." },
      { letra: "E", texto: "Síndrome de Ritter.", correta: false, comentario: "É a forma neonatal da síndrome da pele escaldada estafilocócica, não relacionada à Listeria." },
    ],
    dificuldade: "intermediaria",
    estilo: "fixacao",
    tags: ["listeriose", "granulomatosis infantiseptica"],
    fonte: FONTE_CONGENITA,
  },
  {
    id: "inf-cong-18",
    subtemaId: SUB.storch,
    disciplinaId: "inf",
    enunciado:
      "Gestante com toxoplasmose aguda confirmada e infecção fetal comprovada por PCR no líquido amniótico após 18 semanas. Qual o esquema terapêutico de escolha para reduzir sequelas fetais?",
    alternativas: [
      { letra: "A", texto: "Espiramicina 3g/dia até o fim da gestação.", correta: false, comentario: "A espiramicina é usada quando a infecção fetal NÃO está confirmada — reduz a transmissão mas não trata o feto já infectado." },
      { letra: "B", texto: "Sulfadiazina (4g/dia), pirimetamina (50mg/dia) e ácido folínico (15mg/dia).", correta: true, comentario: "Com infecção fetal confirmada, o esquema tríplice (SPAF) é o indicado por atravessar melhor a barreira placentária e tratar o feto infectado." },
      { letra: "C", texto: "Clindamicina e quinina.", correta: false, comentario: "Não é o esquema padrão para toxoplasmose congênita." },
      { letra: "D", texto: "Ganciclovir endovenoso.", correta: false, comentario: "É antiviral usado para CMV, sem ação sobre o Toxoplasma." },
      { letra: "E", texto: "Penicilina G cristalina.", correta: false, comentario: "É o tratamento da sífilis, sem ação sobre o Toxoplasma." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["toxoplasmose congênita", "esquema tríplice"],
    fonte: FONTE_CONGENITA,
  },
  {
    id: "inf-cong-19",
    subtemaId: SUB.storch,
    disciplinaId: "inf",
    enunciado: "Qual o principal mecanismo fisiopatológico que leva a baixo peso ao nascer e prematuridade na malária congênita/gestacional?",
    alternativas: [
      { letra: "A", texto: "Transmissão direta de esporozoítos via leite materno.", correta: false, comentario: "O Plasmodium não é transmitido pelo leite materno." },
      { letra: "B", texto: "Sequestro de eritrócitos parasitados no espaço interviloso placentário, causando insuficiência placentária.", correta: true, comentario: "O sequestro de hemácias infectadas na placenta compromete a troca materno-fetal, levando a insuficiência placentária, baixo peso e prematuridade — mecanismo indireto, não teratogênico direto." },
      { letra: "C", texto: "Hemólise maciça neonatal por anticorpos IgG anti-Plasmodium.", correta: false, comentario: "Não é o mecanismo principal de baixo peso/prematuridade." },
      { letra: "D", texto: "Teratogênese direta pelos metabólitos do parasita no 1º trimestre.", correta: false, comentario: "A malária não é classicamente teratogênica direta." },
      { letra: "E", texto: "Vasculite do cordão umbilical com trombose das artérias umbilicais.", correta: false, comentario: "Não é o mecanismo central descrito." },
    ],
    dificuldade: "avancada",
    estilo: "diagnostico",
    tags: ["malária gestacional", "insuficiência placentária"],
    fonte: FONTE_CONGENITA,
  },
  {
    id: "inf-cong-20",
    subtemaId: SUB.storch,
    disciplinaId: "inf",
    enunciado:
      "Gestante de 15 semanas, teste treponêmico positivo, VDRL 1:32, com relato de choque anafilático prévio à penicilina. Qual a conduta para garantir o tratamento adequado da gestante e do feto?",
    alternativas: [
      { letra: "A", texto: "Doxiciclina 100mg de 12/12h por 15 dias.", correta: false, comentario: "Tetraciclinas são contraindicadas na gestação (afetam ossos/dentes fetais)." },
      { letra: "B", texto: "Estearato de eritromicina 500mg de 6/6h por 15 dias.", correta: false, comentario: "A eritromicina não atravessa bem a placenta — não trata o feto, apenas a mãe, não prevenindo a sífilis congênita." },
      { letra: "C", texto: "Dessensibilização hospitalar com penicilina G e tratamento com penicilina G benzatina.", correta: true, comentario: "A penicilina é o único fármaco comprovadamente eficaz para prevenir a sífilis congênita — em alergia grave confirmada, a conduta é dessensibilização hospitalar seguida de tratamento com penicilina." },
      { letra: "D", texto: "Ceftriaxona 1g IM por 10 dias.", correta: false, comentario: "Não substitui a penicilina como tratamento comprovadamente eficaz na gestação, apesar de reatividade cruzada teoricamente baixa." },
      { letra: "E", texto: "Azitromicina 2g em dose única.", correta: false, comentario: "Há resistência documentada do T. pallidum a macrolídeos e eficácia não comprovada para prevenir sífilis congênita." },
    ],
    dificuldade: "avancada",
    estilo: "conduta",
    tags: ["sífilis", "alergia à penicilina", "dessensibilização"],
    fonte: FONTE_CONGENITA,
  },
  {
    id: "inf-cong-21",
    subtemaId: SUB.storch,
    disciplinaId: "inf",
    enunciado: "O complexo primário de Ranke na tuberculose congênita costuma se localizar em qual órgão fetal, devido à via de transmissão transplacentária?",
    alternativas: [
      { letra: "A", texto: "Pulmão.", correta: false, comentario: "É o local clássico na TB pós-natal, não na congênita." },
      { letra: "B", texto: "Rim.", correta: false, comentario: "Não é o sítio primário na TB congênita." },
      { letra: "C", texto: "Fígado.", correta: true, comentario: "Os bacilos alcançam o feto pela veia umbilical e chegam primeiro ao fígado — o complexo primário da TB congênita costuma ser hepático, diferente da TB pulmonar pós-natal." },
      { letra: "D", texto: "Baço.", correta: false, comentario: "Não é o sítio primário clássico." },
      { letra: "E", texto: "Cérebro.", correta: false, comentario: "Não é o sítio primário clássico (embora possa haver disseminação secundária)." },
    ],
    dificuldade: "avancada",
    estilo: "fixacao",
    tags: ["tuberculose congênita", "complexo de Ranke"],
    fonte: FONTE_CONGENITA,
  },
  {
    id: "inf-cong-22",
    subtemaId: SUB.storch,
    disciplinaId: "inf",
    enunciado:
      "Achado de hidropisia fetal não imune associado a cardiomegalia e insuficiência cardíaca de alto débito, em feto cuja mãe teve exantema há 3 semanas, sugere infecção por:",
    alternativas: [
      { letra: "A", texto: "Parvovírus B19.", correta: true, comentario: "A anemia grave por aplasia eritroide leva à insuficiência cardíaca de alto débito e hidropisia — quadro clássico do parvovírus B19." },
      { letra: "B", texto: "Vírus da rubéola.", correta: false, comentario: "A rubéola causa cardiopatia estrutural (PCA), não insuficiência cardíaca de alto débito por anemia." },
      { letra: "C", texto: "Citomegalovírus.", correta: false, comentario: "O CMV não é a causa clássica desse padrão hemodinâmico." },
      { letra: "D", texto: "HIV.", correta: false, comentario: "Não causa esse quadro de hidropisia por alto débito." },
      { letra: "E", texto: "Treponema pallidum.", correta: false, comentario: "A sífilis pode causar hidropisia em casos graves, mas o mecanismo clássico de alto débito por anemia aplásica é do parvovírus B19." },
    ],
    dificuldade: "avancada",
    estilo: "diagnostico",
    tags: ["parvovírus B19", "hidropisia fetal", "insuficiência cardíaca de alto débito"],
    fonte: FONTE_CONGENITA,
  },
  {
    id: "inf-cong-23",
    subtemaId: SUB.storch,
    disciplinaId: "inf",
    enunciado: "A surdez neurossensorial, podendo ser progressiva e de início tardio, é a sequela mais comum de qual infecção congênita?",
    alternativas: [
      { letra: "A", texto: "Toxoplasmose.", correta: false, comentario: "A sequela mais comum e tardia da toxoplasmose é a coriorretinite recorrente, não a surdez." },
      { letra: "B", texto: "Citomegalovírus.", correta: true, comentario: "O CMV é a principal causa infecciosa não genética de surdez neurossensorial congênita, podendo progredir mesmo em casos inicialmente assintomáticos." },
      { letra: "C", texto: "Sífilis.", correta: false, comentario: "A surdez da sífilis é um achado tardio (parte da tríade de Hutchinson), mas não é descrita como progressiva do mesmo modo que a do CMV." },
      { letra: "D", texto: "Parvovírus B19.", correta: false, comentario: "O parvovírus B19 não é classicamente associado a surdez." },
      { letra: "E", texto: "Hepatite B.", correta: false, comentario: "Não causa surdez congênita." },
    ],
    dificuldade: "intermediaria",
    estilo: "fixacao",
    tags: ["CMV", "surdez neurossensorial"],
    fonte: FONTE_CONGENITA,
  },
  {
    id: "inf-cong-24",
    subtemaId: SUB.storch,
    disciplinaId: "inf",
    enunciado: "Sobre o uso de dolutegravir (DTG) no esquema antirretroviral inicial de gestantes com HIV, é correto afirmar que:",
    alternativas: [
      { letra: "A", texto: "É contraindicado em qualquer fase da gestação pelo risco de defeito de tubo neural.", correta: false, comentario: "O sinal inicial de risco (estudo em Botsuana) foi reavaliado como muito menor do que se temia inicialmente." },
      { letra: "B", texto: "É o esquema preferencial, inclusive para mulheres em idade fértil e no 1º trimestre, segundo as diretrizes atuais.", correta: true, comentario: "As diretrizes atuais (OMS/Ministério da Saúde) recomendam o DTG como esquema preferencial mesmo no início da gestação, dado o balanço risco-benefício favorável." },
      { letra: "C", texto: "Deve ser substituído por efavirenz em todas as gestantes.", correta: false, comentario: "O DTG é hoje preferido ao efavirenz na maioria dos cenários." },
      { letra: "D", texto: "Só pode ser iniciado após a 28ª semana de gestação.", correta: false, comentario: "Pode ser iniciado desde o 1º trimestre conforme diretrizes atuais." },
      { letra: "E", texto: "É indicado apenas em falha terapêutica a inibidores de protease.", correta: false, comentario: "É esquema de primeira linha, não reserva para falha terapêutica." },
    ],
    dificuldade: "avancada",
    estilo: "conduta",
    tags: ["HIV", "dolutegravir", "gestação"],
    fonte: FONTE_CONGENITA,
  },
  {
    id: "inf-cong-25",
    subtemaId: SUB.storch,
    disciplinaId: "inf",
    enunciado:
      "Feto de 26 semanas com ascite isolada; sorologias maternas para toxoplasmose, rubéola, CMV e sífilis são negativas. A mãe é pedagoga e trabalha com crianças pequenas. Qual exame adicional é mais pertinente?",
    alternativas: [
      { letra: "A", texto: "PCR para parvovírus B19 no líquido amniótico ou sangue fetal.", correta: true, comentario: "Exposição ocupacional a crianças pequenas é um fator de risco clássico para parvovírus B19 (transmissão respiratória em ambiente escolar/creche); é uma causa comum de ascite/hidropisia isolada com sorologias TORCH negativas." },
      { letra: "B", texto: "Teste de avidez para HIV.", correta: false, comentario: "Avidez não se aplica ao diagnóstico de HIV, e o HIV não é causa clássica de ascite fetal isolada." },
      { letra: "C", texto: "Dosagem de alfa-fetoproteína materna.", correta: false, comentario: "É rastreio de defeitos de tubo neural/cromossomopatias, não investigação etiológica de ascite fetal infecciosa." },
      { letra: "D", texto: "Cultura de urina materna para GBS.", correta: false, comentario: "GBS não é causa de ascite fetal." },
      { letra: "E", texto: "Biópsia de vilo corial para cariótipo.", correta: false, comentario: "Investiga cromossomopatia, não etiologia infecciosa, e não é o próximo passo diante do contexto epidemiológico dado." },
    ],
    dificuldade: "avancada",
    estilo: "diagnostico",
    tags: ["parvovírus B19", "ascite fetal", "exposição ocupacional"],
    fonte: FONTE_CONGENITA,
  },
  {
    id: "inf-cong-26",
    subtemaId: SUB.storch,
    disciplinaId: "inf",
    enunciado: "Em relação ao diagnóstico neonatal de HIV, o uso do teste de anticorpos (anti-HIV convencional) no recém-nascido:",
    alternativas: [
      { letra: "A", texto: "É o método de escolha para diagnóstico definitivo na 1ª semana de vida.", correta: false, comentario: "Não é adequado para diagnóstico definitivo no RN." },
      { letra: "B", texto: "Não diferencia anticorpos maternos transferidos pela placenta da infecção real do lactente até os 18 meses.", correta: true, comentario: "O IgG materno atravessa a placenta e persiste no lactente por até 18 meses, tornando o teste de anticorpos não confiável para diagnóstico nessa faixa etária — usam-se testes moleculares (carga viral/PCR)." },
      { letra: "C", texto: "Deve ser realizado apenas se a mãe não fez pré-natal.", correta: false, comentario: "Não é essa a lógica de indicação do teste." },
      { letra: "D", texto: "Garante que o RN não está infectado se positivo com títulos baixos.", correta: false, comentario: "Um resultado positivo não distingue transferência passiva de infecção verdadeira." },
      { letra: "E", texto: "É desnecessário, pois o HIV não atravessa a placenta.", correta: false, comentario: "O HIV pode ser transmitido por via transplacentária, intraparto e pelo aleitamento." },
    ],
    dificuldade: "intermediaria",
    estilo: "diagnostico",
    tags: ["HIV neonatal", "diagnóstico", "anticorpos maternos"],
    fonte: FONTE_CONGENITA,
  },
  {
    id: "inf-cong-27",
    subtemaId: SUB.storch,
    disciplinaId: "inf",
    enunciado:
      "RN de 3 dias com vesículas no couro cabeludo, no local onde foi colocado um eletrodo de monitorização interna durante o parto. Está letárgico, com convulsões; líquor com pleocitose e hiperproteinorraquia. Principal suspeita diagnóstica?",
    alternativas: [
      { letra: "A", texto: "Meningite por GBS.", correta: false, comentario: "Não explica a lesão vesicular localizada no ponto de inoculação (eletrodo de escalpo)." },
      { letra: "B", texto: "Herpes simples neonatal (forma com acometimento do SNC).", correta: true, comentario: "Vesículas no ponto de inoculação (eletrodo de escalpo) + letargia/convulsões + líquor inflamatório é o quadro clássico de herpes neonatal com acometimento de SNC — emergência que exige aciclovir IV imediato." },
      { letra: "C", texto: "Toxoplasmose congênita aguda.", correta: false, comentario: "Não se manifesta com vesículas cutâneas no local do eletrodo." },
      { letra: "D", texto: "Encefalite por vírus Zika.", correta: false, comentario: "Não é a apresentação aguda típica do Zika, e não explica a lesão vesicular local." },
      { letra: "E", texto: "Citomegalovírus disseminado.", correta: false, comentario: "Não costuma causar vesículas localizadas no ponto de inoculação do eletrodo." },
    ],
    dificuldade: "avancada",
    estilo: "diagnostico",
    tags: ["herpes neonatal", "SNC", "eletrodo de escalpo fetal"],
    fonte: FONTE_CONGENITA,
  },

  // ── MALÁRIA ──────────────────────────────────────────────────
  {
    id: "inf-mal-01",
    subtemaId: "inf--malaria--diagnostico-e-tratamento",
    disciplinaId: "inf",
    enunciado:
      "Paciente retorna de viagem à região amazônica há 10 dias e apresenta febre com recorrência a cada 48 horas, calafrios e sudorese. A gota espessa confirma Plasmodium falciparum. Qual a classificação da febre observada?",
    alternativas: [
      { letra: "A", texto: "Febre quartã.", correta: false, comentario: "A febre quartã (a cada 72h) é característica do P. malariae." },
      { letra: "B", texto: "Febre terçã.", correta: true, comentario: "A recorrência a cada 48 horas é chamada de febre terçã, característica de P. falciparum e P. vivax." },
      { letra: "C", texto: "Febre héctica.", correta: false, comentario: "Não é o termo usado para esse padrão de malária." },
      { letra: "D", texto: "Febre contínua.", correta: false, comentario: "Não descreve o padrão intermitente típico da malária." },
    ],
    dificuldade: "fixacao",
    estilo: "diagnostico",
    tags: ["malária", "febre terçã"],
    fonte: "Ministério da Saúde — Guia de Tratamento da Malária no Brasil",
  },
  {
    id: "inf-mal-02",
    subtemaId: "inf--malaria--diagnostico-e-tratamento",
    disciplinaId: "inf",
    enunciado: "Qual espécie de Plasmodium é a principal responsável pelos casos de malária grave e óbitos relacionados à doença?",
    alternativas: [
      { letra: "A", texto: "Plasmodium malariae.", correta: false, comentario: "Associado a febre quartã, geralmente com curso mais brando." },
      { letra: "B", texto: "Plasmodium falciparum.", correta: true, comentario: "É a espécie associada à maior parte dos casos de malária grave e à quase totalidade dos óbitos." },
      { letra: "C", texto: "Plasmodium ovale.", correta: false, comentario: "Associado a recaídas por hipnozoítos, não é a principal causa de malária grave." },
      { letra: "D", texto: "Plasmodium vivax isoladamente.", correta: false, comentario: "Pode cursar com formas graves ocasionalmente, mas não é a principal causa de óbito." },
    ],
    dificuldade: "fixacao",
    estilo: "diagnostico",
    tags: ["malária", "P. falciparum"],
    fonte: "OMS — Guidelines for the Treatment of Malaria",
  },
  {
    id: "inf-mal-03",
    subtemaId: "inf--malaria--diagnostico-e-tratamento",
    disciplinaId: "inf",
    enunciado:
      "Paciente tratado para malária por Plasmodium vivax recebe alta após resolução do quadro agudo com esquizonticida sanguíneo. Qual medicação adicional é necessária para prevenir recaída, e por quê?",
    alternativas: [
      { letra: "A", texto: "Nenhuma medicação adicional é necessária.", correta: false, comentario: "Para P. vivax há risco de recaída pelas formas hepáticas latentes, exigindo tratamento adicional." },
      { letra: "B", texto: "Primaquina, para eliminar os hipnozoítos hepáticos.", correta: true, comentario: "P. vivax (e P. ovale) formam hipnozoítos hepáticos responsáveis por recaídas — a primaquina atua sobre essas formas latentes." },
      { letra: "C", texto: "Doxiciclina, para cobertura de infecção bacteriana secundária.", correta: false, comentario: "Não é essa a indicação nesse contexto." },
      { letra: "D", texto: "Corticoide, para reduzir resposta inflamatória.", correta: false, comentario: "Não tem papel padrão no tratamento pós-episódio agudo." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["malária", "primaquina", "recaída"],
    fonte: "Ministério da Saúde — Guia de Tratamento da Malária no Brasil",
  },
  {
    id: "inf-mal-04",
    subtemaId: "inf--malaria--diagnostico-e-tratamento",
    disciplinaId: "inf",
    enunciado:
      "Paciente com malária apresenta icterícia, anemia, oligúria, hiperlactatemia e episódio de desorientação. Qual a classificação e a conduta quanto ao local de tratamento?",
    alternativas: [
      { letra: "A", texto: "Malária não complicada; tratamento ambulatorial.", correta: false, comentario: "Os sinais descritos caracterizam malária grave, não malária não complicada." },
      { letra: "B", texto: "Malária complicada (grave), com internação hospitalar obrigatória.", correta: true, comentario: "Sinais de hemólise, disfunção orgânica e neurológica (sugerindo malária cerebral) definem malária grave, exigindo internação." },
      { letra: "C", texto: "Malária latente; apenas observação ambulatorial.", correta: false, comentario: "Não existe essa classificação para o quadro descrito, claramente grave." },
      { letra: "D", texto: "Quimioprofilaxia isolada, sem tratamento agudo.", correta: false, comentario: "Quimioprofilaxia é medida preventiva, não tratamento de um caso grave já instalado." },
    ],
    dificuldade: "avancada",
    estilo: "conduta",
    tags: ["malária grave", "malária cerebral"],
    fonte: "Ministério da Saúde — Guia de Tratamento da Malária no Brasil",
  },

  // ── ZIKA E CHIKUNGUNYA ───────────────────────────────────────
  {
    id: "inf-zc-01",
    subtemaId: "inf--arboviroses--zika-e-chikungunya",
    disciplinaId: "inf",
    enunciado:
      "Gestante no primeiro trimestre apresenta exantema pruriginoso leve e conjuntivite não purulenta, com sorologia positiva para Zika vírus. Qual a principal complicação fetal associada?",
    alternativas: [
      { letra: "A", texto: "Cardiopatia congênita isolada.", correta: false, comentario: "Não é a associação clássica mais forte com a infecção por Zika." },
      { letra: "B", texto: "Microcefalia (síndrome congênita do Zika).", correta: true, comentario: "A infecção por Zika na gestação associa-se classicamente à síndrome congênita do Zika, cujo achado mais marcante é a microcefalia." },
      { letra: "C", texto: "Macrossomia fetal.", correta: false, comentario: "Não é achado associado à infecção por Zika." },
      { letra: "D", texto: "Polidrâmnio isolado.", correta: false, comentario: "Não é a principal complicação descrita." },
    ],
    dificuldade: "fixacao",
    estilo: "diagnostico",
    tags: ["Zika", "microcefalia", "síndrome congênita"],
    fonte: "Ministério da Saúde — Guia de Vigilância em Saúde (Arboviroses)",
  },
  {
    id: "inf-zc-02",
    subtemaId: "inf--arboviroses--zika-e-chikungunya",
    disciplinaId: "inf",
    enunciado:
      "Paciente apresenta febre alta de início súbito associada a poliartralgia intensa e incapacitante em mãos e punhos, bilateral e simétrica. Qual arbovirose é a mais provável?",
    alternativas: [
      { letra: "A", texto: "Dengue.", correta: false, comentario: "Cursa mais com mialgia e artralgia leve a moderada, não poliartralgia tão intensa." },
      { letra: "B", texto: "Chikungunya.", correta: true, comentario: "A poliartralgia intensa, incapacitante, bilateral e simétrica é a marca clínica mais característica da chikungunya." },
      { letra: "C", texto: "Zika.", correta: false, comentario: "Cursa tipicamente com artralgia leve, exantema pruriginoso e conjuntivite." },
      { letra: "D", texto: "Febre amarela.", correta: false, comentario: "Não cursa classicamente com esse padrão de poliartralgia intensa." },
    ],
    dificuldade: "intermediaria",
    estilo: "diagnostico",
    tags: ["chikungunya", "poliartralgia"],
    fonte: "Ministério da Saúde — Protocolo de Manejo Clínico de Chikungunya",
  },
  {
    id: "inf-zc-03",
    subtemaId: "inf--arboviroses--zika-e-chikungunya",
    disciplinaId: "inf",
    enunciado:
      "Paciente com quadro agudo compatível com arbovirose (febre, artralgia, exantema), ainda sem diagnóstico laboratorial definido. Qual classe de medicamento deve ser EVITADA até que a dengue seja excluída?",
    alternativas: [
      { letra: "A", texto: "Paracetamol.", correta: false, comentario: "É a droga de escolha para analgesia/antitermia, sem risco de sangramento." },
      { letra: "B", texto: "Anti-inflamatórios não esteroidais (AINE) e ácido acetilsalicílico.", correta: true, comentario: "Enquanto a dengue não for excluída, deve-se evitar AINEs e AAS pelo risco de sangramento." },
      { letra: "C", texto: "Antitérmicos em geral, incluindo paracetamol.", correta: false, comentario: "Paracetamol não deve ser evitado; é o antitérmico seguro de escolha." },
      { letra: "D", texto: "Hidratação oral.", correta: false, comentario: "Não é uma classe de medicamento a ser evitada; é recomendada." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["arboviroses", "AINE", "dengue"],
    fonte: "Ministério da Saúde — Guia de Vigilância em Saúde (Arboviroses)",
  },
  {
    id: "inf-zc-04",
    subtemaId: "inf--arboviroses--zika-e-chikungunya",
    disciplinaId: "inf",
    enunciado:
      "Homem de 30 anos apresenta febre há 5 dias após retorno de área com transmissão ativa de Zika vírus, e relata atividade sexual desprotegida com a parceira nesse período. Além da picada do Aedes, qual via de transmissão do Zika deve ser considerada no aconselhamento?",
    alternativas: [
      { letra: "A", texto: "Transmissão hídrica (água contaminada).", correta: false, comentario: "Não é uma via de transmissão descrita para o Zika vírus." },
      { letra: "B", texto: "Transmissão sexual.", correta: true, comentario: "O Zika vírus tem transmissão sexual documentada, além da vetorial e da vertical (mãe-feto)." },
      { letra: "C", texto: "Transmissão exclusivamente por transfusão sanguínea.", correta: false, comentario: "Não é a via mais relevante a destacar nesse contexto de aconselhamento sexual." },
      { letra: "D", texto: "Não há nenhuma via de transmissão além da picada do mosquito.", correta: false, comentario: "Existem outras vias descritas (sexual e vertical)." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["Zika", "transmissão sexual"],
    fonte: "Ministério da Saúde — Guia de Vigilância em Saúde (Arboviroses)",
  },

  // ── COVID-19 E INFLUENZA ─────────────────────────────────────
  {
    id: "inf-cvi-01",
    subtemaId: "inf--covid-19-e-influenza--manejo-ambulatorial-e-hospitalar",
    disciplinaId: "inf",
    enunciado:
      "Paciente com quadro respiratório agudo realiza TC de tórax, que evidencia opacidades em vidro fosco periféricas e bilaterais. Qual etiologia é mais compatível com esse padrão tomográfico?",
    alternativas: [
      { letra: "A", texto: "Influenza.", correta: false, comentario: "Tipicamente cursa com infiltrado intersticial; o padrão periférico bilateral em vidro fosco é mais associado à COVID-19." },
      { letra: "B", texto: "COVID-19.", correta: true, comentario: "Opacidades em vidro fosco periféricas e bilaterais são o achado tomográfico mais frequente na COVID-19." },
      { letra: "C", texto: "Pneumonia bacteriana típica.", correta: false, comentario: "Cursa mais com consolidação lobar e broncograma aéreo." },
      { letra: "D", texto: "Tuberculose primária.", correta: false, comentario: "Associa-se ao complexo primário (nódulo + linfonodo hilar)." },
    ],
    dificuldade: "intermediaria",
    estilo: "exame",
    tags: ["COVID-19", "tomografia de tórax", "vidro fosco"],
    fonte: "Ministério da Saúde — Protocolo de Manejo Clínico da COVID-19",
  },
  {
    id: "inf-cvi-02",
    subtemaId: "inf--covid-19-e-influenza--manejo-ambulatorial-e-hospitalar",
    disciplinaId: "inf",
    enunciado:
      "Criança apresenta, semanas após quadro de COVID-19, febre persistente, exantema, conjuntivite e disfunção de múltiplos órgãos. Qual a principal hipótese diagnóstica?",
    alternativas: [
      { letra: "A", texto: "Recidiva simples da infecção viral aguda.", correta: false, comentario: "O intervalo de semanas e o padrão multissistêmico não são compatíveis com recidiva viral aguda." },
      { letra: "B", texto: "Síndrome Inflamatória Multissistêmica Pediátrica (SIM-P).", correta: true, comentario: "Quadro ocorrendo semanas após a COVID-19 aguda, com febre e disfunção multissistêmica, é característico da SIM-P." },
      { letra: "C", texto: "Escarlatina.", correta: false, comentario: "Não se relaciona temporalmente com infecção prévia por COVID-19 dessa forma." },
      { letra: "D", texto: "Doença de Kawasaki clássica, sem relação com COVID-19.", correta: false, comentario: "O contexto temporal pós-COVID caracteriza a SIM-P especificamente." },
    ],
    dificuldade: "avancada",
    estilo: "diagnostico",
    tags: ["SIM-P", "COVID-19", "pediatria"],
    fonte: "Ministério da Saúde — Protocolo de Manejo Clínico da COVID-19",
  },
  {
    id: "inf-cvi-03",
    subtemaId: "inf--covid-19-e-influenza--manejo-ambulatorial-e-hospitalar",
    disciplinaId: "inf",
    enunciado:
      "Paciente com síndrome gripal apresenta início súbito de febre alta, mialgia intensa e prostração, associados a tosse seca e coriza. O que diferencia esse quadro de uma IVAS comum?",
    alternativas: [
      { letra: "A", texto: "A presença isolada de coriza.", correta: false, comentario: "Coriza também ocorre em IVAS comuns, não é o diferencial." },
      { letra: "B", texto: "O início súbito associado a sintomas sistêmicos importantes.", correta: true, comentario: "A influenza tem início súbito com sintomas sistêmicos proeminentes, diferentemente da IVAS comum, mais insidiosa." },
      { letra: "C", texto: "A ausência completa de sintomas respiratórios.", correta: false, comentario: "A influenza também cursa com sintomas respiratórios." },
      { letra: "D", texto: "A duração dos sintomas superior a um mês.", correta: false, comentario: "Não é esse o critério diferencial." },
    ],
    dificuldade: "intermediaria",
    estilo: "diagnostico",
    tags: ["influenza", "IVAS", "diagnóstico diferencial"],
    fonte: "Ministério da Saúde — Protocolo de Tratamento de Influenza",
  },
  {
    id: "inf-cvi-04",
    subtemaId: "inf--covid-19-e-influenza--manejo-ambulatorial-e-hospitalar",
    disciplinaId: "inf",
    enunciado:
      "Paciente com influenza confirmada, sem fatores de risco, procura atendimento no 4º dia de sintomas com melhora progressiva. Qual a conduta quanto ao antiviral (oseltamivir)?",
    alternativas: [
      { letra: "A", texto: "Deve ser sempre iniciado, independente do tempo de sintomas ou grupo de risco.", correta: false, comentario: "O benefício é maior se iniciado precocemente; não é obrigatório em todo caso leve e tardio sem fator de risco." },
      { letra: "B", texto: "O benefício é maior nas primeiras 48h; em grupos de risco deve sempre ser considerado mesmo fora dessa janela.", correta: true, comentario: "Idealmente iniciado em até 48h; em paciente sem risco e com melhora, reavalia-se caso a caso, mas grupos de risco sempre recebem o antiviral mesmo fora da janela ideal." },
      { letra: "C", texto: "O antiviral está contraindicado após 48 horas em qualquer paciente.", correta: false, comentario: "Não há contraindicação absoluta após 48h; em grupos de risco o tratamento ainda é recomendado." },
      { letra: "D", texto: "Deve-se substituir por antibioticoterapia empírica de rotina.", correta: false, comentario: "Antibiótico só é indicado se houver suspeita de infecção bacteriana secundária." },
    ],
    dificuldade: "avancada",
    estilo: "conduta",
    tags: ["influenza", "oseltamivir"],
    fonte: "Ministério da Saúde — Protocolo de Tratamento de Influenza",
  },
];
