import type { Questao } from "@/domain/content/types";

/**
 * Banco de questões — Infectologia (OMED VI).
 * Extraídas do "Infectologia OMED · Simulado 160 Questões (Gabarito
 * Comentado)" do usuário, via scripts/extract-pdf.mts. Conferidas com o
 * material e com as diretrizes do MS.
 *
 * Lote 1: Temas 01–04 (Tuberculose, Meningites, Sífilis, HIV/AIDS) — Q1–Q24.
 */

const SUB = {
  tbDx: "inf--tuberculose--diagnostico-e-tratamento",
  tbLatente: "inf--tuberculose--tb-latente",
  meningite: "inf--meningites--bacteriana-vs-viral",
  sifilis: "inf--infeccoes-sexualmente-transmissiveis--sifilis",
  hiv: "inf--hiv-aids--diagnostico-e-tarv",
  dengue: "inf--arboviroses--dengue-classificacao-e-manejo",
  sepse: "inf--sepse--reconhecimento-e-surviving-sepsis",
} as const;

const FONTE = "Simulado OMED Infectologia — 160 questões comentadas (material do usuário)";

export const QUESTOES_INF: Questao[] = [
  // ── TUBERCULOSE ─────────────────────────────────────────────────
  {
    id: "inf-tb-001",
    subtemaId: SUB.tbDx,
    disciplinaId: "inf",
    enunciado:
      "O foco de Ghon, associado à linfadenopatia hilar satélite, constitui o complexo primário de Ranke na tuberculose. Esse achado é típico de qual forma da doença?",
    alternativas: [
      { letra: "A", texto: "TB pós-primária (reativação), tipicamente em ápices pulmonares.", correta: false, comentario: "A reativação cursa com cavitações apicais, sem complexo primário." },
      { letra: "B", texto: "TB primária, mais comum em crianças, após o primeiro contato com o bacilo.", correta: true, comentario: "Foco de Ghon (lesão parenquimatosa) + linfonodo hilar = complexo de Ranke, marca da primoinfecção." },
      { letra: "C", texto: "TB miliar, por disseminação hematogênica maciça.", correta: false, comentario: "A miliar mostra micronódulos difusos ('grão de milho'), não complexo primário." },
      { letra: "D", texto: "TB pleural, por contiguidade de um foco subpleural.", correta: false, comentario: "Cursa com derrame pleural exsudativo, não com esse complexo." },
    ],
    dificuldade: "fixacao",
    estilo: "fixacao",
    tags: ["tuberculose", "complexo de Ranke", "TB primária"],
    fonte: FONTE,
  },
  {
    id: "inf-tb-002",
    subtemaId: SUB.tbDx,
    disciplinaId: "inf",
    enunciado:
      "Segundo o Ministério da Saúde, qual exame é preconizado como teste de escolha inicial para todo sintomático respiratório, substituindo a baciloscopia como primeira linha onde disponível?",
    alternativas: [
      { letra: "A", texto: "Cultura em meio líquido (MGIT).", correta: false, comentario: "É o padrão-ouro, mas demorada — não serve como triagem inicial." },
      { letra: "B", texto: "PPD (prova tuberculínica).", correta: false, comentario: "Avalia infecção latente, não doença ativa." },
      { letra: "C", texto: "TRM-TB (teste rápido molecular, GeneXpert).", correta: true, comentario: "O MS preconiza o TRM-TB como primeira linha: detecta o DNA do bacilo em ~2h e ainda identifica resistência à rifampicina." },
      { letra: "D", texto: "IGRA (interferon-gamma release assay).", correta: false, comentario: "Também avalia infecção latente, não doença ativa." },
    ],
    dificuldade: "fixacao",
    estilo: "conduta",
    tags: ["tuberculose", "TRM-TB", "GeneXpert"],
    fonte: FONTE,
  },
  {
    id: "inf-tb-003",
    subtemaId: SUB.tbDx,
    disciplinaId: "inf",
    enunciado:
      "Qual a duração total recomendada do tratamento da tuberculose meningoencefálica e osteoarticular com o esquema básico (RHZE/RH)?",
    alternativas: [
      { letra: "A", texto: "6 meses, igual à forma pulmonar.", correta: false, comentario: "6 meses é a duração da TB pulmonar; essas formas exigem tratamento mais longo." },
      { letra: "B", texto: "9 meses.", correta: false, comentario: "Não é a duração preconizada pelo MS para essas formas." },
      { letra: "C", texto: "12 meses, com fase de manutenção estendida.", correta: true, comentario: "TB meningoencefálica e osteoarticular: 12 meses (2 RHZE + 10 RH). Na meníngea associa-se corticoide." },
      { letra: "D", texto: "18 meses, exigindo fármacos de segunda linha.", correta: false, comentario: "Segunda linha só na resistência; o esquema básico é mantido." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["tuberculose", "TB meningoencefálica", "duração"],
    fonte: FONTE,
  },
  {
    id: "inf-tb-004",
    subtemaId: SUB.tbDx,
    disciplinaId: "inf",
    enunciado:
      "Paciente em uso do esquema RHZE evolui com discromatopsia (perda da percepção vermelho-verde) e redução da acuidade visual. Qual fármaco é o responsável mais provável?",
    alternativas: [
      { letra: "A", texto: "Rifampicina.", correta: false, comentario: "Causa coloração alaranjada de secreções e hepatotoxicidade, não neurite óptica." },
      { letra: "B", texto: "Isoniazida.", correta: false, comentario: "Classicamente causa neuropatia PERIFÉRICA (prevenida com piridoxina)." },
      { letra: "C", texto: "Pirazinamida.", correta: false, comentario: "Associa-se a hiperuricemia/artralgia e hepatotoxicidade." },
      { letra: "D", texto: "Etambutol.", correta: true, comentario: "O etambutol causa neurite óptica dose-dependente: discromatopsia vermelho-verde e queda da acuidade visual." },
    ],
    dificuldade: "fixacao",
    estilo: "diagnostico",
    tags: ["tuberculose", "etambutol", "neurite óptica"],
    fonte: FONTE,
  },
  {
    id: "inf-tb-005",
    subtemaId: SUB.tbLatente,
    disciplinaId: "inf",
    enunciado:
      "No tratamento da infecção latente pelo M. tuberculosis (ILTB/TPT), qual esquema é hoje considerado preferencial por melhor adesão?",
    alternativas: [
      { letra: "A", texto: "Isoniazida isolada por 6–9 meses.", correta: false, comentario: "Esquema clássico, mas longo — adesão bem pior." },
      { letra: "B", texto: "Rifampicina isolada por 4 meses.", correta: false, comentario: "É alternativa válida, porém o 3HP é o preferencial pela posologia semanal." },
      { letra: "C", texto: "3HP: isoniazida + rifapentina semanal, por 3 meses.", correta: true, comentario: "Apenas 12 doses semanais — curso curto com adesão muito superior, hoje preferencial." },
      { letra: "D", texto: "RHZE por 2 meses seguido de RH por 1 mês.", correta: false, comentario: "Esse é esquema de doença ATIVA, não de infecção latente." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["ILTB", "3HP", "rifapentina"],
    fonte: FONTE,
  },
  {
    id: "inf-tb-006",
    subtemaId: SUB.tbDx,
    disciplinaId: "inf",
    enunciado:
      "Paciente em tratamento de TB pulmonar apresenta urina e suor com coloração alaranjada após início do RHZE. Qual a conduta?",
    alternativas: [
      { letra: "A", texto: "Suspender o esquema e investigar hepatotoxicidade.", correta: false, comentario: "Não há relação com hepatotoxicidade; suspender por isso comprometeria o tratamento." },
      { letra: "B", texto: "Reduzir a dose de rifampicina pela metade.", correta: false, comentario: "Reduzir dose favorece resistência, sem qualquer benefício." },
      { letra: "C", texto: "Tranquilizar o paciente: é efeito benigno da rifampicina, sem necessidade de suspender.", correta: true, comentario: "A rifampicina cora secreções de laranja-avermelhado — efeito esperado e inofensivo; orientar evita abandono." },
      { letra: "D", texto: "Substituir a rifampicina por uma quinolona.", correta: false, comentario: "Trocar droga de primeira linha por efeito benigno é inadequado." },
    ],
    dificuldade: "fixacao",
    estilo: "conduta",
    tags: ["rifampicina", "efeito adverso", "adesão"],
    fonte: FONTE,
  },

  // ── MENINGITES ──────────────────────────────────────────────────
  {
    id: "inf-men-007",
    subtemaId: SUB.meningite,
    disciplinaId: "inf",
    enunciado:
      "Qual a principal indicação de tomografia de crânio ANTES da punção lombar na suspeita de meningite bacteriana?",
    alternativas: [
      { letra: "A", texto: "Todo paciente, sem exceção.", correta: false, comentario: "TC universal atrasa o antibiótico e piora o desfecho — não se faz de rotina." },
      { letra: "B", texto: "Apenas em pacientes acima de 60 anos.", correta: false, comentario: "A idade isolada não é o critério." },
      { letra: "C", texto: "Imunossupressão, lesão de SNC prévia, convulsão recente, papiledema, déficit focal ou rebaixamento importante da consciência.", correta: true, comentario: "São os preditores de lesão com efeito de massa (risco de herniação). Fora deles, punciona-se direto. Se a TC for necessária, colher hemocultura e iniciar ATB ANTES do exame." },
      { letra: "D", texto: "Apenas quando há suspeita de meningite viral.", correta: false, comentario: "A TC não diferencia meningite viral de bacteriana." },
    ],
    dificuldade: "avancada",
    estilo: "conduta",
    tags: ["meningite", "punção lombar", "TC de crânio"],
    fonte: FONTE,
  },
  {
    id: "inf-men-008",
    subtemaId: SUB.meningite,
    disciplinaId: "inf",
    enunciado:
      "Em qual situação a Listeria monocytogenes deve ser obrigatoriamente coberta no esquema empírico da meningite bacteriana?",
    alternativas: [
      { letra: "A", texto: "Crianças entre 1 e 5 anos.", correta: false, comentario: "Nessa faixa predominam meningococo e pneumococo." },
      { letra: "B", texto: "Pacientes acima de 50 anos, gestantes, etilistas ou imunossuprimidos.", correta: true, comentario: "São os grupos de risco para Listeria → acrescentar AMPICILINA ao esquema (a cefalosporina de 3ª geração não cobre Listeria)." },
      { letra: "C", texto: "Apenas em recém-nascidos.", correta: false, comentario: "O RN é grupo de risco, mas não o único — a cobertura vai além dele." },
      { letra: "D", texto: "Não é necessário cobrir Listeria em nenhuma faixa etária.", correta: false, comentario: "Deixar Listeria descoberta nos grupos de risco é erro grave." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["meningite", "Listeria", "ampicilina"],
    fonte: FONTE,
  },
  {
    id: "inf-men-009",
    subtemaId: SUB.meningite,
    disciplinaId: "inf",
    enunciado:
      "A dexametasona reduz sequelas neurológicas (especialmente perda auditiva) na meningite bacteriana. Qual o momento ideal de administração?",
    alternativas: [
      { letra: "A", texto: "Apenas após a cultura do líquor identificar o agente.", correta: false, comentario: "Esperar a cultura perde completamente a janela terapêutica." },
      { letra: "B", texto: "24 horas após o antibiótico, quando a lise bacteriana já ocorreu.", correta: false, comentario: "Tarde demais: o objetivo é justamente conter a inflamação DA lise." },
      { letra: "C", texto: "Junto ou pouco antes da primeira dose do antibiótico.", correta: true, comentario: "O corticoide precisa estar presente quando a lise bacteriana liberar componentes inflamatórios — depois disso perde o benefício." },
      { letra: "D", texto: "Somente na meningite meningocócica confirmada.", correta: false, comentario: "O maior benefício é justamente na pneumocócica." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["meningite", "dexametasona"],
    fonte: FONTE,
  },
  {
    id: "inf-men-010",
    subtemaId: SUB.meningite,
    disciplinaId: "inf",
    enunciado: "Sobre a quimioprofilaxia de contatos próximos na meningite bacteriana, assinale a correta:",
    alternativas: [
      { letra: "A", texto: "É indicada de rotina tanto para meningococo quanto para pneumococo.", correta: false, comentario: "Não há indicação de rotina no pneumococo." },
      { letra: "B", texto: "Indicada na doença meningocócica (rifampicina 600 mg 12/12h por 2 dias no adulto) e seletivamente no Hib, mas não é rotina no pneumococo.", correta: true, comentario: "Meningococo e Hib têm transmissão por contato próximo prolongado; o pneumococo não justifica quimioprofilaxia de contatos." },
      { letra: "C", texto: "Indicada apenas se o caso índice evoluir para óbito.", correta: false, comentario: "A indicação independe do desfecho do caso índice." },
      { letra: "D", texto: "Feita exclusivamente com ceftriaxona IM em todos os contatos.", correta: false, comentario: "A ceftriaxona é alternativa (ex.: gestantes); a rifampicina é a opção padrão." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["meningite", "quimioprofilaxia", "rifampicina"],
    fonte: FONTE,
  },
  {
    id: "inf-men-011",
    subtemaId: SUB.meningite,
    disciplinaId: "inf",
    enunciado:
      "Qual a principal sequela da meningite bacteriana (sobretudo pneumocócica) que justifica audiometria após a alta?",
    alternativas: [
      { letra: "A", texto: "Perda auditiva neurossensorial.", correta: true, comentario: "É a sequela mais frequente (inflamação coclear/VIII par) — daí a audiometria de rotina após a alta e o uso precoce de dexametasona." },
      { letra: "B", texto: "Cegueira cortical.", correta: false, comentario: "Possível, porém rara." },
      { letra: "C", texto: "Paralisia facial periférica bilateral.", correta: false, comentario: "Não é a sequela característica." },
      { letra: "D", texto: "Anosmia permanente.", correta: false, comentario: "Não é sequela típica de meningite bacteriana." },
    ],
    dificuldade: "fixacao",
    estilo: "diagnostico",
    tags: ["meningite", "sequela", "perda auditiva"],
    fonte: FONTE,
  },
  {
    id: "inf-men-012",
    subtemaId: SUB.meningite,
    disciplinaId: "inf",
    enunciado: "Sobre os sinais de Kernig e Brudzinski na suspeita de meningite, qual afirmativa está correta?",
    alternativas: [
      { letra: "A", texto: "Têm alta sensibilidade isolada; a ausência de ambos exclui meningite com segurança.", correta: false, comentario: "Perigoso: a ausência NÃO exclui meningite." },
      { letra: "B", texto: "Têm sensibilidade baixa isoladamente; a ausência não exclui meningite.", correta: true, comentario: "A sensibilidade é baixa (~5–30%) — a suspeita clínica manda puncionar mesmo com esses sinais negativos." },
      { letra: "C", texto: "São específicos apenas para meningite viral.", correta: false, comentario: "Refletem irritação meníngea de qualquer etiologia." },
      { letra: "D", texto: "Devem substituir a punção lombar quando positivos.", correta: false, comentario: "Nada substitui a punção — é ela que define etiologia e conduta." },
    ],
    dificuldade: "intermediaria",
    estilo: "diagnostico",
    tags: ["meningite", "Kernig", "Brudzinski", "semiologia"],
    fonte: FONTE,
  },

  // ── SÍFILIS ─────────────────────────────────────────────────────
  {
    id: "inf-sif-013",
    subtemaId: SUB.sifilis,
    disciplinaId: "inf",
    enunciado: "Qual característica diferencia classicamente o cancro duro (sífilis primária) do cancro mole (H. ducreyi)?",
    alternativas: [
      { letra: "A", texto: "O cancro duro é doloroso e o cancro mole é indolor.", correta: false, comentario: "Está invertido." },
      { letra: "B", texto: "O cancro duro é indolor e o cancro mole é doloroso.", correta: true, comentario: "Cancro duro (T. pallidum): úlcera única, indolor, base endurecida, fundo limpo. Cancro mole (H. ducreyi): múltiplas, dolorosas, fundo sujo." },
      { letra: "C", texto: "Apenas o cancro mole apresenta adenopatia satélite.", correta: false, comentario: "Ambos cursam com adenopatia; no cancro mole ela supura (bubão)." },
      { letra: "D", texto: "O cancro duro é sempre múltiplo.", correta: false, comentario: "Classicamente é lesão ÚNICA." },
    ],
    dificuldade: "fixacao",
    estilo: "diagnostico",
    tags: ["sífilis", "cancro duro", "cancro mole"],
    fonte: FONTE,
  },
  {
    id: "inf-sif-014",
    subtemaId: SUB.sifilis,
    disciplinaId: "inf",
    enunciado: "Sobre os testes sorológicos para sífilis, qual afirmativa está correta?",
    alternativas: [
      { letra: "A", texto: "Os testes não-treponêmicos (VDRL/RPR) permanecem reagentes para sempre, mesmo após o tratamento.", correta: false, comentario: "É o oposto: os testes NÃO-treponêmicos caem com o tratamento; são os treponêmicos que permanecem reagentes pela vida toda." },
      { letra: "B", texto: "Os testes treponêmicos (FTA-Abs) servem para seguimento de cura, pois seus títulos caem com o tratamento.", correta: false, comentario: "Os treponêmicos não são usados para seguimento — permanecem reagentes mesmo após cura." },
      { letra: "C", texto: "O VDRL é usado para diagnóstico de atividade e seguimento de resposta terapêutica, sendo quantificável em títulos.", correta: true, comentario: "VDRL/RPR são quantificáveis; queda de pelo menos 2 diluições em 3 meses indica sucesso terapêutico." },
      { letra: "D", texto: "Testes treponêmicos não podem apresentar falso-positivo em nenhuma situação clínica.", correta: false, comentario: "Nenhum teste é infalível; a afirmativa absoluta já a torna incorreta." },
    ],
    dificuldade: "intermediaria",
    estilo: "diagnostico",
    tags: ["sífilis", "VDRL", "sorologia"],
    fonte: FONTE,
  },
  {
    id: "inf-sif-015",
    subtemaId: SUB.sifilis,
    disciplinaId: "inf",
    enunciado: "Qual é o tratamento de escolha para neurossífilis, em qualquer fase da doença?",
    alternativas: [
      { letra: "A", texto: "Penicilina G benzatina 2,4 milhões UI IM, dose única.", correta: false, comentario: "A benzatina não atinge concentrações liquóricas adequadas — não trata neurossífilis." },
      { letra: "B", texto: "Penicilina G benzatina 2,4 milhões UI IM, semanal por 3 semanas.", correta: false, comentario: "Esse é o esquema para sífilis latente tardia, não para neurossífilis." },
      { letra: "C", texto: "Penicilina G cristalina EV, 18–24 milhões UI/dia, por 10–14 dias.", correta: true, comentario: "A via endovenosa fracionada a cada 4h é necessária para atingir concentração liquórica terapêutica." },
      { letra: "D", texto: "Doxiciclina 100 mg 12/12h por 28 dias.", correta: false, comentario: "Não é o tratamento de escolha para neurossífilis; penicilina cristalina EV é insubstituível nesse contexto." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["sífilis", "neurossífilis", "penicilina"],
    fonte: FONTE,
  },
  {
    id: "inf-sif-016",
    subtemaId: SUB.sifilis,
    disciplinaId: "inf",
    enunciado:
      "A reação de Jarisch-Herxheimer, que pode ocorrer nas primeiras 24 horas após a primeira dose de penicilina no tratamento da sífilis, caracteriza-se por:",
    alternativas: [
      { letra: "A", texto: "Reação alérgica grave que contraindica a continuidade do tratamento com penicilina.", correta: false, comentario: "Não é reação alérgica — é causada pela lise maciça de espiroquetas." },
      { letra: "B", texto: "Reação febril aguda por lise maciça de espiroquetas, que não contraindica a continuidade do tratamento.", correta: true, comentario: "Febre, mialgia, cefaleia e piora transitória das lesões; manejo é sintomático, sem suspender a penicilina." },
      { letra: "C", texto: "Sinal de resistência bacteriana à penicilina, exigindo troca imediata para doxiciclina.", correta: false, comentario: "Não indica resistência — o T. pallidum não desenvolveu resistência documentada à penicilina." },
      { letra: "D", texto: "Evento exclusivo da sífilis terciária, nunca observado em fases mais precoces.", correta: false, comentario: "Pode ocorrer em qualquer fase tratada, não é exclusivo da terciária." },
    ],
    dificuldade: "intermediaria",
    estilo: "diagnostico",
    tags: ["sífilis", "Jarisch-Herxheimer"],
    fonte: FONTE,
  },
  {
    id: "inf-sif-017",
    subtemaId: SUB.sifilis,
    disciplinaId: "inf",
    enunciado: "Qual dos seguintes é um achado clássico de sífilis congênita na radiografia de ossos longos?",
    alternativas: [
      { letra: "A", texto: "Sinal de Wimberger (rarefação da metáfise proximal da tíbia).", correta: true, comentario: "Junto à pseudoparalisia de Parrot, reflete periostite/metafisite da sífilis congênita." },
      { letra: "B", texto: "Sinal do duplo contorno.", correta: false, comentario: "Não é achado de sífilis congênita — é descrito em outros contextos radiológicos." },
      { letra: "C", texto: "Sinal de Codman.", correta: false, comentario: "Achado clássico de osteossarcoma, não de sífilis congênita." },
      { letra: "D", texto: "Triângulo de Codman com reação periosteal em 'casca de cebola'.", correta: false, comentario: "Padrão de sarcoma de Ewing, não de sífilis congênita." },
    ],
    dificuldade: "avancada",
    estilo: "diagnostico",
    tags: ["sífilis congênita", "radiografia", "sinal de Wimberger"],
    fonte: FONTE,
  },
  {
    id: "inf-sif-018",
    subtemaId: SUB.sifilis,
    disciplinaId: "inf",
    enunciado:
      "Para que o tratamento da sífilis na gestação seja considerado adequado, evitando a notificação da criança como sífilis congênita, quais critérios devem ser cumpridos simultaneamente?",
    alternativas: [
      { letra: "A", texto: "Apenas o uso de penicilina benzatina, independentemente do momento da gestação.", correta: false, comentario: "O momento importa: precisa ser iniciado até 30 dias antes do parto." },
      { letra: "B", texto: "Esquema completo com penicilina benzatina para o estágio, iniciado até 30 dias antes do parto, com queda documentada de titulação e parceiro tratado.", correta: true, comentario: "Todos os critérios devem ser cumpridos simultaneamente; a falta de qualquer um leva à notificação da criança como sífilis congênita." },
      { letra: "C", texto: "Uso de doxiciclina como alternativa válida em qualquer trimestre, desde que o parceiro seja tratado.", correta: false, comentario: "Doxiciclina é contraindicada na gestação — não atravessa a placenta de forma eficaz para proteger o feto." },
      { letra: "D", texto: "Apenas a queda do título de VDRL, independentemente do tratamento do parceiro.", correta: false, comentario: "O tratamento do parceiro é critério obrigatório, não dispensável." },
    ],
    dificuldade: "avancada",
    estilo: "conduta",
    tags: ["sífilis gestacional", "sífilis congênita", "tratamento adequado"],
    fonte: FONTE,
  },

  // ── HIV/AIDS ─────────────────────────────────────────────────────
  {
    id: "inf-hiv-019",
    subtemaId: SUB.hiv,
    disciplinaId: "inf",
    enunciado: "Segundo a estratégia 'treat all' atualmente recomendada, qual é o critério de CD4 para indicação de início de TARV?",
    alternativas: [
      { letra: "A", texto: "CD4 < 500 células/mm³.", correta: false, comentario: "Não há mais corte de CD4 para indicar TARV." },
      { letra: "B", texto: "CD4 < 350 células/mm³.", correta: false, comentario: "Critério de estratégias antigas, superado pelo 'treat all'." },
      { letra: "C", texto: "TARV indicada para todo paciente HIV positivo, independentemente do valor de CD4 ou carga viral.", correta: true, comentario: "O 'treat all' recomenda início o mais precocemente possível para todo HIV+, reduzindo transmissibilidade e morbimortalidade." },
      { letra: "D", texto: "CD4 < 200 células/mm³, correspondendo à definição de AIDS.", correta: false, comentario: "Esse é o corte para definição de AIDS, não o critério de início de TARV hoje." },
    ],
    dificuldade: "fixacao",
    estilo: "fixacao",
    tags: ["HIV", "TARV", "treat all"],
    fonte: FONTE,
  },
  {
    id: "inf-hiv-020",
    subtemaId: SUB.hiv,
    disciplinaId: "inf",
    enunciado: "Qual é o esquema antirretroviral preferencial de primeira linha para adultos virgens de tratamento no Brasil atualmente?",
    alternativas: [
      { letra: "A", texto: "Zidovudina + lamivudina + efavirenz.", correta: false, comentario: "Esquema antigo, substituído pelo esquema com dolutegravir." },
      { letra: "B", texto: "Tenofovir + lamivudina + dolutegravir (TDF+3TC+DTG).", correta: true, comentario: "Comprimido de dose fixa combinada, 1x/dia; dolutegravir tem alta barreira genética à resistência." },
      { letra: "C", texto: "Tenofovir + entricitabina + ritonavir.", correta: false, comentario: "Ritonavir é usado como booster de inibidores de protease, não faz parte do esquema preferencial atual." },
      { letra: "D", texto: "Abacavir + lamivudina + darunavir.", correta: false, comentario: "Não é o esquema de primeira linha preferencial no Brasil." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["HIV", "TARV", "dolutegravir"],
    fonte: FONTE,
  },
  {
    id: "inf-hiv-021",
    subtemaId: SUB.hiv,
    disciplinaId: "inf",
    enunciado: "Em relação à coinfecção TB-HIV, qual o momento correto para início da TARV conforme o valor de CD4?",
    alternativas: [
      { letra: "A", texto: "CD4 < 50: iniciar TARV em até 2 semanas do início do tratamento de TB; CD4 ≥ 50: iniciar entre 8-12 semanas.", correta: true, comentario: "Quanto mais imunossuprimido, mais precoce a TARV, apesar do risco de síndrome de reconstituição imune (SIRI) — o benefício supera o risco." },
      { letra: "B", texto: "TARV deve sempre ser iniciada no mesmo dia do diagnóstico de TB, independentemente do CD4.", correta: false, comentario: "Início simultâneo aumenta muito o risco de SIRI grave; o momento depende do CD4." },
      { letra: "C", texto: "TARV deve ser postergada até o término completo do tratamento de TB, para evitar SIRI.", correta: false, comentario: "Postergar tanto aumenta a mortalidade, especialmente em CD4 baixo." },
      { letra: "D", texto: "CD4 < 50: iniciar TARV apenas após 8 semanas; CD4 ≥ 50: iniciar imediatamente.", correta: false, comentario: "Está invertido — quanto menor o CD4, mais precoce deve ser o início." },
    ],
    dificuldade: "avancada",
    estilo: "conduta",
    tags: ["HIV", "tuberculose", "coinfecção", "SIRI"],
    fonte: FONTE,
  },
  {
    id: "inf-hiv-022",
    subtemaId: SUB.hiv,
    disciplinaId: "inf",
    enunciado: "Qual profilaxia primária é indicada para pneumocistose em pacientes HIV positivos com CD4 < 200 células/mm³?",
    alternativas: [
      { letra: "A", texto: "Azitromicina semanal.", correta: false, comentario: "Azitromicina é usada na profilaxia de complexo Mycobacterium avium, não de pneumocistose." },
      { letra: "B", texto: "Sulfametoxazol-trimetoprima (SMX-TMP).", correta: true, comentario: "Mesma droga também previne neurotoxoplasmose (indicada se CD4 < 100 e IgG antitoxoplasma reagente)." },
      { letra: "C", texto: "Fluconazol diário.", correta: false, comentario: "Fluconazol é usado no tratamento/profilaxia de candidíase e criptococose, não de pneumocistose." },
      { letra: "D", texto: "Ganciclovir profilático.", correta: false, comentario: "Ganciclovir é usado para citomegalovírus, não para pneumocistose." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["HIV", "pneumocistose", "profilaxia"],
    fonte: FONTE,
  },
  {
    id: "inf-hiv-023",
    subtemaId: SUB.hiv,
    disciplinaId: "inf",
    enunciado: "Sobre o conceito 'Indetectável = Intransmissível (I=I)', assinale a alternativa correta.",
    alternativas: [
      { letra: "A", texto: "Elimina o risco de transmissão sexual quando a carga viral está indetectável de forma sustentada, mas não altera a contraindicação absoluta de amamentação em mães HIV positivas no Brasil.", correta: true, comentario: "I=I vale para transmissão sexual; a amamentação continua contraindicada no Brasil independentemente da carga viral materna, substituída por fórmula." },
      { letra: "B", texto: "Permite a amamentação segura em mães HIV positivas com carga viral indetectável.", correta: false, comentario: "A contraindicação à amamentação é absoluta no Brasil, mesmo com carga viral indetectável." },
      { letra: "C", texto: "Aplica-se apenas à transmissão vertical, não à transmissão sexual.", correta: false, comentario: "É o oposto: I=I refere-se especificamente à transmissão sexual." },
      { letra: "D", texto: "É válido apenas para pacientes em uso de inibidores de protease.", correta: false, comentario: "O conceito vale para qualquer esquema TARV eficaz, não é específico de classe de fármaco." },
    ],
    dificuldade: "avancada",
    estilo: "diagnostico",
    tags: ["HIV", "I=I", "amamentação", "transmissão"],
    fonte: FONTE,
  },
  {
    id: "inf-hiv-024",
    subtemaId: SUB.hiv,
    disciplinaId: "inf",
    enunciado:
      "Qual é o prazo máximo recomendado para início da profilaxia pós-exposição (PEP) ao HIV após exposição sexual desprotegida ou acidente biológico?",
    alternativas: [
      { letra: "A", texto: "24 horas, idealmente na primeira hora.", correta: false, comentario: "O prazo máximo é maior que 24h." },
      { letra: "B", texto: "72 horas, idealmente nas primeiras 2 horas.", correta: true, comentario: "PEP mantida por 28 dias, com o mesmo esquema TARV preferencial do tratamento — quanto mais precoce, maior a eficácia." },
      { letra: "C", texto: "7 dias, sem necessidade de pressa.", correta: false, comentario: "Prazo muito além do recomendado — a eficácia cai com o atraso." },
      { letra: "D", texto: "48 horas, apenas em caso de violência sexual.", correta: false, comentario: "O prazo de 72h vale para qualquer exposição de risco, não só violência sexual." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["HIV", "PEP", "profilaxia pós-exposição"],
    fonte: FONTE,
  },

  // ── DENGUE E ARBOVIROSES ────────────────────────────────────────
  {
    id: "inf-den-025",
    subtemaId: SUB.dengue,
    disciplinaId: "inf",
    enunciado: "Qual é o principal fator de risco para o desenvolvimento de dengue grave?",
    alternativas: [
      { letra: "A", texto: "Primeira infecção por qualquer sorotipo.", correta: false, comentario: "A primoinfecção costuma ser mais branda; o risco de gravidade aumenta na reinfecção por outro sorotipo." },
      { letra: "B", texto: "Infecção secundária por sorotipo diferente do da infecção prévia (mecanismo de ADE).", correta: true, comentario: "Anticorpos heterotípicos não neutralizantes facilitam a entrada viral em macrófagos (amplificação dependente de anticorpos), aumentando a resposta inflamatória e o extravasamento plasmático." },
      { letra: "C", texto: "Uso prévio de vacina, independentemente de infecção prévia.", correta: false, comentario: "Não é o fator clássico de gravidade; a vacina tem indicações específicas conforme sorostatus." },
      { letra: "D", texto: "Idade entre 20 e 30 anos.", correta: false, comentario: "Extremos de idade e comorbidades pesam mais; a faixa citada não é fator de risco por si." },
    ],
    dificuldade: "intermediaria",
    estilo: "fixacao",
    tags: ["dengue", "ADE", "dengue grave"],
    fonte: FONTE,
  },
  {
    id: "inf-den-026",
    subtemaId: SUB.dengue,
    disciplinaId: "inf",
    enunciado: "Em qual momento da evolução da dengue costumam surgir os sinais de alarme?",
    alternativas: [
      { letra: "A", texto: "Nos primeiros dois dias de febre alta.", correta: false, comentario: "A fase febril inicial raramente traz os sinais de alarme." },
      { letra: "B", texto: "Tipicamente quando a febre cede (defervescência), entre o 3º e o 7º dia.", correta: true, comentario: "A defervescência marca a entrada na fase crítica: é quando ocorre o extravasamento plasmático. A queda da febre NÃO é melhora." },
      { letra: "C", texto: "Apenas na convalescença.", correta: false, comentario: "A convalescença é fase de recuperação (risco de hipervolemia), não de surgimento de alarme." },
      { letra: "D", texto: "Sem relação temporal com a febre.", correta: false, comentario: "Há relação clara: a fase crítica gira em torno da defervescência." },
    ],
    dificuldade: "fixacao",
    estilo: "fixacao",
    tags: ["dengue", "sinais de alarme", "fase crítica"],
    fonte: FONTE,
  },
  {
    id: "inf-den-027",
    subtemaId: SUB.dengue,
    disciplinaId: "inf",
    enunciado: "Qual classe de analgésico/antitérmico é formalmente contraindicada enquanto houver suspeita de dengue?",
    alternativas: [
      { letra: "A", texto: "Paracetamol.", correta: false, comentario: "É a primeira escolha sintomática na dengue." },
      { letra: "B", texto: "Dipirona.", correta: false, comentario: "Também é opção aceita para febre/dor na dengue." },
      { letra: "C", texto: "AAS e AINEs, pelo risco hemorrágico.", correta: true, comentario: "AAS e anti-inflamatórios aumentam o risco de sangramento (e AAS traz risco de síndrome de Reye em crianças) — proibidos na suspeita de dengue." },
      { letra: "D", texto: "Todos os antitérmicos até confirmação laboratorial.", correta: false, comentario: "Paracetamol e dipirona são liberados; não se espera exame para controlar a febre." },
    ],
    dificuldade: "fixacao",
    estilo: "conduta",
    tags: ["dengue", "AAS", "AINE", "contraindicação"],
    fonte: FONTE,
  },
  {
    id: "inf-den-028",
    subtemaId: SUB.dengue,
    disciplinaId: "inf",
    enunciado: "Qual manifestação é mais sugestiva de zika em comparação com dengue e chikungunya?",
    alternativas: [
      { letra: "A", texto: "Febre alta com artralgia intensa e simétrica.", correta: false, comentario: "Artralgia intensa e incapacitante aponta para chikungunya." },
      { letra: "B", texto: "Exantema pruriginoso precoce (1º–2º dia) com conjuntivite não purulenta e febre baixa ou ausente.", correta: true, comentario: "É o padrão típico da zika — além do risco de microcefalia (vertical) e Guillain-Barré." },
      { letra: "C", texto: "Plaquetopenia progressiva com hemoconcentração.", correta: false, comentario: "Marca do extravasamento na dengue, não da zika." },
      { letra: "D", texto: "Dor retro-orbitária intensa com febre de 39–40 °C.", correta: false, comentario: "Mais característico da dengue." },
    ],
    dificuldade: "intermediaria",
    estilo: "diagnostico",
    tags: ["zika", "arboviroses", "diagnóstico diferencial"],
    fonte: FONTE,
  },
  {
    id: "inf-den-029",
    subtemaId: SUB.dengue,
    disciplinaId: "inf",
    enunciado: "Segundo a classificação de risco do MS para dengue, qual a conduta no Grupo D (choque)?",
    alternativas: [
      { letra: "A", texto: "Hidratação oral abundante e retorno se sinal de alarme.", correta: false, comentario: "Conduta do Grupo A (sem alarme), inadequada no choque." },
      { letra: "B", texto: "Soro fisiológico 0,9% 10 mL/kg em 1 hora.", correta: false, comentario: "É a expansão do Grupo C (com sinais de alarme), não do choque." },
      { letra: "C", texto: "SF 0,9% 20 mL/kg em até 20 minutos, repetindo até 3 vezes, com internação em UTI.", correta: true, comentario: "Grupo D = choque: expansão rápida e vigorosa, reavaliando após cada bolus, em ambiente de terapia intensiva." },
      { letra: "D", texto: "Observação ambulatorial com hemograma seriado.", correta: false, comentario: "Inaceitável no choque, que exige expansão imediata." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["dengue", "grupo D", "choque", "expansão"],
    fonte: FONTE,
  },

  // ── SEPSE E CHOQUE SÉPTICO ──────────────────────────────────────
  {
    id: "inf-sep-030",
    subtemaId: SUB.sepse,
    disciplinaId: "inf",
    enunciado: "Segundo o consenso Sepsis-3, qual afirmativa está correta sobre o qSOFA?",
    alternativas: [
      { letra: "A", texto: "É critério diagnóstico definitivo de sepse, dispensando o SOFA.", correta: false, comentario: "O qSOFA não fecha diagnóstico — é ferramenta de alerta." },
      { letra: "B", texto: "É triagem rápida à beira do leito, não critério diagnóstico definitivo — o diagnóstico exige SOFA ≥ 2.", correta: true, comentario: "qSOFA (FR ≥ 22, PAS ≤ 100, Glasgow < 15) sinaliza risco; sepse = infecção + aumento do SOFA ≥ 2. A Surviving Sepsis desaconselha usá-lo como triagem única." },
      { letra: "C", texto: "Deve ser calculado apenas em pacientes já em UTI.", correta: false, comentario: "É justamente uma ferramenta de beira de leito, fora da UTI." },
      { letra: "D", texto: "Substitui a coleta de lactato.", correta: false, comentario: "O lactato é parte da avaliação e da ressuscitação; o qSOFA não o substitui." },
    ],
    dificuldade: "intermediaria",
    estilo: "fixacao",
    tags: ["sepse", "qSOFA", "Sepsis-3"],
    fonte: FONTE,
  },
  {
    id: "inf-sep-031",
    subtemaId: SUB.sepse,
    disciplinaId: "inf",
    enunciado: "Como é definido o choque séptico segundo o Sepsis-3?",
    alternativas: [
      { letra: "A", texto: "Qualquer séptico com PAS < 90 mmHg em algum momento.", correta: false, comentario: "Hipotensão transitória não define choque séptico." },
      { letra: "B", texto: "Necessidade de vasopressor para PAM ≥ 65 mmHg + lactato > 2 mmol/L, apesar de reposição volêmica adequada.", correta: true, comentario: "É a definição do Sepsis-3 — a combinação de vasoplegia refratária a volume e hiperlactatemia, com mortalidade > 40%." },
      { letra: "C", texto: "SOFA ≥ 4, independentemente de vasopressor.", correta: false, comentario: "O SOFA gradua disfunção, mas não define choque isoladamente." },
      { letra: "D", texto: "Febre + hipotensão transitória responsiva a volume.", correta: false, comentario: "Se responde a volume, não é choque séptico estabelecido." },
    ],
    dificuldade: "avancada",
    estilo: "fixacao",
    tags: ["choque séptico", "lactato", "Sepsis-3"],
    fonte: FONTE,
  },
  {
    id: "inf-sep-032",
    subtemaId: SUB.sepse,
    disciplinaId: "inf",
    enunciado: "Quais ações compõem o pacote da primeira hora (Hour-1 Bundle) da Surviving Sepsis Campaign?",
    alternativas: [
      { letra: "A", texto: "Lactato, 2 hemoculturas antes do ATB, antibiótico empírico amplo, cristaloide 30 mL/kg se indicado, vasopressor se PAM < 65 apesar de volume.", correta: true, comentario: "São as 5 ações iniciadas simultaneamente na 1ª hora. A hemocultura não deve atrasar o antibiótico." },
      { letra: "B", texto: "Apenas antibiótico e hemocultura.", correta: false, comentario: "Faltam lactato, reposição volêmica e vasopressor." },
      { letra: "C", texto: "TC de abdome, hemocultura, ATB, drenagem cirúrgica imediata e vasopressor.", correta: false, comentario: "TC e cirurgia não fazem parte do bundle de 1h (o controle do foco é conduzido à parte)." },
      { letra: "D", texto: "Sequência obrigatória em 3h/6h do protocolo antigo.", correta: false, comentario: "O modelo atual é o Hour-1 Bundle, simultâneo, não a divisão 3h/6h." },
    ],
    dificuldade: "avancada",
    estilo: "conduta",
    tags: ["sepse", "Hour-1 Bundle", "Surviving Sepsis"],
    fonte: FONTE,
  },
  {
    id: "inf-sep-033",
    subtemaId: SUB.sepse,
    disciplinaId: "inf",
    enunciado: "Qual é o vasopressor de primeira escolha no choque séptico?",
    alternativas: [
      { letra: "A", texto: "Dopamina.", correta: false, comentario: "Associa-se a mais arritmias; deixou de ser primeira escolha." },
      { letra: "B", texto: "Noradrenalina.", correta: true, comentario: "É o vasopressor de 1ª escolha; a vasopressina entra como 2ª droga (poupadora de catecolamina)." },
      { letra: "C", texto: "Adrenalina com hidrocortisona de rotina.", correta: false, comentario: "Hidrocortisona só no choque refratário; adrenalina não é a 1ª escolha." },
      { letra: "D", texto: "Vasopressina isolada.", correta: false, comentario: "A vasopressina é adjuvante, não usada isoladamente como 1ª droga." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["sepse", "noradrenalina", "vasopressor"],
    fonte: FONTE,
  },
];
