import type { Questao } from "@/domain/content/types";

type Row = [string, string, string, string, string, string, string];
const build = (disciplinaId: string, fonte: string, rows: Row[]): Questao[] => rows.map(([id, subtemaId, enunciado, correta, d1, d2, d3]) => {
  const disciplina = subtemaId.split("--")[0] || disciplinaId;
  return ({ id, disciplinaId: disciplina, subtemaId, enunciado,
  alternativas: [
    { letra: "A", texto: correta, correta: true, comentario: `Correta: ${correta}. O raciocínio deve ser aplicado junto ao quadro clínico e às diretrizes vigentes.` },
    { letra: "B", texto: d1, correta: false, comentario: `Distrator: ${d1}. Essa opção não responde ao achado central do caso.` },
    { letra: "C", texto: d2, correta: false, comentario: `Distrator: ${d2}. Não é a melhor interpretação neste contexto.` },
    { letra: "D", texto: d3, correta: false, comentario: `Distrator: ${d3}. A conduta deve ser individualizada e não se baseia apenas nessa afirmação.` },
  ], dificuldade: "intermediaria", estilo: "residencia", tags: [disciplina, "lote-editorial-2026"], fonte,
  });
});

const F_PED = "Ministério da Saúde/SBP/AAP — protocolos de pediatria e urgências; lote editorial revisado em 2026-08-03.";
export const QUESTOES_PED_LOTE_01 = build("ped", F_PED, [
  ["ped-lote01-001", "ped--emergencias-pediatricas--desidratacao-e-reidratacao", "Em criança com diarreia, letargia, olhos encovados e pulso fraco, qual prioridade?", "Classificar como desidratação grave e iniciar expansão/reidratação venosa conforme protocolo.", "Oferecer apenas suco por via oral e observar", "Aguardar coprocultura antes de hidratar", "Restringir líquidos para evitar vômitos"],
  ["ped-lote01-002", "ped--emergencias-pediatricas--desidratacao-e-reidratacao", "Qual sinal favorece desidratação em lactente?", "Mucosas secas, redução de lágrimas e enchimento capilar prolongado no conjunto clínico.", "Fontanela discretamente cheia", "Diurese aumentada", "Ganho ponderal rápido"],
  ["ped-lote01-003", "ped--emergencias-pediatricas--desidratacao-e-reidratacao", "Na reidratação oral de criança alerta, qual solução é preferível?", "Solução de reidratação oral com composição padronizada e administração fracionada.", "Refrigerante sem gás", "Água pura como única reposição", "Bebida energética hipertônica"],
  ["ped-lote01-004", "ped--infeccoes-respiratorias-na-infancia--bronquiolite", "Lactente com bronquiolite típica e boa saturação deve receber inicialmente:", "Suporte, higiene nasal, hidratação e oxigênio apenas se houver hipoxemia persistente.", "Antibiótico de rotina", "Corticoide sistêmico para todos", "Radiografia diária"],
  ["ped-lote01-005", "ped--infeccoes-respiratorias-na-infancia--bronquiolite", "Qual achado indica gravidade na bronquiolite?", "Apneia, exaustão, dificuldade alimentar importante ou hipoxemia persistente.", "Tosse isolada", "Coriza sem esforço", "Sibilo leve sem repercussão"],
  ["ped-lote01-006", "ped--infeccoes-respiratorias-na-infancia--crupe-laringotraqueobronquite", "Criança com crupe e estridor em repouso deve receber:", "Corticoide e, se moderado/grave, adrenalina nebulizada com observação após resposta.", "Apenas antitussígeno", "Antibiótico oral obrigatório", "Manobra de Heimlich"],
  ["ped-lote01-007", "ped--infeccoes-respiratorias-na-infancia--crupe-laringotraqueobronquite", "Qual sinal sugere epiglotite em vez de crupe viral?", "Toxemia, sialorreia, posição em tripé e ausência de tosse ladrante.", "Rouquidão isolada", "Coriza há uma semana", "Estridor apenas ao chorar"],
  ["ped-lote01-008", "ped--neonatologia--ictericia-neonatal", "Icterícia nas primeiras 24 horas de vida deve ser considerada:", "Potencialmente patológica, exigindo avaliação rápida de bilirrubina e hemólise.", "Fisiológica em todos os casos", "Indicativa de aleitamento suficiente", "Sem necessidade de exame"],
  ["ped-lote01-009", "ped--neonatologia--ictericia-neonatal", "Na hiperbilirrubinemia indireta neonatal, a fototerapia é indicada conforme:", "Bilirrubina total, idade pós-natal em horas, idade gestacional e fatores de risco.", "Apenas peso ao nascer", "Cor da pele isoladamente", "Bilirrubina direta isolada"],
  ["ped-lote01-010", "ped--emergencias-pediatricas--convulsao-febril", "Convulsão febril simples caracteriza-se por:", "Crise generalizada, breve, única no episódio e em criança sem infecção do SNC.", "Crise focal prolongada recorrente", "Crise sem febre", "Meningite confirmada"],
  ["ped-lote01-011", "ped--emergencias-pediatricas--convulsao-febril", "Durante convulsão ativa em criança, a primeira medida é:", "Proteger via aérea e segurança, cronometrar a crise e tratar se persistente conforme protocolo.", "Conter os membros à força", "Colocar objeto na boca", "Oferecer líquido durante a crise"],
  ["ped-lote01-012", "ped--emergencias-pediatricas--convulsao-febril", "Qual situação exige investigar causa secundária em convulsão febril?", "Sinais meníngeos, alteração persistente do sensório ou crise focal/prolongada.", "Primeiro episódio breve típico", "História familiar positiva", "Febre baixa isolada"],
  ["ped-lote01-013", "ped--emergencias-pediatricas--desidratacao-e-reidratacao", "Em diarreia aguda sem sinais de gravidade, antibiótico:", "Não é rotineiro; deve ser reservado a indicações específicas, como disenteria selecionada.", "É obrigatório em toda diarreia", "Substitui reidratação", "Previne todas as complicações"],
  ["ped-lote01-014", "ped--infeccoes-respiratorias-na-infancia--bronquiolite", "Em bronquiolite, o uso rotineiro de salbutamol:", "Não é recomendado de forma universal; pode ser considerado apenas em resposta clínica bem documentada.", "É obrigatório em todos os lactentes", "Cura a infecção viral", "Substitui oxigênio na hipoxemia"],
  ["ped-lote01-015", "ped--infeccoes-respiratorias-na-infancia--crupe-laringotraqueobronquite", "Estridor após engasgo súbito, sem pródromo viral, sugere:", "Corpo estranho de via aérea até prova em contrário.", "Crupe recorrente obrigatório", "Bronquiolite típica", "Laringite bacteriana comprovada"],
  ["ped-lote01-016", "ped--neonatologia--ictericia-neonatal", "A icterícia conjugada no recém-nascido:", "É sempre anormal e demanda investigação de colestase e doença hepatobiliar.", "É fisiológica até 30 dias", "Indica apenas aleitamento materno", "Dispensa fracionamento da bilirrubina"],
  ["ped-lote01-017", "ped--emergencias-pediatricas--convulsao-febril", "Após crise febril simples, a orientação adequada inclui:", "Orientar segurança, retorno se sinais de alarme e acompanhamento do desenvolvimento; anticonvulsivante contínuo não é rotina.", "Fenobarbital para toda criança", "Proibir vacinas", "Tomografia anual obrigatória"],
  ["ped-lote01-018", "ped--emergencias-pediatricas--desidratacao-e-reidratacao", "Qual achado sugere choque hipovolêmico em criança?", "Extremidades frias, pulsos fracos, alteração do sensório e perfusão periférica ruim.", "Pressão normal exclui choque", "Apetite preservado", "Diurese aumentada"],
  ["ped-lote01-019", "ped--infeccoes-respiratorias-na-infancia--bronquiolite", "Em lactente com bronquiolite, alimentação por sonda pode ser considerada quando:", "O esforço respiratório impede ingestão segura, mantendo atenção ao risco de aspiração.", "Há apenas coriza", "A família solicita exame", "A saturação está normal e sem esforço"],
  ["ped-lote01-020", "ped--neonatologia--ictericia-neonatal", "No recém-nascido com icterícia e anemia, o próximo passo inclui:", "Investigar incompatibilidade sanguínea, reticulócitos, esfregaço e teste de antiglobulina conforme o caso.", "Presumir icterícia fisiológica", "Suspender toda alimentação", "Dar ferro antes de medir bilirrubina"],
]);

const F_CIR_MFC = "MS/WSES/SBC — princípios de cirurgia, atenção primária e segurança do paciente; lote editorial revisado em 2026-08-03.";
export const QUESTOES_CIR_MFC_LOTE_01 = build("cir", F_CIR_MFC, [
  ["cir-mfc-lote01-001", "cir--abdome-agudo--colecistite-e-colangite", "Na suspeita de colecistite aguda, o exame inicial mais útil costuma ser:", "Ultrassonografia de abdome, correlacionada com dor, febre e marcadores inflamatórios.", "Colonoscopia urgente", "Ressonância cerebral", "Densitometria óssea"],
  ["cir-mfc-lote01-002", "cir--abdome-agudo--colecistite-e-colangite", "A tríade de Charcot sugere colangite e combina:", "Febre, dor em hipocôndrio direito e icterícia.", "Tosse, hemoptise e febre", "Dor lombar, hematúria e edema", "Cefaleia, rigidez e exantema"],
  ["cir-mfc-lote01-003", "cir--abdome-agudo--colecistite-e-colangite", "Paciente com colangite e choque necessita inicialmente de:", "Suporte hemodinâmico, antibiótico e drenagem biliar urgente conforme disponibilidade e gravidade.", "Alta com analgésico", "Apenas dieta zero por 72 horas", "Colonoscopia eletiva"],
  ["cir-mfc-lote01-004", "cir--abdome-agudo--colecistite-e-colangite", "Na colecistite aguda, o tratamento definitivo em paciente operável é:", "Colecistectomia laparoscópica precoce após estabilização e avaliação anestésica.", "Apendicectomia", "Observação indefinida", "Corticoide isolado"],
  ["cir-mfc-lote01-005", "mfc--epidemiologia--tipos-de-estudo", "Estudo que acompanha expostos e não expostos ao longo do tempo é:", "Coorte, adequada para estimar incidência e risco relativo.", "Caso-controle exclusivamente", "Série de casos sem seguimento", "Estudo ecológico obrigatório"],
  ["cir-mfc-lote01-006", "mfc--epidemiologia--medidas-de-associacao", "O risco relativo é mais diretamente obtido em:", "Estudos de coorte, comparando incidência entre expostos e não expostos.", "Relato de caso único", "Estudo transversal sem denominador", "Opinião de especialista"],
  ["cir-mfc-lote01-007", "mfc--epidemiologia--medidas-de-associacao", "Uma medida de efeito nula para risco relativo é:", "RR igual a 1, indicando ausência de associação na escala multiplicativa.", "RR igual a 0 sempre", "RR maior que 10 sempre", "RR negativo"],
  ["cir-mfc-lote01-008", "mfc--epidemiologia--testes-diagnosticos-sensibilidade-e-especificidade", "Teste muito sensível é especialmente útil para:", "Ajudar a excluir doença quando o resultado é negativo em cenário apropriado.", "Confirmar toda doença com positivo", "Substituir o exame clínico", "Eliminar falsos positivos"],
  ["cir-mfc-lote01-009", "mfc--epidemiologia--testes-diagnosticos-sensibilidade-e-especificidade", "O valor preditivo positivo depende fortemente de:", "Prevalência pré-teste, além da sensibilidade e especificidade.", "Somente idade do aparelho", "Apenas tamanho da amostra histórica", "Apenas valor de referência laboratorial"],
  ["cir-mfc-lote01-010", "mfc--epidemiologia--tipos-de-estudo", "Viés de seleção ocorre quando:", "A forma de inclusão altera sistematicamente a comparabilidade entre grupos.", "Todos recebem o mesmo diagnóstico", "O desfecho é medido duas vezes", "A amostra é sempre aleatória"],
  ["cir-mfc-lote01-011", "cir--abdome-agudo--colecistite-e-colangite", "Dor em hipocôndrio direito com sinal de Murphy positivo favorece:", "Inflamação da vesícula biliar, devendo integrar quadro clínico e ultrassom.", "Pancreatite sempre", "Meningite", "Cistite simples"],
  ["cir-mfc-lote01-012", "cir--abdome-agudo--colecistite-e-colangite", "Em abdome agudo com instabilidade, a prioridade é:", "Reanimação simultânea, identificação de causas ameaçadoras e acionamento cirúrgico precoce.", "Aguardar todos os exames eletivos", "Oferecer laxante", "Realizar colonoscopia sem preparo"],
  ["cir-mfc-lote01-013", "mfc--epidemiologia--tipos-de-estudo", "O estudo caso-controle é eficiente especialmente para:", "Doenças raras ou com longo período de latência, partindo do desfecho.", "Calcular incidência diretamente sempre", "Medir prevalência em população inteira sem amostra", "Randomizar tratamento"],
  ["cir-mfc-lote01-014", "mfc--epidemiologia--medidas-de-associacao", "Confundimento ocorre quando:", "Uma terceira variável se associa à exposição e ao desfecho, distorcendo a relação observada.", "O desfecho é impossível de medir", "Há apenas erro de digitação", "A amostra é maior que a população"],
  ["cir-mfc-lote01-015", "mfc--epidemiologia--testes-diagnosticos-sensibilidade-e-especificidade", "Especificidade alta é útil para:", "Ajudar a confirmar doença quando o teste é positivo em contexto adequado.", "Descartar doença com resultado negativo", "Aumentar automaticamente a prevalência", "Substituir seguimento clínico"],
  ["cir-mfc-lote01-016", "cir--abdome-agudo--colecistite-e-colangite", "A presença de pneumoperitônio em paciente com peritonite sugere:", "Perfuração de víscera oca e necessidade de avaliação cirúrgica urgente.", "Gastrite simples", "Diarreia viral autolimitada", "Cefaleia tensional"],
  ["cir-mfc-lote01-017", "mfc--epidemiologia--tipos-de-estudo", "Ensaio clínico randomizado reduz principalmente:", "Confusão por distribuição aleatória de fatores prognósticos entre os grupos.", "Necessidade de consentimento", "Toda perda de seguimento", "Todo erro de mensuração"],
  ["cir-mfc-lote01-018", "mfc--epidemiologia--medidas-de-associacao", "A diferença absoluta de risco expressa:", "A diferença entre incidências dos grupos, útil para comunicar benefício ou dano absoluto.", "Apenas a razão entre médias", "A prevalência sem denominador", "A sensibilidade do exame"],
  ["cir-mfc-lote01-019", "cir--abdome-agudo--colecistite-e-colangite", "Antibiótico na infecção intra-abdominal deve considerar:", "Foco provável, gravidade, flora local, alergias e necessidade de controle de foco.", "Somente a cor da secreção", "Apenas o peso sem função renal", "Nenhuma cultura ou contexto"],
  ["cir-mfc-lote01-020", "mfc--epidemiologia--testes-diagnosticos-sensibilidade-e-especificidade", "A razão de verossimilhança positiva indica:", "Quanto um teste positivo aumenta a chance pré-teste da doença.", "A mortalidade bruta do hospital", "Apenas o número de pacientes incluídos", "A duração do tratamento"],
]);

const F_CNP = "SBC/SBN/Neurologia/SBPT — diretrizes de cardiologia, neurologia e pneumologia; lote editorial revisado em 2026-08-03.";
export const QUESTOES_CARDIO_NEURO_PNEUMO_LOTE_01 = build("clm", F_CNP, [
  ["clm-lote01-001", "cardio--sindrome-coronariana-aguda-sca-iam--diagnostico-e-conduta", "Na dor torácica suspeita de SCA, o ECG deve ser realizado idealmente em:", "Até 10 minutos da chegada, com repetição se o quadro persistir e o primeiro exame não for diagnóstico.", "Após troponina de 6 horas", "Somente após teste ergométrico", "Depois da alta"],
  ["clm-lote01-002", "cardio--sindrome-coronariana-aguda-sca-iam--diagnostico-e-conduta", "Troponina elevada indica:", "Lesão miocárdica, que precisa ser interpretada com dinâmica e evidência clínica de isquemia.", "Infarto tipo 1 em qualquer situação", "Apenas insuficiência renal", "Doença coronariana obstrutiva sempre"],
  ["clm-lote01-003", "cardio--sindrome-coronariana-aguda-sca-iam--diagnostico-e-conduta", "Em IAM com supra de ST, a prioridade é:", "Reperfusão imediata por estratégia disponível e apropriada, sem atrasos evitáveis.", "Aguardar teste funcional", "Prescrever somente estatina", "Adiar avaliação por 24 horas"],
  ["clm-lote01-004", "cardio--sindrome-coronariana-aguda-sca-iam--diagnostico-e-conduta", "A dupla antiagregação na SCA deve ser:", "Individualizada conforme estratégia de reperfusão, risco isquêmico e risco hemorrágico.", "Igual para todos sem contraindicação", "Contraindicada após stent", "Substituída sempre por anticoagulante"],
  ["clm-lote01-005", "neuro--avc-isquemico--diagnostico-e-conduta", "Antes da trombólise no AVC isquêmico, é essencial:", "TC de crânio sem contraste para excluir hemorragia e verificar critérios clínicos e temporais.", "PET cerebral de rotina", "Punção lombar em todos", "Angiografia coronária"],
  ["clm-lote01-006", "neuro--avc-isquemico--diagnostico-e-conduta", "Na suspeita de oclusão de grande vaso, deve-se considerar:", "Angioimagem e trombectomia mecânica em pacientes elegíveis, conforme janela e critérios.", "Apenas repouso", "Corticoide universal", "Antibiótico empírico para todos"],
  ["clm-lote01-007", "neuro--avc-hemorragico-hsa-e-hemorragia-intraparenquimatosa--diagnostico-e-conduta", "Cefaleia súbita máxima desde o início sugere:", "Hemorragia subaracnoidea até investigação adequada, mesmo sem déficit focal inicial.", "Cefaleia tensional típica", "Sinusite simples sempre", "Enxaqueca sem necessidade de avaliação"],
  ["clm-lote01-008", "neuro--avc-hemorragico-hsa-e-hemorragia-intraparenquimatosa--diagnostico-e-conduta", "Na hemorragia intracerebral, o manejo inicial inclui:", "Controle cuidadoso da pressão, reversão de anticoagulação quando indicada e avaliação neurocirúrgica.", "Trombólise imediata", "AAS em dose de ataque", "Alta se a dor melhorar"],
  ["clm-lote01-009", "neuro--crise-convulsiva-e-status-epilepticus--diagnostico-e-conduta", "Status epilepticus convulsivo exige inicialmente:", "Suporte ABC, glicemia e benzodiazepínico sem atrasar tratamento por exames não essenciais.", "Aguardar EEG antes de medicar", "Conter fisicamente o paciente", "Oferecer água"],
  ["clm-lote01-010", "neuro--crise-convulsiva-e-status-epilepticus--diagnostico-e-conduta", "Após benzodiazepínico sem controle da crise, a conduta é:", "Administrar fármaco de segunda linha e investigar causas reversíveis em paralelo.", "Encerrar atendimento", "Suspender monitorização", "Dar apenas antitérmico"],
  ["clm-lote01-011", "pneumo--derrame-pleural--diagnostico-e-conduta", "Pelos critérios de Light, exsudato é definido por:", "Pelo menos um critério positivo entre as razões de proteína/LDH ou LDH pleural elevado.", "Todos os critérios simultaneamente", "pH abaixo de 7,40 isolado", "Glicose sérica baixa isolada"],
  ["clm-lote01-012", "pneumo--derrame-pleural--diagnostico-e-conduta", "Derrame parapneumônico complicado costuma exigir:", "Antibiótico e drenagem quando há pus, pH muito baixo, loculações ou outros critérios de complicação.", "Apenas diurético", "Toracocentese nunca", "Corticoide isolado"],
  ["clm-lote01-013", "pneumo--tromboembolismo-pulmonar--diagnostico-e-conduta", "Na avaliação de TEP, o escore clínico serve para:", "Estimar probabilidade pré-teste e orientar D-dímero ou imagem, não substituir julgamento clínico.", "Confirmar TEP sozinho", "Excluir doença em choque", "Definir dose de antibiótico"],
  ["clm-lote01-014", "pneumo--tromboembolismo-pulmonar--diagnostico-e-conduta", "Paciente instável com alta suspeita de TEP requer:", "Suporte hemodinâmico e estratégia de reperfusão/anticoagulação conforme risco e contraindicações.", "Alta para casa", "D-dímero como único exame", "Antitussígeno"],
  ["clm-lote01-015", "cardio--insuficiencia-cardiaca--diagnostico-e-conduta", "Na insuficiência cardíaca com fração reduzida, terapias modificadoras incluem:", "Combinação baseada em evidências, como bloqueio neuro-hormonal e inibidor de SGLT2 quando indicado.", "Apenas diurético em todos", "Suspender todos os fármacos após melhora", "Antibiótico crônico"],
  ["clm-lote01-016", "neuro--cefaleias-primarias-e-sinais-de-alarme--diagnostico-e-conduta", "Qual é sinal de alarme em cefaleia?", "Início súbito explosivo, déficit focal, febre com rigidez ou mudança progressiva do padrão.", "Cefaleia estável há anos", "Melhora com sono", "História familiar de enxaqueca isolada"],
  ["clm-lote01-017", "pneumo--asma--diagnostico-e-conduta", "Crise asmática grave deve ser reconhecida por:", "Fala entrecortada, uso de musculatura acessória, hipoxemia, exaustão ou silêncio auscultatório.", "Tosse leve isolada", "Saturação normal e exame tranquilo", "Apenas rinorreia"],
  ["clm-lote01-018", "cardio--fibrilacao-atrial--diagnostico-e-conduta", "Na fibrilação atrial, a anticoagulação é decidida por:", "Risco tromboembólico, risco hemorrágico, preferências e contexto clínico, não pelo ECG isolado.", "Idade apenas", "Frequência cardíaca apenas", "Presença de palpitação apenas"],
  ["clm-lote01-019", "neuro--meningites--diagnostico-e-conduta", "Suspeita de meningite bacteriana com instabilidade exige:", "Coletar culturas sem atrasar antibiótico e suporte; punção lombar depende de segurança clínica.", "Aguardar líquor por horas", "Antiviral isolado sempre", "Alta após analgésico"],
  ["clm-lote01-020", "pneumo--doenca-pulmonar-obstrutiva-cronica-dpoc--diagnostico-e-conduta", "Exacerbação de DPOC deve ser manejada com:", "Broncodilatador de curta ação, oxigênio titulado e corticoide/antibiótico em indicações clínicas.", "Oxigênio em fluxo máximo para todos", "Antibiótico sempre por 30 dias", "Repouso sem broncodilatador"],
]);

const F_NGEH = "KDIGO/AGA/ASH/Endocrine Society — recomendações de nefrologia, gastroenterologia, hematologia e endocrinologia; lote editorial revisado em 2026-08-03.";
export const QUESTOES_NEFRO_GASTRO_HEMATO_ENDO_LOTE_01 = build("clinicas", F_NGEH, [
  ["nge-lote01-001", "nefro--sindromes-glomerulares--nefritica-e-nefrotica", "Hematúria dismórfica e cilindros hemáticos indicam:", "Origem glomerular da hematúria, devendo integrar proteinúria e função renal.", "Sangramento uretral isolado", "Cistite simples obrigatoriamente", "Contaminação menstrual comprovada"],
  ["nge-lote01-002", "nefro--sindromes-glomerulares--nefritica-e-nefrotica", "Síndrome nefrótica é caracterizada por:", "Proteinúria importante, hipoalbuminemia e edema, com investigação da causa.", "Apenas hematúria microscópica", "Hipercalcemia isolada", "Leucocitose sem proteinúria"],
  ["nge-lote01-003", "nefro--injuria-renal-aguda-e-doenca-renal-cronica--diagnostico-e-conduta", "Na injúria renal aguda, a avaliação inicial inclui:", "Revisão de volume, medicamentos, obstrução e tendência de creatinina/diurese.", "Ignorar débito urinário", "Apenas dosar ureia uma vez", "Iniciar diálise em todos"],
  ["nge-lote01-004", "nefro--injuria-renal-aguda-e-doenca-renal-cronica--diagnostico-e-conduta", "Indicação clássica de diálise urgente é:", "Hipercalemia refratária, acidose grave, sobrecarga refratária ou síndrome urêmica clinicamente relevante.", "Creatinina isolada abaixo de qualquer limite", "Edema leve responsivo a diurético", "Proteinúria sem complicação"],
  ["nge-lote01-005", "gastro--hepatites-virais--diagnostico-e-conduta", "Anti-HCV reagente deve ser seguido por:", "Pesquisa de HCV-RNA para definir infecção ativa.", "Nova dosagem do mesmo anticorpo apenas", "Biópsia imediata em todos", "Tireoglobulina"],
  ["nge-lote01-006", "gastro--cirrose-e-hipertensao-portal--diagnostico-e-conduta", "Ascite nova em paciente cirrótico deve ser avaliada por:", "Paracentese diagnóstica, incluindo contagem de polimorfonucleares e cultura.", "Apenas diurético sem análise", "Colonoscopia urgente sempre", "Restrição absoluta de proteína"],
  ["nge-lote01-007", "gastro--hemorragia-digestiva--diagnostico-e-conduta", "Na hemorragia digestiva alta com instabilidade, a prioridade é:", "Reanimação, avaliação de via aérea quando necessário e endoscopia após estabilização inicial.", "Aguardar hemoglobina normalizar", "Apenas antiácido oral", "Alta se o sangramento cessar"],
  ["nge-lote01-008", "gastro--doencas-inflamatorias-intestinais--diagnostico-e-conduta", "Na retocolite ulcerativa, sangue e muco com urgência evacuatória sugerem:", "Inflamação colônica contínua, cuja gravidade deve ser estratificada clínica e endoscopicamente.", "Doença exclusivamente gástrica", "Apendicite obrigatória", "Pancreatite isolada"],
  ["nge-lote01-009", "hemato--anemias--investigacao-e-classificacao", "Ferritina baixa em anemia microcítica indica:", "Deficiência de ferro, devendo investigar perdas, ingestão e absorção conforme idade e sexo.", "Talassemia isolada obrigatória", "Hemólise intravascular sempre", "Anemia aplástica"],
  ["nge-lote01-010", "hemato--anemias--investigacao-e-classificacao", "Reticulocitose em anemia sugere:", "Resposta medular aumentada, como hemólise ou perda sanguínea, se a medula estiver preservada.", "Falência medular pura", "Deficiência absoluta de eritropoietina sempre", "Ausência de destruição"],
  ["nge-lote01-011", "hemato--coagulopatias--investigacao-e-conduta", "TP prolongado isolado sugere alteração predominante da via:", "Extrínseca/comum, devendo considerar vitamina K, varfarina, fígado e outros contextos.", "Plaquetas apenas", "Fator VIII isolado obrigatoriamente", "Fibrinólise fisiológica"],
  ["nge-lote01-012", "hemato--coagulopatias--investigacao-e-conduta", "Na suspeita de trombocitopenia imune, a avaliação inicial deve:", "Confirmar contagem, revisar esfregaço e excluir causas secundárias e emergências hemorrágicas.", "Transfundir plaquetas em todos", "Ignorar medicamentos", "Fazer esplenectomia imediata"],
  ["nge-lote01-013", "endocrino--diabetes-mellitus--diagnostico-e-conduta", "Em cetoacidose diabética, a primeira prioridade terapêutica é:", "Reposição de volume e avaliação de potássio, seguida de insulina e correções protocolizadas.", "Insulina sem avaliar potássio", "Bicarbonato em todos", "Restringir líquidos"],
  ["nge-lote01-014", "endocrino--diabetes-mellitus--diagnostico-e-conduta", "Hipoglicemia em paciente consciente deve ser tratada com:", "Carboidrato de ação rápida e reavaliação, investigando a causa e prevenindo recorrência.", "Insulina adicional", "Jejum prolongado", "Apenas água"],
  ["nge-lote01-015", "endocrino--nodulo-e-cancer-de-tireoide--diagnostico-e-conduta", "TSH suprimido em paciente com nódulo tireoidiano indica inicialmente:", "Considerar cintilografia para avaliar autonomia funcional antes de definir PAAF.", "Tireoidectomia total imediata", "Tireoglobulina como rastreio", "Nenhuma investigação"],
  ["nge-lote01-016", "endocrino--insuficiencia-adrenal--diagnostico-e-conduta", "Crise adrenal suspeita exige:", "Hidrocortisona e reposição volêmica imediatas, sem atrasar tratamento para teste confirmatório.", "Apenas levotiroxina", "Restrição salina", "Diurético de alça"],
  ["nge-lote01-017", "nefro--disturbios-hidroeletroliticos-e-acido-base--diagnostico-e-conduta", "Hiponatremia sintomática grave deve ser corrigida:", "Com solução hipertônica em ambiente monitorado, evitando correção excessivamente rápida.", "Com água livre em excesso", "Normalizando em minutos sem monitorar", "Com diurético isolado em todos"],
  ["nge-lote01-018", "gastro--pancreatite-aguda--diagnostico-e-conduta", "O diagnóstico de pancreatite aguda geralmente requer:", "Dois de três: dor típica, lipase/amilase elevada e imagem compatível.", "Apenas leucocitose", "Apenas ultrassom normal", "Bilirrubina baixa isolada"],
  ["nge-lote01-019", "hemato--neoplasias-hematologicas--diagnostico-e-conduta", "Febre, sudorese noturna e perda ponderal em linfadenopatia persistente exigem:", "Investigação estruturada, incluindo exame completo, hemograma e obtenção adequada de tecido quando indicado.", "Antibiótico indefinido sem reavaliação", "Corticoide antes da biópsia em todos", "Ignorar duração"],
  ["nge-lote01-020", "endocrino--tireoide--hipotireoidismo-e-hipertireoidismo--diagnostico-e-conduta", "TSH elevado e T4 livre reduzido confirmam padrão de:", "Hipotireoidismo primário, cuja causa e gravidade orientam reposição.", "Hipertireoidismo central", "Eutireoidismo obrigatório", "Cetoacidose"],
]);
