import type { Dificuldade, EstiloQuestao, Questao } from "@/domain/content/types";

type Opcao = [texto: string, correta: boolean, comentario: string];
type Entrada = { id: string; subtemaId: string; disciplinaId: "psiq" | "neuro"; enunciado: string; opcoes: [Opcao, Opcao, Opcao, Opcao]; dificuldade: Dificuldade; estilo: EstiloQuestao; tags: string[]; fonte: string; figura?: string };
const letras = ["A", "B", "C", "D"];
const montar = (e: Entrada): Questao => ({ ...e, alternativas: e.opcoes.map(([texto, correta, comentario], i) => ({ letra: letras[i], texto, correta, comentario })) });
const NG215 = "NICE NG215 — Medicines associated with dependence or withdrawal symptoms";
const NG97 = "NICE NG97 — Dementia: assessment, management and support";
const CG178 = "NICE CG178 — Psychosis and schizophrenia in adults";
const WHO = "WHO 2026 — Risk reduction of cognitive decline and dementia";

export const QUESTOES_NEUROPSIQ_RECENTES: Questao[] = [
  montar({ id: "psiq-recente-001", subtemaId: "psiq--psicofarmacologia--antidepressivos-antipsicoticos-e-estabilizadores", disciplinaId: "psiq", enunciado: "Antes de iniciar antidepressivo em uma pessoa com depressão, qual dado muda mais a hipótese e a segurança da conduta?", opcoes: [["História de episódio de mania ou hipomania", true, "A presença de elevação episódica de energia/atividade pode indicar bipolaridade e muda a estratégia."], ["Preferência por comprimido pequeno", false, "É uma preferência válida, mas não redefine o risco diagnóstico."], ["Uma escala de sintomas isolada", false, "Escalas apoiam o rastreio, mas não substituem a história longitudinal."], ["A ausência de dor lombar", false, "Não é dado discriminativo para a decisão psicofarmacológica."]], dificuldade: "intermediaria", estilo: "conduta", tags: ["psicofarmacologia", "bipolaridade"], fonte: CG178 }),
  montar({ id: "psiq-recente-002", subtemaId: "psiq--psicofarmacologia--antidepressivos-antipsicoticos-e-estabilizadores", disciplinaId: "psiq", enunciado: "Paciente iniciou antipsicótico e ganhou peso, está mais sonolento e relata sede. Qual é a melhor próxima ação?", opcoes: [["Reavaliar eficácia, efeitos metabólicos, sinais clínicos e plano de monitorização", true, "A segurança exige medida objetiva e revisão compartilhada, não apenas esperar o próximo ano."], ["Aumentar a dose para vencer a sonolência", false, "Pode piorar o efeito adverso sem responder ao problema."], ["Suspender abruptamente sem avaliar risco de recaída", false, "A retirada deve considerar risco, síndrome tratada e plano seguro."], ["Ignorar porque o ganho de peso é esperado", false, "Ser esperado não o torna clinicamente irrelevante."]], dificuldade: "intermediaria", estilo: "conduta", tags: ["antipsicoticos", "metabolico"], fonte: CG178 }),
  montar({ id: "psiq-recente-003", subtemaId: "psiq--psicofarmacologia--antidepressivos-antipsicoticos-e-estabilizadores", disciplinaId: "psiq", enunciado: "Qual princípio é mais seguro ao escolher um estabilizador do humor?", opcoes: [["Integrar polo atual, recorrência, órgãos-alvo, gestação, interações e preferência", true, "A escolha é longitudinal e individualizada; nenhum marcador isolado resolve a decisão."], ["Escolher sempre o fármaco com maior sedação", false, "Sedação não é objetivo universal e pode gerar dano."], ["Usar antidepressivo isolado para todo episódio depressivo", false, "Pode ser inadequado quando há bipolaridade."], ["Dispensar exames porque efeitos adversos são raros", false, "Monitorização depende do fármaco e é parte da prescrição segura."]], dificuldade: "avancada", estilo: "conduta", tags: ["estabilizadores", "seguranca"], fonte: "NICE CG185 — Bipolar disorder: assessment and management" }),

  montar({ id: "psiq-recente-004", subtemaId: "psiq--sono-e-hipnosedativos--retirada-de-benzodiazepinicos-e-z-drugs", disciplinaId: "psiq", enunciado: "Qual estratégia é mais adequada para retirar benzodiazepínico usado por longo período?", opcoes: [["Redução gradual, compartilhada, com ritmo ajustável e tratamento da causa de base", true, "A retirada lenta reduz risco e permite ajustar sintomas e segurança."], ["Suspensão abrupta para evitar dependência", false, "A interrupção abrupta pode precipitar abstinência importante."], ["Trocar automaticamente por outro sedativo", false, "Isso pode apenas transferir o risco de dependência."], ["Manter indefinidamente sem revisar indicação", false, "Uso prolongado requer reavaliação periódica."]], dificuldade: "intermediaria", estilo: "conduta", tags: ["benzodiazepinicos", "abstinencia"], fonte: NG215 }),
  montar({ id: "psiq-recente-005", subtemaId: "psiq--sono-e-hipnosedativos--retirada-de-benzodiazepinicos-e-z-drugs", disciplinaId: "psiq", enunciado: "Após reduzir hipnosedativo, paciente tem insônia e ansiedade, sem sinais de instabilidade. O que ajuda a diferenciar abstinência de recaída?", opcoes: [["Cronologia em relação à redução, padrão dos sintomas e resposta a pausas/ajustes", true, "A relação temporal e o curso ajudam a separar fenômenos que podem coexistir."], ["Apenas a intensidade da ansiedade", false, "Intensidade isolada não diferencia as entidades."], ["Uma fotografia do estado mental sem história", false, "A trajetória é essencial."], ["Presumir que toda piora é recaída", false, "Isso pode levar a manter desnecessariamente o medicamento."]], dificuldade: "avancada", estilo: "caso", tags: ["abstinencia", "recaida"], fonte: NG215 }),
  montar({ id: "psiq-recente-006", subtemaId: "psiq--sono-e-hipnosedativos--retirada-de-benzodiazepinicos-e-z-drugs", disciplinaId: "psiq", enunciado: "Qual achado durante retirada de sedativo exige avaliação urgente?", opcoes: [["Convulsão, delirium, instabilidade autonômica ou alteração intensa da consciência", true, "São sinais de abstinência grave ou causa concorrente que não deve ser manejada em casa."], ["Uma noite de sono ruim", false, "Pode ocorrer, mas isoladamente não define urgência."], ["Sonho vívido sem alteração funcional", false, "Não é sinal isolado de gravidade."], ["Leve irritabilidade transitória", false, "Pode ser monitorada conforme o plano clínico."]], dificuldade: "avancada", estilo: "conduta", tags: ["abstinencia", "urgencia"], fonte: NG215 }),

  montar({ id: "psiq-recente-007", subtemaId: "psiq--transtornos-por-uso-de-substancias--intoxicacao-e-abstinencia", disciplinaId: "psiq", enunciado: "Pessoa chega sonolenta após possível ingestão de várias substâncias. Qual é a prioridade?", opcoes: [["ABCDE, glicemia, oxigenação, trauma e monitorização", true, "A estabilização e a identificação de ameaças imediatas precedem o rótulo toxicológico."], ["Perguntar primeiro se foi intencional", false, "A intenção é importante, mas não antes de estabilizar funções vitais."], ["Concluir que é crise psiquiátrica", false, "Alteração da consciência exige investigação clínica."], ["Dar alta se não houver acompanhante", false, "Ausência de acompanhante aumenta a vulnerabilidade, não reduz o risco."]], dificuldade: "intermediaria", estilo: "conduta", tags: ["intoxicacao", "ABCDE"], fonte: NG215 }),
  montar({ id: "psiq-recente-008", subtemaId: "psiq--transtornos-por-uso-de-substancias--intoxicacao-e-abstinencia", disciplinaId: "psiq", enunciado: "Qual dado favorece abstinência, em vez de intoxicação, em uma pessoa que interrompeu uso diário?", opcoes: [["Início após redução/cessação, com sinais autonômicos e cronologia compatível", true, "A relação com a interrupção e a síndrome resultante orientam abstinência."], ["Qualquer pupila diferente do normal", false, "Pupila isolada é inespecífica."], ["Negação do uso pela pessoa", false, "A informação pode estar incompleta, mas não define a síndrome."], ["Somente o resultado de uma escala", false, "Escala não substitui exame e cronologia."]], dificuldade: "fixacao", estilo: "diagnostico", tags: ["abstinencia", "toxindrome"], fonte: NG215 }),
  montar({ id: "psiq-recente-009", subtemaId: "psiq--transtornos-por-uso-de-substancias--intoxicacao-e-abstinencia", disciplinaId: "psiq", enunciado: "Em alteração comportamental com febre, desatenção e agitação, qual erro deve ser evitado?", opcoes: [["Rotular como transtorno psiquiátrico sem procurar infecção, intoxicação, abstinência ou causa neurológica", true, "Causas clínicas e tóxicas podem ser fatais e se apresentam com sintomas psiquiátricos."], ["Verificar glicemia", false, "É uma medida apropriada."], ["Perguntar sobre medicações", false, "A revisão medicamentosa é essencial."], ["Avaliar risco de auto e heteroagressão", false, "É parte da avaliação de segurança."]], dificuldade: "intermediaria", estilo: "caso", tags: ["delirium", "toxindrome"], fonte: "NICE CG178 — Psychosis and schizophrenia in adults" }),

  montar({ id: "psiq-recente-010", subtemaId: "psiq--transtornos-por-uso-de-substancias--alcool-e-sedativos-abordagem-clinica", disciplinaId: "psiq", enunciado: "Qual combinação aumenta especialmente o risco de depressão respiratória?", opcoes: [["Álcool e benzodiazepínico", true, "São depressores do sistema nervoso central e podem ter efeito aditivo."], ["Água e cafeína", false, "Não é combinação depressora equivalente."], ["Paracetamol e água", false, "Não produz esse mecanismo de risco."], ["Antibiótico e exercício", false, "Não descreve uma interação depressora."]], dificuldade: "fixacao", estilo: "fixacao", tags: ["alcool", "sedativos"], fonte: NG215 }),
  montar({ id: "psiq-recente-011", subtemaId: "psiq--transtornos-por-uso-de-substancias--alcool-e-sedativos-abordagem-clinica", disciplinaId: "psiq", enunciado: "Tremor, sudorese, taquicardia, alucinações e confusão após parar álcool indicam que a prioridade é:", opcoes: [["Avaliação urgente em ambiente monitorado para abstinência grave/delirium", true, "Confusão e instabilidade autonômica podem evoluir rapidamente e exigem tratamento protocolar."], ["Apenas aconselhamento em consulta de rotina", false, "Subestima risco potencialmente fatal."], ["Prescrever hipnótico e liberar", false, "Sedativo sem avaliação e monitorização pode agravar risco."], ["Diagnosticar esquizofrenia", false, "A cronologia de abstinência torna essa conclusão inadequada."]], dificuldade: "avancada", estilo: "caso", tags: ["alcool", "delirium"], fonte: "NICE CG115 — Alcohol-use disorders: diagnosis and management" }),
  montar({ id: "psiq-recente-012", subtemaId: "psiq--transtornos-por-uso-de-substancias--alcool-e-sedativos-abordagem-clinica", disciplinaId: "psiq", enunciado: "Após estabilização de abstinência alcoólica, qual medida melhora a continuidade?", opcoes: [["Plano longitudinal com redução de danos, tratamento da dependência, saúde mental e rede de apoio", true, "A estabilização é apenas a porta de entrada do cuidado."], ["Encerrar acompanhamento quando os sinais autonômicos cessarem", false, "O risco de recaída e comorbidades permanece."], ["Manter sedativo sem data de revisão", false, "Isso cria novo risco sem plano."], ["Focar somente na abstinência sem avaliar moradia e suporte", false, "Contexto social influencia segurança e adesão."]], dificuldade: "intermediaria", estilo: "conduta", tags: ["alcool", "continuidade"], fonte: "NICE CG115 — Alcohol-use disorders: diagnosis and management" }),

  montar({ id: "neuro-recente-001", subtemaId: "neuro--neuroanatomia-clinica--vias-motoras-sensitivas-e-sindromes-cruzadas", disciplinaId: "neuro", enunciado: "Fraqueza com hiperreflexia e padrão piramidal sugere lesão predominante em:", opcoes: [["Neurônio motor superior", true, "O padrão de liberação piramidal favorece via corticospinal central."], ["Junção neuromuscular isolada", false, "A junção costuma produzir fatigabilidade sem sinais piramidais."], ["Músculo sem acometimento neural", false, "Não explica hiperreflexia típica."], ["Nervo periférico sensitivo", false, "Não explica o conjunto motor central."]], dificuldade: "fixacao", estilo: "diagnostico", tags: ["localizacao", "via-motora"], fonte: "Neuroanatomia clínica visual e funcional — síntese autoral" }),
  montar({ id: "neuro-recente-002", subtemaId: "neuro--neuroanatomia-clinica--vias-motoras-sensitivas-e-sindromes-cruzadas", disciplinaId: "neuro", enunciado: "Déficit de nervo craniano ipsilateral associado a déficit corporal contralateral localiza melhor a lesão em:", opcoes: [["Tronco encefálico", true, "Síndromes cruzadas refletem acometimento de estruturas cranianas e vias longas no tronco."], ["Nervo periférico distal", false, "Não produziria esse padrão cruzado."], ["Músculo proximal", false, "Não explica nervo craniano e corpo contralateral."], ["Córtex occipital isolado", false, "Não é a localização típica dessa combinação."]], dificuldade: "intermediaria", estilo: "diagnostico", tags: ["tronco", "sindromes-cruzadas"], fonte: "Neuroanatomia clínica visual e funcional — síntese autoral" }),
  montar({ id: "neuro-recente-003", subtemaId: "neuro--neuroanatomia-clinica--vias-motoras-sensitivas-e-sindromes-cruzadas", disciplinaId: "neuro", enunciado: "Nível sensitivo bem definido em tronco ou membros inferiores deve fazer pensar primeiro em:", opcoes: [["Lesão medular até prova em contrário", true, "Um nível sensitivo é um dado de localização medular e define urgência investigativa."], ["Ansiedade isolada", false, "Ansiedade não explica nível neurológico objetivo."], ["Miopatia proximal", false, "Miopatia não costuma produzir nível sensitivo."], ["Insônia", false, "Não tem relação anatômica com o achado."]], dificuldade: "intermediaria", estilo: "conduta", tags: ["medula", "nivel-sensitivo"], fonte: "Neuroanatomia clínica visual e funcional — síntese autoral" }),

  montar({ id: "neuro-recente-004", subtemaId: "neuro--amnesias-e-sindromes-demenciais--delirium-versus-demencia", disciplinaId: "neuro", enunciado: "Qual característica favorece delirium em um idoso hospitalizado?", opcoes: [["Início agudo, desatenção e flutuação ao longo do dia", true, "Essa tríade é mais compatível com delirium do que com demência isolada."], ["Perda de memória lentamente progressiva por anos", false, "Favorece síndrome demencial."], ["Consciência preservada sem variação", false, "Não favorece delirium."], ["História familiar isolada", false, "Não define o quadro agudo."]], dificuldade: "fixacao", estilo: "diagnostico", tags: ["delirium", "demencia"], fonte: "NICE CG103 — Delirium" }),
  montar({ id: "neuro-recente-005", subtemaId: "neuro--amnesias-e-sindromes-demenciais--delirium-versus-demencia", disciplinaId: "neuro", enunciado: "Qual é a primeira abordagem diante de delirium suspeito?", opcoes: [["Buscar e tratar precipitantes, revisar medicamentos e oferecer medidas de orientação e segurança", true, "A causa reversível e o ambiente são o centro do manejo inicial."], ["Solicitar somente imagem cerebral e aguardar", false, "A investigação não deve atrasar correção de causas comuns."], ["Usar antipsicótico de rotina", false, "Não é conduta automática e pode trazer dano."], ["Presumir progressão inevitável da demência", false, "Delirium é uma alteração aguda potencialmente reversível."]], dificuldade: "intermediaria", estilo: "conduta", tags: ["delirium", "seguranca"], fonte: "NICE CG103 — Delirium" }),
  montar({ id: "neuro-recente-006", subtemaId: "neuro--amnesias-e-sindromes-demenciais--delirium-versus-demencia", disciplinaId: "neuro", enunciado: "Qual achado não deve ser usado isoladamente para concluir que um paciente tem demência?", opcoes: [["Uma imagem cerebral sem integração com história e funcionalidade", true, "Imagem isolada não determina síndrome nem fenótipo."], ["Perda funcional progressiva confirmada por informante", false, "É dado importante da avaliação."], ["Curso insidioso com prejuízo cognitivo", false, "É compatível com síndrome demencial."], ["Avaliação cognitiva interpretada no contexto", false, "Ajuda quando integrada à história clínica."]], dificuldade: "intermediaria", estilo: "diagnostico", tags: ["demencia", "imagem"], fonte: NG97 }),

  montar({ id: "neuro-recente-007", subtemaId: "neuro--amnesias-e-sindromes-demenciais--fenotipos-demenciais-e-tratamento", disciplinaId: "neuro", enunciado: "Flutuação cognitiva, alucinações visuais recorrentes e parkinsonismo sugerem qual fenótipo?", opcoes: [["Demência com corpos de Lewy", true, "A combinação é um padrão clínico de alto rendimento para Lewy."], ["Demência frontotemporal comportamental", false, "FTD tende a iniciar com comportamento ou linguagem, sem esse conjunto típico."], ["Amnésia dissociativa", false, "Não explica parkinsonismo progressivo."], ["Delirium isolado de longa duração", false, "Curso persistente e fenótipo sugerem outra hipótese, embora delirium possa coexistir."]], dificuldade: "intermediaria", estilo: "diagnostico", tags: ["demencia", "lewy"], fonte: NG97 }),
  montar({ id: "neuro-recente-008", subtemaId: "neuro--amnesias-e-sindromes-demenciais--fenotipos-demenciais-e-tratamento", disciplinaId: "neuro", enunciado: "Segundo a NICE, qual afirmação sobre tratamento sintomático da doença de Alzheimer é correta?", opcoes: [["Inibidores de acetilcolinesterase são opções para doença leve a moderada; memantina tem indicações em doença moderada/grave ou quando aqueles não podem ser usados", true, "A indicação depende do estágio, tolerância e avaliação especializada."], ["Memantina é obrigatória para todo esquecimento subjetivo", false, "Não há indicação universal para queixa subjetiva."], ["Antipsicótico deve ser usado de rotina para qualquer agitação", false, "Risco e benefício precisam ser avaliados; não é rotina universal."], ["Suplemento vitamínico previne demência mesmo sem deficiência", false, "A OMS não recomenda uso rotineiro sem deficiência documentada."]], dificuldade: "avancada", estilo: "conduta", tags: ["alzheimer", "tratamento"], fonte: NG97 }),
  montar({ id: "neuro-recente-009", subtemaId: "neuro--amnesias-e-sindromes-demenciais--fenotipos-demenciais-e-tratamento", disciplinaId: "neuro", enunciado: "Qual medida faz parte da redução de risco de declínio cognitivo segundo a atualização da OMS?", opcoes: [["Atividade física e controle de fatores cardiovasculares, com cuidado auditivo quando indicado", true, "A recomendação integra fatores modificáveis ao longo da vida."], ["Usar vitamina em todos os adultos", false, "Não há indicação rotineira sem deficiência."], ["Evitar qualquer atividade intelectual", false, "Não é recomendação baseada em evidência."], ["Tratar apenas a memória e ignorar tabagismo", false, "Tabaco e risco vascular fazem parte da prevenção."]], dificuldade: "intermediaria", estilo: "conduta", tags: ["prevencao", "demencia"], fonte: WHO }),
];
