import type { Dificuldade, EstiloQuestao, Questao } from "@/domain/content/types";

type Opcao = [texto: string, correta: boolean, comentario: string];
type Entrada = {
  id: string;
  subtemaId: string;
  disciplinaId: "psiq" | "neuro";
  enunciado: string;
  opcoes: [Opcao, Opcao, Opcao, Opcao];
  dificuldade: Dificuldade;
  estilo: EstiloQuestao;
  tags: string[];
  fonte: string;
  figura?: string | string[];
};

const letras = ["A", "B", "C", "D"];
const montar = (entrada: Entrada): Questao => ({
  id: entrada.id,
  subtemaId: entrada.subtemaId,
  disciplinaId: entrada.disciplinaId,
  enunciado: entrada.enunciado,
  alternativas: entrada.opcoes.map(([texto, correta, comentario], indice) => ({
    letra: letras[indice],
    texto,
    correta,
    comentario,
  })),
  dificuldade: entrada.dificuldade,
  estilo: entrada.estilo,
  tags: entrada.tags,
  fonte: entrada.fonte,
  figura: entrada.figura,
});

const NICE_DEP = "NICE NG222 — Depression in adults";
const NICE_BIP = "NICE CG185 — Bipolar disorder";
const NICE_PSI = "NICE CG178 — Psychosis and schizophrenia in adults";
const NICE_RISCO = "NICE NG225 — Self-harm";
const ASAM_BZD = "ASAM 2025 — Joint Clinical Practice Guideline on Benzodiazepine Tapering";

export const QUESTOES_NEUROPSIQ_SEMANA: Questao[] = [
  montar({
    id: "psiq-semana-001",
    subtemaId: "psiq--entrevista-e-psicopatologia--anamnese-e-exame-do-estado-mental",
    disciplinaId: "psiq",
    enunciado: "Qual registro representa melhor um achado do exame do estado mental?",
    opcoes: [
      ["Paciente difícil e estranho.", false, "Rótulos vagos não descrevem o fenômeno observado e reduzem a reprodutibilidade do exame."],
      ["Fala com latência aumentada, baixo volume e respostas breves.", true, "A alternativa descreve componentes observáveis da fala sem transformar observação em diagnóstico."],
      ["Paciente certamente deprimido.", false, "“Certamente deprimido” é interpretação diagnóstica; o EEM deve primeiro registrar os achados."],
      ["Comportamento inadequado.", false, "“Inadequado” precisa ser substituído pela conduta concreta, seu contexto e impacto."],
    ],
    dificuldade: "fixacao",
    estilo: "fixacao",
    tags: ["eem", "psicopatologia"],
    fonte: NICE_DEP,
    figura: "psiq-exame-mental-map",
  }),
  montar({
    id: "psiq-semana-002",
    subtemaId: "psiq--entrevista-e-psicopatologia--anamnese-e-exame-do-estado-mental",
    disciplinaId: "psiq",
    enunciado: "Homem de 58 anos apresenta alucinações visuais iniciadas há horas, desatenção flutuante e febre. Qual é o melhor enquadramento inicial?",
    opcoes: [
      ["Esquizofrenia de início tardio, sem necessidade de avaliação clínica.", false, "Início hiperagudo, febre e desatenção flutuante tornam causa orgânica muito mais provável."],
      ["Transtorno delirante persistente.", false, "O quadro flutuante com alteração atencional não corresponde ao padrão de transtorno delirante."],
      ["Delirium até prova em contrário, com investigação da causa clínica.", true, "Desatenção, flutuação e doença aguda são o núcleo sindrômico do delirium e exigem busca etiológica."],
      ["Crise de ansiedade com despersonalização.", false, "Ansiedade não explica adequadamente febre e alteração flutuante da atenção."],
    ],
    dificuldade: "intermediaria",
    estilo: "caso",
    tags: ["delirium", "organico"],
    fonte: NICE_PSI,
  }),
  montar({
    id: "psiq-semana-003",
    subtemaId: "psiq--entrevista-e-psicopatologia--anamnese-e-exame-do-estado-mental",
    disciplinaId: "psiq",
    enunciado: "Ao final de uma primeira entrevista psiquiátrica, qual síntese mais ajuda a decidir o próximo passo?",
    opcoes: [
      ["Lista de todos os sintomas em ordem alfabética.", false, "Uma lista sem hierarquia não expressa síndrome, contexto, risco ou decisão."],
      ["Uma hipótese única, sem diferenciais, para transmitir segurança.", false, "Fechamento prematuro aumenta o risco de perder causas orgânicas, afetivas ou relacionadas a substâncias."],
      ["Síndrome provável, diferenciais prioritários, fatores precipitantes/protetores, segurança e plano.", true, "Essa formulação integra diagnóstico provisório, contexto, risco e ação clínica."],
      ["Somente o escore de um questionário de rastreio.", false, "Rastreio auxilia, mas não substitui entrevista, função, exame do estado mental e formulação."],
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["formulacao", "eem"],
    fonte: NICE_DEP,
  }),
  montar({
    id: "psiq-semana-004",
    subtemaId: "psiq--entrevista-e-psicopatologia--anamnese-e-exame-do-estado-mental",
    disciplinaId: "psiq",
    enunciado: "No mapa do exame do estado mental, qual domínio precisa fechar a avaliação mesmo quando a queixa principal é insônia?",
    opcoes: [
      ["Somente aparência.", false, "Aparência é relevante, mas não fecha implicações de crítica, decisão e perigo."],
      ["Somente memória remota.", false, "Memória remota isolada não avalia segurança nem capacidade de decisão."],
      ["Crítica, julgamento e segurança.", true, "Esses domínios conectam os achados à capacidade, ao risco e ao plano imediato."],
      ["Preferência musical.", false, "Esse dado pode surgir no contexto biográfico, mas não é domínio obrigatório do EEM."],
    ],
    dificuldade: "fixacao",
    estilo: "imagem",
    tags: ["eem", "seguranca"],
    fonte: NICE_RISCO,
    figura: "psiq-exame-mental-map",
  }),

  montar({
    id: "psiq-semana-005",
    subtemaId: "psiq--transtornos-do-humor--depressao-e-avaliacao-de-seguranca",
    disciplinaId: "psiq",
    enunciado: "Paciente procura atendimento por depressão recorrente. Qual pergunta tem maior potencial de mudar o diagnóstico e a estratégia farmacológica?",
    opcoes: [
      ["Qual sua cor favorita?", false, "A pergunta não diferencia depressão unipolar de bipolaridade."],
      ["Já houve período de energia/atividade aumentada, menor necessidade de sono ou desinibição?", true, "Episódios de ativação podem indicar bipolaridade e mudam a segurança do tratamento."],
      ["Você prefere comprimido pequeno?", false, "Preferência de formulação pode importar depois, mas não resolve o diagnóstico diferencial central."],
      ["Quantos copos de água bebe?", false, "Pode ser útil em contextos específicos, porém não é a pergunta discriminativa principal nesta vinheta."],
    ],
    dificuldade: "intermediaria",
    estilo: "diagnostico",
    tags: ["depressao", "bipolaridade"],
    fonte: NICE_BIP,
  }),
  montar({
    id: "psiq-semana-006",
    subtemaId: "psiq--transtornos-do-humor--depressao-e-avaliacao-de-seguranca",
    disciplinaId: "psiq",
    enunciado: "Sobre a avaliação de suicídio em pessoa com depressão, qual afirmação é correta?",
    opcoes: [
      ["Perguntar diretamente induz a tentativa e deve ser evitado.", false, "Perguntas claras permitem reconhecer necessidade, proteção e ação; não devem ser omitidas por esse mito."],
      ["Uma escala que indique baixo risco permite alta automática.", false, "Escalas não devem predizer ou decidir alta de forma isolada."],
      ["Devem ser explorados ideação, intenção, plano, acesso a meios, histórico, proteção e ambiente.", true, "A formulação integra fatores dinâmicos, históricos e recursos concretos."],
      ["Somente tentativas anteriores importam.", false, "Histórico é relevante, mas estado atual, acesso, intoxicação, psicose e suporte também mudam a conduta."],
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["depressao", "suicidio"],
    fonte: NICE_RISCO,
  }),
  montar({
    id: "psiq-semana-007",
    subtemaId: "psiq--transtornos-do-humor--depressao-e-avaliacao-de-seguranca",
    disciplinaId: "psiq",
    enunciado: "Paciente com depressão apresenta delírio de culpa, recusa alimentar e incapacidade de manter autocuidado. Qual é a prioridade?",
    opcoes: [
      ["Orientar retorno em três meses.", false, "Psicose e incapacidade de autocuidado tornam a espera prolongada insegura."],
      ["Iniciar apenas higiene do sono.", false, "A medida é insuficiente para gravidade, psicose e prejuízo funcional apresentados."],
      ["Avaliação especializada urgente e garantia de segurança.", true, "Depressão grave com psicose e autocuidado comprometido exige rota urgente."],
      ["Aplicar somente um questionário online.", false, "Instrumento pode documentar sintomas, mas não substitui avaliação urgente e plano de segurança."],
    ],
    dificuldade: "avancada",
    estilo: "caso",
    tags: ["depressao-psicotica", "urgencia"],
    fonte: NICE_DEP,
  }),
  montar({
    id: "psiq-semana-008",
    subtemaId: "psiq--transtornos-do-humor--depressao-e-avaliacao-de-seguranca",
    disciplinaId: "psiq",
    enunciado: "Após iniciar tratamento para depressão, qual acompanhamento é mais completo?",
    opcoes: [
      ["Repetir receita indefinidamente se o paciente não reclamar.", false, "Ausência de queixa espontânea não comprova resposta, adesão ou segurança."],
      ["Avaliar sintoma-alvo, função, adesão, efeitos adversos, ativação e segurança em prazo definido.", true, "Monitorização útil mede benefício e risco e prevê ação diante de piora."],
      ["Medir apenas peso corporal.", false, "Peso pode ser relevante, porém não captura resposta, função, ativação ou risco."],
      ["Trocar de fármaco a cada três dias.", false, "Mudanças precoces e sucessivas impedem avaliar resposta e aumentam efeitos adversos."],
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["depressao", "seguimento"],
    fonte: NICE_DEP,
  }),

  montar({
    id: "psiq-semana-009",
    subtemaId: "psiq--transtornos-do-humor--transtorno-bipolar",
    disciplinaId: "psiq",
    enunciado: "Qual achado diferencia mania de hipomania de forma decisiva?",
    opcoes: [
      ["Humor alegre em qualquer intensidade.", false, "Alegria não caracteriza por si só episódio de elevação patológica do humor."],
      ["Presença de prejuízo grave, hospitalização ou psicose.", true, "Esses elementos definem mania; psicose exclui a classificação como hipomania."],
      ["Duração de algumas horas após café.", false, "Estimulação transitória por cafeína não estabelece episódio afetivo."],
      ["Ter realizado muitas tarefas em um dia produtivo.", false, "Produtividade isolada sem mudança episódica e prejuízo não define mania."],
    ],
    dificuldade: "fixacao",
    estilo: "diagnostico",
    tags: ["mania", "hipomania"],
    fonte: NICE_BIP,
  }),
  montar({
    id: "psiq-semana-010",
    subtemaId: "psiq--transtornos-do-humor--transtorno-bipolar",
    disciplinaId: "psiq",
    enunciado: "Adulto em consulta por depressão relata quatro dias de hiperatividade e desinibição no passado. Qual é a melhor interpretação?",
    opcoes: [
      ["O relato fecha automaticamente transtorno bipolar.", false, "A duração chama atenção, mas diagnóstico exige caracterização completa do episódio e exclusão de causas."],
      ["O relato é irrelevante porque a queixa atual é depressão.", false, "História de ativação pode mudar diagnóstico e tratamento."],
      ["É um sinal para avaliação especializada de possível bipolaridade.", true, "A recomendação é investigar cuidadosamente episódios de ativação em adultos com depressão."],
      ["Comprova transtorno de personalidade.", false, "Episódio temporal de ativação não estabelece por si só transtorno de personalidade."],
    ],
    dificuldade: "intermediaria",
    estilo: "caso",
    tags: ["bipolar", "rastreio"],
    fonte: NICE_BIP,
  }),
  montar({
    id: "psiq-semana-011",
    subtemaId: "psiq--transtornos-do-humor--transtorno-bipolar",
    disciplinaId: "psiq",
    enunciado: "Qual conjunto deve integrar a avaliação de risco durante mania?",
    opcoes: [
      ["Somente risco de suicídio.", false, "A mania amplia riscos financeiros, sexuais, de direção, exploração, violência e negligência."],
      ["Gastos, sexo de risco, direção, exploração, auto/heteroagressão e negligência.", true, "A formulação deve abranger riscos próprios da desinibição e da perda de crítica."],
      ["Somente pressão arterial.", false, "O dado pode ser clínico, mas não substitui avaliação comportamental e de segurança."],
      ["Somente presença de euforia.", false, "Humor não mede sozinho gravidade, vulnerabilidade ou dano iminente."],
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["mania", "seguranca"],
    fonte: NICE_BIP,
  }),
  montar({
    id: "psiq-semana-012",
    subtemaId: "psiq--transtornos-do-humor--transtorno-bipolar",
    disciplinaId: "psiq",
    enunciado: "Paciente com provável depressão bipolar recebe antidepressivo isolado e evolui com menor necessidade de sono, aceleração e impulsividade. Qual é a leitura mais adequada?",
    opcoes: [
      ["Resposta antidepressiva ideal.", false, "Ativação com redução da necessidade de sono e impulsividade sugere mudança de polo, não simples melhora."],
      ["Possível virada/ativação maniforme, exigindo reavaliação diagnóstica e urgente do esquema.", true, "O quadro pede revisão da hipótese bipolar, segurança e tratamento especializado."],
      ["Efeito esperado sem relevância.", false, "A mudança pode produzir dano e não deve ser normalizada."],
      ["Prova de dependência psicológica.", false, "A vinheta descreve síndrome de ativação, não critério de dependência."],
    ],
    dificuldade: "avancada",
    estilo: "caso",
    tags: ["bipolar", "antidepressivo"],
    fonte: NICE_BIP,
  }),

  montar({
    id: "psiq-semana-013",
    subtemaId: "psiq--ansiedade-panico-e-toc--diagnostico-e-abordagem",
    disciplinaId: "psiq",
    enunciado: "Primeira crise de 'pânico' em paciente com dor torácica, síncope e saturação baixa deve ser abordada como:",
    opcoes: [
      ["Transtorno do pânico confirmado.", false, "Sinais objetivos e primeira apresentação exigem excluir emergência clínica."],
      ["Evento clínico potencialmente grave até avaliação adequada.", true, "Dor, síncope e hipoxemia não podem ser atribuídas à ansiedade sem investigação."],
      ["TOC com baixa crítica.", false, "A vinheta não descreve obsessão ou compulsão."],
      ["Somatização sem necessidade de exame.", false, "O rótulo precoce pode atrasar diagnóstico cardiopulmonar."],
    ],
    dificuldade: "intermediaria",
    estilo: "caso",
    tags: ["panico", "diferencial"],
    fonte: "NICE CG113 — Panic disorder",
  }),
  montar({
    id: "psiq-semana-014",
    subtemaId: "psiq--ansiedade-panico-e-toc--diagnostico-e-abordagem",
    disciplinaId: "psiq",
    enunciado: "Qual achado favorece obsessão do TOC em vez de delírio?",
    opcoes: [
      ["Pensamento intrusivo, indesejado e acompanhado de tentativa de neutralização.", true, "Essa relação com o pensamento é típica de obsessão, embora o insight possa variar."],
      ["Crença fixa, não questionada, sem resistência.", false, "Convicção rígida sem crítica favorece delírio, conforme o contexto."],
      ["Flutuação de atenção com febre.", false, "O achado favorece delirium e causa orgânica aguda."],
      ["Pressão de fala e grandiosidade.", false, "O conjunto favorece um episódio maniforme e não caracteriza obsessão do TOC."],
    ],
    dificuldade: "intermediaria",
    estilo: "diagnostico",
    tags: ["toc", "psicose"],
    fonte: "NICE CG31 — Obsessive-compulsive disorder",
  }),
  montar({
    id: "psiq-semana-015",
    subtemaId: "psiq--ansiedade-panico-e-toc--diagnostico-e-abordagem",
    disciplinaId: "psiq",
    enunciado: "Qual intervenção psicológica é especificamente central no TOC?",
    opcoes: [
      ["Exposição e prevenção de resposta.", true, "A pessoa se expõe gradualmente ao gatilho e reduz o ritual neutralizador com planejamento terapêutico."],
      ["Evitar permanentemente todo gatilho.", false, "Evitação mantém a ameaça percebida e o ciclo compulsivo."],
      ["Reasseguramento ilimitado pela família.", false, "Reasseguramento pode tornar-se parte do ritual e perpetuar o transtorno."],
      ["Privação de sono.", false, "Privação de sono é insegura e não constitui tratamento do TOC."],
    ],
    dificuldade: "fixacao",
    estilo: "conduta",
    tags: ["toc", "tcc"],
    fonte: "NICE CG31 — Obsessive-compulsive disorder",
  }),

  montar({
    id: "psiq-semana-016",
    subtemaId: "psiq--psicoses--primeiro-episodio-psicotico",
    disciplinaId: "psiq",
    enunciado: "Qual apresentação de primeiro episódio psicótico mais exige investigação orgânica dirigida?",
    opcoes: [
      ["Evolução insidiosa com retraimento e sintomas negativos.", false, "Pode ocorrer em psicose primária, embora avaliação clínica completa continue necessária."],
      ["Início abrupto com febre, crise convulsiva e déficit focal.", true, "O conjunto é forte sinal de causa neurológica/infecciosa e demanda investigação imediata."],
      ["História familiar de esquizofrenia sem sinais neurológicos.", false, "História familiar aumenta suspeita de primário, mas não é o principal alarme orgânico."],
      ["Ideias autorreferentes crônicas sem flutuação.", false, "O padrão não contém os alarmes orgânicos centrais da alternativa correta."],
    ],
    dificuldade: "intermediaria",
    estilo: "caso",
    tags: ["psicose", "organico"],
    fonte: NICE_PSI,
  }),
  montar({
    id: "psiq-semana-017",
    subtemaId: "psiq--psicoses--primeiro-episodio-psicotico",
    disciplinaId: "psiq",
    enunciado: "Em pessoa com risco aumentado de psicose, mas sem psicose estabelecida, qual conduta é mais adequada?",
    opcoes: [
      ["Antipsicótico obrigatório para prevenção.", false, "Antipsicótico não é recomendado apenas para tentar prevenir psicose sem diagnóstico estabelecido."],
      ["Acompanhamento especializado, intervenção psicológica e tratamento de comorbidades.", true, "A rota reduz atraso, monitora evolução e trata necessidades presentes sem medicalização preventiva indevida."],
      ["Nenhum acompanhamento até surgir crise grave.", false, "Espera passiva perde oportunidade de cuidado precoce."],
      ["Internação compulsória automática.", false, "Risco aumentado sem emergência não justifica medida automática e desproporcional."],
    ],
    dificuldade: "avancada",
    estilo: "conduta",
    tags: ["psicose", "prevencao"],
    fonte: NICE_PSI,
  }),
  montar({
    id: "psiq-semana-018",
    subtemaId: "psiq--psicoses--primeiro-episodio-psicotico",
    disciplinaId: "psiq",
    enunciado: "Paciente com esquizofrenia mantém sintomas incapacitantes após dois ensaios adequados de antipsicóticos diferentes, com adesão confirmada. Qual passo deve ser considerado em serviço especializado?",
    opcoes: [
      ["Repetir indefinidamente o mesmo esquema sem revisão.", false, "Persistência após ensaios adequados pede avaliação de resistência e mudança de estratégia."],
      ["Clozapina, com monitorização apropriada.", true, "Diretrizes recomendam considerar clozapina após falha de dois antipsicóticos adequados."],
      ["Suspender todo cuidado psicossocial.", false, "Intervenções psicossociais continuam importantes mesmo quando há resistência farmacológica."],
      ["Benzodiazepínico como monoterapia definitiva.", false, "Benzodiazepínico não trata o núcleo da esquizofrenia resistente."],
    ],
    dificuldade: "avancada",
    estilo: "conduta",
    tags: ["psicose", "clozapina"],
    fonte: NICE_PSI,
  }),
  montar({
    id: "psiq-semana-019",
    subtemaId: "psiq--psicoses--primeiro-episodio-psicotico",
    disciplinaId: "psiq",
    enunciado: "A figura relaciona circuitos e sintomas. Qual é o uso clínico mais correto desse tipo de mapa?",
    opcoes: [
      ["Substituir a entrevista por uma localização cerebral única.", false, "Sintomas psiquiátricos emergem de redes e contexto; o mapa não substitui avaliação clínica."],
      ["Integrar fenômeno e rede como modelo explicativo, mantendo diagnóstico clínico e diferenciais.", true, "O mapa organiza aprendizagem, mas não transforma circuito em biomarcador diagnóstico isolado."],
      ["Confirmar diagnóstico por uma imagem estrutural normal.", false, "Imagem normal não confirma transtorno psiquiátrico, e exame não indicado não acrescenta valor."],
      ["Prescrever segundo a cor do circuito.", false, "Cores são recurso didático, não algoritmo farmacológico."],
    ],
    dificuldade: "intermediaria",
    estilo: "imagem",
    tags: ["psicose", "circuitos"],
    fonte: NICE_PSI,
    figura: "psiq-exame-mental-map",
  }),

  montar({
    id: "psiq-semana-020",
    subtemaId: "psiq--psicofarmacologia--principios-e-monitorizacao",
    disciplinaId: "psiq",
    enunciado: "Qual plano caracteriza uma prescrição psicofarmacológica de boa qualidade?",
    opcoes: [
      ["Nome do fármaco sem sintoma-alvo nem revisão.", false, "Sem alvo e prazo não é possível medir benefício ou decidir continuidade."],
      ["Hipótese, alvo, benefício esperado, risco relevante, prazo e plano de continuidade/retirada.", true, "Esses elementos transformam a receita em experimento clínico monitorável e compartilhado."],
      ["Adicionar novo fármaco a cada efeito adverso.", false, "A cascata de prescrição aumenta interações e pode mascarar o problema inicial."],
      ["Manter todos os medicamentos porque já estão na lista.", false, "Revisão periódica de indicação e carga anticolinérgica/sedativa é parte do cuidado."],
    ],
    dificuldade: "fixacao",
    estilo: "conduta",
    tags: ["psicofarmacologia", "monitorizacao"],
    fonte: NICE_DEP,
  }),
  montar({
    id: "psiq-semana-021",
    subtemaId: "psiq--psicofarmacologia--principios-e-monitorizacao",
    disciplinaId: "psiq",
    enunciado: "Antes de iniciar antipsicótico com risco metabólico, qual conjunto basal é mais pertinente?",
    opcoes: [
      ["Peso/cintura, pressão, glicemia ou HbA1c e perfil lipídico, além de riscos individuais.", true, "A linha de base permite escolher, prevenir e detectar efeitos metabólicos longitudinalmente."],
      ["Somente radiografia de tórax.", false, "Radiografia não monitora o risco metabólico típico da classe."],
      ["Somente tipagem sanguínea.", false, "Tipagem não responde à pergunta de risco e seguimento metabólico."],
      ["Nenhuma medida porque efeitos são inevitáveis.", false, "Risco varia entre pessoas e fármacos e deve ser discutido e monitorado."],
    ],
    dificuldade: "intermediaria",
    estilo: "exame",
    tags: ["antipsicotico", "metabolico"],
    fonte: NICE_PSI,
  }),
  montar({
    id: "psiq-semana-022",
    subtemaId: "psiq--psicofarmacologia--principios-e-monitorizacao",
    disciplinaId: "psiq",
    enunciado: "Antes de acrescentar um segundo psicofármaco por resposta parcial, qual sequência é mais racional?",
    opcoes: [
      ["Confirmar diagnóstico, alvo, adesão, dose/duração, efeitos e fatores perpetuadores.", true, "A sequência evita chamar de resistência o que é diagnóstico incorreto, exposição inadequada ou baixa adesão."],
      ["Adicionar imediatamente e avaliar depois.", false, "A adição sem revisão aumenta polifarmácia e dificulta atribuir benefício ou dano."],
      ["Duplicar todos os fármacos simultaneamente.", false, "Mudanças múltiplas impedem avaliar causalidade e elevam risco."],
      ["Ignorar substâncias e interações.", false, "Substâncias e interações podem explicar falha, toxicidade ou ativação."],
    ],
    dificuldade: "avancada",
    estilo: "conduta",
    tags: ["polifarmacia", "resposta-parcial"],
    fonte: NICE_DEP,
  }),

  montar({
    id: "psiq-semana-023",
    subtemaId: "psiq--sono-e-hipnosedativos--insonia-e-uso-seguro",
    disciplinaId: "psiq",
    enunciado: "Qual é a intervenção central para insônia crônica?",
    opcoes: [
      ["Terapia cognitivo-comportamental para insônia.", true, "TCC-I atua nos mecanismos que perpetuam a insônia e não se limita a recomendações genéricas."],
      ["Benzodiazepínico indefinido para todos.", false, "Uso prolongado amplia dependência, quedas e prejuízo cognitivo e não é estratégia universal."],
      ["Álcool antes de dormir.", false, "Álcool fragmenta o sono e aumenta riscos, apesar de sedação inicial."],
      ["Ficar mais tempo na cama acordado.", false, "Tempo excessivo acordado na cama reforça associação entre leito e vigília."],
    ],
    dificuldade: "fixacao",
    estilo: "conduta",
    tags: ["insonia", "tcci"],
    fonte: "NICE HTG624 — Sleepio for insomnia",
    figura: "psiq-hipnosedativos-seguranca-map",
  }),
  montar({
    id: "psiq-semana-024",
    subtemaId: "psiq--sono-e-hipnosedativos--insonia-e-uso-seguro",
    disciplinaId: "psiq",
    enunciado: "Pessoa dorme três horas por noite há cinco dias, sente-se cheia de energia, fala aceleradamente e iniciou gastos impulsivos. Qual é a prioridade diagnóstica?",
    opcoes: [
      ["Insônia primária resistente.", false, "Ausência de cansaço com ativação e impulsividade não corresponde a insônia isolada."],
      ["Possível episódio maniforme.", true, "Redução da necessidade de sono acompanhada de energia e desinibição é pista central de mania/hipomania."],
      ["Apneia obstrutiva do sono isolada.", false, "Apneia costuma causar sono não reparador e sonolência, não ativação maniforme."],
      ["Higiene do sono inadequada apenas.", false, "Rotina pode contribuir, mas não explica o conjunto sindrômico."],
    ],
    dificuldade: "intermediaria",
    estilo: "caso",
    tags: ["sono", "mania"],
    fonte: NICE_BIP,
  }),
  montar({
    id: "psiq-semana-025",
    subtemaId: "psiq--sono-e-hipnosedativos--insonia-e-uso-seguro",
    disciplinaId: "psiq",
    enunciado: "Paciente usa benzodiazepínico diariamente há anos e deseja parar hoje. Qual orientação é mais segura?",
    opcoes: [
      ["Interromper abruptamente para evitar dependência.", false, "Retirada abrupta após uso prolongado pode causar abstinência grave, inclusive convulsões."],
      ["Planejar redução gradual, individualizada e supervisionada.", true, "A retirada deve equilibrar risco, sintomas e preferência, com ajustes ao longo do processo."],
      ["Dobrar a dose antes de suspender.", false, "Aumentar sem indicação amplia exposição e não torna a retirada segura."],
      ["Substituir por álcool.", false, "Álcool soma depressão do SNC, dependência e risco de overdose."],
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["benzodiazepinico", "retirada"],
    fonte: ASAM_BZD,
    figura: "psiq-hipnosedativos-seguranca-map",
  }),
  montar({
    id: "psiq-semana-026",
    subtemaId: "psiq--sono-e-hipnosedativos--insonia-e-uso-seguro",
    disciplinaId: "psiq",
    enunciado: "Idosa com quedas recorrentes usa dois sedativos noturnos e relata sonolência diurna. Qual é o melhor próximo passo?",
    opcoes: [
      ["Adicionar terceiro hipnótico.", false, "Aumentar sedação tende a piorar quedas e cognição."],
      ["Revisar indicações, interações, carga sedativa e planejar desprescrição segura.", true, "A vinheta sugere dano medicamentoso; revisar e reduzir com segurança é prioritário."],
      ["Ignorar os medicamentos porque são noturnos.", false, "Efeitos residuais e interações podem persistir durante o dia."],
      ["Proibir atividade física definitivamente.", false, "A medida não corrige a causa provável e pode piorar funcionalidade."],
    ],
    dificuldade: "avancada",
    estilo: "caso",
    tags: ["hipnosedativos", "idoso", "quedas"],
    fonte: ASAM_BZD,
  }),

  montar({
    id: "psiq-semana-027",
    subtemaId: "psiq--emergencias-psiquiatricas--avaliacao-de-seguranca-e-risco-suicida",
    disciplinaId: "psiq",
    enunciado: "Qual uso de escala de risco suicida é inadequado?",
    opcoes: [
      ["Apoiar conversa e documentação como parte de avaliação ampla.", false, "Instrumentos podem organizar dados quando não substituem julgamento e necessidades."],
      ["Classificar baixo risco e decidir alta automaticamente.", true, "Diretrizes desaconselham usar escala ou estrato global para prever suicídio ou decidir alta."],
      ["Identificar itens que merecem exploração clínica.", false, "Itens podem abrir perguntas, desde que não sejam tratados como previsão."],
      ["Combinar com história, estado atual, ambiente e proteção.", false, "A integração contextual é necessária para formulação dinâmica."],
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["suicidio", "escalas"],
    fonte: NICE_RISCO,
  }),
  montar({
    id: "psiq-semana-028",
    subtemaId: "psiq--emergencias-psiquiatricas--avaliacao-de-seguranca-e-risco-suicida",
    disciplinaId: "psiq",
    enunciado: "Qual elemento pertence a um plano de segurança colaborativo?",
    opcoes: [
      ["Sinais pessoais, estratégias, contatos, serviços e redução de acesso a meios.", true, "O plano deve ser específico, acionável e construído com a pessoa."],
      ["Promessa genérica de nunca mais pensar em suicídio.", false, "Contrato de não suicídio não substitui avaliação, plano e seguimento."],
      ["Apenas um número de telefone sem próximos passos.", false, "Contato é útil, mas insuficiente sem sinais, estratégias e acesso planejado."],
      ["Ocultar o plano da rede de apoio em qualquer circunstância.", false, "Com consentimento e segurança, rede de apoio pode ser parte concreta do plano."],
    ],
    dificuldade: "fixacao",
    estilo: "conduta",
    tags: ["plano-seguranca", "suicidio"],
    fonte: NICE_RISCO,
  }),
  montar({
    id: "psiq-semana-029",
    subtemaId: "psiq--emergencias-psiquiatricas--avaliacao-de-seguranca-e-risco-suicida",
    disciplinaId: "psiq",
    enunciado: "Pessoa intoxicada relata plano suicida iminente, tem acesso ao meio e está agitada. Qual é a conduta prioritária?",
    opcoes: [
      ["Deixá-la sozinha para reduzir estímulos.", false, "Perigo imediato e intoxicação exigem supervisão e ambiente seguro."],
      ["Garantir segurança e avaliação presencial urgente, com manejo clínico da intoxicação.", true, "A situação reúne intenção, meio, agitação e incapacidade potencial, exigindo intervenção imediata."],
      ["Agendar consulta eletiva para o próximo mês.", false, "Atraso é incompatível com o risco e o estado clínico atuais."],
      ["Aplicar escala e encerrar após o resultado.", false, "Nenhum escore substitui ação urgente diante de perigo explícito."],
    ],
    dificuldade: "avancada",
    estilo: "caso",
    tags: ["suicidio", "urgencia", "intoxicacao"],
    fonte: NICE_RISCO,
  }),
  montar({
    id: "psiq-semana-030",
    subtemaId: "psiq--emergencias-psiquiatricas--avaliacao-de-seguranca-e-risco-suicida",
    disciplinaId: "psiq",
    enunciado: "Qual registro demonstra melhor uma formulação dinâmica de segurança?",
    opcoes: [
      ["Baixo risco.", false, "O rótulo não descreve necessidades, mudanças, proteção nem plano."],
      ["Nega ideação.", false, "Uma resposta isolada não integra histórico, comportamento, intoxicação, proteção ou contexto."],
      ["Após perda recente, apresenta intenção e acesso; irmã disponível, meios serão restringidos e avaliação urgente acionada.", true, "O registro conecta gatilho, estado atual, recursos e ações concretas."],
      ["Pontuação 3/10, sem outras informações.", false, "O número isolado não explica risco, necessidade ou decisão clínica."],
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["formulacao-risco", "seguranca"],
    fonte: NICE_RISCO,
  }),

  montar({
    id: "neuro-semana-001",
    subtemaId: "neuro--neuroanatomia-clinica--localizacao-neurologica",
    disciplinaId: "neuro",
    enunciado: "Paciente apresenta afasia e hemiparesia direita de predomínio braquiofacial. Qual nível anatômico é mais provável?",
    opcoes: [
      ["Córtex cerebral esquerdo, território de artéria cerebral média.", true, "Afasia é sinal cortical dominante; o padrão braquiofacial reforça território de ACM esquerda."],
      ["Nervo fibular comum.", false, "Mononeuropatia fibular não explica afasia nem déficit braquiofacial."],
      ["Cerebelo direito.", false, "Lesão cerebelar causa ataxia/dismetria, não afasia com hemiparesia."],
      ["Junção neuromuscular.", false, "Junção causa fatigabilidade sem sinal cortical como afasia."],
    ],
    dificuldade: "intermediaria",
    estilo: "caso",
    tags: ["localizacao", "cortex"],
    fonte: "Neuroanatomia clínica — síntese autoral",
    figura: "neuro-localizacao-clinica-map",
  }),
  montar({
    id: "neuro-semana-002",
    subtemaId: "neuro--neuroanatomia-clinica--localizacao-neurologica",
    disciplinaId: "neuro",
    enunciado: "Diplopia por paresia de nervo craniano ipsilateral associada a hemiparesia contralateral sugere lesão em:",
    opcoes: [
      ["Tronco encefálico.", true, "Síndromes cruzadas combinam núcleo/fascículo de nervo craniano ipsilateral e via longa contralateral."],
      ["Córtex occipital isolado.", false, "Córtex occipital produz defeito visual, não síndrome de nervo craniano cruzada típica."],
      ["Nervo periférico do membro inferior.", false, "Uma mononeuropatia não explica déficit de nervo craniano e hemiparesia contralateral."],
      ["Músculo esquelético difuso.", false, "Miopatia não gera padrão cruzado com nervo craniano focal."],
    ],
    dificuldade: "intermediaria",
    estilo: "diagnostico",
    tags: ["localizacao", "tronco"],
    fonte: "Neuroanatomia clínica — síntese autoral",
    figura: "neuro-localizacao-clinica-map",
  }),
  montar({
    id: "neuro-semana-003",
    subtemaId: "neuro--neuroanatomia-clinica--localizacao-neurologica",
    disciplinaId: "neuro",
    enunciado: "Fraqueza abaixo de determinado nível, hiperreflexia, nível sensitivo e retenção urinária localizam prioritariamente em:",
    opcoes: [
      ["Medula espinal.", true, "Via piramidal abaixo da lesão, nível sensitivo e esfíncteres formam padrão medular."],
      ["Cerebelo.", false, "Cerebelo causa incoordenação, sem nível sensitivo ou síndrome piramidal típica."],
      ["Nervo mediano.", false, "Mononeuropatia mediana limita-se ao seu território e não causa nível ou retenção."],
      ["Hipocampo.", false, "Hipocampo relaciona-se à memória, não ao padrão motor-sensitivo-esfincteriano."],
    ],
    dificuldade: "fixacao",
    estilo: "imagem",
    tags: ["localizacao", "medula"],
    fonte: "Neuroanatomia clínica — síntese autoral",
    figura: "neuro-localizacao-clinica-map",
  }),
  montar({
    id: "neuro-semana-004",
    subtemaId: "neuro--amnesias-e-sindromes-demenciais--diagnostico-e-conduta",
    disciplinaId: "neuro",
    enunciado: "Idoso hospitalizado apresenta desatenção, flutuação ao longo do dia e declínio percebido há dois dias. Qual é o primeiro diagnóstico sindrômico?",
    opcoes: [
      ["Doença de Alzheimer definida.", false, "Alzheimer costuma ser insidioso e progressivo, não hiperagudo e flutuante."],
      ["Delirium.", true, "Início agudo, desatenção e flutuação definem a síndrome e exigem busca da causa."],
      ["Demência frontotemporal.", false, "A evolução típica é progressiva, não flutuante em dois dias."],
      ["Amnésia global transitória de semanas.", false, "AGT é episódio amnéstico isolado e autolimitado, sem desatenção global persistente."],
    ],
    dificuldade: "fixacao",
    estilo: "caso",
    tags: ["demencia", "delirium"],
    fonte: "Ministério da Saúde — PCDT Doença de Alzheimer 2025",
    figura: "neuro-demencias-algoritmo-map",
  }),
  montar({
    id: "neuro-semana-005",
    subtemaId: "neuro--amnesias-e-sindromes-demenciais--diagnostico-e-conduta",
    disciplinaId: "neuro",
    enunciado: "Qual tríade sugere hidrocefalia de pressão normal, causa potencialmente tratável de declínio cognitivo?",
    opcoes: [
      ["Ataxia, surdez e diplopia.", false, "O conjunto não corresponde à tríade clássica de HPN."],
      ["Alteração de marcha, sintomas urinários e declínio cognitivo.", true, "Marcha costuma ser precoce e a ventriculomegalia desproporcional apoia o diagnóstico."],
      ["Cefaleia, febre e rigidez de nuca.", false, "Essa tríade sugere síndrome meníngea aguda."],
      ["Tremor, coreia e mioclonia.", false, "Movimentos anormais podem ocorrer em outras doenças, mas não formam a tríade de HPN."],
    ],
    dificuldade: "fixacao",
    estilo: "diagnostico",
    tags: ["demencia", "hpn"],
    fonte: "Ministério da Saúde — PCDT Doença de Alzheimer 2025",
  }),
  montar({
    id: "neuro-semana-006",
    subtemaId: "neuro--amnesias-e-sindromes-demenciais--diagnostico-e-conduta",
    disciplinaId: "neuro",
    enunciado: "No algoritmo de declínio cognitivo, qual passo deve anteceder a atribuição de uma etiologia neurodegenerativa?",
    opcoes: [
      ["Confirmar perda funcional, excluir delirium e revisar causas tratáveis.", true, "A síndrome e as causas modificáveis são avaliadas antes de rotular etiologia."],
      ["Escolher medicamento apenas pela idade.", false, "Idade isolada não define síndrome, etiologia ou tratamento."],
      ["Interpretar uma imagem sem história clínica.", false, "Imagem precisa ser correlacionada ao padrão cognitivo e funcional."],
      ["Ignorar informação do acompanhante.", false, "Informante é essencial para estabelecer mudança do basal e perda funcional."],
    ],
    dificuldade: "intermediaria",
    estilo: "imagem",
    tags: ["demencia", "algoritmo"],
    fonte: "Ministério da Saúde — PCDT Doença de Alzheimer 2025",
    figura: "neuro-demencias-algoritmo-map",
  }),
];
