import type { Questao } from "@/domain/content/types";

/**
 * Banco de questões — Pediatria (OMED).
 * Extraídas do "Simulado de Pediatria — Gabarito Comentado" do usuário
 * (Desidratação/Diarreia, Bronquiolite/Crupe, Icterícia Neonatal, Convulsão
 * Febril). Gabarito e comentários por alternativa conferidos com MS/SBP/AAP.
 */

const SUB = {
  desidratacao: "ped--emergencias-pediatricas--desidratacao-e-reidratacao",
  bronquiolite: "ped--infeccoes-respiratorias-na-infancia--bronquiolite",
  crupe: "ped--infeccoes-respiratorias-na-infancia--crupe-laringotraqueobronquite",
  ictericia: "ped--neonatologia--ictericia-neonatal",
  convulsao: "ped--emergencias-pediatricas--convulsao-febril",
} as const;

const FONTE = "Simulado OMED Pediatria — gabarito comentado (material do usuário)";

export const QUESTOES_PED: Questao[] = [
  // ── DESIDRATAÇÃO E DIARREIA ─────────────────────────────────────
  {
    id: "ped-des-01",
    subtemaId: SUB.desidratacao,
    disciplinaId: "ped",
    enunciado:
      "Lactente de 10 meses, diarreia há 3 dias, irritado, olhos encovados, sinal da prega desaparece lentamente. Conduta segundo o Ministério da Saúde?",
    alternativas: [
      { letra: "A", texto: "Plano B: SRO 50–100 mL/kg em 4–6h, sob supervisão na unidade, com reavaliação.", correta: true, comentario: "Irritação + olhos fundos + prega lentificada = 'algum grau de desidratação' → Plano B (TRO supervisionada)." },
      { letra: "B", texto: "Hidratação venosa imediata (Plano C).", correta: false, comentario: "Plano C é para desidratação grave (letargia, prega muito lenta >2s, incapaz de beber) — não é o caso." },
      { letra: "C", texto: "Plano A: aleitamento e SRO apenas em domicílio.", correta: false, comentario: "Plano A é para pacientes SEM sinais de desidratação; aqui já há sinais." },
      { letra: "D", texto: "Racecadotrila e alta hospitalar.", correta: false, comentario: "Antidiarreicos não são primeira linha; a prioridade é reidratar." },
    ],
    dificuldade: "fixacao",
    estilo: "conduta",
    tags: ["desidratação", "plano B", "TRO"],
    fonte: FONTE,
  },
  {
    id: "ped-des-03",
    subtemaId: SUB.desidratacao,
    disciplinaId: "ped",
    enunciado: "Sobre a suplementação de zinco na diarreia aguda infantil, é correto afirmar:",
    alternativas: [
      { letra: "A", texto: "É indicada apenas nos casos graves.", correta: false, comentario: "É recomendada para TODOS os casos de diarreia aguda, independentemente da gravidade." },
      { letra: "B", texto: "Reduz a duração e a gravidade do episódio e previne novos episódios por 2–3 meses (10–14 dias).", correta: true, comentario: "Recomendação OMS/MS: zinco por 10–14 dias reduz duração/gravidade e previne recorrência." },
      { letra: "C", texto: "É contraindicada em menores de 6 meses.", correta: false, comentario: "É indicada também <6 meses, em dose menor (10 mg/dia vs 20 mg/dia)." },
      { letra: "D", texto: "Substitui a reidratação como pilar do tratamento.", correta: false, comentario: "É adjuvante; a reidratação continua sendo o pilar." },
    ],
    dificuldade: "fixacao",
    estilo: "conduta",
    tags: ["diarreia", "zinco"],
    fonte: FONTE,
  },
  {
    id: "ped-des-05",
    subtemaId: SUB.desidratacao,
    disciplinaId: "ped",
    enunciado:
      "Lactente de 14 meses, diarreia com sangue e febre alta. Agente mais provável?",
    alternativas: [
      { letra: "A", texto: "Rotavírus.", correta: false, comentario: "Rotavírus causa diarreia aquosa, sem sangue." },
      { letra: "B", texto: "Shigella.", correta: true, comentario: "Shigella é a causa clássica de disenteria (sangue + muco) com febre alta e toxemia." },
      { letra: "C", texto: "E. coli enterotoxigênica (ETEC).", correta: false, comentario: "ETEC ('diarreia do viajante') causa quadro aquoso." },
      { letra: "D", texto: "Giardia lamblia.", correta: false, comentario: "Giardia causa diarreia subaguda/crônica, sem sangue nem febre alta." },
    ],
    dificuldade: "intermediaria",
    estilo: "diagnostico",
    tags: ["diarreia", "disenteria", "shigella"],
    fonte: FONTE,
  },
  {
    id: "ped-des-07",
    subtemaId: SUB.desidratacao,
    disciplinaId: "ped",
    enunciado: "Composição do SRO de baixa osmolaridade (OMS) — sódio e glicose:",
    alternativas: [
      { letra: "A", texto: "Sódio 90 mEq/L e glicose 111 mmol/L.", correta: false, comentario: "Corresponde à fórmula antiga, de maior osmolaridade, hoje substituída." },
      { letra: "B", texto: "Sódio 75 mEq/L e glicose 75 mmol/L (~245 mOsm/L).", correta: true, comentario: "SRO de baixa osmolaridade atual: Na 75, glicose 75 — reduz vômitos e volume fecal." },
      { letra: "C", texto: "Sódio 130 mEq/L e glicose 50 mmol/L.", correta: false, comentario: "Não corresponde à formulação padronizada." },
      { letra: "D", texto: "Sódio 45 mEq/L e glicose 140 mmol/L.", correta: false, comentario: "Não corresponde à formulação padronizada." },
    ],
    dificuldade: "avancada",
    estilo: "exame",
    tags: ["SRO", "reidratação oral"],
    fonte: FONTE,
  },
  {
    id: "ped-des-11",
    subtemaId: SUB.desidratacao,
    disciplinaId: "ped",
    enunciado:
      "Criança de 5 anos, diarreia sanguinolenta evolui com palidez, oligúria e trombocitopenia. Hipótese e agente?",
    alternativas: [
      { letra: "A", texto: "Febre tifoide (Salmonella typhi).", correta: false, comentario: "Não cursa com a tríade hemolítico-renal." },
      { letra: "B", texto: "Síndrome hemolítico-urêmica por E. coli produtora de toxina Shiga (STEC/O157:H7).", correta: true, comentario: "Anemia hemolítica + injúria renal + trombocitopenia após diarreia sanguinolenta = SHU, classicamente por STEC." },
      { letra: "C", texto: "Púrpura de Henoch-Schönlein.", correta: false, comentario: "Cursa com púrpura palpável, artrite e dor abdominal — padrão distinto." },
      { letra: "D", texto: "Disenteria por Shigella sonnei.", correta: false, comentario: "A associação clássica com SHU é STEC (ou S. dysenteriae tipo 1)." },
    ],
    dificuldade: "avancada",
    estilo: "diagnostico",
    tags: ["SHU", "diarreia", "STEC"],
    fonte: FONTE,
  },
  {
    id: "ped-des-68",
    subtemaId: SUB.desidratacao,
    disciplinaId: "ped",
    enunciado: "Lactente de 8 meses, diarreia aguda, SEM sinais de desidratação. Conduta?",
    alternativas: [
      { letra: "A", texto: "Plano A: manter alimentação/aleitamento e ofertar SRO em casa após cada evacuação.", correta: true, comentario: "Ausência de sinais de desidratação = Plano A, manejo domiciliar." },
      { letra: "B", texto: "Plano B na unidade de saúde.", correta: false, comentario: "Plano B é para 'algum grau' de desidratação." },
      { letra: "C", texto: "Internação hospitalar.", correta: false, comentario: "Desnecessária sem sinais de desidratação." },
      { letra: "D", texto: "Dieta zero por 24h.", correta: false, comentario: "Contraindicada; manter alimentação/aleitamento." },
    ],
    dificuldade: "fixacao",
    estilo: "conduta",
    tags: ["diarreia", "plano A"],
    fonte: FONTE,
  },

  // ── BRONQUIOLITE E CRUPE ────────────────────────────────────────
  {
    id: "ped-bvc-13",
    subtemaId: SUB.bronquiolite,
    disciplinaId: "ped",
    enunciado:
      "Lactente de 4 meses, 1º episódio de sibilância após pródromo catarral, tiragem subcostal, FR 62. Diagnóstico e conduta baseada em evidências?",
    alternativas: [
      { letra: "A", texto: "Asma; iniciar broncodilatador e corticoide.", correta: false, comentario: "Asma é diagnóstico de exclusão nessa idade; 1º episódio com pródromo viral sugere bronquiolite." },
      { letra: "B", texto: "Bronquiolite viral aguda; suporte, O2 se SatO2 <90–92% e hidratação, sem broncodilatador/corticoide de rotina.", correta: true, comentario: "Conduta AAP/SBP: suporte. Broncodilatador e corticoide não são recomendados de rotina." },
      { letra: "C", texto: "Pneumonia bacteriana; amoxicilina.", correta: false, comentario: "Sem consolidação; antibiótico não é rotina." },
      { letra: "D", texto: "Crupe; corticoide + adrenalina.", correta: false, comentario: "Crupe cursa com estridor/tosse ladrante, não sibilância." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["bronquiolite", "VSR", "suporte"],
    fonte: FONTE,
  },
  {
    id: "ped-bvc-16",
    subtemaId: SUB.crupe,
    disciplinaId: "ped",
    enunciado: "Tratamento de escolha para crupe viral MODERADO (estridor em repouso, sem agitação)?",
    alternativas: [
      { letra: "A", texto: "Nebulização com soro fisiológico isolada.", correta: false, comentario: "Insuficiente para crupe moderado." },
      { letra: "B", texto: "Dexametasona 0,6 mg/kg VO ou IM, dose única.", correta: true, comentario: "Corticoide é o tratamento padrão, reduz edema e necessidade de reavaliação/internação." },
      { letra: "C", texto: "Antibiótico (amoxicilina).", correta: false, comentario: "Crupe é viral; antibiótico não indicado." },
      { letra: "D", texto: "Broncodilatador inalatório.", correta: false, comentario: "Sem papel no crupe (obstrução laríngea/subglótica, não brônquica)." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["crupe", "dexametasona"],
    fonte: FONTE,
  },
  {
    id: "ped-bvc-21",
    subtemaId: SUB.crupe,
    disciplinaId: "ped",
    enunciado: "Após adrenalina nebulizada no crupe grave, qual o tempo mínimo de observação?",
    alternativas: [
      { letra: "A", texto: "30 minutos.", correta: false, comentario: "Insuficiente diante do risco de rebote." },
      { letra: "B", texto: "1 hora.", correta: false, comentario: "Ainda insuficiente." },
      { letra: "C", texto: "3 a 4 horas.", correta: true, comentario: "O efeito da adrenalina é rápido mas transitório; observar 3–4h pelo risco de rebote." },
      { letra: "D", texto: "Internação obrigatória de 24h.", correta: false, comentario: "Não é obrigatória se a criança permanecer estável no período de observação." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["crupe", "adrenalina", "rebote"],
    fonte: FONTE,
  },
  {
    id: "ped-bvc-22",
    subtemaId: SUB.crupe,
    disciplinaId: "ped",
    enunciado: "Principal causa BACTERIANA de estridor agudo grave, hoje rara após a vacinação universal contra Hib?",
    alternativas: [
      { letra: "A", texto: "Epiglotite aguda por Haemophilus influenzae tipo b.", correta: true, comentario: "Era a principal causa bacteriana de estridor grave antes da vacina Hib; hoje rara." },
      { letra: "B", texto: "Traqueíte bacteriana.", correta: false, comentario: "Diferencial importante, mas não é a que despencou com a vacina Hib." },
      { letra: "C", texto: "Abscesso retrofaríngeo.", correta: false, comentario: "Cursa mais com dor cervical/torcicolo do que estridor predominante." },
      { letra: "D", texto: "Difteria laríngea.", correta: false, comentario: "Relaciona-se à cobertura DTP, não à vacina Hib." },
    ],
    dificuldade: "intermediaria",
    estilo: "diagnostico",
    tags: ["epiglotite", "Hib", "estridor"],
    fonte: FONTE,
  },
  {
    id: "ped-bvc-59",
    subtemaId: SUB.crupe,
    disciplinaId: "ped",
    enunciado: "Principal diferença clínica entre crupe e epiglotite?",
    alternativas: [
      { letra: "A", texto: "A presença de estridor.", correta: false, comentario: "Estridor pode estar em ambas — não é o diferenciador central." },
      { letra: "B", texto: "A toxemia e prostração intensa (com sialorreia, posição em tripé e disfagia) da epiglotite.", correta: true, comentario: "A epiglotite é toxêmica/prostrada; o crupe cursa com criança menos toxemiada — a gravidade sistêmica é o diferencial." },
      { letra: "C", texto: "A tosse metálica.", correta: false, comentario: "É do crupe, mas isolada não capta a diferença central de toxemia." },
      { letra: "D", texto: "A faixa etária.", correta: false, comentario: "As idades se sobrepõem; idade isolada não é o diferencial confiável." },
    ],
    dificuldade: "intermediaria",
    estilo: "diagnostico",
    tags: ["crupe", "epiglotite", "diagnóstico diferencial"],
    fonte: FONTE,
  },

  // ── ICTERÍCIA NEONATAL ──────────────────────────────────────────
  {
    id: "ped-ict-25",
    subtemaId: SUB.ictericia,
    disciplinaId: "ped",
    enunciado:
      "RN com 18h de vida, icterícia zona 2, mãe O+, RN A+, Coombs direto positivo. Diagnóstico e conduta?",
    alternativas: [
      { letra: "A", texto: "Icterícia fisiológica; observação.", correta: false, comentario: "Icterícia antes de 24h é sempre patológica." },
      { letra: "B", texto: "Incompatibilidade ABO; bilirrubinas seriadas e fototerapia conforme nomograma.", correta: true, comentario: "Mãe O / RN A(ou B) com Coombs direto positivo = incompatibilidade ABO (hemólise)." },
      { letra: "C", texto: "Icterícia do leite materno; suspender aleitamento.", correta: false, comentario: "Essa é tardia (após 1ª semana) e não se suspende o aleitamento." },
      { letra: "D", texto: "Atresia de vias biliares.", correta: false, comentario: "Cursaria com colestase (acolia/colúria), não esse quadro precoce hemolítico." },
    ],
    dificuldade: "intermediaria",
    estilo: "diagnostico",
    tags: ["icterícia neonatal", "incompatibilidade ABO", "Coombs"],
    fonte: FONTE,
  },
  {
    id: "ped-ict-26",
    subtemaId: SUB.ictericia,
    disciplinaId: "ped",
    enunciado: "Icterícia após a 1ª semana de vida, com fezes acólicas e colúria, sugere fortemente:",
    alternativas: [
      { letra: "A", texto: "Deficiência de G6PD.", correta: false, comentario: "Causa hemólise (bilirrubina indireta), sem acolia." },
      { letra: "B", texto: "Colestase (bilirrubina direta elevada) — excluir atresia de vias biliares com urgência.", correta: true, comentario: "Acolia + colúria = elevação de bilirrubina DIRETA (colestase); a atresia biliar deve ser excluída rapidamente." },
      { letra: "C", texto: "Esferocitose hereditária.", correta: false, comentario: "Hemólise/hiperbilirrubinemia indireta, sem acolia." },
      { letra: "D", texto: "Icterícia do leite materno.", correta: false, comentario: "É indireta e não causa acolia/colúria." },
    ],
    dificuldade: "intermediaria",
    estilo: "diagnostico",
    tags: ["colestase", "atresia biliar", "icterícia"],
    fonte: FONTE,
  },
  {
    id: "ped-ict-27",
    subtemaId: SUB.ictericia,
    disciplinaId: "ped",
    enunciado: "Principal complicação neurológica da hiperbilirrubinemia indireta livre que atravessa a barreira hematoencefálica?",
    alternativas: [
      { letra: "A", texto: "Hidrocefalia obstrutiva.", correta: false, comentario: "Não é causada por hiperbilirrubinemia." },
      { letra: "B", texto: "Kernicterus (encefalopatia bilirrubínica).", correta: true, comentario: "É a complicação neurológica clássica da hiperbilirrubinemia indireta grave não tratada." },
      { letra: "C", texto: "Meningite asséptica.", correta: false, comentario: "Sem relação causal." },
      { letra: "D", texto: "Paralisia cerebral espástica isolada.", correta: false, comentario: "Pode ser sequela tardia do kernicterus, mas a complicação direta é o próprio kernicterus." },
    ],
    dificuldade: "fixacao",
    estilo: "diagnostico",
    tags: ["kernicterus", "bilirrubina"],
    fonte: FONTE,
  },
  {
    id: "ped-ict-31",
    subtemaId: SUB.ictericia,
    disciplinaId: "ped",
    enunciado: "Principal mecanismo de ação da fototerapia na icterícia neonatal?",
    alternativas: [
      { letra: "A", texto: "Foto-oxidação sistêmica generalizada.", correta: false, comentario: "Não é o mecanismo." },
      { letra: "B", texto: "Conversão da bilirrubina em fotoisômeros hidrossolúveis (ex.: lumirrubina), excretáveis sem conjugação hepática.", correta: true, comentario: "A luz gera fotoisômeros hidrossolúveis excretados na bile/urina sem depender da conjugação hepática." },
      { letra: "C", texto: "Hemólise reversa.", correta: false, comentario: "Não existe tal mecanismo." },
      { letra: "D", texto: "Quelação hepática da bilirrubina.", correta: false, comentario: "Não atua por quelação." },
    ],
    dificuldade: "intermediaria",
    estilo: "exame",
    tags: ["fototerapia", "icterícia"],
    fonte: FONTE,
  },

  // ── CONVULSÃO FEBRIL ────────────────────────────────────────────
  {
    id: "ped-cf-37",
    subtemaId: SUB.convulsao,
    disciplinaId: "ped",
    enunciado:
      "Lactente de 18 meses, crise tônico-clônica generalizada de 3 min durante pico febril por otite, recupera rapidamente. Diagnóstico?",
    alternativas: [
      { letra: "A", texto: "Epilepsia mioclônica.", correta: false, comentario: "Sem crises mioclônicas nem padrão epiléptico compatível." },
      { letra: "B", texto: "Convulsão febril simples.", correta: true, comentario: "Generalizada, <15 min, única, recuperação rápida, 6m–5a, associada à febre = simples." },
      { letra: "C", texto: "Convulsão febril complexa.", correta: false, comentario: "Complexa exige >15 min, foco ou recorrência em 24h." },
      { letra: "D", texto: "Meningite.", correta: false, comentario: "Recuperação rápida e completa argumenta contra." },
    ],
    dificuldade: "fixacao",
    estilo: "diagnostico",
    tags: ["convulsão febril", "simples"],
    fonte: FONTE,
  },
  {
    id: "ped-cf-38",
    subtemaId: SUB.convulsao,
    disciplinaId: "ped",
    enunciado: "Qual característica define uma convulsão febril como 'complexa'?",
    alternativas: [
      { letra: "A", texto: "Duração >15 min, recorrência em <24h ou caráter focal.", correta: true, comentario: "Qualquer um destes três define a crise febril complexa." },
      { letra: "B", texto: "Ocorrer entre 6 meses e 5 anos.", correta: false, comentario: "É a faixa etária geral, não critério de complexidade." },
      { letra: "C", texto: "Ser tônico-clônica generalizada.", correta: false, comentario: "Característica da forma simples." },
      { letra: "D", texto: "Ausência de déficit pós-ictal.", correta: false, comentario: "Achado tranquilizador, compatível com crise simples." },
    ],
    dificuldade: "fixacao",
    estilo: "diagnostico",
    tags: ["convulsão febril", "complexa"],
    fonte: FONTE,
  },
  {
    id: "ped-cf-40",
    subtemaId: SUB.convulsao,
    disciplinaId: "ped",
    enunciado: "Manejo agudo de crise convulsiva febril com duração >5 minutos?",
    alternativas: [
      { letra: "A", texto: "Dipirona endovenosa.", correta: false, comentario: "Trata a febre, não aborta a crise." },
      { letra: "B", texto: "Benzodiazepínico (diazepam ou midazolam).", correta: true, comentario: "Crises >5 min devem ser abortadas com benzodiazepínico, conforme protocolo de estado de mal." },
      { letra: "C", texto: "Banho morno.", correta: false, comentario: "Não aborta crise e pode ser contraproducente." },
      { letra: "D", texto: "Fenitoína de ataque em todos os casos.", correta: false, comentario: "Não é a primeira escolha nesse contexto inicial." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["convulsão febril", "benzodiazepínico"],
    fonte: FONTE,
  },
  {
    id: "ped-cf-43",
    subtemaId: SUB.convulsao,
    disciplinaId: "ped",
    enunciado: "Risco estimado de desenvolver epilepsia após uma convulsão febril SIMPLES?",
    alternativas: [
      { letra: "A", texto: "Cerca de 30%.", correta: false, comentario: "Muito superestimado." },
      { letra: "B", texto: "Cerca de 10%.", correta: false, comentario: "Superestimado para a forma simples." },
      { letra: "C", texto: "Em torno de 1% (discretamente acima da população geral).", correta: true, comentario: "O prognóstico da convulsão febril simples é excelente; risco ~1%." },
      { letra: "D", texto: "Cerca de 50%.", correta: false, comentario: "Extremamente superestimado." },
    ],
    dificuldade: "intermediaria",
    estilo: "diagnostico",
    tags: ["convulsão febril", "prognóstico", "epilepsia"],
    fonte: FONTE,
  },
  {
    id: "ped-cf-53",
    subtemaId: SUB.convulsao,
    disciplinaId: "ped",
    enunciado: "Situação em que a punção lombar é fortemente recomendada na primeira crise febril?",
    alternativas: [
      { letra: "A", texto: "Tosse isolada em criança de 3 anos.", correta: false, comentario: "Não é indicação de punção." },
      { letra: "B", texto: "Idade <6–12 meses (imunização incompleta) ou uso prévio de antibiótico que possa mascarar meningite.", correta: true, comentario: "Nessas situações há maior risco/dificuldade de excluir meningite → punção lombar recomendada." },
      { letra: "C", texto: "Crise com duração >2 minutos.", correta: false, comentario: "A duração isolada não é o critério definidor." },
      { letra: "D", texto: "Vômitos isolados.", correta: false, comentario: "Não são indicação formal específica." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["convulsão febril", "punção lombar", "meningite"],
    fonte: FONTE,
  },
];
