import type { Questao } from "@/domain/content/types";

const PED = {
  desidratacao: "ped--emergencias-pediatricas--desidratacao-e-reidratacao",
  bronquiolite: "ped--infeccoes-respiratorias-na-infancia--bronquiolite",
  crupe: "ped--infeccoes-respiratorias-na-infancia--crupe-laringotraqueobronquite",
  ictericia: "ped--neonatologia--ictericia-neonatal",
  convulsao: "ped--emergencias-pediatricas--convulsao-febril",
} as const;

const STORCH = "inf--infeccoes-congenitas--storch-visao-infectologica";
const FONTE_PED = "Google Drive — Simulado de Pediatria 1 (material do usuário)";
const FONTE_INF = "Google Drive — Exame Nacional de Infectologia Perinatal e Medicina Fetal (material do usuário)";

export const QUESTOES_PENDENTES_EXTRAIDAS: Questao[] = [
  {
    id: "ped-sim1-036",
    subtemaId: PED.ictericia,
    disciplinaId: "ped",
    enunciado: "RN pré-termo tardio, com 35 semanas, apresenta icterícia moderada. Qual é o principal cuidado ao usar os gráficos de indicação de fototerapia?",
    alternativas: [
      { letra: "A", texto: "Ignorar a idade gestacional.", correta: false, comentario: "A prematuridade modifica o limiar terapêutico e não pode ser ignorada." },
      { letra: "B", texto: "Usar o gráfico específico para idade gestacional, idade pós-natal e fatores de risco.", correta: true, comentario: "Os limiares dependem da idade gestacional, das horas de vida e dos fatores de neurotoxicidade." },
      { letra: "C", texto: "Suspender preventivamente a amamentação.", correta: false, comentario: "A amamentação deve ser apoiada; suspensão rotineira não é indicada." },
      { letra: "D", texto: "Iniciar fototerapia apenas se a bilirrubina total superar 25 mg/dL.", correta: false, comentario: "Não existe um corte único; o limiar é individualizado pelo nomograma." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["icterícia neonatal", "fototerapia", "prematuridade"],
    fonte: FONTE_PED,
  },
  {
    id: "ped-sim1-044",
    subtemaId: PED.convulsao,
    disciplinaId: "ped",
    enunciado: "Lactente de 10 meses apresenta crise convulsiva generalizada breve durante febre após vacinação. A possibilidade de convulsão febril é:",
    alternativas: [
      { letra: "A", texto: "Excluída por ter ocorrido após vacinação.", correta: false, comentario: "A vacinação não exclui a síndrome quando a febre é o gatilho e os demais critérios são atendidos." },
      { letra: "B", texto: "Aceitável, pois a febre pode atuar como gatilho.", correta: true, comentario: "O diagnóstico depende da faixa etária, febre e ausência de infecção do SNC ou causa metabólica; a origem da febre não o invalida." },
      { letra: "C", texto: "Impossível antes dos 12 meses.", correta: false, comentario: "Convulsão febril ocorre tipicamente entre 6 meses e 5 anos." },
      { letra: "D", texto: "Diagnóstica de encefalopatia vacinal.", correta: false, comentario: "Uma crise breve associada à febre não define encefalopatia." },
    ],
    dificuldade: "fixacao",
    estilo: "diagnostico",
    tags: ["convulsão febril", "vacinação", "febre"],
    fonte: FONTE_PED,
  },
  {
    id: "ped-sim1-046",
    subtemaId: PED.convulsao,
    disciplinaId: "ped",
    enunciado: "Criança apresenta crise convulsiva durante febre. Depois da crise, permanece sonolenta por 15 minutos e então desperta normalmente. Qual a conduta no pronto-atendimento?",
    alternativas: [
      { letra: "A", texto: "Internação obrigatória.", correta: false, comentario: "Recuperação completa após curto período pós-ictal não impõe internação por si só." },
      { letra: "B", texto: "Observar, procurar a causa da febre e, se permanecer bem, dar alta com orientação.", correta: true, comentario: "Após crise febril simples e recuperação neurológica completa, a conduta é observação, avaliação do foco e orientação familiar." },
      { letra: "C", texto: "Punção lombar imediata em todos os casos.", correta: false, comentario: "Punção é reservada à suspeita de meningite ou a situações clínicas selecionadas." },
      { letra: "D", texto: "EEG de urgência.", correta: false, comentario: "EEG não é exame rotineiro após crise febril simples." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["convulsão febril", "pós-ictal", "alta"],
    fonte: FONTE_PED,
  },
  {
    id: "ped-sim1-050",
    subtemaId: PED.convulsao,
    disciplinaId: "ped",
    enunciado: "Em qual faixa etária ocorre a maior incidência de convulsão febril?",
    alternativas: [
      { letra: "A", texto: "Do nascimento aos 6 meses.", correta: false, comentario: "Abaixo de 6 meses outras causas devem ser investigadas com especial atenção." },
      { letra: "B", texto: "Dos 6 meses aos 5 anos, com pico por volta dos 18 meses.", correta: true, comentario: "Essa é a faixa etária clássica, com maior frequência no segundo ano de vida." },
      { letra: "C", texto: "Dos 5 aos 10 anos.", correta: false, comentario: "Após 5 anos o diagnóstico típico se torna menos provável." },
      { letra: "D", texto: "Na adolescência.", correta: false, comentario: "Não é a faixa típica da síndrome." },
    ],
    dificuldade: "fixacao",
    estilo: "fixacao",
    tags: ["convulsão febril", "epidemiologia"],
    fonte: FONTE_PED,
  },
  {
    id: "ped-sim1-052",
    subtemaId: PED.convulsao,
    disciplinaId: "ped",
    enunciado: "Qual é o prognóstico intelectual de crianças que tiveram convulsão febril simples?",
    alternativas: [
      { letra: "A", texto: "Ruim, com perda progressiva de QI a cada crise.", correta: false, comentario: "Crises febris simples não causam declínio intelectual progressivo." },
      { letra: "B", texto: "Excelente, sem diferença relevante em relação a crianças que nunca tiveram crises.", correta: true, comentario: "O desenvolvimento cognitivo costuma permanecer normal após convulsão febril simples." },
      { letra: "C", texto: "Associado a TDAH na maioria dos casos.", correta: false, comentario: "Essa associação majoritária não existe." },
      { letra: "D", texto: "Dependente do uso crônico de anticonvulsivante.", correta: false, comentario: "Profilaxia crônica não melhora o prognóstico cognitivo e não é indicada rotineiramente." },
    ],
    dificuldade: "fixacao",
    estilo: "fixacao",
    tags: ["convulsão febril", "prognóstico"],
    fonte: FONTE_PED,
  },
  {
    id: "ped-sim1-054",
    subtemaId: PED.convulsao,
    disciplinaId: "ped",
    enunciado: "Qual é um dos principais fatores de risco para recorrência de convulsão febril?",
    alternativas: [
      { letra: "A", texto: "Primeira crise antes dos 12 meses.", correta: true, comentario: "Quanto mais precoce a primeira crise, maior a chance de recorrência." },
      { letra: "B", texto: "Sexo masculino isoladamente.", correta: false, comentario: "Não é o principal preditor entre as opções." },
      { letra: "C", texto: "Febre acima de 40 °C na primeira crise.", correta: false, comentario: "Crise com temperatura relativamente baixa e início precoce se associa mais à recorrência." },
      { letra: "D", texto: "Uso de dipirona.", correta: false, comentario: "Antitérmico não determina recorrência." },
    ],
    dificuldade: "fixacao",
    estilo: "fixacao",
    tags: ["convulsão febril", "recorrência"],
    fonte: FONTE_PED,
  },
  {
    id: "ped-sim1-057",
    subtemaId: PED.ictericia,
    disciplinaId: "ped",
    enunciado: "RN com 48 horas, icterícia zona 3, mãe O positivo, RN A positivo, Coombs direto positivo e bilirrubina total de 18 mg/dL. Qual é o mecanismo mais provável?",
    alternativas: [
      { letra: "A", texto: "Hemólise por anticorpos maternos anti-A/anti-B.", correta: true, comentario: "Mãe O e RN A/B com Coombs positivo caracterizam doença hemolítica por incompatibilidade ABO." },
      { letra: "B", texto: "Deficiência de G6PD obrigatória.", correta: false, comentario: "Pode causar hemólise, mas não explica o padrão materno-neonatal e o Coombs positivo." },
      { letra: "C", texto: "Icterícia do leite materno.", correta: false, comentario: "É mais tardia e não causa Coombs positivo." },
      { letra: "D", texto: "Policitemia.", correta: false, comentario: "Aumenta a carga de bilirrubina, mas não produz Coombs positivo por incompatibilidade ABO." },
    ],
    dificuldade: "intermediaria",
    estilo: "diagnostico",
    tags: ["icterícia neonatal", "incompatibilidade ABO", "Coombs"],
    fonte: FONTE_PED,
  },
  {
    id: "ped-sim1-058",
    subtemaId: PED.bronquiolite,
    disciplinaId: "ped",
    enunciado: "Lactente de 3 meses apresenta primeiro episódio de sibilância após pródromo viral, está hidratado e mantém SatO₂ de 93%. Qual a conduta de escolha?",
    alternativas: [
      { letra: "A", texto: "Adrenalina nebulizada de rotina.", correta: false, comentario: "Adrenalina não é tratamento rotineiro da bronquiolite." },
      { letra: "B", texto: "Corticoide sistêmico.", correta: false, comentario: "Corticoide não traz benefício rotineiro na bronquiolite típica." },
      { letra: "C", texto: "Suporte, com higiene nasal, hidratação e reavaliação clínica.", correta: true, comentario: "O tratamento é de suporte; com saturação estável de 93% e sem gravidade, não há indicação automática de oxigênio ou broncodilatador." },
      { letra: "D", texto: "Salbutamol contínuo.", correta: false, comentario: "Broncodilatadores não são recomendados rotineiramente no primeiro episódio típico." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["bronquiolite", "suporte", "oximetria"],
    fonte: FONTE_PED,
  },
  {
    id: "ped-sim1-061",
    subtemaId: PED.desidratacao,
    disciplinaId: "ped",
    enunciado: "Lactente de 6 meses com diarreia há 5 dias, olhos encovados e sede intensa inicia TRO e vomita duas vezes. Qual a melhor conduta?",
    alternativas: [
      { letra: "A", texto: "Interromper imediatamente e migrar para Plano C.", correta: false, comentario: "Dois vômitos não configuram falha da TRO se a criança consegue continuar recebendo pequenos volumes." },
      { letra: "B", texto: "Substituir a SRO por água de coco.", correta: false, comentario: "Água de coco não substitui a composição padronizada da SRO." },
      { letra: "C", texto: "Continuar a TRO em volumes menores e mais frequentes, reavaliando.", correta: true, comentario: "Vômitos ocasionais são manejados com pausa breve e oferta fracionada; a TRO deve ser mantida." },
      { letra: "D", texto: "Iniciar antibiótico pela duração da diarreia.", correta: false, comentario: "A duração isolada não indica antibiótico." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["diarreia", "TRO", "vômitos"],
    fonte: FONTE_PED,
  },
  {
    id: "ped-sim1-063",
    subtemaId: PED.ictericia,
    disciplinaId: "ped",
    enunciado: "Em um lactente com icterícia, qual achado laboratorial obriga investigação de colestase?",
    alternativas: [
      { letra: "A", texto: "Elevação isolada de bilirrubina indireta.", correta: false, comentario: "Hiperbilirrubinemia indireta isolada não define colestase." },
      { letra: "B", texto: "Bilirrubina direta igual ou superior a 1,0 mg/dL.", correta: true, comentario: "Bilirrubina direta ≥1 mg/dL é anormal e exige investigação rápida de colestase; o antigo critério percentual não deve atrasar a avaliação." },
      { letra: "C", texto: "Hemoglobina discretamente reduzida.", correta: false, comentario: "Anemia não define colestase." },
      { letra: "D", texto: "Leucocitose isolada.", correta: false, comentario: "Não é marcador diagnóstico de colestase." },
    ],
    dificuldade: "fixacao",
    estilo: "exame",
    tags: ["icterícia", "colestase", "bilirrubina direta"],
    fonte: FONTE_PED,
  },
  {
    id: "ped-sim1-064",
    subtemaId: PED.ictericia,
    disciplinaId: "ped",
    enunciado: "Lactente de 2 meses, em aleitamento materno exclusivo, com ganho ponderal adequado e icterícia persistente, sem colúria ou acolia. Qual a hipótese mais provável?",
    alternativas: [
      { letra: "A", texto: "Icterícia do leite materno.", correta: true, comentario: "Em lactente saudável, com bom ganho de peso e hiperbilirrubinemia indireta tardia, essa é a hipótese mais provável; ainda assim, icterícia prolongada exige fracionar bilirrubinas para excluir colestase." },
      { letra: "B", texto: "Hepatite neonatal obrigatória.", correta: false, comentario: "Seria mais provável com sinais de colestase ou doença sistêmica." },
      { letra: "C", texto: "Atresia de vias biliares como diagnóstico já confirmado.", correta: false, comentario: "Deve ser excluída se houver bilirrubina direta elevada, colúria ou acolia, mas a vinheta não a confirma." },
      { letra: "D", texto: "Incompatibilidade Rh.", correta: false, comentario: "A doença hemolítica Rh costuma se manifestar precocemente e não corresponde ao padrão descrito." },
    ],
    dificuldade: "intermediaria",
    estilo: "diagnostico",
    tags: ["icterícia do leite materno", "icterícia prolongada"],
    fonte: FONTE_PED,
  },
  {
    id: "ped-sim1-065",
    subtemaId: PED.crupe,
    disciplinaId: "ped",
    enunciado: "Qual é o principal mecanismo da adrenalina nebulizada no crupe?",
    alternativas: [
      { letra: "A", texto: "Broncodilatação predominante.", correta: false, comentario: "O alvo clínico é o edema subglótico, não broncoespasmo." },
      { letra: "B", texto: "Vasoconstrição da mucosa laríngea, com redução rápida do edema.", correta: true, comentario: "A ação alfa-adrenérgica reduz temporariamente o edema subglótico e melhora o estridor." },
      { letra: "C", texto: "Ação anti-inflamatória tardia.", correta: false, comentario: "Essa função é do corticoide; a adrenalina tem efeito rápido e transitório." },
      { letra: "D", texto: "Aumento do clearance mucociliar.", correta: false, comentario: "Não é o mecanismo responsável pela melhora imediata." },
    ],
    dificuldade: "fixacao",
    estilo: "fixacao",
    tags: ["crupe", "adrenalina", "edema subglótico"],
    fonte: FONTE_PED,
  },
  {
    id: "ped-sim1-066",
    subtemaId: PED.bronquiolite,
    disciplinaId: "ped",
    enunciado: "Considerando os critérios clássicos de elegibilidade para palivizumabe usados no material-fonte, qual criança se enquadra?",
    alternativas: [
      { letra: "A", texto: "Prematuro de 34 semanas, saudável.", correta: false, comentario: "Não atendia ao corte clássico federal de prematuridade extrema." },
      { letra: "B", texto: "Lactente de 1 ano com asma.", correta: false, comentario: "Asma isolada não é critério de elegibilidade." },
      { letra: "C", texto: "Prematuro de 27 semanas, com 5 meses no início da sazonalidade.", correta: true, comentario: "Atende ao critério clássico de idade gestacional ≤28 semanas e idade inferior a 1 ano. Em 2026, o SUS está em transição para nirsevimabe; a escolha do produto deve seguir o protocolo vigente e o histórico da sazonalidade anterior." },
      { letra: "D", texto: "Criança de 3 anos com cardiopatia já corrigida.", correta: false, comentario: "Ultrapassa a faixa etária e não há repercussão hemodinâmica ativa descrita." },
    ],
    dificuldade: "intermediaria",
    estilo: "conduta",
    tags: ["VSR", "palivizumabe", "nirsevimabe"],
    fonte: FONTE_PED,
  },
  {
    id: "inf-cong-src-05",
    subtemaId: STORCH,
    disciplinaId: "inf",
    enunciado: "No manejo pós-natal de criança exposta ao HIV, qual conduta é proscrita pelas normas brasileiras de prevenção da transmissão vertical?",
    alternativas: [
      { letra: "A", texto: "Profilaxia antirretroviral neonatal conforme estratificação de risco.", correta: false, comentario: "A profilaxia neonatal integra a prevenção da transmissão vertical." },
      { letra: "B", texto: "Inibição da lactação materna.", correta: false, comentario: "No Brasil, a lactação deve ser inibida e substituída por alimentação segura fornecida pelo SUS." },
      { letra: "C", texto: "Aleitamento materno exclusivo nos primeiros seis meses.", correta: true, comentario: "No Brasil, o aleitamento é contraindicado em pessoas vivendo com HIV, mesmo com carga viral suprimida, pelo risco residual de transmissão." },
      { letra: "D", texto: "Seguimento virológico do lactente.", correta: false, comentario: "A investigação com testes moleculares faz parte do acompanhamento." },
      { letra: "E", texto: "Vacinação conforme as condições clínicas e o calendário aplicável.", correta: false, comentario: "A vacinação é mantida com ajustes quando houver imunossupressão." },
    ],
    dificuldade: "fixacao",
    estilo: "conduta",
    tags: ["HIV", "transmissão vertical", "aleitamento"],
    fonte: FONTE_INF,
  },
  {
    id: "inf-cong-src-15",
    subtemaId: STORCH,
    disciplinaId: "inf",
    enunciado: "Gestante de 12 semanas tem IgG e IgM positivos para toxoplasmose, mas alta avidez de IgG. Qual a interpretação mais provável?",
    alternativas: [
      { letra: "A", texto: "Infecção adquirida no último mês.", correta: false, comentario: "Infecção recente tende a apresentar baixa avidez." },
      { letra: "B", texto: "Infecção adquirida há pelo menos três a quatro meses, tornando improvável aquisição na gestação atual.", correta: true, comentario: "Alta avidez no primeiro trimestre afasta, em geral, infecção adquirida recentemente." },
      { letra: "C", texto: "Infecção fetal confirmada.", correta: false, comentario: "Sorologia materna não confirma infecção fetal." },
      { letra: "D", texto: "Resultado obrigatoriamente inconclusivo.", correta: false, comentario: "A alta avidez precoce tem utilidade para afastar infecção recente." },
      { letra: "E", texto: "Reativação com risco fetal de 50%.", correta: false, comentario: "Essa conclusão não decorre do teste de avidez." },
    ],
    dificuldade: "intermediaria",
    estilo: "exame",
    tags: ["toxoplasmose", "avidez de IgG", "gestação"],
    fonte: FONTE_INF,
  },
  {
    id: "inf-cong-src-18",
    subtemaId: STORCH,
    disciplinaId: "inf",
    enunciado: "Na transmissão vertical do vírus da hepatite C, qual fator está mais fortemente associado ao aumento do risco entre as opções?",
    alternativas: [
      { letra: "A", texto: "Via de parto vaginal.", correta: false, comentario: "Cesárea não é indicada apenas para prevenir transmissão do HCV." },
      { letra: "B", texto: "Coinfecção materna pelo HIV.", correta: true, comentario: "A coinfecção pelo HIV aumenta o risco, sobretudo quando não controlada; carga viral detectável do HCV também é determinante." },
      { letra: "C", texto: "Aleitamento materno sem fissuras ou sangramento.", correta: false, comentario: "Não é contraindicado nessas condições." },
      { letra: "D", texto: "Amniocentese isoladamente.", correta: false, comentario: "Procedimentos invasivos devem ser evitados quando possível, mas a coinfecção HIV é a associação mais forte listada." },
      { letra: "E", texto: "Anti-HCV positivo independentemente de RNA viral.", correta: false, comentario: "Sem viremia não ocorre transmissão vertical." },
    ],
    dificuldade: "intermediaria",
    estilo: "fixacao",
    tags: ["hepatite C", "transmissão vertical", "HIV"],
    fonte: FONTE_INF,
  },
  {
    id: "inf-cong-src-23",
    subtemaId: STORCH,
    disciplinaId: "inf",
    enunciado: "Qual é a manifestação típica do pênfigo sifilítico na sífilis congênita precoce?",
    alternativas: [
      { letra: "A", texto: "Vesículas e bolhas em palmas e plantas, que deixam erosões ao romper.", correta: true, comentario: "O acometimento palmoplantar bolhoso é característico da sífilis congênita precoce." },
      { letra: "B", texto: "Exantema que poupa extremidades.", correta: false, comentario: "A sífilis pode justamente acometer palmas e plantas." },
      { letra: "C", texto: "Crostas melicéricas periorificiais.", correta: false, comentario: "Sugere impetigo." },
      { letra: "D", texto: "Nódulos dolorosos em superfícies extensoras.", correta: false, comentario: "Não descreve pênfigo sifilítico." },
      { letra: "E", texto: "Lesões exclusivamente petequiais.", correta: false, comentario: "Não é a lesão clássica perguntada." },
    ],
    dificuldade: "fixacao",
    estilo: "diagnostico",
    tags: ["sífilis congênita", "pênfigo sifilítico"],
    fonte: FONTE_INF,
  },
  {
    id: "inf-cong-src-25",
    subtemaId: STORCH,
    disciplinaId: "inf",
    enunciado: "RN de 3 dias tem vesículas no couro cabeludo no local de eletrodo interno, letargia, convulsões e líquor com pleocitose e hiperproteinorraquia. Qual a principal hipótese?",
    alternativas: [
      { letra: "A", texto: "Meningite por estreptococo do grupo B.", correta: false, comentario: "Pode causar sepse/meningite, mas as vesículas e a porta de entrada favorecem HSV." },
      { letra: "B", texto: "Herpes simples neonatal com acometimento do sistema nervoso central.", correta: true, comentario: "Vesículas, encefalite e exposição por eletrodo de escalpo formam um quadro clássico de HSV neonatal." },
      { letra: "C", texto: "Toxoplasmose congênita.", correta: false, comentario: "Não costuma causar vesículas localizadas no sítio do eletrodo." },
      { letra: "D", texto: "Síndrome congênita do Zika.", correta: false, comentario: "Não explica o padrão vesicular e encefalítico agudo." },
      { letra: "E", texto: "CMV congênito.", correta: false, comentario: "CMV não produz tipicamente vesículas agrupadas nesse contexto." },
    ],
    dificuldade: "avancada",
    estilo: "diagnostico",
    tags: ["herpes neonatal", "encefalite", "eletrodo de escalpo"],
    fonte: FONTE_INF,
  },
  {
    id: "inf-cong-src-28",
    subtemaId: STORCH,
    disciplinaId: "inf",
    enunciado: "Calcificações intracranianas grosseiras, difusas pelo parênquima e descritas como 'em pipoca' são mais características de:",
    alternativas: [
      { letra: "A", texto: "Citomegalovírus.", correta: false, comentario: "CMV se associa classicamente a calcificações periventriculares." },
      { letra: "B", texto: "Toxoplasmose congênita.", correta: true, comentario: "A toxoplasmose produz calcificações intracranianas difusas, além de hidrocefalia e coriorretinite." },
      { letra: "C", texto: "Zika.", correta: false, comentario: "Zika costuma produzir calcificações corticais/subcorticais com microcefalia grave." },
      { letra: "D", texto: "Rubéola.", correta: false, comentario: "Calcificação difusa em pipoca não é o padrão típico." },
      { letra: "E", texto: "Sífilis.", correta: false, comentario: "Não é o padrão radiológico clássico da sífilis congênita." },
    ],
    dificuldade: "intermediaria",
    estilo: "imagem",
    tags: ["toxoplasmose congênita", "calcificações"],
    fonte: FONTE_INF,
  },
  {
    id: "inf-cong-src-30",
    subtemaId: STORCH,
    disciplinaId: "inf",
    enunciado: "Qual é a principal janela gestacional associada à síndrome da varicela congênita, com cicatrizes cutâneas, hipoplasia de membros e defeitos oculares?",
    alternativas: [
      { letra: "A", texto: "Entre a 13ª e a 20ª semana.", correta: true, comentario: "O risco é maior na primeira metade da gestação, particularmente entre 13 e 20 semanas." },
      { letra: "B", texto: "Apenas entre 28 e 32 semanas.", correta: false, comentario: "Essa não é a janela clássica da embriopatia." },
      { letra: "C", texto: "Somente nas últimas 48 horas antes do parto.", correta: false, comentario: "Esse período se associa a varicela neonatal grave, não à síndrome congênita clássica." },
      { letra: "D", texto: "Apenas durante o parto.", correta: false, comentario: "A síndrome decorre de infecção intrauterina." },
      { letra: "E", texto: "Exclusivamente no primeiro mês de vida.", correta: false, comentario: "Isso seria transmissão pós-natal." },
    ],
    dificuldade: "fixacao",
    estilo: "fixacao",
    tags: ["varicela congênita", "gestação"],
    fonte: FONTE_INF,
  },
  {
    id: "inf-cong-src-31",
    subtemaId: STORCH,
    disciplinaId: "inf",
    enunciado: "Gestante de 36 semanas tem febre alta, dor retro-orbital e mialgia, entra em trabalho de parto e o RN desenvolve plaquetopenia e sangramento no segundo dia. Qual a principal hipótese?",
    alternativas: [
      { letra: "A", texto: "Dengue perinatal.", correta: true, comentario: "Doença materna próxima ao parto pode transmitir dengue ao neonato, que evolui com febre, trombocitopenia e sangramento." },
      { letra: "B", texto: "Síndrome congênita do Zika.", correta: false, comentario: "Zika congênito se associa principalmente a alterações neurológicas estruturais." },
      { letra: "C", texto: "Sepse por estreptococo do grupo B como única possibilidade.", correta: false, comentario: "É diferencial, mas a síndrome materna e a plaquetopenia apontam para dengue." },
      { letra: "D", texto: "Doença hemorrágica por deficiência de vitamina K.", correta: false, comentario: "Não explica o quadro febril materno típico de dengue." },
      { letra: "E", texto: "CMV disseminado.", correta: false, comentario: "A temporalidade aguda periparto favorece dengue." },
    ],
    dificuldade: "avancada",
    estilo: "diagnostico",
    tags: ["dengue perinatal", "plaquetopenia", "transmissão vertical"],
    fonte: FONTE_INF,
  },
  {
    id: "inf-cong-src-33",
    subtemaId: STORCH,
    disciplinaId: "inf",
    enunciado: "Na sífilis congênita, a pseudoparalisia de Parrot decorre de:",
    alternativas: [
      { letra: "A", texto: "Gomas em nervos periféricos.", correta: false, comentario: "Não é o mecanismo clássico." },
      { letra: "B", texto: "Dor intensa por osteocondrite metafisária, levando à imobilidade do membro.", correta: true, comentario: "O lactente deixa de mover o membro por dor osteoarticular, sem paralisia neurológica verdadeira." },
      { letra: "C", texto: "AVC isquêmico intrauterino.", correta: false, comentario: "Não explica a pseudoparalisia característica." },
      { letra: "D", texto: "Miosite aguda isolada.", correta: false, comentario: "A lesão típica é osteocondrite/periostite." },
      { letra: "E", texto: "Luxação congênita bilateral do quadril.", correta: false, comentario: "Não é a etiologia desse sinal." },
    ],
    dificuldade: "fixacao",
    estilo: "diagnostico",
    tags: ["sífilis congênita", "Parrot", "osteocondrite"],
    fonte: FONTE_INF,
  },
  {
    id: "inf-cong-src-35",
    subtemaId: STORCH,
    disciplinaId: "inf",
    enunciado: "Lactente exposto à sífilis teve mãe adequadamente tratada, está assintomático e apresenta VDRL neonatal com título igual ao materno. Qual a conduta inicial mais adequada?",
    alternativas: [
      { letra: "A", texto: "Penicilina cristalina obrigatória por 10 dias.", correta: false, comentario: "Sem sinais, com tratamento materno adequado e título não superior ao materno, não há indicação automática desse esquema." },
      { letra: "B", texto: "Acompanhamento clínico e sorológico seriado até negativação.", correta: true, comentario: "O seguimento deve confirmar a queda dos títulos; persistência ou elevação exige reavaliação e tratamento." },
      { letra: "C", texto: "Punção lombar obrigatória em todos os casos.", correta: false, comentario: "A avaliação invasiva depende do cenário de risco, sinais e adequação do tratamento materno." },
      { letra: "D", texto: "Penicilina benzatina em dose única obrigatória.", correta: false, comentario: "Pode ser considerada em cenários específicos, mas não é obrigatória na situação de baixo risco bem acompanhada." },
      { letra: "E", texto: "Considerar curado sem qualquer seguimento.", correta: false, comentario: "O acompanhamento sorológico é indispensável." },
    ],
    dificuldade: "avancada",
    estilo: "conduta",
    tags: ["sífilis congênita", "VDRL", "seguimento"],
    fonte: FONTE_INF,
  },
  {
    id: "inf-cong-src-36",
    subtemaId: STORCH,
    disciplinaId: "inf",
    enunciado: "Como costuma se manifestar a transmissão vertical do chikungunya no período periparto?",
    alternativas: [
      { letra: "A", texto: "Microcefalia com calcificações cerebrais como regra.", correta: false, comentario: "Esse padrão remete sobretudo à síndrome congênita do Zika." },
      { letra: "B", texto: "Febre, irritabilidade, exantema e edema de extremidades.", correta: true, comentario: "Esse conjunto é típico da doença neonatal por transmissão periparto." },
      { letra: "C", texto: "Catarata e persistência do canal arterial.", correta: false, comentario: "É a tríade da rubéola congênita." },
      { letra: "D", texto: "Rinite e descamação palmoplantar.", correta: false, comentario: "Sugere sífilis congênita." },
      { letra: "E", texto: "Acolia fecal isolada.", correta: false, comentario: "Não é manifestação típica." },
    ],
    dificuldade: "intermediaria",
    estilo: "diagnostico",
    tags: ["chikungunya", "perinatal", "arbovirose"],
    fonte: FONTE_INF,
  },
  {
    id: "inf-cong-src-37",
    subtemaId: STORCH,
    disciplinaId: "inf",
    enunciado: "Em gestante HBsAg reagente, qual deve ser a via de parto preferencial para prevenção da transmissão vertical da hepatite B?",
    alternativas: [
      { letra: "A", texto: "Cesárea eletiva obrigatória.", correta: false, comentario: "Cesárea não é indicada apenas pelo HBsAg." },
      { letra: "B", texto: "Via obstétrica habitual, reservando cesárea para indicações obstétricas.", correta: true, comentario: "A prevenção neonatal depende de vacina e imunoglobulina nas primeiras horas; a via de parto segue indicação obstétrica." },
      { letra: "C", texto: "Cesárea sem contato com mucosa vaginal.", correta: false, comentario: "Não há recomendação desse procedimento para reduzir transmissão." },
      { letra: "D", texto: "Parto na água.", correta: false, comentario: "Não previne transmissão do HBV." },
      { letra: "E", texto: "Indução universal com 37 semanas.", correta: false, comentario: "Não é indicada por HBsAg isoladamente." },
    ],
    dificuldade: "fixacao",
    estilo: "conduta",
    tags: ["hepatite B", "parto", "transmissão vertical"],
    fonte: FONTE_INF,
  },
  {
    id: "inf-cong-src-39",
    subtemaId: STORCH,
    disciplinaId: "inf",
    enunciado: "O sinal de Higoumenakis, espessamento da extremidade medial da clavícula, é estigma tardio de:",
    alternativas: [
      { letra: "A", texto: "Rubéola congênita.", correta: false, comentario: "Não é estigma da rubéola." },
      { letra: "B", texto: "Sífilis congênita.", correta: true, comentario: "O espessamento clavicular é um dos estigmas ósseos tardios da sífilis congênita." },
      { letra: "C", texto: "Toxoplasmose congênita.", correta: false, comentario: "Não faz parte da tríade clássica da toxoplasmose." },
      { letra: "D", texto: "Osteogênese imperfeita.", correta: false, comentario: "Não é o sinal descrito." },
      { letra: "E", texto: "Raquitismo.", correta: false, comentario: "O raquitismo produz outros achados osteometabólicos." },
    ],
    dificuldade: "fixacao",
    estilo: "diagnostico",
    tags: ["sífilis congênita", "Higoumenakis"],
    fonte: FONTE_INF,
  },
];
