"use client";

import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import NextImage from "next/image";
import { FileImage, Image as ImageIcon, LockKeyhole, RefreshCw, ShieldCheck, Trash2, Upload } from "lucide-react";
import { carregarMidiaPrivada, excluirMidiaPrivada, salvarMidiaPrivada, type EntradaMidiaPrivada, type MidiaPrivada, type TipoOrigemMidiaPrivada } from "@/lib/midia-privada";
import { CatalogoMateriaisPrivados } from "@/components/midia/CatalogoMateriaisPrivados";

const vazio: EntradaMidiaPrivada = { titulo: "", tipoOrigem: "pdf_comercial", disciplina: "", tema: "", subtema: "", diagnostico: "", modalidade: "", fonte: "", pagina: null, observacao: "", pacienteAnonimizado: false, autorizacaoPaciente: false };
const ROTULOS: Record<TipoOrigemMidiaPrivada, string> = { pdf_comercial: "PDF comercial - uso privado", paciente: "Paciente anonimizado e autorizado", propria_privada: "Imagem propria mantida privada" };

export function MidiaPrivadaClient() {
  const [autenticado, setAutenticado] = useState<boolean | null>(null);
  const [itens, setItens] = useState<MidiaPrivada[]>([]);
  const [entrada, setEntrada] = useState<EntradaMidiaPrivada>(vazio);
  const [arquivo, setArquivo] = useState<File | null>(null);
  const [confirmacaoPrivada, setConfirmacaoPrivada] = useState(false);
  const [mensagem, setMensagem] = useState("");
  const [ocupado, setOcupado] = useState(false);

  const carregar = async () => { setOcupado(true); try { setItens(await carregarMidiaPrivada()); } catch (e) { setMensagem(e instanceof Error ? e.message : "Nao foi possivel carregar."); } finally { setOcupado(false); } };
  useEffect(() => { let ativo = true; let cancelar: (() => void) | undefined; void import("@/infra/supabase/client").then(async ({ getSupabaseAnon }) => { const supabase = getSupabaseAnon(); const { data } = await supabase.auth.getSession(); if (!ativo) return; const ok = Boolean(data.session?.user); setAutenticado(ok); if (ok) await carregar(); const a = supabase.auth.onAuthStateChange((_evento, sessao) => { if (!ativo) return; setAutenticado(Boolean(sessao?.user)); if (!sessao?.user) setItens([]); }); cancelar = () => a.data.subscription.unsubscribe(); }).catch(() => { if (ativo) setAutenticado(false); }); return () => { ativo = false; cancelar?.(); }; }, []);
  const alterar = <K extends keyof EntradaMidiaPrivada>(campo: K, valor: EntradaMidiaPrivada[K]) => setEntrada((atual) => ({ ...atual, [campo]: valor }));
  const enviar = async (evento: FormEvent) => { evento.preventDefault(); if (!arquivo) { setMensagem("Escolha uma imagem."); return; } if (entrada.tipoOrigem === "pdf_comercial" && !confirmacaoPrivada) { setMensagem("Confirme o uso somente privado."); return; } setOcupado(true); setMensagem(""); try { await salvarMidiaPrivada(arquivo, entrada); setEntrada(vazio); setArquivo(null); setConfirmacaoPrivada(false); await carregar(); setMensagem("Imagem salva na biblioteca privada."); } catch (e) { setMensagem(e instanceof Error ? e.message : "Nao foi possivel salvar."); } finally { setOcupado(false); } };
  const excluir = async (item: MidiaPrivada) => { if (!window.confirm(`Remover permanentemente \"${item.titulo}\"?`)) return; setOcupado(true); try { await excluirMidiaPrivada(item); setItens((atuais) => atuais.filter((x) => x.id !== item.id)); setMensagem("Imagem privada removida."); } catch (e) { setMensagem(e instanceof Error ? e.message : "Nao foi possivel remover."); } finally { setOcupado(false); } };

  if (autenticado === null) return <div className="mx-auto max-w-4xl px-5 py-12 text-sm text-text-muted">Verificando sua sessao...</div>;
  if (!autenticado) return <Bloqueio />;
  return <div className="mx-auto max-w-6xl px-5 py-8 sm:px-8 sm:py-10">
    <header className="rounded-2xl border border-border bg-surface p-6 sm:p-8" style={{ boxShadow: "var(--shadow)" }}><div className="flex items-start gap-4"><span className="rounded-xl bg-accent p-3 text-accent-contrast"><LockKeyhole className="size-7" /></span><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-accent">Acesso pela sua conta</p><h1 className="mt-2 text-3xl font-bold text-text">Minha midia privada</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-text-muted">Arquivos fora do repositorio e do GitHub Pages. A conta proprietaria e exigida e cada visualizacao usa um link temporario de cinco minutos.</p></div></div></header>
    {mensagem && <p role="status" className="mt-5 rounded-xl border border-border bg-surface-2 px-4 py-3 text-sm text-text-muted">{mensagem}</p>}
    <section className="mt-6 grid gap-4 md:grid-cols-3"><Regra titulo="Publica" texto="Imagem propria ou com licenca aberta verificada vai para a aba Midia." /><Regra titulo="PDF comercial" texto="Somente aqui, para estudo pessoal, com origem e pagina." /><Regra titulo="Paciente" texto="Somente anonimizada e com autorizacao apropriada; privada por padrao." /></section>
    <section className="mt-6 rounded-2xl border border-border bg-surface p-5 sm:p-6"><div className="flex items-start gap-3"><span className="rounded-xl bg-surface-2 p-2.5 text-accent"><ShieldCheck className="size-5" /></span><div><h2 className="text-lg font-bold text-text">Curadoria feita pelo Codex</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-text-muted">Nos lotes de acervo, o Codex identifica imagens clinicamente uteis, confere origem e restricao de uso, classifica por disciplina, tema, subtema, achado e modalidade, e as correlaciona ao resumo ou caso correto. Voce nao precisa fazer essa ligacao manualmente.</p><p className="mt-2 max-w-3xl text-sm leading-6 text-text-muted">Imagem propria ou aberta pode ser preparada para a biblioteca publica com credito e licenca. Captura de material comercial continua somente aqui, com origem e pagina, e imagem de paciente continua privada e exige anonimato e autorizacao.</p></div></div></section>
    <CatalogoMateriaisPrivados />
    <form onSubmit={enviar} className="mt-6 rounded-2xl border border-border bg-surface p-5 sm:p-6"><h2 className="flex items-center gap-2 text-lg font-bold text-text"><Upload className="size-5 text-accent" /> Adicionar imagem privada</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
      <Campo label="Imagem"><input required type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={(e: ChangeEvent<HTMLInputElement>) => setArquivo(e.target.files?.[0] ?? null)} className={input} /></Campo>
      <Campo label="Titulo"><input required value={entrada.titulo} maxLength={180} onChange={(e) => alterar("titulo", e.target.value)} className={input} /></Campo>
      <Campo label="Tipo"><select value={entrada.tipoOrigem} onChange={(e) => { alterar("tipoOrigem", e.target.value as TipoOrigemMidiaPrivada); setConfirmacaoPrivada(false); }} className={input}>{Object.entries(ROTULOS).map(([v, r]) => <option key={v} value={v}>{r}</option>)}</select></Campo>
      <Campo label="Disciplina"><input value={entrada.disciplina} onChange={(e) => alterar("disciplina", e.target.value)} className={input} /></Campo><Campo label="Tema"><input value={entrada.tema} onChange={(e) => alterar("tema", e.target.value)} className={input} /></Campo><Campo label="Subtema"><input value={entrada.subtema} onChange={(e) => alterar("subtema", e.target.value)} className={input} /></Campo>
      <Campo label="Diagnostico/achado"><input value={entrada.diagnostico} onChange={(e) => alterar("diagnostico", e.target.value)} className={input} /></Campo><Campo label="Modalidade"><input value={entrada.modalidade} onChange={(e) => alterar("modalidade", e.target.value)} className={input} /></Campo><Campo label="Origem"><input required={entrada.tipoOrigem === "pdf_comercial"} value={entrada.fonte} onChange={(e) => alterar("fonte", e.target.value)} className={input} /></Campo><Campo label="Pagina"><input required={entrada.tipoOrigem === "pdf_comercial"} type="number" min={1} value={entrada.pagina ?? ""} onChange={(e) => alterar("pagina", e.target.value ? Number(e.target.value) : null)} className={input} /></Campo>
    </div><Campo label="Observacao"><textarea value={entrada.observacao} maxLength={2000} rows={3} onChange={(e) => alterar("observacao", e.target.value)} className={`${input} resize-y`} /></Campo>
    {entrada.tipoOrigem === "pdf_comercial" && <label className="mt-4 flex gap-3 rounded-xl border border-border bg-surface-2 p-4 text-sm text-text-muted"><input required type="checkbox" checked={confirmacaoPrivada} onChange={(e) => setConfirmacaoPrivada(e.target.checked)} />Confirmo que a captura ficara somente na biblioteca autenticada para meu estudo pessoal.</label>}
    {entrada.tipoOrigem === "paciente" && <div className="mt-4 grid gap-3 rounded-xl border border-border bg-surface-2 p-4 text-sm text-text-muted sm:grid-cols-2"><label className="flex gap-3"><input required type="checkbox" checked={entrada.pacienteAnonimizado} onChange={(e) => alterar("pacienteAnonimizado", e.target.checked)} />Imagem completamente anonimizada.</label><label className="flex gap-3"><input required type="checkbox" checked={entrada.autorizacaoPaciente} onChange={(e) => alterar("autorizacaoPaciente", e.target.checked)} />Autorizacao apropriada confirmada.</label></div>}
    <button disabled={ocupado} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-accent px-4 py-2.5 text-sm font-bold text-accent-contrast disabled:opacity-60"><ShieldCheck className="size-4" />{ocupado ? "Processando..." : "Salvar com acesso privado"}</button></form>
    <section className="mt-6 rounded-2xl border border-border bg-surface p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-bold text-text"><FileImage className="size-5 text-accent" /> Biblioteca protegida</h2><p className="text-sm text-text-muted">{itens.length} imagem(ns) nesta conta.</p></div><button disabled={ocupado} onClick={() => void carregar()} className="inline-flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-sm text-text-muted"><RefreshCw className="size-4" />Renovar</button></div>
      {!itens.length ? <p className="mt-5 rounded-xl bg-surface-2 p-4 text-sm text-text-muted">Nenhuma imagem privada cadastrada.</p> : <div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{itens.map((item) => <article key={item.id} className="overflow-hidden rounded-xl border border-border bg-surface-2">{item.urlTemporaria ? <NextImage src={item.urlTemporaria} alt={item.titulo} width={800} height={600} unoptimized className="aspect-[4/3] w-full bg-bg object-contain" /> : <div className="grid aspect-[4/3] place-items-center bg-bg text-sm text-text-muted"><ImageIcon className="size-8" />Visualizacao expirada</div>}<div className="p-4"><p className="text-[10px] font-semibold uppercase text-accent">{ROTULOS[item.tipoOrigem]}</p><h3 className="mt-1 font-bold text-text">{item.titulo}</h3><p className="mt-2 text-xs text-text-muted">{[item.disciplina, item.tema, item.subtema, item.modalidade].filter(Boolean).join(" · ") || "Sem classificacao"}</p>{item.fonte && <p className="mt-2 text-xs text-text-muted">Origem: {item.fonte}{item.pagina ? `, p. ${item.pagina}` : ""}</p>}<button disabled={ocupado} onClick={() => void excluir(item)} className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-red-600"><Trash2 className="size-3" />Remover</button></div></article>)}</div>}
    </section>
  </div>;
}

const input = "mt-1 w-full rounded-lg border border-border bg-bg px-3 py-2.5 text-sm text-text outline-none focus:border-accent";
function Campo({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-xs font-semibold text-text-muted">{label}{children}</label>; }
function Regra({ titulo, texto }: { titulo: string; texto: string }) { return <article className="rounded-xl border border-border bg-surface p-4"><h2 className="font-bold text-text">{titulo}</h2><p className="mt-1 text-sm leading-6 text-text-muted">{texto}</p></article>; }
function Bloqueio() { return <div className="mx-auto max-w-3xl px-5 py-12"><section className="rounded-2xl border border-border bg-surface p-6"><LockKeyhole className="size-7 text-accent" /><h1 className="mt-3 text-2xl font-bold text-text">Minha midia privada</h1><p className="mt-2 text-sm text-text-muted">Entre pelo cabecalho. Sem sessao, nenhum arquivo ou metadado privado e solicitado.</p><Link href="/midia" className="mt-4 inline-flex text-sm font-semibold text-accent">Abrir biblioteca publica</Link></section></div>; }
