import type { ConteudoSubtema } from "@/domain/content/types";

export const CONTEUDOS_GASTRO_EXTRA: Record<string, ConteudoSubtema> = {
  "gastro--doenca-de-wilson--diagnostico-e-conduta": {
    subtemaId: "gastro--doenca-de-wilson--diagnostico-e-conduta",
    titulo: "Doença de Wilson — Diagnóstico e Conduta",
    atualizadoEm: "2026-07-27",
    origem: "complemento_ia",
    blocos: [
      { secao: "Panorama", corpo: "_Doença de Wilson — Diagnóstico e Conduta em prova é decisão prática: reconhecer o padrão, excluir sinais de gravidade e escolher a conduta inicial sem transformar rastreio em tratamento excessivo._" },
      { secao: "Definição", corpo: "Doença de Wilson — Diagnóstico e Conduta é abordado aqui como subtema de alto rendimento da OMED. O eixo é diferenciar apresentação típica, formas graves e situações em que a conduta muda imediatamente.\n\nWilson é distúrbio autossômico recessivo do ATP7B, com acúmulo de cobre em fígado, cérebro e córnea.\n\nJovem com hepatopatia, alteração neuropsiquiátrica, Coombs negativo com hemólise ou anel de Kayser-Fleischer deve ser investigado.\n\nTratamento usa quelantes ou zinco conforme cenário, e insuficiência hepática aguda pode exigir transplante." },
      { secao: "Fisiopatologia", corpo: "O mecanismo central explica a clínica e a prova: agressão inicial → alteração anatômica ou molecular → sinal clínico/laboratorial → complicação. Memorizar a conduta sem esse encadeamento gera erro em vinhetas com apresentação atípica." },
      { secao: "Fatores de risco e estratificação", corpo: "Estratifique por idade, comorbidades, imunossupressão, gestação, sinais sistêmicos, extensão da doença e risco de perda de órgão/função. Em oncologia, entram performance status, estadiamento e biologia molecular; em clínica, gravidade e resposta inicial." },
      { secao: "Avaliação clínica", corpo: "Procure sintomas dominantes, tempo de evolução, sinais de alarme e achados que mudam urgência. A banca costuma esconder a resposta em detalhes simples: febre persistente, perda ponderal, dor desproporcional, alteração neurológica, instabilidade, sangramento ou disfunção orgânica." },
      { secao: "Diagnóstico", corpo: "Use exame dirigido, laboratório e imagem apenas quando mudam a decisão. O diagnóstico não deve depender de um teste isolado quando o quadro clínico já exige ação; por outro lado, neoplasias e síndromes complexas exigem confirmação histológica, estadiamento e revisão de biomarcadores quando aplicável." },
      { secao: "Diagnóstico diferencial", corpo: "Diferenciais cobrados: doença infecciosa versus inflamatória, benigna versus maligna, periférica versus central, emergência verdadeira versus quadro ambulatorial. O discriminador costuma ser padrão temporal, exame físico focal, exame complementar-chave ou resposta esperada ao tratamento inicial." },
      { secao: "Condutas", corpo: "A conduta inicial deve ser proporcional ao risco: estabilizar primeiro, confirmar quando seguro, tratar causa reversível, encaminhar casos complexos e evitar terapias desatualizadas. Quando houver diretriz recente, a recomendação vigente prevalece sobre material antigo." },
      { secao: "Complicações", corpo: "Complicações relevantes incluem perda funcional, infecção secundária, trombose/sangramento, insuficiência orgânica, progressão maligna ou recorrência. Em prova, complicação é cobrada como indicação de internação, encaminhamento, imagem, antibiótico, procedimento ou mudança de linha terapêutica." },
      { secao: "Fluxograma de conduta", corpo: "1. Reconheça o padrão clínico.\n2. Procure sinal de gravidade ou instabilidade.\n3. Solicite o exame que confirma e muda conduta.\n4. Inicie tratamento seguro e atual.\n5. Reavalie resposta e complicações.\n6. Encaminhe para especialista quando houver neoplasia, falha terapêutica, doença sistêmica ou risco de órgão-alvo." },
      { secao: "Tabela comparativa", corpo: "| Situação | Pista principal | Conduta de prova |\n|---|---|---|\n| Quadro leve/típico | Sem sinal de alarme | Tratamento inicial e seguimento |\n| Sinal de gravidade | Instabilidade, disfunção ou risco de órgão | Internar/encaminhar e tratar precocemente |\n| Suspeita oncológica | Massa, perda ponderal, sangramento, imagem ou histologia suspeita | Confirmar tecido, estadiar e definir terapia por estágio/biomarcador |\n| Diagnóstico incerto | Achados mistos ou falha ao tratamento | Reavaliar diferencial e solicitar exame de maior acurácia |" },
      { secao: "Pérolas OMED", corpo: "- A melhor resposta costuma ser a primeira conduta segura, não o exame mais sofisticado.\n- Não trate número isolado: trate risco, contexto e tendência.\n- Em câncer, estadiamento e biomarcadores mudam tanto quanto o tipo histológico.\n- Em doenças inflamatórias/infecciosas, gravidade clínica pesa mais que nomenclatura." },
      { secao: "Pegadinhas clássicas", corpo: "- Confundir rastreio com diagnóstico definitivo.\n- Usar conduta antiga quando diretriz atual mudou o padrão.\n- Ignorar sinal de alarme por o paciente parecer estável.\n- Marcar terapia sistêmica sem confirmar histologia/estágio quando isso é obrigatório." },
      { secao: "Integração entre temas", corpo: "Integra-se com infectologia, emergência, radiologia, farmacologia, cirurgia e medicina de família. A utilidade no Codex Medicus é conectar resumo, questão e dashboard: erro em uma vinheta deve virar revisão ativa do subtema." },
      { secao: "Mnemônico", corpo: "**PARE**: **P**adrão clínico, **A**larmes, **R**isco/estágio, **E**scolha terapêutica." },
      { secao: "Questões da OMED", corpo: "A questão associada treina o ponto de maior risco deste subtema: reconhecer a pista decisiva e evitar a alternativa antiga, excessiva ou insuficiente." },
      { secao: "Resumo de 5 minutos", corpo: "> Doença de Wilson — Diagnóstico e Conduta: reconheça o padrão, classifique gravidade, confirme com o exame que muda conduta e trate conforme diretriz vigente. Ponto de prova: não transformar exceção em regra e não atrasar intervenção quando há risco de órgão ou vida.\n\n---" },
    ],
    referencias: [
      "AASLD Practice Guidance on Wilson Disease.",
      "EASL Clinical Practice Guidelines: Wilson's disease.",
      "Sociedade Brasileira de Hepatologia: hepatopatias metabólicas.",
    ],
  },

  "gastro--doenca-hepatica-alcoolica--diagnostico-e-conduta": {
    subtemaId: "gastro--doenca-hepatica-alcoolica--diagnostico-e-conduta",
    titulo: "Doença Hepática Alcoólica — Diagnóstico e Conduta",
    atualizadoEm: "2026-07-27",
    origem: "complemento_ia",
    blocos: [
      { secao: "Panorama", corpo: "_Doença Hepática Alcoólica — Diagnóstico e Conduta em prova é decisão prática: reconhecer o padrão, excluir sinais de gravidade e escolher a conduta inicial sem transformar rastreio em tratamento excessivo._" },
      { secao: "Definição", corpo: "Doença Hepática Alcoólica — Diagnóstico e Conduta é abordado aqui como subtema de alto rendimento da OMED. O eixo é diferenciar apresentação típica, formas graves e situações em que a conduta muda imediatamente.\n\nO espectro vai de esteatose a hepatite alcoólica, fibrose e cirrose.\n\nHepatite alcoólica típica tem icterícia recente, AST maior que ALT com valores geralmente abaixo de 400 e relação AST/ALT > 1,5.\n\nAbstinência é a intervenção central; casos graves exigem estratificação prognóstica e avaliação de corticoide quando não houver contraindicação." },
      { secao: "Fisiopatologia", corpo: "O mecanismo central explica a clínica e a prova: agressão inicial → alteração anatômica ou molecular → sinal clínico/laboratorial → complicação. Memorizar a conduta sem esse encadeamento gera erro em vinhetas com apresentação atípica." },
      { secao: "Fatores de risco e estratificação", corpo: "Estratifique por idade, comorbidades, imunossupressão, gestação, sinais sistêmicos, extensão da doença e risco de perda de órgão/função. Em oncologia, entram performance status, estadiamento e biologia molecular; em clínica, gravidade e resposta inicial." },
      { secao: "Avaliação clínica", corpo: "Procure sintomas dominantes, tempo de evolução, sinais de alarme e achados que mudam urgência. A banca costuma esconder a resposta em detalhes simples: febre persistente, perda ponderal, dor desproporcional, alteração neurológica, instabilidade, sangramento ou disfunção orgânica." },
      { secao: "Diagnóstico", corpo: "Use exame dirigido, laboratório e imagem apenas quando mudam a decisão. O diagnóstico não deve depender de um teste isolado quando o quadro clínico já exige ação; por outro lado, neoplasias e síndromes complexas exigem confirmação histológica, estadiamento e revisão de biomarcadores quando aplicável." },
      { secao: "Diagnóstico diferencial", corpo: "Diferenciais cobrados: doença infecciosa versus inflamatória, benigna versus maligna, periférica versus central, emergência verdadeira versus quadro ambulatorial. O discriminador costuma ser padrão temporal, exame físico focal, exame complementar-chave ou resposta esperada ao tratamento inicial." },
      { secao: "Condutas", corpo: "A conduta inicial deve ser proporcional ao risco: estabilizar primeiro, confirmar quando seguro, tratar causa reversível, encaminhar casos complexos e evitar terapias desatualizadas. Quando houver diretriz recente, a recomendação vigente prevalece sobre material antigo." },
      { secao: "Complicações", corpo: "Complicações relevantes incluem perda funcional, infecção secundária, trombose/sangramento, insuficiência orgânica, progressão maligna ou recorrência. Em prova, complicação é cobrada como indicação de internação, encaminhamento, imagem, antibiótico, procedimento ou mudança de linha terapêutica." },
      { secao: "Fluxograma de conduta", corpo: "1. Reconheça o padrão clínico.\n2. Procure sinal de gravidade ou instabilidade.\n3. Solicite o exame que confirma e muda conduta.\n4. Inicie tratamento seguro e atual.\n5. Reavalie resposta e complicações.\n6. Encaminhe para especialista quando houver neoplasia, falha terapêutica, doença sistêmica ou risco de órgão-alvo." },
      { secao: "Tabela comparativa", corpo: "| Situação | Pista principal | Conduta de prova |\n|---|---|---|\n| Quadro leve/típico | Sem sinal de alarme | Tratamento inicial e seguimento |\n| Sinal de gravidade | Instabilidade, disfunção ou risco de órgão | Internar/encaminhar e tratar precocemente |\n| Suspeita oncológica | Massa, perda ponderal, sangramento, imagem ou histologia suspeita | Confirmar tecido, estadiar e definir terapia por estágio/biomarcador |\n| Diagnóstico incerto | Achados mistos ou falha ao tratamento | Reavaliar diferencial e solicitar exame de maior acurácia |" },
      { secao: "Pérolas OMED", corpo: "- A melhor resposta costuma ser a primeira conduta segura, não o exame mais sofisticado.\n- Não trate número isolado: trate risco, contexto e tendência.\n- Em câncer, estadiamento e biomarcadores mudam tanto quanto o tipo histológico.\n- Em doenças inflamatórias/infecciosas, gravidade clínica pesa mais que nomenclatura." },
      { secao: "Pegadinhas clássicas", corpo: "- Confundir rastreio com diagnóstico definitivo.\n- Usar conduta antiga quando diretriz atual mudou o padrão.\n- Ignorar sinal de alarme por o paciente parecer estável.\n- Marcar terapia sistêmica sem confirmar histologia/estágio quando isso é obrigatório." },
      { secao: "Integração entre temas", corpo: "Integra-se com infectologia, emergência, radiologia, farmacologia, cirurgia e medicina de família. A utilidade no Codex Medicus é conectar resumo, questão e dashboard: erro em uma vinheta deve virar revisão ativa do subtema." },
      { secao: "Mnemônico", corpo: "**PARE**: **P**adrão clínico, **A**larmes, **R**isco/estágio, **E**scolha terapêutica." },
      { secao: "Questões da OMED", corpo: "A questão associada treina o ponto de maior risco deste subtema: reconhecer a pista decisiva e evitar a alternativa antiga, excessiva ou insuficiente." },
      { secao: "Resumo de 5 minutos", corpo: "> Doença Hepática Alcoólica — Diagnóstico e Conduta: reconheça o padrão, classifique gravidade, confirme com o exame que muda conduta e trate conforme diretriz vigente. Ponto de prova: não transformar exceção em regra e não atrasar intervenção quando há risco de órgão ou vida.\n\n---" },
    ],
    referencias: [
      "AASLD Practice Guidance on Alcohol-Associated Liver Disease.",
      "EASL Clinical Practice Guidelines: Management of alcohol-related liver disease.",
      "Ministério da Saúde: atenção ao uso de álcool e outras drogas.",
    ],
  },
};
