import type { ConteudoSubtema } from "@/domain/content/types";

export const CONTEUDOS_ONCO: Record<string, ConteudoSubtema> = {
  "onco--emergencias-oncologicas--diagnostico-e-conduta": {
    subtemaId: "onco--emergencias-oncologicas--diagnostico-e-conduta",
    titulo: "Emergências Oncológicas — Diagnóstico e Conduta",
    atualizadoEm: "2026-07-27",
    origem: "complemento_ia",
    blocos: [
      { secao: "Panorama", corpo: "_Emergências Oncológicas — Diagnóstico e Conduta em prova é decisão prática: reconhecer o padrão, excluir sinais de gravidade e escolher a conduta inicial sem transformar rastreio em tratamento excessivo._" },
      { secao: "Definição", corpo: "Emergências Oncológicas — Diagnóstico e Conduta é abordado aqui como subtema de alto rendimento da OMED. O eixo é diferenciar apresentação típica, formas graves e situações em que a conduta muda imediatamente.\n\nEmergências oncológicas incluem neutropenia febril, síndrome de lise tumoral, hipercalcemia maligna, compressão medular, síndrome da veia cava superior e tamponamento/derrame maligno.\n\nNeutropenia febril é antibiótico antipseudomonas imediato após culturas, sem esperar foco evidente.\n\nCompressão medular exige corticoide, RM de coluna e tratamento local urgente conforme radiossensibilidade e estabilidade." },
      { secao: "Fisiopatologia", corpo: "O mecanismo central explica a clínica e a prova: agressão inicial → alteração anatômica ou molecular → sinal clínico/laboratorial → complicação. Memorizar a conduta sem esse encadeamento gera erro em vinhetas com apresentação atípica." },
      { secao: "Fatores de risco e estratificação", corpo: "Estratifique por idade, comorbidades, imunossupressão, gestação, sinais sistêmicos, extensão da doença e risco de perda de órgão/função. Em oncologia, entram performance status, estadiamento e biologia molecular; em clínica, gravidade e resposta inicial." },
      { secao: "Avaliação clínica", corpo: "Procure sintomas dominantes, tempo de evolução, sinais de alarme e achados que mudam urgência. A banca costuma esconder a resposta em detalhes simples: febre persistente, perda ponderal, dor desproporcional, alteração neurológica, instabilidade, sangramento ou disfunção orgânica." },
      { secao: "Diagnóstico", corpo: "Use exame dirigido, laboratório e imagem apenas quando mudam a decisão. O diagnóstico não deve depender de um teste isolado quando o quadro clínico já exige ação; por outro lado, neoplasias e síndromes complexas exigem confirmação histológica, estadiamento e revisão de biomarcadores quando aplicável." },
      { secao: "Diagnóstico diferencial", corpo: "Diferenciais cobrados: doença infecciosa versus inflamatória, benigna versus maligna, periférica versus central, emergência verdadeira versus quadro ambulatorial. O discriminador costuma ser padrão temporal, exame físico focal, exame complementar-chave ou resposta esperada ao tratamento inicial." },
      { secao: "Condutas", corpo: "A conduta inicial deve ser proporcional ao risco: estabilizar primeiro, confirmar quando seguro, tratar causa reversível, encaminhar casos complexos e evitar terapias desatualizadas. Quando houver diretriz recente, a recomendação vigente prevalece sobre material antigo." },
      { secao: "Complicações", corpo: "Complicações relevantes incluem perda funcional, infecção secundária, trombose/sangramento, insuficiência orgânica, progressão maligna ou recorrência. Em prova, complicação é cobrada como indicação de internação, encaminhamento, imagem, antibiótico, procedimento ou mudança de linha terapêutica." },
      { secao: "Fluxograma de conduta", corpo: "1. Reconheça o padrão clínico.\n2. Procure sinal de gravidade ou instabilidade.\n3. Solicite o exame que confirma e muda conduta.\n4. Inicie tratamento seguro e atual.\n5. Reavalie resposta e complicações.\n6. Encaminhe para especialista quando houver neoplasia, falha terapêutica, doença sistêmica ou risco de órgão-alvo." },
      { secao: "Tabela comparativa", corpo: "| Situação | Pista principal | Conduta de prova |\n|---|---|---|\n| Quadro leve/típico | Sem sinal de alarme | Tratamento inicial e seguimento |\n| Sinal de gravidade | Instabilidade, disfunção ou risco de órgão | Internar/encaminhar e tratar precocemente |\n| Suspeita oncológica | Massa, perda ponderal, sangramento, imagem ou histologia suspeita | Confirmar tecido, estadiar e definir terapia por estágio/biomarcador |\n| Diagnóstico incerto | Achados mistos ou falha ao tratamento | Reavaliar diferencial e solicitar exame de maior acurácia |" },
      { secao: "Pérolas OMED", corpo: "- A melhor resposta costuma ser a primeira conduta segura, não o exame mais sofisticado.\n- Não trate número isolado: trate risco, contexto e tendência.\n- Em câncer, estadiamento e biomarcadores mudam tanto quanto o tipo histológico.\n- Em doenças inflamatórias/infecciosas, gravidade clínica pesa mais que nomenclatura." },
      { secao: "Pegadinhas clássicas", corpo: "- Confundir rastreio com diagnóstico definitivo.\n- Usar conduta antiga quando diretriz atual mudou o padrão.\n- Ignorar sinal de alarme por o paciente parecer estável.\n- Marcar terapia sistêmica sem confirmar histologia/estágio quando isso é obrigatório." },
      { secao: "Integração entre temas", corpo: "Integra-se com infectologia, emergência, radiologia, farmacologia, cirurgia e medicina de família. A utilidade no Codex Medicus é conectar resumo, questão e dashboard: erro em uma vinheta deve virar revisão ativa do subtema." },
      { secao: "Mnemônico", corpo: "**PARE**: **P**adrão clínico, **A**larmes, **R**isco/estágio, **E**scolha terapêutica." },
      { secao: "Questões da OMED", corpo: "A questão associada treina o ponto de maior risco deste subtema: reconhecer a pista decisiva e evitar a alternativa antiga, excessiva ou insuficiente." },
      { secao: "Resumo de 5 minutos", corpo: "> Emergências Oncológicas — Diagnóstico e Conduta: reconheça o padrão, classifique gravidade, confirme com o exame que muda conduta e trate conforme diretriz vigente. Ponto de prova: não transformar exceção em regra e não atrasar intervenção quando há risco de órgão ou vida.\n\n---" },
    ],
    referencias: [
      "ASCO. Antineoplastic Therapy Administration Safety Standards, 2024.",
      "IDSA/ASCO guidance on fever and neutropenia in adults with cancer.",
      "NCI PDQ Supportive and Palliative Care summaries.",
    ],
  },

  "onco--cancer-de-pulmao--diagnostico-e-conduta": {
    subtemaId: "onco--cancer-de-pulmao--diagnostico-e-conduta",
    titulo: "Câncer de Pulmão — Diagnóstico e Conduta",
    atualizadoEm: "2026-07-27",
    origem: "complemento_ia",
    blocos: [
      { secao: "Panorama", corpo: "_Câncer de Pulmão — Diagnóstico e Conduta em prova é decisão prática: reconhecer o padrão, excluir sinais de gravidade e escolher a conduta inicial sem transformar rastreio em tratamento excessivo._" },
      { secao: "Definição", corpo: "Câncer de Pulmão — Diagnóstico e Conduta é abordado aqui como subtema de alto rendimento da OMED. O eixo é diferenciar apresentação típica, formas graves e situações em que a conduta muda imediatamente.\n\nA primeira divisão é carcinoma de pequenas células versus não pequenas células; no CPNPC, histologia e biomarcadores guiam tratamento.\n\nDoença inicial pode ser cirúrgica; doença localmente avançada usa abordagem multimodal; doença metastática depende de PD-L1 e alterações acionáveis como EGFR, ALK, ROS1, BRAF, MET, RET, NTRK e KRAS G12C.\n\nTabagismo segue o principal fator de risco, mas adenocarcinoma também ocorre em não tabagistas." },
      { secao: "Fisiopatologia", corpo: "O mecanismo central explica a clínica e a prova: agressão inicial → alteração anatômica ou molecular → sinal clínico/laboratorial → complicação. Memorizar a conduta sem esse encadeamento gera erro em vinhetas com apresentação atípica." },
      { secao: "Fatores de risco e estratificação", corpo: "Estratifique por idade, comorbidades, imunossupressão, gestação, sinais sistêmicos, extensão da doença e risco de perda de órgão/função. Em oncologia, entram performance status, estadiamento e biologia molecular; em clínica, gravidade e resposta inicial." },
      { secao: "Avaliação clínica", corpo: "Procure sintomas dominantes, tempo de evolução, sinais de alarme e achados que mudam urgência. A banca costuma esconder a resposta em detalhes simples: febre persistente, perda ponderal, dor desproporcional, alteração neurológica, instabilidade, sangramento ou disfunção orgânica." },
      { secao: "Diagnóstico", corpo: "Use exame dirigido, laboratório e imagem apenas quando mudam a decisão. O diagnóstico não deve depender de um teste isolado quando o quadro clínico já exige ação; por outro lado, neoplasias e síndromes complexas exigem confirmação histológica, estadiamento e revisão de biomarcadores quando aplicável." },
      { secao: "Diagnóstico diferencial", corpo: "Diferenciais cobrados: doença infecciosa versus inflamatória, benigna versus maligna, periférica versus central, emergência verdadeira versus quadro ambulatorial. O discriminador costuma ser padrão temporal, exame físico focal, exame complementar-chave ou resposta esperada ao tratamento inicial." },
      { secao: "Condutas", corpo: "A conduta inicial deve ser proporcional ao risco: estabilizar primeiro, confirmar quando seguro, tratar causa reversível, encaminhar casos complexos e evitar terapias desatualizadas. Quando houver diretriz recente, a recomendação vigente prevalece sobre material antigo." },
      { secao: "Complicações", corpo: "Complicações relevantes incluem perda funcional, infecção secundária, trombose/sangramento, insuficiência orgânica, progressão maligna ou recorrência. Em prova, complicação é cobrada como indicação de internação, encaminhamento, imagem, antibiótico, procedimento ou mudança de linha terapêutica." },
      { secao: "Fluxograma de conduta", corpo: "1. Reconheça o padrão clínico.\n2. Procure sinal de gravidade ou instabilidade.\n3. Solicite o exame que confirma e muda conduta.\n4. Inicie tratamento seguro e atual.\n5. Reavalie resposta e complicações.\n6. Encaminhe para especialista quando houver neoplasia, falha terapêutica, doença sistêmica ou risco de órgão-alvo." },
      { secao: "Tabela comparativa", corpo: "| Situação | Pista principal | Conduta de prova |\n|---|---|---|\n| Quadro leve/típico | Sem sinal de alarme | Tratamento inicial e seguimento |\n| Sinal de gravidade | Instabilidade, disfunção ou risco de órgão | Internar/encaminhar e tratar precocemente |\n| Suspeita oncológica | Massa, perda ponderal, sangramento, imagem ou histologia suspeita | Confirmar tecido, estadiar e definir terapia por estágio/biomarcador |\n| Diagnóstico incerto | Achados mistos ou falha ao tratamento | Reavaliar diferencial e solicitar exame de maior acurácia |" },
      { secao: "Pérolas OMED", corpo: "- A melhor resposta costuma ser a primeira conduta segura, não o exame mais sofisticado.\n- Não trate número isolado: trate risco, contexto e tendência.\n- Em câncer, estadiamento e biomarcadores mudam tanto quanto o tipo histológico.\n- Em doenças inflamatórias/infecciosas, gravidade clínica pesa mais que nomenclatura." },
      { secao: "Pegadinhas clássicas", corpo: "- Confundir rastreio com diagnóstico definitivo.\n- Usar conduta antiga quando diretriz atual mudou o padrão.\n- Ignorar sinal de alarme por o paciente parecer estável.\n- Marcar terapia sistêmica sem confirmar histologia/estágio quando isso é obrigatório." },
      { secao: "Integração entre temas", corpo: "Integra-se com infectologia, emergência, radiologia, farmacologia, cirurgia e medicina de família. A utilidade no Codex Medicus é conectar resumo, questão e dashboard: erro em uma vinheta deve virar revisão ativa do subtema." },
      { secao: "Mnemônico", corpo: "**PARE**: **P**adrão clínico, **A**larmes, **R**isco/estágio, **E**scolha terapêutica." },
      { secao: "Questões da OMED", corpo: "A questão associada treina o ponto de maior risco deste subtema: reconhecer a pista decisiva e evitar a alternativa antiga, excessiva ou insuficiente." },
      { secao: "Resumo de 5 minutos", corpo: "> Câncer de Pulmão — Diagnóstico e Conduta: reconheça o padrão, classifique gravidade, confirme com o exame que muda conduta e trate conforme diretriz vigente. Ponto de prova: não transformar exceção em regra e não atrasar intervenção quando há risco de órgão ou vida.\n\n---" },
    ],
    referencias: [
      "NCI PDQ. Non-Small Cell Lung Cancer Treatment, atualizado em 2025.",
      "NCI PDQ. Small Cell Lung Cancer Treatment.",
      "NCCN Guidelines for Patients: Lung Cancer Screening and Lung Cancer.",
    ],
  },

  "onco--principios-de-oncologia--estadiamento-e-tratamento": {
    subtemaId: "onco--principios-de-oncologia--estadiamento-e-tratamento",
    titulo: "Princípios de Oncologia — Estadiamento e Tratamento",
    atualizadoEm: "2026-07-27",
    origem: "complemento_ia",
    blocos: [
      { secao: "Panorama", corpo: "_Princípios de Oncologia — Estadiamento e Tratamento em prova é decisão prática: reconhecer o padrão, excluir sinais de gravidade e escolher a conduta inicial sem transformar rastreio em tratamento excessivo._" },
      { secao: "Definição", corpo: "Princípios de Oncologia — Estadiamento e Tratamento é abordado aqui como subtema de alto rendimento da OMED. O eixo é diferenciar apresentação típica, formas graves e situações em que a conduta muda imediatamente.\n\nO TNM resume extensão local, linfonodal e metastática; estágio muda intenção terapêutica.\n\nTratamento pode ser curativo, adjuvante, neoadjuvante, paliativo ou de suporte.\n\nPerformance status, histologia, biomarcadores e preferência do paciente integram a decisão." },
      { secao: "Fisiopatologia", corpo: "O mecanismo central explica a clínica e a prova: agressão inicial → alteração anatômica ou molecular → sinal clínico/laboratorial → complicação. Memorizar a conduta sem esse encadeamento gera erro em vinhetas com apresentação atípica." },
      { secao: "Fatores de risco e estratificação", corpo: "Estratifique por idade, comorbidades, imunossupressão, gestação, sinais sistêmicos, extensão da doença e risco de perda de órgão/função. Em oncologia, entram performance status, estadiamento e biologia molecular; em clínica, gravidade e resposta inicial." },
      { secao: "Avaliação clínica", corpo: "Procure sintomas dominantes, tempo de evolução, sinais de alarme e achados que mudam urgência. A banca costuma esconder a resposta em detalhes simples: febre persistente, perda ponderal, dor desproporcional, alteração neurológica, instabilidade, sangramento ou disfunção orgânica." },
      { secao: "Diagnóstico", corpo: "Use exame dirigido, laboratório e imagem apenas quando mudam a decisão. O diagnóstico não deve depender de um teste isolado quando o quadro clínico já exige ação; por outro lado, neoplasias e síndromes complexas exigem confirmação histológica, estadiamento e revisão de biomarcadores quando aplicável." },
      { secao: "Diagnóstico diferencial", corpo: "Diferenciais cobrados: doença infecciosa versus inflamatória, benigna versus maligna, periférica versus central, emergência verdadeira versus quadro ambulatorial. O discriminador costuma ser padrão temporal, exame físico focal, exame complementar-chave ou resposta esperada ao tratamento inicial." },
      { secao: "Condutas", corpo: "A conduta inicial deve ser proporcional ao risco: estabilizar primeiro, confirmar quando seguro, tratar causa reversível, encaminhar casos complexos e evitar terapias desatualizadas. Quando houver diretriz recente, a recomendação vigente prevalece sobre material antigo." },
      { secao: "Complicações", corpo: "Complicações relevantes incluem perda funcional, infecção secundária, trombose/sangramento, insuficiência orgânica, progressão maligna ou recorrência. Em prova, complicação é cobrada como indicação de internação, encaminhamento, imagem, antibiótico, procedimento ou mudança de linha terapêutica." },
      { secao: "Fluxograma de conduta", corpo: "1. Reconheça o padrão clínico.\n2. Procure sinal de gravidade ou instabilidade.\n3. Solicite o exame que confirma e muda conduta.\n4. Inicie tratamento seguro e atual.\n5. Reavalie resposta e complicações.\n6. Encaminhe para especialista quando houver neoplasia, falha terapêutica, doença sistêmica ou risco de órgão-alvo." },
      { secao: "Tabela comparativa", corpo: "| Situação | Pista principal | Conduta de prova |\n|---|---|---|\n| Quadro leve/típico | Sem sinal de alarme | Tratamento inicial e seguimento |\n| Sinal de gravidade | Instabilidade, disfunção ou risco de órgão | Internar/encaminhar e tratar precocemente |\n| Suspeita oncológica | Massa, perda ponderal, sangramento, imagem ou histologia suspeita | Confirmar tecido, estadiar e definir terapia por estágio/biomarcador |\n| Diagnóstico incerto | Achados mistos ou falha ao tratamento | Reavaliar diferencial e solicitar exame de maior acurácia |" },
      { secao: "Pérolas OMED", corpo: "- A melhor resposta costuma ser a primeira conduta segura, não o exame mais sofisticado.\n- Não trate número isolado: trate risco, contexto e tendência.\n- Em câncer, estadiamento e biomarcadores mudam tanto quanto o tipo histológico.\n- Em doenças inflamatórias/infecciosas, gravidade clínica pesa mais que nomenclatura." },
      { secao: "Pegadinhas clássicas", corpo: "- Confundir rastreio com diagnóstico definitivo.\n- Usar conduta antiga quando diretriz atual mudou o padrão.\n- Ignorar sinal de alarme por o paciente parecer estável.\n- Marcar terapia sistêmica sem confirmar histologia/estágio quando isso é obrigatório." },
      { secao: "Integração entre temas", corpo: "Integra-se com infectologia, emergência, radiologia, farmacologia, cirurgia e medicina de família. A utilidade no Codex Medicus é conectar resumo, questão e dashboard: erro em uma vinheta deve virar revisão ativa do subtema." },
      { secao: "Mnemônico", corpo: "**PARE**: **P**adrão clínico, **A**larmes, **R**isco/estágio, **E**scolha terapêutica." },
      { secao: "Questões da OMED", corpo: "A questão associada treina o ponto de maior risco deste subtema: reconhecer a pista decisiva e evitar a alternativa antiga, excessiva ou insuficiente." },
      { secao: "Resumo de 5 minutos", corpo: "> Princípios de Oncologia — Estadiamento e Tratamento: reconheça o padrão, classifique gravidade, confirme com o exame que muda conduta e trate conforme diretriz vigente. Ponto de prova: não transformar exceção em regra e não atrasar intervenção quando há risco de órgão ou vida.\n\n---" },
    ],
    referencias: [
      "AJCC Cancer Staging Manual, 8th edition.",
      "NCI PDQ Cancer Treatment summaries.",
      "ASCO cancer care standards, 2024.",
    ],
  },

  "onco--farmacologia-oncologica-e-imunoterapia--principios-praticos": {
    subtemaId: "onco--farmacologia-oncologica-e-imunoterapia--principios-praticos",
    titulo: "Farmacologia Oncológica e Imunoterapia — Princípios Práticos",
    atualizadoEm: "2026-07-27",
    origem: "complemento_ia",
    blocos: [
      { secao: "Panorama", corpo: "_Farmacologia Oncológica e Imunoterapia — Princípios Práticos em prova é decisão prática: reconhecer o padrão, excluir sinais de gravidade e escolher a conduta inicial sem transformar rastreio em tratamento excessivo._" },
      { secao: "Definição", corpo: "Farmacologia Oncológica e Imunoterapia — Princípios Práticos é abordado aqui como subtema de alto rendimento da OMED. O eixo é diferenciar apresentação típica, formas graves e situações em que a conduta muda imediatamente.\n\nQuimioterapia citotóxica mira divisão celular; terapia-alvo mira uma alteração molecular; imunoterapia remove freios da resposta antitumoral.\n\nCheckpoint inhibitors podem causar eventos imunes em pele, intestino, pulmão, fígado, hipófise e tireoide.\n\nCAR-T e anticorpos biespecíficos exigem atenção a síndrome de liberação de citocinas e neurotoxicidade." },
      { secao: "Fisiopatologia", corpo: "O mecanismo central explica a clínica e a prova: agressão inicial → alteração anatômica ou molecular → sinal clínico/laboratorial → complicação. Memorizar a conduta sem esse encadeamento gera erro em vinhetas com apresentação atípica." },
      { secao: "Fatores de risco e estratificação", corpo: "Estratifique por idade, comorbidades, imunossupressão, gestação, sinais sistêmicos, extensão da doença e risco de perda de órgão/função. Em oncologia, entram performance status, estadiamento e biologia molecular; em clínica, gravidade e resposta inicial." },
      { secao: "Avaliação clínica", corpo: "Procure sintomas dominantes, tempo de evolução, sinais de alarme e achados que mudam urgência. A banca costuma esconder a resposta em detalhes simples: febre persistente, perda ponderal, dor desproporcional, alteração neurológica, instabilidade, sangramento ou disfunção orgânica." },
      { secao: "Diagnóstico", corpo: "Use exame dirigido, laboratório e imagem apenas quando mudam a decisão. O diagnóstico não deve depender de um teste isolado quando o quadro clínico já exige ação; por outro lado, neoplasias e síndromes complexas exigem confirmação histológica, estadiamento e revisão de biomarcadores quando aplicável." },
      { secao: "Diagnóstico diferencial", corpo: "Diferenciais cobrados: doença infecciosa versus inflamatória, benigna versus maligna, periférica versus central, emergência verdadeira versus quadro ambulatorial. O discriminador costuma ser padrão temporal, exame físico focal, exame complementar-chave ou resposta esperada ao tratamento inicial." },
      { secao: "Condutas", corpo: "A conduta inicial deve ser proporcional ao risco: estabilizar primeiro, confirmar quando seguro, tratar causa reversível, encaminhar casos complexos e evitar terapias desatualizadas. Quando houver diretriz recente, a recomendação vigente prevalece sobre material antigo." },
      { secao: "Complicações", corpo: "Complicações relevantes incluem perda funcional, infecção secundária, trombose/sangramento, insuficiência orgânica, progressão maligna ou recorrência. Em prova, complicação é cobrada como indicação de internação, encaminhamento, imagem, antibiótico, procedimento ou mudança de linha terapêutica." },
      { secao: "Fluxograma de conduta", corpo: "1. Reconheça o padrão clínico.\n2. Procure sinal de gravidade ou instabilidade.\n3. Solicite o exame que confirma e muda conduta.\n4. Inicie tratamento seguro e atual.\n5. Reavalie resposta e complicações.\n6. Encaminhe para especialista quando houver neoplasia, falha terapêutica, doença sistêmica ou risco de órgão-alvo." },
      { secao: "Tabela comparativa", corpo: "| Situação | Pista principal | Conduta de prova |\n|---|---|---|\n| Quadro leve/típico | Sem sinal de alarme | Tratamento inicial e seguimento |\n| Sinal de gravidade | Instabilidade, disfunção ou risco de órgão | Internar/encaminhar e tratar precocemente |\n| Suspeita oncológica | Massa, perda ponderal, sangramento, imagem ou histologia suspeita | Confirmar tecido, estadiar e definir terapia por estágio/biomarcador |\n| Diagnóstico incerto | Achados mistos ou falha ao tratamento | Reavaliar diferencial e solicitar exame de maior acurácia |" },
      { secao: "Pérolas OMED", corpo: "- A melhor resposta costuma ser a primeira conduta segura, não o exame mais sofisticado.\n- Não trate número isolado: trate risco, contexto e tendência.\n- Em câncer, estadiamento e biomarcadores mudam tanto quanto o tipo histológico.\n- Em doenças inflamatórias/infecciosas, gravidade clínica pesa mais que nomenclatura." },
      { secao: "Pegadinhas clássicas", corpo: "- Confundir rastreio com diagnóstico definitivo.\n- Usar conduta antiga quando diretriz atual mudou o padrão.\n- Ignorar sinal de alarme por o paciente parecer estável.\n- Marcar terapia sistêmica sem confirmar histologia/estágio quando isso é obrigatório." },
      { secao: "Integração entre temas", corpo: "Integra-se com infectologia, emergência, radiologia, farmacologia, cirurgia e medicina de família. A utilidade no Codex Medicus é conectar resumo, questão e dashboard: erro em uma vinheta deve virar revisão ativa do subtema." },
      { secao: "Mnemônico", corpo: "**PARE**: **P**adrão clínico, **A**larmes, **R**isco/estágio, **E**scolha terapêutica." },
      { secao: "Questões da OMED", corpo: "A questão associada treina o ponto de maior risco deste subtema: reconhecer a pista decisiva e evitar a alternativa antiga, excessiva ou insuficiente." },
      { secao: "Resumo de 5 minutos", corpo: "> Farmacologia Oncológica e Imunoterapia — Princípios Práticos: reconheça o padrão, classifique gravidade, confirme com o exame que muda conduta e trate conforme diretriz vigente. Ponto de prova: não transformar exceção em regra e não atrasar intervenção quando há risco de órgão ou vida.\n\n---" },
    ],
    referencias: [
      "ASCO. Antineoplastic Therapy Administration Safety Standards, 2024.",
      "NCI. Immunotherapy to Treat Cancer.",
      "ESMO supportive care resources.",
    ],
  },
};
