import type { ConteudoSubtema } from "@/domain/content/types";

export const CONTEUDOS_OTORRINO: Record<string, ConteudoSubtema> = {
  "otorrino--rinite-e-rinossinusite--diagnostico-e-conduta": {
    subtemaId: "otorrino--rinite-e-rinossinusite--diagnostico-e-conduta",
    titulo: "Rinite e Rinossinusite — Diagnóstico e Conduta",
    atualizadoEm: "2026-07-27",
    origem: "complemento_ia",
    blocos: [
      { secao: "Panorama", corpo: "_Rinite e Rinossinusite — Diagnóstico e Conduta em prova é decisão prática: reconhecer o padrão, excluir sinais de gravidade e escolher a conduta inicial sem transformar rastreio em tratamento excessivo._" },
      { secao: "Definição", corpo: "Rinite e Rinossinusite — Diagnóstico e Conduta é abordado aqui como subtema de alto rendimento da OMED. O eixo é diferenciar apresentação típica, formas graves e situações em que a conduta muda imediatamente.\n\nRinite alérgica é prurido, espirros, rinorreia clara e obstrução com gatilho ambiental.\n\nRinossinusite viral é muito mais comum que bacteriana; antibiótico entra em persistência, piora bifásica ou gravidade.\n\nCorticoide intranasal é pilar em rinite alérgica e rinossinusite crônica." },
      { secao: "Fisiopatologia", corpo: "O mecanismo central explica a clínica e a prova: agressão inicial → alteração anatômica ou molecular → sinal clínico/laboratorial → complicação. Memorizar a conduta sem esse encadeamento gera erro em vinhetas com apresentação atípica." },
      { secao: "Fatores de risco e estratificação", corpo: "Estratifique por idade, comorbidades, imunossupressão, gestação, sinais sistêmicos, extensão da doença e risco de perda de órgão/função. Em oncologia, entram performance status, estadiamento e biologia molecular; em clínica, gravidade e resposta inicial." },
      { secao: "Avaliação clínica", corpo: "Procure sintomas dominantes, tempo de evolução, sinais de alarme e achados que mudam urgência. A banca costuma esconder a resposta em detalhes simples: febre persistente, perda ponderal, dor desproporcional, alteração neurológica, instabilidade, sangramento ou disfunção orgânica." },
      { secao: "Diagnóstico", corpo: "Use exame dirigido, laboratório e imagem apenas quando mudam a decisão. O diagnóstico não deve depender de um teste isolado quando o quadro clínico já exige ação; por outro lado, neoplasias e síndromes complexas exigem confirmação histológica, estadiamento e revisão de biomarcadores quando aplicável." },
      { secao: "Diagnóstico diferencial", corpo: "Diferenciais cobrados: doença infecciosa versus inflamatória, benigna versus maligna, periférica versus central, emergência verdadeira versus quadro ambulatorial. O discriminador costuma ser padrão temporal, exame físico focal, exame complementar-chave ou resposta esperada ao tratamento inicial." },
      { secao: "Condutas", corpo: "A conduta inicial deve ser proporcional ao risco: estabilizar primeiro, confirmar quando seguro, tratar causa reversível, encaminhar casos complexos e evitar terapias desatualizadas. Quando houver diretriz recente, a recomendação vigente prevalece sobre material antigo." },
      { secao: "Complicações", corpo: "Complicações relevantes incluem perda funcional, infecção secundária, trombose/sangramento, insuficiência orgânica, progressão maligna ou recorrência. Em prova, complicação é cobrada como indicação de internação, encaminhamento, imagem, antibiótico, procedimento ou mudança de linha terapêutica." },
      { secao: "Fluxograma de conduta", corpo: "1. Reconheça o padrão clínico.\n2. Procure sinal de gravidade ou instabilidade.\n3. Solicite o exame que confirma e muda conduta.\n4. Inicie tratamento seguro e atual.\n5. Reavalie resposta e complicações.\n6. Encaminhe para especialista quando houver neoplasia, falha terapêutica, doença sistêmica ou risco de órgão-alvo." },
      { secao: "Tabela comparativa", corpo: "| Situação | Pista principal | Conduta de prova |\n|---|---|---|\n| Quadro leve/típico | Sem sinal de alarme | Tratamento inicial e seguimento |\n| Sinal de gravidade | Instabilidade, disfunção ou risco de órgão | Internar/encaminhar e tratar precocemente |\n| Suspeita oncológica | Massa, perda ponderal, sangramento, imagem ou histologia suspeita | Confirmar tecido, estadiar e definir terapia por estágio/biomarcador |\n| Diagnóstico incerto | Achados mistos ou falha ao tratamento | Reavaliar diferencial e solicitar exame de maior acurácia |" },
      { secao: "Pérolas OMED", corpo: "- A melhor resposta costuma ser a primeira conduta segura, não o exame mais sofisticado.\n- Não trate número isolado: trate risco, contexto e tendência.\n- Em câncer, estadiamento e biomarcadores mudam tanto quanto o tipo histológico.\n- Em doenças inflamatórias/infecciosas, gravidade clínica pesa mais que nomenclatura." },
      { secao: "Pegadinhas clássicas", corpo: "- Confundir rastreio com diagnóstico definitivo.\n- Usar conduta antiga quando diretriz atual mudou o padrão.\n- Ignorar sinal de alarme por o paciente parecer estável.\n- Marcar terapia sistêmica sem confirmar histologia/estágio quando isso é obrigatório." },
      { secao: "Integração entre temas", corpo: "Integra-se com infectologia, emergência, radiologia, farmacologia, cirurgia e medicina de família. A utilidade no Codex Medicus é conectar resumo, questão e dashboard: erro em uma vinheta deve virar revisão ativa do subtema." },
      { secao: "Mnemônico", corpo: "**PARE**: **P**adrão clínico, **A**larmes, **R**isco/estágio, **E**scolha terapêutica." },
      { secao: "Questões da OMED", corpo: "A questão associada treina o ponto de maior risco deste subtema: reconhecer a pista decisiva e evitar a alternativa antiga, excessiva ou insuficiente." },
      { secao: "Resumo de 5 minutos", corpo: "> Rinite e Rinossinusite — Diagnóstico e Conduta: reconheça o padrão, classifique gravidade, confirme com o exame que muda conduta e trate conforme diretriz vigente. Ponto de prova: não transformar exceção em regra e não atrasar intervenção quando há risco de órgão ou vida.\n\n---" },
    ],
    referencias: [
      "AAO-HNSF. Clinical Practice Guideline: Allergic Rhinitis.",
      "AAO-HNSF. Adult Sinusitis guideline update.",
      "EPOS 2020: European Position Paper on Rhinosinusitis and Nasal Polyps.",
    ],
  },

  "otorrino--otites--media-externa-e-complicacoes": {
    subtemaId: "otorrino--otites--media-externa-e-complicacoes",
    titulo: "Otites — Média, Externa e Complicações",
    atualizadoEm: "2026-07-27",
    origem: "complemento_ia",
    blocos: [
      { secao: "Panorama", corpo: "_Otites — Média, Externa e Complicações em prova é decisão prática: reconhecer o padrão, excluir sinais de gravidade e escolher a conduta inicial sem transformar rastreio em tratamento excessivo._" },
      { secao: "Definição", corpo: "Otites — Média, Externa e Complicações é abordado aqui como subtema de alto rendimento da OMED. O eixo é diferenciar apresentação típica, formas graves e situações em que a conduta muda imediatamente.\n\nOMA exige início agudo, sinais inflamatórios e efusão em orelha média; abaulamento timpânico é pista forte.\n\nOtite externa dói ao tracionar pavilhão ou comprimir trago.\n\nMastoidite, paralisia facial, vertigem intensa e sinais intracranianos são alarmes." },
      { secao: "Fisiopatologia", corpo: "O mecanismo central explica a clínica e a prova: agressão inicial → alteração anatômica ou molecular → sinal clínico/laboratorial → complicação. Memorizar a conduta sem esse encadeamento gera erro em vinhetas com apresentação atípica." },
      { secao: "Fatores de risco e estratificação", corpo: "Estratifique por idade, comorbidades, imunossupressão, gestação, sinais sistêmicos, extensão da doença e risco de perda de órgão/função. Em oncologia, entram performance status, estadiamento e biologia molecular; em clínica, gravidade e resposta inicial." },
      { secao: "Avaliação clínica", corpo: "Procure sintomas dominantes, tempo de evolução, sinais de alarme e achados que mudam urgência. A banca costuma esconder a resposta em detalhes simples: febre persistente, perda ponderal, dor desproporcional, alteração neurológica, instabilidade, sangramento ou disfunção orgânica." },
      { secao: "Diagnóstico", corpo: "Use exame dirigido, laboratório e imagem apenas quando mudam a decisão. O diagnóstico não deve depender de um teste isolado quando o quadro clínico já exige ação; por outro lado, neoplasias e síndromes complexas exigem confirmação histológica, estadiamento e revisão de biomarcadores quando aplicável." },
      { secao: "Diagnóstico diferencial", corpo: "Diferenciais cobrados: doença infecciosa versus inflamatória, benigna versus maligna, periférica versus central, emergência verdadeira versus quadro ambulatorial. O discriminador costuma ser padrão temporal, exame físico focal, exame complementar-chave ou resposta esperada ao tratamento inicial." },
      { secao: "Condutas", corpo: "A conduta inicial deve ser proporcional ao risco: estabilizar primeiro, confirmar quando seguro, tratar causa reversível, encaminhar casos complexos e evitar terapias desatualizadas. Quando houver diretriz recente, a recomendação vigente prevalece sobre material antigo." },
      { secao: "Complicações", corpo: "Complicações relevantes incluem perda funcional, infecção secundária, trombose/sangramento, insuficiência orgânica, progressão maligna ou recorrência. Em prova, complicação é cobrada como indicação de internação, encaminhamento, imagem, antibiótico, procedimento ou mudança de linha terapêutica." },
      { secao: "Fluxograma de conduta", corpo: "1. Reconheça o padrão clínico.\n2. Procure sinal de gravidade ou instabilidade.\n3. Solicite o exame que confirma e muda conduta.\n4. Inicie tratamento seguro e atual.\n5. Reavalie resposta e complicações.\n6. Encaminhe para especialista quando houver neoplasia, falha terapêutica, doença sistêmica ou risco de órgão-alvo." },
      { secao: "Tabela comparativa", corpo: "| Situação | Pista principal | Conduta de prova |\n|---|---|---|\n| Quadro leve/típico | Sem sinal de alarme | Tratamento inicial e seguimento |\n| Sinal de gravidade | Instabilidade, disfunção ou risco de órgão | Internar/encaminhar e tratar precocemente |\n| Suspeita oncológica | Massa, perda ponderal, sangramento, imagem ou histologia suspeita | Confirmar tecido, estadiar e definir terapia por estágio/biomarcador |\n| Diagnóstico incerto | Achados mistos ou falha ao tratamento | Reavaliar diferencial e solicitar exame de maior acurácia |" },
      { secao: "Pérolas OMED", corpo: "- A melhor resposta costuma ser a primeira conduta segura, não o exame mais sofisticado.\n- Não trate número isolado: trate risco, contexto e tendência.\n- Em câncer, estadiamento e biomarcadores mudam tanto quanto o tipo histológico.\n- Em doenças inflamatórias/infecciosas, gravidade clínica pesa mais que nomenclatura." },
      { secao: "Pegadinhas clássicas", corpo: "- Confundir rastreio com diagnóstico definitivo.\n- Usar conduta antiga quando diretriz atual mudou o padrão.\n- Ignorar sinal de alarme por o paciente parecer estável.\n- Marcar terapia sistêmica sem confirmar histologia/estágio quando isso é obrigatório." },
      { secao: "Integração entre temas", corpo: "Integra-se com infectologia, emergência, radiologia, farmacologia, cirurgia e medicina de família. A utilidade no Codex Medicus é conectar resumo, questão e dashboard: erro em uma vinheta deve virar revisão ativa do subtema." },
      { secao: "Mnemônico", corpo: "**PARE**: **P**adrão clínico, **A**larmes, **R**isco/estágio, **E**scolha terapêutica." },
      { secao: "Questões da OMED", corpo: "A questão associada treina o ponto de maior risco deste subtema: reconhecer a pista decisiva e evitar a alternativa antiga, excessiva ou insuficiente." },
      { secao: "Resumo de 5 minutos", corpo: "> Otites — Média, Externa e Complicações: reconheça o padrão, classifique gravidade, confirme com o exame que muda conduta e trate conforme diretriz vigente. Ponto de prova: não transformar exceção em regra e não atrasar intervenção quando há risco de órgão ou vida.\n\n---" },
    ],
    referencias: [
      "AAP. The Diagnosis and Management of Acute Otitis Media.",
      "AAO-HNSF. Tympanostomy Tubes in Children guideline update.",
      "AAO-HNSF. Acute Otitis Externa guideline.",
    ],
  },

  "otorrino--vertigem-e-hints--sindromes-vestibulares": {
    subtemaId: "otorrino--vertigem-e-hints--sindromes-vestibulares",
    titulo: "Vertigem e HINTS — Síndromes Vestibulares",
    atualizadoEm: "2026-07-27",
    origem: "complemento_ia",
    blocos: [
      { secao: "Panorama", corpo: "_Vertigem e HINTS — Síndromes Vestibulares em prova é decisão prática: reconhecer o padrão, excluir sinais de gravidade e escolher a conduta inicial sem transformar rastreio em tratamento excessivo._" },
      { secao: "Definição", corpo: "Vertigem e HINTS — Síndromes Vestibulares é abordado aqui como subtema de alto rendimento da OMED. O eixo é diferenciar apresentação típica, formas graves e situações em que a conduta muda imediatamente.\n\nVPPB é vertigem breve desencadeada por posição e tratada com manobra de reposicionamento.\n\nSíndrome vestibular aguda contínua exige separar neurite vestibular de AVC de circulação posterior.\n\nHINTS só deve ser usado em paciente com nistagmo e vertigem contínua, por examinador treinado." },
      { secao: "Fisiopatologia", corpo: "O mecanismo central explica a clínica e a prova: agressão inicial → alteração anatômica ou molecular → sinal clínico/laboratorial → complicação. Memorizar a conduta sem esse encadeamento gera erro em vinhetas com apresentação atípica." },
      { secao: "Fatores de risco e estratificação", corpo: "Estratifique por idade, comorbidades, imunossupressão, gestação, sinais sistêmicos, extensão da doença e risco de perda de órgão/função. Em oncologia, entram performance status, estadiamento e biologia molecular; em clínica, gravidade e resposta inicial." },
      { secao: "Avaliação clínica", corpo: "Procure sintomas dominantes, tempo de evolução, sinais de alarme e achados que mudam urgência. A banca costuma esconder a resposta em detalhes simples: febre persistente, perda ponderal, dor desproporcional, alteração neurológica, instabilidade, sangramento ou disfunção orgânica." },
      { secao: "Diagnóstico", corpo: "Use exame dirigido, laboratório e imagem apenas quando mudam a decisão. O diagnóstico não deve depender de um teste isolado quando o quadro clínico já exige ação; por outro lado, neoplasias e síndromes complexas exigem confirmação histológica, estadiamento e revisão de biomarcadores quando aplicável." },
      { secao: "Diagnóstico diferencial", corpo: "Diferenciais cobrados: doença infecciosa versus inflamatória, benigna versus maligna, periférica versus central, emergência verdadeira versus quadro ambulatorial. O discriminador costuma ser padrão temporal, exame físico focal, exame complementar-chave ou resposta esperada ao tratamento inicial." },
      { secao: "Condutas", corpo: "A conduta inicial deve ser proporcional ao risco: estabilizar primeiro, confirmar quando seguro, tratar causa reversível, encaminhar casos complexos e evitar terapias desatualizadas. Quando houver diretriz recente, a recomendação vigente prevalece sobre material antigo." },
      { secao: "Complicações", corpo: "Complicações relevantes incluem perda funcional, infecção secundária, trombose/sangramento, insuficiência orgânica, progressão maligna ou recorrência. Em prova, complicação é cobrada como indicação de internação, encaminhamento, imagem, antibiótico, procedimento ou mudança de linha terapêutica." },
      { secao: "Fluxograma de conduta", corpo: "1. Reconheça o padrão clínico.\n2. Procure sinal de gravidade ou instabilidade.\n3. Solicite o exame que confirma e muda conduta.\n4. Inicie tratamento seguro e atual.\n5. Reavalie resposta e complicações.\n6. Encaminhe para especialista quando houver neoplasia, falha terapêutica, doença sistêmica ou risco de órgão-alvo." },
      { secao: "Tabela comparativa", corpo: "| Situação | Pista principal | Conduta de prova |\n|---|---|---|\n| Quadro leve/típico | Sem sinal de alarme | Tratamento inicial e seguimento |\n| Sinal de gravidade | Instabilidade, disfunção ou risco de órgão | Internar/encaminhar e tratar precocemente |\n| Suspeita oncológica | Massa, perda ponderal, sangramento, imagem ou histologia suspeita | Confirmar tecido, estadiar e definir terapia por estágio/biomarcador |\n| Diagnóstico incerto | Achados mistos ou falha ao tratamento | Reavaliar diferencial e solicitar exame de maior acurácia |" },
      { secao: "Pérolas OMED", corpo: "- A melhor resposta costuma ser a primeira conduta segura, não o exame mais sofisticado.\n- Não trate número isolado: trate risco, contexto e tendência.\n- Em câncer, estadiamento e biomarcadores mudam tanto quanto o tipo histológico.\n- Em doenças inflamatórias/infecciosas, gravidade clínica pesa mais que nomenclatura." },
      { secao: "Pegadinhas clássicas", corpo: "- Confundir rastreio com diagnóstico definitivo.\n- Usar conduta antiga quando diretriz atual mudou o padrão.\n- Ignorar sinal de alarme por o paciente parecer estável.\n- Marcar terapia sistêmica sem confirmar histologia/estágio quando isso é obrigatório." },
      { secao: "Integração entre temas", corpo: "Integra-se com infectologia, emergência, radiologia, farmacologia, cirurgia e medicina de família. A utilidade no Codex Medicus é conectar resumo, questão e dashboard: erro em uma vinheta deve virar revisão ativa do subtema." },
      { secao: "Mnemônico", corpo: "**PARE**: **P**adrão clínico, **A**larmes, **R**isco/estágio, **E**scolha terapêutica." },
      { secao: "Questões da OMED", corpo: "A questão associada treina o ponto de maior risco deste subtema: reconhecer a pista decisiva e evitar a alternativa antiga, excessiva ou insuficiente." },
      { secao: "Resumo de 5 minutos", corpo: "> Vertigem e HINTS — Síndromes Vestibulares: reconheça o padrão, classifique gravidade, confirme com o exame que muda conduta e trate conforme diretriz vigente. Ponto de prova: não transformar exceção em regra e não atrasar intervenção quando há risco de órgão ou vida.\n\n---" },
    ],
    referencias: [
      "GRACE-3 Emergency Medicine guideline for acute dizziness and vertigo, 2023.",
      "AAO-HNSF. Benign Paroxysmal Positional Vertigo guideline update.",
      "Bárány Society vestibular disorders classification.",
    ],
  },

  "otorrino--tumores-de-glandulas-salivares-e-orofaringe--diagnostico-e-conduta": {
    subtemaId: "otorrino--tumores-de-glandulas-salivares-e-orofaringe--diagnostico-e-conduta",
    titulo: "Tumores de Glândulas Salivares e Orofaringe — Diagnóstico e Conduta",
    atualizadoEm: "2026-07-27",
    origem: "complemento_ia",
    blocos: [
      { secao: "Panorama", corpo: "_Tumores de Glândulas Salivares e Orofaringe — Diagnóstico e Conduta em prova é decisão prática: reconhecer o padrão, excluir sinais de gravidade e escolher a conduta inicial sem transformar rastreio em tratamento excessivo._" },
      { secao: "Definição", corpo: "Tumores de Glândulas Salivares e Orofaringe — Diagnóstico e Conduta é abordado aqui como subtema de alto rendimento da OMED. O eixo é diferenciar apresentação típica, formas graves e situações em que a conduta muda imediatamente.\n\nMassa salivar endurecida, crescimento rápido, dor ou paralisia facial sugere malignidade.\n\nCâncer de orofaringe relacionado a HPV costuma envolver tonsila/base de língua e tem prognóstico diferente.\n\nDiagnóstico exige exame ORL, imagem e confirmação histológica." },
      { secao: "Fisiopatologia", corpo: "O mecanismo central explica a clínica e a prova: agressão inicial → alteração anatômica ou molecular → sinal clínico/laboratorial → complicação. Memorizar a conduta sem esse encadeamento gera erro em vinhetas com apresentação atípica." },
      { secao: "Fatores de risco e estratificação", corpo: "Estratifique por idade, comorbidades, imunossupressão, gestação, sinais sistêmicos, extensão da doença e risco de perda de órgão/função. Em oncologia, entram performance status, estadiamento e biologia molecular; em clínica, gravidade e resposta inicial." },
      { secao: "Avaliação clínica", corpo: "Procure sintomas dominantes, tempo de evolução, sinais de alarme e achados que mudam urgência. A banca costuma esconder a resposta em detalhes simples: febre persistente, perda ponderal, dor desproporcional, alteração neurológica, instabilidade, sangramento ou disfunção orgânica." },
      { secao: "Diagnóstico", corpo: "Use exame dirigido, laboratório e imagem apenas quando mudam a decisão. O diagnóstico não deve depender de um teste isolado quando o quadro clínico já exige ação; por outro lado, neoplasias e síndromes complexas exigem confirmação histológica, estadiamento e revisão de biomarcadores quando aplicável." },
      { secao: "Diagnóstico diferencial", corpo: "Diferenciais cobrados: doença infecciosa versus inflamatória, benigna versus maligna, periférica versus central, emergência verdadeira versus quadro ambulatorial. O discriminador costuma ser padrão temporal, exame físico focal, exame complementar-chave ou resposta esperada ao tratamento inicial." },
      { secao: "Condutas", corpo: "A conduta inicial deve ser proporcional ao risco: estabilizar primeiro, confirmar quando seguro, tratar causa reversível, encaminhar casos complexos e evitar terapias desatualizadas. Quando houver diretriz recente, a recomendação vigente prevalece sobre material antigo." },
      { secao: "Complicações", corpo: "Complicações relevantes incluem perda funcional, infecção secundária, trombose/sangramento, insuficiência orgânica, progressão maligna ou recorrência. Em prova, complicação é cobrada como indicação de internação, encaminhamento, imagem, antibiótico, procedimento ou mudança de linha terapêutica." },
      { secao: "Fluxograma de conduta", corpo: "1. Reconheça o padrão clínico.\n2. Procure sinal de gravidade ou instabilidade.\n3. Solicite o exame que confirma e muda conduta.\n4. Inicie tratamento seguro e atual.\n5. Reavalie resposta e complicações.\n6. Encaminhe para especialista quando houver neoplasia, falha terapêutica, doença sistêmica ou risco de órgão-alvo." },
      { secao: "Tabela comparativa", corpo: "| Situação | Pista principal | Conduta de prova |\n|---|---|---|\n| Quadro leve/típico | Sem sinal de alarme | Tratamento inicial e seguimento |\n| Sinal de gravidade | Instabilidade, disfunção ou risco de órgão | Internar/encaminhar e tratar precocemente |\n| Suspeita oncológica | Massa, perda ponderal, sangramento, imagem ou histologia suspeita | Confirmar tecido, estadiar e definir terapia por estágio/biomarcador |\n| Diagnóstico incerto | Achados mistos ou falha ao tratamento | Reavaliar diferencial e solicitar exame de maior acurácia |" },
      { secao: "Pérolas OMED", corpo: "- A melhor resposta costuma ser a primeira conduta segura, não o exame mais sofisticado.\n- Não trate número isolado: trate risco, contexto e tendência.\n- Em câncer, estadiamento e biomarcadores mudam tanto quanto o tipo histológico.\n- Em doenças inflamatórias/infecciosas, gravidade clínica pesa mais que nomenclatura." },
      { secao: "Pegadinhas clássicas", corpo: "- Confundir rastreio com diagnóstico definitivo.\n- Usar conduta antiga quando diretriz atual mudou o padrão.\n- Ignorar sinal de alarme por o paciente parecer estável.\n- Marcar terapia sistêmica sem confirmar histologia/estágio quando isso é obrigatório." },
      { secao: "Integração entre temas", corpo: "Integra-se com infectologia, emergência, radiologia, farmacologia, cirurgia e medicina de família. A utilidade no Codex Medicus é conectar resumo, questão e dashboard: erro em uma vinheta deve virar revisão ativa do subtema." },
      { secao: "Mnemônico", corpo: "**PARE**: **P**adrão clínico, **A**larmes, **R**isco/estágio, **E**scolha terapêutica." },
      { secao: "Questões da OMED", corpo: "A questão associada treina o ponto de maior risco deste subtema: reconhecer a pista decisiva e evitar a alternativa antiga, excessiva ou insuficiente." },
      { secao: "Resumo de 5 minutos", corpo: "> Tumores de Glândulas Salivares e Orofaringe — Diagnóstico e Conduta: reconheça o padrão, classifique gravidade, confirme com o exame que muda conduta e trate conforme diretriz vigente. Ponto de prova: não transformar exceção em regra e não atrasar intervenção quando há risco de órgão ou vida.\n\n---" },
    ],
    referencias: [
      "NCI PDQ. Oropharyngeal Cancer Treatment.",
      "NCI PDQ. Salivary Gland Cancer Treatment.",
      "WHO Classification of Head and Neck Tumours.",
    ],
  },
};
