import type { ConteudoSubtema } from "@/domain/content/types";

export const CONTEUDOS_REUMATO_EXTRA: Record<string, ConteudoSubtema> = {
  "reumato--sindrome-de-sjogren-e-behcet--diagnostico-e-conduta": {
    subtemaId: "reumato--sindrome-de-sjogren-e-behcet--diagnostico-e-conduta",
    titulo: "Síndrome de Sjögren e Doença de Behçet — Diagnóstico e Conduta",
    atualizadoEm: "2026-07-27",
    origem: "complemento_ia",
    blocos: [
      { secao: "Panorama", corpo: "_Síndrome de Sjögren e Doença de Behçet — Diagnóstico e Conduta em prova é decisão prática: reconhecer o padrão, excluir sinais de gravidade e escolher a conduta inicial sem transformar rastreio em tratamento excessivo._" },
      { secao: "Definição", corpo: "Síndrome de Sjögren e Doença de Behçet — Diagnóstico e Conduta é abordado aqui como subtema de alto rendimento da OMED. O eixo é diferenciar apresentação típica, formas graves e situações em que a conduta muda imediatamente.\n\nSjögren combina xerostomia/xeroftalmia, anti-Ro/SSA e risco de linfoma; sempre investigar causas medicamentosas e hepatite C/HIV quando pertinente.\n\nBehçet é vasculite variável com úlceras orais recorrentes, genitais, uveíte e acometimento vascular/neurológico.\n\nTratamento depende de órgão: sintomático glandular em Sjögren; colchicina/corticoide/imunossupressor/biológico em Behçet conforme gravidade." },
      { secao: "Fisiopatologia", corpo: "O mecanismo central explica a clínica e a prova: agressão inicial → alteração anatômica ou molecular → sinal clínico/laboratorial → complicação. Memorizar a conduta sem esse encadeamento gera erro em vinhetas com apresentação atípica." },
      { secao: "Fatores de risco e estratificação", corpo: "Estratifique por idade, comorbidades, imunossupressão, gestação, sinais sistêmicos, extensão da doença e risco de perda de órgão/função. Em oncologia, entram performance status, estadiamento e biologia molecular; em clínica, gravidade e resposta inicial." },
      { secao: "Avaliação clínica", corpo: "Procure sintomas dominantes, tempo de evolução, sinais de alarme e achados que mudam urgência. A banca costuma esconder a resposta em detalhes simples: febre persistente, perda ponderal, dor desproporcional, alteração neurológica, instabilidade, sangramento ou disfunção orgânica." },
      { secao: "Diagnóstico", corpo: "Use exame dirigido, laboratório e imagem apenas quando mudam a decisão. O diagnóstico não deve depender de um teste isolado quando o quadro clínico já exige ação; por outro lado, neoplasias e síndromes complexas exigem confirmação histológica, estadiamento e revisão de biomarcadores quando aplicável." },
      { secao: "Diagnóstico diferencial", corpo: "Diferenciais cobrados: doença infecciosa versus inflamatória, benigna versus maligna, periférica versus central, emergência verdadeira versus quadro ambulatorial. O discriminador costuma ser padrão temporal, exame físico focal, exame complementar-chave ou resposta esperada ao tratamento inicial." },
      { secao: "Condutas", corpo: "A conduta inicial deve ser proporcional ao risco: estabilizar primeiro, confirmar quando seguro, tratar causa reversível, encaminhar casos complexos e evitar terapias desatualizadas. Quando houver diretriz recente, a recomendação vigente prevalece sobre material antigo." },
      { secao: "Complicações", corpo: "Complicações relevantes incluem perda funcional, infecção secundária, trombose/sangramento, insuficiência orgânica, progressão maligna ou recorrência. Em prova, complicação é cobrada como indicação de internação, encaminhamento, imagem, antibiótico, procedimento ou mudança de linha terapêutica." },
      { secao: "Fluxograma de conduta", corpo: "1. Reconheça o padrão clínico.\n2. Procure sinal de gravidade ou instabilidade.\n3. Solicite o exame que confirma e muda conduta.\n4. Inicie tratamento seguro e atual.\n5. Reavalie resposta e complicações.\n6. Encaminhe para especialista quando houver neoplasia, falha terapêutica, doença sistêmica ou risco de órgão-alvo." },
      { secao: "Tabela comparativa", corpo: "| Situação | Pista principal | Conduta de prova |\n|---|---|---|\n| Quadro leve/típico | Sem sinal de alarme | Tratamento inicial e seguimento |\n| Sinal de gravidade | Instabilidade, disfunção ou risco de órgão | Internar/encaminhar e tratar precocemente |\n| Suspeita oncológica | Massa, perda ponderal, sangramento, imagem ou histologia suspeita | Confirmar tecido, estadiar e definir terapia por estágio/biomarcador |\n| Diagnóstico incerto | Achados mistos ou falha ao tratamento | Reavaliar diferencial e solicitar exame de maior acurácia |" },
      { secao: "Pérolas OMED", corpo: "- A melhor resposta costuma ser a primeira conduta segura, não o exame mais sofisticado.\n- Não trate número isolado: trate risco, contexto e tendência.\n- Em câncer, estadiamento e biomarcadores mudam tanto quanto o tipo histológico.\n- Em doenças inflamatórias/infecciosas, gravidade clínica pesa mais que nomenclatura." },
      { secao: "Pegadinhas clássicas", corpo: "- Confundir rastreio com diagnóstico definitivo.\n- Usar conduta antiga quando diretriz atual mudou o padrão.\n- Ignorar sinal de alarme por o paciente parecer estável.\n- Marcar terapia sistêmica sem confirmar histologia/estágio quando isso é obrigatório." },
      { secao: "Integração entre temas", corpo: "Integra-se com infectologia, emergência, radiologia, farmacologia, cirurgia e medicina de família. A utilidade no Codex Medicus é conectar resumo, questão e dashboard: erro em uma vinheta deve virar revisão ativa do subtema." },
      { secao: "Mnemônico", corpo: "**PARE**: **P**adrão clínico, **A**larmes, **R**isco/estágio, **E**scolha terapêutica." },
      { secao: "Questões da OMED", corpo: "A questão associada treina o ponto de maior risco deste subtema: reconhecer a pista decisiva e evitar a alternativa antiga, excessiva ou insuficiente." },
      { secao: "Resumo de 5 minutos", corpo: "> Síndrome de Sjögren e Doença de Behçet — Diagnóstico e Conduta: reconheça o padrão, classifique gravidade, confirme com o exame que muda conduta e trate conforme diretriz vigente. Ponto de prova: não transformar exceção em regra e não atrasar intervenção quando há risco de órgão ou vida.\n\n---" },
    ],
    referencias: [
      "EULAR recommendations for the management of Sjögren's syndrome.",
      "EULAR recommendations for the management of Behçet's syndrome.",
      "Sociedade Brasileira de Reumatologia: materiais de orientação em doenças autoimunes.",
    ],
  },

  "reumato--vasculites-por-imunocomplexos--crioglobulinemia-e-iga": {
    subtemaId: "reumato--vasculites-por-imunocomplexos--crioglobulinemia-e-iga",
    titulo: "Vasculites por Imunocomplexos — Crioglobulinemia e IgA",
    atualizadoEm: "2026-07-27",
    origem: "complemento_ia",
    blocos: [
      { secao: "Panorama", corpo: "_Vasculites por Imunocomplexos — Crioglobulinemia e IgA em prova é decisão prática: reconhecer o padrão, excluir sinais de gravidade e escolher a conduta inicial sem transformar rastreio em tratamento excessivo._" },
      { secao: "Definição", corpo: "Vasculites por Imunocomplexos — Crioglobulinemia e IgA é abordado aqui como subtema de alto rendimento da OMED. O eixo é diferenciar apresentação típica, formas graves e situações em que a conduta muda imediatamente.\n\nCrioglobulinemia costuma associar púrpura palpável, artralgia, neuropatia, glomerulonefrite e hepatite C.\n\nVasculite por IgA combina púrpura palpável, dor abdominal, artralgia e acometimento renal.\n\nUrina tipo I e função renal são obrigatórios no seguimento." },
      { secao: "Fisiopatologia", corpo: "O mecanismo central explica a clínica e a prova: agressão inicial → alteração anatômica ou molecular → sinal clínico/laboratorial → complicação. Memorizar a conduta sem esse encadeamento gera erro em vinhetas com apresentação atípica." },
      { secao: "Fatores de risco e estratificação", corpo: "Estratifique por idade, comorbidades, imunossupressão, gestação, sinais sistêmicos, extensão da doença e risco de perda de órgão/função. Em oncologia, entram performance status, estadiamento e biologia molecular; em clínica, gravidade e resposta inicial." },
      { secao: "Avaliação clínica", corpo: "Procure sintomas dominantes, tempo de evolução, sinais de alarme e achados que mudam urgência. A banca costuma esconder a resposta em detalhes simples: febre persistente, perda ponderal, dor desproporcional, alteração neurológica, instabilidade, sangramento ou disfunção orgânica." },
      { secao: "Diagnóstico", corpo: "Use exame dirigido, laboratório e imagem apenas quando mudam a decisão. O diagnóstico não deve depender de um teste isolado quando o quadro clínico já exige ação; por outro lado, neoplasias e síndromes complexas exigem confirmação histológica, estadiamento e revisão de biomarcadores quando aplicável." },
      { secao: "Diagnóstico diferencial", corpo: "Diferenciais cobrados: doença infecciosa versus inflamatória, benigna versus maligna, periférica versus central, emergência verdadeira versus quadro ambulatorial. O discriminador costuma ser padrão temporal, exame físico focal, exame complementar-chave ou resposta esperada ao tratamento inicial." },
      { secao: "Condutas", corpo: "A conduta inicial deve ser proporcional ao risco: estabilizar primeiro, confirmar quando seguro, tratar causa reversível, encaminhar casos complexos e evitar terapias desatualizadas. Quando houver diretriz recente, a recomendação vigente prevalece sobre material antigo." },
      { secao: "Complicações", corpo: "Complicações relevantes incluem perda funcional, infecção secundária, trombose/sangramento, insuficiência orgânica, progressão maligna ou recorrência. Em prova, complicação é cobrada como indicação de internação, encaminhamento, imagem, antibiótico, procedimento ou mudança de linha terapêutica." },
      { secao: "Fluxograma de conduta", corpo: "1. Reconheça o padrão clínico.\n2. Procure sinal de gravidade ou instabilidade.\n3. Solicite o exame que confirma e muda conduta.\n4. Inicie tratamento seguro e atual.\n5. Reavalie resposta e complicações.\n6. Encaminhe para especialista quando houver neoplasia, falha terapêutica, doença sistêmica ou risco de órgão-alvo." },
      { secao: "Tabela comparativa", corpo: "| Situação | Pista principal | Conduta de prova |\n|---|---|---|\n| Quadro leve/típico | Sem sinal de alarme | Tratamento inicial e seguimento |\n| Sinal de gravidade | Instabilidade, disfunção ou risco de órgão | Internar/encaminhar e tratar precocemente |\n| Suspeita oncológica | Massa, perda ponderal, sangramento, imagem ou histologia suspeita | Confirmar tecido, estadiar e definir terapia por estágio/biomarcador |\n| Diagnóstico incerto | Achados mistos ou falha ao tratamento | Reavaliar diferencial e solicitar exame de maior acurácia |" },
      { secao: "Pérolas OMED", corpo: "- A melhor resposta costuma ser a primeira conduta segura, não o exame mais sofisticado.\n- Não trate número isolado: trate risco, contexto e tendência.\n- Em câncer, estadiamento e biomarcadores mudam tanto quanto o tipo histológico.\n- Em doenças inflamatórias/infecciosas, gravidade clínica pesa mais que nomenclatura." },
      { secao: "Pegadinhas clássicas", corpo: "- Confundir rastreio com diagnóstico definitivo.\n- Usar conduta antiga quando diretriz atual mudou o padrão.\n- Ignorar sinal de alarme por o paciente parecer estável.\n- Marcar terapia sistêmica sem confirmar histologia/estágio quando isso é obrigatório." },
      { secao: "Integração entre temas", corpo: "Integra-se com infectologia, emergência, radiologia, farmacologia, cirurgia e medicina de família. A utilidade no Codex Medicus é conectar resumo, questão e dashboard: erro em uma vinheta deve virar revisão ativa do subtema." },
      { secao: "Mnemônico", corpo: "**PARE**: **P**adrão clínico, **A**larmes, **R**isco/estágio, **E**scolha terapêutica." },
      { secao: "Questões da OMED", corpo: "A questão associada treina o ponto de maior risco deste subtema: reconhecer a pista decisiva e evitar a alternativa antiga, excessiva ou insuficiente." },
      { secao: "Resumo de 5 minutos", corpo: "> Vasculites por Imunocomplexos — Crioglobulinemia e IgA: reconheça o padrão, classifique gravidade, confirme com o exame que muda conduta e trate conforme diretriz vigente. Ponto de prova: não transformar exceção em regra e não atrasar intervenção quando há risco de órgão ou vida.\n\n---" },
    ],
    referencias: [
      "EULAR recommendations for primary small and medium vessel vasculitis.",
      "KDIGO Glomerular Diseases guideline.",
      "Sociedade Brasileira de Reumatologia: vasculites.",
    ],
  },

  "reumato--miopatias-inflamatorias--dermatomiosite-e-polimiosite": {
    subtemaId: "reumato--miopatias-inflamatorias--dermatomiosite-e-polimiosite",
    titulo: "Miopatias Inflamatórias — Dermatomiosite e Polimiosite",
    atualizadoEm: "2026-07-27",
    origem: "complemento_ia",
    blocos: [
      { secao: "Panorama", corpo: "_Miopatias Inflamatórias — Dermatomiosite e Polimiosite em prova é decisão prática: reconhecer o padrão, excluir sinais de gravidade e escolher a conduta inicial sem transformar rastreio em tratamento excessivo._" },
      { secao: "Definição", corpo: "Miopatias Inflamatórias — Dermatomiosite e Polimiosite é abordado aqui como subtema de alto rendimento da OMED. O eixo é diferenciar apresentação típica, formas graves e situações em que a conduta muda imediatamente.\n\nFraqueza proximal simétrica, CK elevada e autoanticorpos orientam miopatia inflamatória.\n\nDermatomiosite tem heliotropo e pápulas de Gottron; em adulto exige rastreio de neoplasia conforme risco.\n\nDispneia pode indicar doença pulmonar intersticial, especialmente em síndrome antisintetase." },
      { secao: "Fisiopatologia", corpo: "O mecanismo central explica a clínica e a prova: agressão inicial → alteração anatômica ou molecular → sinal clínico/laboratorial → complicação. Memorizar a conduta sem esse encadeamento gera erro em vinhetas com apresentação atípica." },
      { secao: "Fatores de risco e estratificação", corpo: "Estratifique por idade, comorbidades, imunossupressão, gestação, sinais sistêmicos, extensão da doença e risco de perda de órgão/função. Em oncologia, entram performance status, estadiamento e biologia molecular; em clínica, gravidade e resposta inicial." },
      { secao: "Avaliação clínica", corpo: "Procure sintomas dominantes, tempo de evolução, sinais de alarme e achados que mudam urgência. A banca costuma esconder a resposta em detalhes simples: febre persistente, perda ponderal, dor desproporcional, alteração neurológica, instabilidade, sangramento ou disfunção orgânica." },
      { secao: "Diagnóstico", corpo: "Use exame dirigido, laboratório e imagem apenas quando mudam a decisão. O diagnóstico não deve depender de um teste isolado quando o quadro clínico já exige ação; por outro lado, neoplasias e síndromes complexas exigem confirmação histológica, estadiamento e revisão de biomarcadores quando aplicável." },
      { secao: "Diagnóstico diferencial", corpo: "Diferenciais cobrados: doença infecciosa versus inflamatória, benigna versus maligna, periférica versus central, emergência verdadeira versus quadro ambulatorial. O discriminador costuma ser padrão temporal, exame físico focal, exame complementar-chave ou resposta esperada ao tratamento inicial." },
      { secao: "Condutas", corpo: "A conduta inicial deve ser proporcional ao risco: estabilizar primeiro, confirmar quando seguro, tratar causa reversível, encaminhar casos complexos e evitar terapias desatualizadas. Quando houver diretriz recente, a recomendação vigente prevalece sobre material antigo." },
      { secao: "Complicações", corpo: "Complicações relevantes incluem perda funcional, infecção secundária, trombose/sangramento, insuficiência orgânica, progressão maligna ou recorrência. Em prova, complicação é cobrada como indicação de internação, encaminhamento, imagem, antibiótico, procedimento ou mudança de linha terapêutica." },
      { secao: "Fluxograma de conduta", corpo: "1. Reconheça o padrão clínico.\n2. Procure sinal de gravidade ou instabilidade.\n3. Solicite o exame que confirma e muda conduta.\n4. Inicie tratamento seguro e atual.\n5. Reavalie resposta e complicações.\n6. Encaminhe para especialista quando houver neoplasia, falha terapêutica, doença sistêmica ou risco de órgão-alvo." },
      { secao: "Tabela comparativa", corpo: "| Situação | Pista principal | Conduta de prova |\n|---|---|---|\n| Quadro leve/típico | Sem sinal de alarme | Tratamento inicial e seguimento |\n| Sinal de gravidade | Instabilidade, disfunção ou risco de órgão | Internar/encaminhar e tratar precocemente |\n| Suspeita oncológica | Massa, perda ponderal, sangramento, imagem ou histologia suspeita | Confirmar tecido, estadiar e definir terapia por estágio/biomarcador |\n| Diagnóstico incerto | Achados mistos ou falha ao tratamento | Reavaliar diferencial e solicitar exame de maior acurácia |" },
      { secao: "Pérolas OMED", corpo: "- A melhor resposta costuma ser a primeira conduta segura, não o exame mais sofisticado.\n- Não trate número isolado: trate risco, contexto e tendência.\n- Em câncer, estadiamento e biomarcadores mudam tanto quanto o tipo histológico.\n- Em doenças inflamatórias/infecciosas, gravidade clínica pesa mais que nomenclatura." },
      { secao: "Pegadinhas clássicas", corpo: "- Confundir rastreio com diagnóstico definitivo.\n- Usar conduta antiga quando diretriz atual mudou o padrão.\n- Ignorar sinal de alarme por o paciente parecer estável.\n- Marcar terapia sistêmica sem confirmar histologia/estágio quando isso é obrigatório." },
      { secao: "Integração entre temas", corpo: "Integra-se com infectologia, emergência, radiologia, farmacologia, cirurgia e medicina de família. A utilidade no Codex Medicus é conectar resumo, questão e dashboard: erro em uma vinheta deve virar revisão ativa do subtema." },
      { secao: "Mnemônico", corpo: "**PARE**: **P**adrão clínico, **A**larmes, **R**isco/estágio, **E**scolha terapêutica." },
      { secao: "Questões da OMED", corpo: "A questão associada treina o ponto de maior risco deste subtema: reconhecer a pista decisiva e evitar a alternativa antiga, excessiva ou insuficiente." },
      { secao: "Resumo de 5 minutos", corpo: "> Miopatias Inflamatórias — Dermatomiosite e Polimiosite: reconheça o padrão, classifique gravidade, confirme com o exame que muda conduta e trate conforme diretriz vigente. Ponto de prova: não transformar exceção em regra e não atrasar intervenção quando há risco de órgão ou vida.\n\n---" },
    ],
    referencias: [
      "EULAR/ACR classification criteria for idiopathic inflammatory myopathies.",
      "British Society for Rheumatology guideline for idiopathic inflammatory myopathy.",
      "Sociedade Brasileira de Reumatologia: miopatias inflamatórias.",
    ],
  },
};
