import type { CasoClinico } from "@/domain/content/types";

// Lote autoral clínico 2026-08-03: casos inéditos, estruturados para raciocínio em etapas.
type Spec = [string,string,string,string,string,string,string,string,string];
const subtemaPublicado = (id: string): string => ({
  "reumato--artrite-reumatoide--diagnostico-e-tratamento": "reumato--artrites--artrite-reumatoide",
  "derma--dermatoses-inflamatorias--psoriase-e-dermatite": "derma--dermatoses-inflamatorias--geral",
  "derma--infeccoes-e-infestacoes--micoses-e-escabiose": "derma--dermatoses-inflamatorias--geral",
}[id] ?? id);
const caseFrom = (s: Spec, id: string): CasoClinico => ({ id, disciplinaId: s[0], subtemaId: subtemaPublicado(s[1]), titulo: s[2], resumo: s[3], dificuldade: "avancada", tags: s[8].replace(/^\\[|\\]$/g, "").split(",").map((tag) => tag.trim().replace(/^['\"]|['\"]$/g, "")), etapas: [
  { tipo: "historia", titulo: "Apresentação", corpo: s[4], pergunta: "Qual síndrome ou problema prioritário deve ser reconhecido primeiro?", resposta: "O contexto e a cronologia apontam para o problema descrito; confirme gravidade, estabilidade e sinais de órgão-alvo antes de escolher exames ou tratamento." },
  { tipo: "laboratorio", titulo: "Dados decisivos", corpo: s[5], pergunta: "Como esses dados mudam sua hipótese e a urgência?", resposta: "Os achados devem ser integrados ao quadro clínico, evitando interpretar um valor isolado fora da probabilidade pré-teste." },
  { tipo: "conduta", titulo: "Plano", corpo: s[6], pergunta: "Qual é a próxima conduta segura?", resposta: s[6] },
], discussao: "Caso construído para treinar reconhecimento sindrômico, gravidade e decisão compartilhada. A conduta deve ser individualizada conforme comorbidades, recursos e protocolo local.", referencias: [s[7]] });

export const CASOS_CLINICOS_LOTE_20260803: CasoClinico[] = [
  caseFrom(["nefro","nefro--sindromes-glomerulares--nefritica-e-nefrotica","Nefrite pós-infecciosa no adulto","Hematúria cor de coca-cola, edema e hipertensão após faringite.","33 anos, edema palpebral e urina escura duas semanas após odinofagia; PA 158/96.","Urina mostra hemácias dismórficas e cilindros hemáticos; C3 baixo, creatinina 1,8 mg/dL.","O padrão é síndrome nefrítica; quantificar proteinúria, acompanhar função renal e investigar estreptococo, reservando biópsia para evolução atípica.","KDIGO 2024 CKD Guideline","['síndrome nefrítica','C3 baixo']"], "caso-nefro-novo-01"),
  caseFrom(["nefro","nefro--sindromes-glomerulares--nefritica-e-nefrotica","Síndrome nefrótica e risco trombótico","Edema generalizado com proteinúria maciça exige reconhecer complicações.","Mulher de 28 anos com edema de membros inferiores e ganho de 8 kg em um mês; PA normal.","Proteinúria 8 g/24 h, albumina 1,8 g/dL, colesterol elevado e creatinina normal.","Confirmar etiologia, reduzir edema com medidas individualizadas e avaliar trombose, infecção e dislipidemia; não presumir causa sem investigação.","KDIGO 2024 CKD Guideline","['síndrome nefrótica','hipoalbuminemia']"], "caso-nefro-novo-02"),
  caseFrom(["nefro","nefro--injuria-renal-aguda-e-doenca-renal-cronica--diagnostico-e-conduta","Necrose tubular por choque","A tendência da creatinina e o contexto hemodinâmico orientam a causa da IRA.","Paciente de 64 anos após choque séptico apresenta oligúria e creatinina subindo de 1,0 para 3,0 mg/dL.","Sedimento com cilindros granulosos castanhos; ultrassom sem obstrução.","Rever perfusão, suspender nefrotóxicos, ajustar doses e tratar a causa; diálise depende de complicações, não de um número isolado.","KDIGO 2012 AKI Guideline","['IRA','necrose tubular aguda']"], "caso-nefro-novo-03"),
  caseFrom(["nefro","nefro--injuria-renal-aguda-e-doenca-renal-cronica--diagnostico-e-conduta","Indicação de terapia renal substitutiva","Hipercalemia refratária pode ser emergência dialítica.","Homem com IRA apresenta fraqueza, K 7,2 mEq/L e alterações de condução no ECG.","Após cálcio, insulina-glicose e beta-agonista, o potássio permanece elevado; há acidose grave.","Solicitar terapia renal substitutiva urgente enquanto mantém estabilização cardíaca e medidas temporizadoras.","KDIGO 2012 AKI Guideline","['hipercalemia','diálise']"], "caso-nefro-novo-04"),
  caseFrom(["nefro","nefro--disturbios-hidroeletroliticos-e-acido-base--diagnostico-e-conduta","Hiponatremia sintomática","A correção inicial deve tratar sintomas sem ultrapassar limites seguros.","Paciente com Na 112 mEq/L apresenta convulsão; osmolaridade sérica baixa e hipovolemia clínica.","Após solução hipertônica em ambiente monitorado, o sódio sobe rapidamente para 120.","Interromper a correção e considerar estratégia de relowering conforme protocolo, monitorando sódio seriado para evitar lesão osmótica.","European Clinical Practice Guideline Hyponatraemia","['hiponatremia','correção segura']"], "caso-nefro-novo-05"),
  caseFrom(["nefro","nefro--disturbios-hidroeletroliticos-e-acido-base--diagnostico-e-conduta","Acidose metabólica em DRC","O ânion gap e o contexto determinam a abordagem da acidose.","Paciente com DRC avançada tem bicarbonato 15 mEq/L, ânion gap normal e respiração compensatória.","Não há choque nem intoxicação; potássio está controlado e não há indicação dialítica imediata.","Investigar causas, otimizar tratamento da DRC e considerar alcalinização individualizada, acompanhando volume e potássio.","KDIGO 2024 CKD Guideline","['acidose metabólica','DRC']"], "caso-nefro-novo-06"),
  caseFrom(["reumato","reumato--vasculites-de-grandes-e-medios-vasos--diagnostico-e-conduta","Arterite de células gigantes","Cefaleia nova com sintomas visuais é urgência de preservação da visão.","Mulher de 74 anos apresenta cefaleia temporal, claudicação mandibular e VHS elevado.","Surge amaurose fugaz unilateral; artéria temporal dolorosa.","Iniciar glicocorticoide imediatamente e organizar confirmação diagnóstica sem atrasar a proteção visual.","ACR Vasculitis Guideline","['arterite de células gigantes','amaurose']"], "caso-reumato-novo-07"),
  caseFrom(["reumato","reumato--vasculites-anca-associadas--diagnostico-e-conduta","Vasculite ANCA com glomerulonefrite","A combinação de pulmão e rim requer confirmação rápida e tratamento de órgão ameaçado.","Homem de 42 anos tem hemoptise, sinusite crônica e creatinina crescente.","Urina com cilindros hemáticos; ANCA anti-PR3 positivo e TC com vidro fosco.","Internar, obter investigação dirigida e iniciar terapia de indução para vasculite grave conforme equipe especializada; não aguardar todos os exames se risco vital.","ACR Vasculitis Guideline","['ANCA','hemorragia alveolar']"], "caso-reumato-novo-08"),
  caseFrom(["reumato","reumato--esclerose-sistemica--diagnostico-e-conduta","Crise renal esclerodérmica","Hipertensão abrupta com queda renal em esclerose sistêmica exige tratamento imediato.","Paciente com esclerodermia difusa desenvolve cefaleia, PA 210/120 e oligúria.","Creatinina dobra em uma semana; há anemia hemolítica microangiopática.","Iniciar inibidor da ECA e monitorização hospitalar, mesmo que a creatinina inicialmente possa subir.","ACR Systemic Sclerosis Guideline","['esclerose sistêmica','crise renal']"], "caso-reumato-novo-09"),
  caseFrom(["reumato","reumato--espondiloartrites--diagnostico-e-conduta","Espondiloartrite axial","Dor lombar inflamatória e sacroiliíte diferenciam-se de lombalgia mecânica.","Homem de 25 anos tem dor lombar há oito meses, melhora com exercício e acorda na segunda metade da noite.","RM mostra edema ósseo sacroilíaco; não há déficit neurológico.","Confirmar o fenótipo, estimular exercício e iniciar tratamento anti-inflamatório; escalonamento depende de atividade persistente e avaliação especializada.","ACR/SAA/SPARTAN axial spondyloarthritis guideline","['espondiloartrite','sacroiliíte']"], "caso-reumato-novo-10"),
  caseFrom(["reumato","reumato--sindrome-de-sjogren-e-behcet--diagnostico-e-conduta","Síndrome de Sjögren","Xeroftalmia e xerostomia com autoanticorpos exigem avaliação sistêmica.","Mulher de 46 anos refere areia nos olhos, cáries recorrentes e aumento parotídeo.","Teste de Schirmer reduzido e anti-Ro positivo; creatinina normal.","Confirmar classificação, tratar secura local e rastrear manifestações sistêmicas e linfoproliferativas.","EULAR recommendations for Sjögren syndrome","['Sjögren','anti-Ro']"], "caso-reumato-novo-11"),
  caseFrom(["reumato","reumato--vasculites-por-imunocomplexos--crioglobulinemia-e-iga","Vasculite crioglobulinêmica","Púrpura palpável, neuropatia e C4 baixo sugerem vasculite por imunocomplexos.","Paciente com hepatite C apresenta púrpura em membros inferiores e parestesias.","C4 baixo, fator reumatoide positivo e crioglobulinas detectáveis.","Investigar e tratar a causa, avaliando gravidade renal/neurológica para definir terapia antiviral e imunomodulação.","EULAR recommendations for cryoglobulinaemic vasculitis","['crioglobulinemia','púrpura palpável']"], "caso-reumato-novo-12"),
  caseFrom(["reumato","reumato--miopatias-inflamatorias--dermatomiosite-e-polimiosite","Dermatomiosite","Fraqueza proximal e lesões cutâneas características apontam para miopatia inflamatória.","Mulher de 51 anos apresenta dificuldade para subir escadas e pápulas de Gottron.","CK elevada e fraqueza proximal simétrica; há disfagia leve.","Confirmar atividade muscular, rastrear neoplasia conforme risco e iniciar tratamento multidisciplinar, incluindo prevenção de aspiração.","EULAR/ACR classification criteria for idiopathic inflammatory myopathies","['dermatomiosite','pápulas de Gottron']"], "caso-reumato-novo-13"),
  caseFrom(["reumato","reumato--artrite-reumatoide--diagnostico-e-tratamento","Artrite reumatoide inicial","Sinovite persistente deve receber tratamento modificador precoce.","Mulher de 39 anos tem rigidez matinal de duas horas e artrite simétrica de mãos há 10 semanas.","Anti-CCP positivo, PCR elevada e erosões iniciais na radiografia.","Encaminhar precocemente e iniciar DMARD conforme avaliação, usando ponte anti-inflamatória quando apropriado.","ACR Guideline for Treatment of Rheumatoid Arthritis","['artrite reumatoide','DMARD']"], "caso-reumato-novo-14"),
  caseFrom(["onco","onco--emergencias-oncologicas--diagnostico-e-conduta","Síndrome da lise tumoral","Hiperpotassemia e hiperfosfatemia após quimioterapia podem ameaçar a vida.","Paciente com linfoma volumoso inicia quimioterapia e, 24 horas depois, apresenta náusea e oligúria.","K 6,8, fósforo alto, cálcio baixo, ácido úrico elevado e creatinina em ascensão.","Tratar como emergência metabólica, com monitorização, controle de potássio e terapia para ácido úrico conforme risco e protocolo.","ASCO guideline on tumor lysis syndrome","['lise tumoral','hipercalemia']"], "caso-onco-novo-15"),
  caseFrom(["onco","onco--emergencias-oncologicas--diagnostico-e-conduta","Compressão medular metastática","Dor vertebral nova com déficit motor exige descompressão diagnóstica rápida.","Homem com câncer de próstata apresenta dor torácica progressiva e dificuldade para caminhar.","RM mostra massa epidural; há hiperreflexia e retenção urinária.","Administrar corticoide conforme protocolo e acionar oncologia/neurocirurgia para tratamento urgente, sem atrasar RM.","NICE guideline on metastatic spinal cord compression","['compressão medular','metástase']"], "caso-onco-novo-16"),
  caseFrom(["onco","onco--cancer-de-pulmao--diagnostico-e-conduta","Rastreamento de câncer de pulmão","O benefício do rastreamento depende de risco e método correto.","Homem de 62 anos fumou 40 maços-ano e parou há 5 anos, assintomático.","Não há perda ponderal nem hemoptise; exame físico é normal.","Discutir rastreamento anual com TC de baixa dose se preencher critérios nacionais e compartilhados; radiografia simples não substitui o método.","USPSTF Lung Cancer Screening Recommendation","['rastreamento','TC de baixa dose']"], "caso-onco-novo-17"),
  caseFrom(["onco","onco--principios-de-oncologia--estadiamento-e-tratamento","Biópsia antes do tratamento","O tecido define diagnóstico, biomarcadores e planejamento.","Mulher com nódulo pulmonar e linfonodos aumentados apresenta imagem altamente suspeita.","Ainda não há histologia nem perfil molecular; está hemodinamicamente estável.","Obter amostra adequada antes de terapia definitiva, escolhendo a via mais segura e representativa.","NCI Non-Small Cell Lung Cancer Treatment","['biópsia','biomarcadores']"], "caso-onco-novo-18"),
  caseFrom(["onco","onco--farmacologia-oncologica-e-imunoterapia--principios-praticos","Toxicidade imune por checkpoint","Diarreia importante durante imunoterapia pode ser colite imune.","Paciente em pembrolizumabe apresenta dez evacuações diárias, sem instabilidade.","Exames excluem infecção comum; há dor abdominal e sangue nas fezes.","Suspender temporariamente o agente, classificar gravidade e iniciar corticoide/terapia especializada conforme protocolo.","ASCO guideline management of immune-related adverse events","['imunoterapia','colite']"], "caso-onco-novo-19"),
  caseFrom(["onco","onco--principios-de-oncologia--estadiamento-e-tratamento","Cuidados paliativos precoces","Controle de sintomas e planejamento podem coexistir com tratamento antitumoral.","Paciente com câncer metastático relata dor, dispneia e sofrimento familiar apesar de tratamento ativo.","Performance status reduzido e múltiplos sintomas; não há decisão compartilhada documentada.","Integrar cuidados paliativos precocemente e alinhar objetivos, sem interpretar isso como abandono terapêutico.","ASCO guideline on palliative care","['cuidados paliativos','comunicação']"], "caso-onco-novo-20"),
  caseFrom(["hemato","hemato--anemias--investigacao-e-classificacao","Anemia ferropriva no homem","Deficiência de ferro em homem adulto exige procurar perda oculta.","Homem de 58 anos tem Hb 9,2, VCM 72 e ferritina baixa, sem sangramento visível.","Teste de sangue oculto é negativo; não há uso de AINE informado.","Investigar trato gastrointestinal conforme idade e contexto, sem encerrar avaliação por teste fecal negativo.","AGA guideline gastrointestinal evaluation of iron deficiency anemia","['ferropriva','sangramento oculto']"], "caso-hemato-novo-21"),
  caseFrom(["hemato","hemato--leucemias--agudas-e-cronicas","Leucemia promielocítica aguda","Coagulopatia com promielócitos anormais é emergência hematológica.","Mulher de 31 anos apresenta equimoses, febre e sangramento gengival; hemograma mostra pancitopenia.","Esfregaço com promielócitos hipergranulares e suspeita de CIVD.","Iniciar ATRA imediatamente na suspeita e corrigir coagulopatia enquanto confirma PML-RARA.","European LeukemiaNet APL recommendations","['LPA','ATRA','CIVD']"], "caso-hemato-novo-22"),
  caseFrom(["hemato","hemato--leucemias--agudas-e-cronicas","Neutropenia febril","Febre em paciente neutropênico requer antibiótico empírico rápido.","Paciente em quimioterapia tem temperatura 38,5 °C e neutrófilos 300/mm³.","Está estável, sem foco evidente, e coleta hemoculturas antes do antibiótico não deve atrasá-lo.","Iniciar antibiótico antipseudomonas conforme protocolo local e estratificar risco para definir internação.","ASCO/IDSA guideline febrile neutropenia","['neutropenia febril','antibiótico empírico']"], "caso-hemato-novo-23"),
  caseFrom(["hemato","hemato--linfomas--hodgkin-e-nao-hodgkin","Linfoma e biópsia","Amostra arquitetural é essencial para classificar linfoma.","Paciente com linfonodo cervical persistente, perda de peso e sudorese noturna.","Punção aspirativa mostra células atípicas, mas não define arquitetura nem subtipo.","Realizar biópsia adequada, preferencialmente excisional quando viável, antes de corticoide isolado.","NCCN B-Cell Lymphomas guideline","['linfoma','biópsia excisional']"], "caso-hemato-novo-24"),
  caseFrom(["hemato","hemato--mieloma-multiplo-e-neoplasias-mieloproliferativas--diagnostico-e-conduta","Hiperviscosidade na macroglobulinemia","Alteração visual e sangramento mucoso com IgM muito elevada sugerem hiperviscosidade.","Homem de 67 anos com fadiga, visão turva e epistaxe; pico monoclonal IgM.","Fundo de olho mostra veias dilatadas; há confusão leve.","Fazer plasmaférese urgente para sintomas de hiperviscosidade e iniciar tratamento hematológico definitivo.","International Myeloma Working Group recommendations","['IgM','hiperviscosidade']"], "caso-hemato-novo-25"),
  caseFrom(["hemato","hemato--medicina-transfusional--indicacoes-de-hemocomponentes","Transfusão restritiva","Hemoglobina isolada não obriga transfusão em paciente estável.","Mulher internada, estável, Hb 7,1 g/dL, sem sangramento e sem isquemia.","Não há sintomas relevantes nem doença coronariana ativa.","Usar estratégia restritiva e individualizar transfusão conforme sintomas, contexto e protocolo institucional.","AABB International Guidelines for RBC transfusion","['transfusão','estratégia restritiva']"], "caso-hemato-novo-26"),
  caseFrom(["derma","derma--piodermites--diagnostico-e-conduta","Celulite sem coleção","A ausência de coleção muda a prioridade terapêutica.","Homem com eritema quente e doloroso na perna, sem flutuação ou necrose.","Ultrassom à beira-leito não mostra abscesso; sinais vitais estáveis.","Tratar celulite com antibiótico apropriado, elevação e reavaliação; não indicar incisão sem coleção.","IDSA Skin and Soft Tissue Infection Guideline","['celulite','abscesso']"], "caso-derma-novo-27"),
  caseFrom(["derma","derma--neoplasias-cutaneas--cbc-cec-e-melanoma","Carcinoma basocelular","Lesão perolada ulcerada em área fotoexposta exige confirmação e tratamento local.","Idoso com pápula perolada sangrante no nariz há oito meses.","Dermatoscopia mostra vasos arboriformes; não há linfonodos palpáveis.","Fazer biópsia apropriada e encaminhar para tratamento definitivo, considerando cirurgia micrográfica em área de alto risco.","AAD Basal Cell Carcinoma Guideline","['carcinoma basocelular','biópsia']"], "caso-derma-novo-28"),
  caseFrom(["derma","derma--neoplasias-cutaneas--cbc-cec-e-melanoma","Melanoma e Breslow","A profundidade de invasão orienta estadiamento e margem.","Lesão pigmentada assimétrica cresce e muda de cor em seis meses.","Biópsia revela melanoma invasivo; o laudo deve informar espessura de Breslow e ulceração.","Encaminhar para estadiamento e tratamento conforme espessura, sem destruir a lesão por métodos sem histologia.","AAD Melanoma Guideline","['melanoma','Breslow']"], "caso-derma-novo-29"),
  caseFrom(["derma","derma--dermatoses-inflamatorias--psoriase-e-dermatite","Psoríase e artrite","Dor e rigidez articular em psoríase exigem rastreio ativo.","Paciente com placas extensas apresenta dor lombar inflamatória e dactilite.","Há limitação funcional e unhas com pitting; não é apenas doença cutânea.","Rastrear artrite psoriásica e encaminhar para reumatologia; a terapia deve cobrir pele e articulações quando possível.","AAD-NPF Psoriasis Guideline","['psoríase','artrite psoriásica']"], "caso-derma-novo-30"),
  caseFrom(["derma","derma--dermatoses-inflamatorias--psoriase-e-dermatite","Dermatite atópica moderada","A base do tratamento é restauração de barreira e controle da inflamação.","Criança com prurido intenso, xerose e eczema flexural recorrente.","Não há sinais de infecção bacteriana sistêmica; banho quente agrava o quadro.","Orientar emoliente contínuo, corticoide tópico apropriado e escalonamento conforme gravidade e resposta.","AAD Atopic Dermatitis Guideline","['dermatite atópica','barreira cutânea']"], "caso-derma-novo-31"),
  caseFrom(["derma","derma--infeccoes-e-infestacoes--micoses-e-escabiose","Escabiose na família","Prurido noturno e contatos sintomáticos orientam manejo coletivo.","Mulher com prurido intenso noturno e lesões em punhos, espaços interdigitais e abdome.","Dois familiares também coçam; não há febre ou impetiginização extensa.","Tratar simultaneamente os contatos e orientar medidas ambientais, além da terapia específica do caso.","CDC Scabies Clinical Care","['escabiose','contatos']"], "caso-derma-novo-32")
];
