import type { CasoClinico, EtapaCaso } from "@/domain/content/types";

type CasoFonte = Omit<CasoClinico, "dificuldade" | "etapas" | "discussao" | "referencias"> & {
  etapas: EtapaCaso[];
  discussao: string;
  referencias?: string[];
};

const caso = (dados: CasoFonte): CasoClinico => ({
  ...dados,
  dificuldade: "avancada",
  referencias: dados.referencias ?? ["Material do usuário — banco discursivo OMED", "Diretrizes brasileiras vigentes"],
});

const STORCH = "inf--infeccoes-congenitas--storch-visao-infectologica";

export const CASOS_EXTRAIDOS: CasoClinico[] = [
  caso({
    id: "caso-ped-disc-01",
    disciplinaId: "ped",
    subtemaId: "ped--emergencias-pediatricas--desidratacao-e-reidratacao",
    titulo: "Lactente em choque por gastroenterite",
    resumo: "Reconhecimento da desidratação grave e expansão volêmica imediata.",
    tags: ["desidratação", "choque", "Plano C"],
    etapas: [
      {
        tipo: "historia",
        titulo: "Apresentação",
        corpo: "Lactente de **8 kg** com gastroenterite aguda, letárgico, pulsos finos e tempo de enchimento capilar de 5 segundos.",
        pergunta: "Como classificar o quadro?",
        resposta: "Há **desidratação grave com choque hipovolêmico**. Letargia e hipoperfusão exigem ressuscitação imediata; não se deve insistir apenas em hidratação oral.",
      },
      {
        tipo: "conduta",
        titulo: "Expansão rápida",
        corpo: "O acesso venoso foi obtido e a criança está monitorizada.",
        pergunta: "Qual solução e volume inicial devem ser prescritos?",
        resposta: "Administrar **cristaloide isotônico** (SF 0,9% ou Ringer lactato), em geral **20 mL/kg** rapidamente: para 8 kg, **160 mL**, com reavaliação imediata de perfusão, pulsos, consciência e diurese. Repetir conforme resposta e protocolo, investigando comorbidades que exijam bolus menores.",
      },
    ],
    discussao: "A prioridade é restaurar perfusão. Depois da estabilização, completa-se o déficit, repõem-se perdas e se retoma alimentação/TRO conforme tolerância.",
    referencias: ["Ministério da Saúde — Manejo do paciente com diarreia", "PALS — Pediatric Advanced Life Support"],
  }),
  caso({
    id: "caso-ped-disc-02",
    disciplinaId: "ped",
    subtemaId: "ped--infeccoes-respiratorias-na-infancia--bronquiolite",
    titulo: "Por que broncodilatador não é rotina na bronquiolite?",
    resumo: "A fisiopatologia explica por que o tratamento é predominantemente de suporte.",
    tags: ["bronquiolite", "VSR", "suporte"],
    etapas: [
      {
        tipo: "hipoteses",
        titulo: "Mecanismo da obstrução",
        corpo: "Lactente com primeiro episódio de sibilância após pródromo viral apresenta taquipneia e tiragem leve.",
        pergunta: "O que obstrui as pequenas vias aéreas?",
        resposta: "O vírus lesa o epitélio bronquiolar, gerando **edema, necrose, muco e detritos celulares**. O pequeno calibre do lactente amplifica a resistência, com aprisionamento aéreo e atelectasias.",
      },
      {
        tipo: "conduta",
        titulo: "Implicação terapêutica",
        corpo: "O lactente está hidratado e sem hipoxemia persistente.",
        pergunta: "Por que salbutamol e corticoide não são usados rotineiramente?",
        resposta: "O problema dominante não é broncoespasmo reversível nem inflamação responsiva a corticoide. Ensaios não mostram benefício clínico rotineiro. A conduta é **higiene nasal, hidratação, alimentação fracionada e oxigênio se indicado**.",
      },
    ],
    discussao: "A exceção deve ser individualizada quando o diagnóstico é incerto ou há fenótipo recorrente compatível com asma; isso não transforma broncodilatador em rotina da bronquiolite típica.",
    referencias: ["Sociedade Brasileira de Pediatria — Bronquiolite viral aguda", "AAP — Bronchiolitis guideline"],
  }),
  caso({
    id: "caso-ped-disc-03",
    disciplinaId: "ped",
    subtemaId: "ped--neonatologia--ictericia-neonatal",
    titulo: "Icterícia por pouca ingesta ou pelo leite materno?",
    resumo: "Tempo de início, ganho ponderal e mecanismo diferenciam os dois quadros.",
    tags: ["icterícia", "aleitamento", "bilirrubina"],
    etapas: [
      {
        tipo: "historia",
        titulo: "Primeira semana",
        corpo: "RN no 4º dia, pega inadequada, poucas micções e perda ponderal excessiva apresenta hiperbilirrubinemia indireta.",
        pergunta: "Qual o mecanismo mais provável?",
        resposta: "É **icterícia associada à ingesta insuficiente**: menor aporte e trânsito intestinal aumentam a circulação entero-hepática. Corrigir técnica e frequência das mamadas é central.",
      },
      {
        tipo: "evolucao",
        titulo: "Depois da primeira semana",
        corpo: "Outro lactente, saudável e ganhando peso, mantém icterícia indireta após a segunda semana.",
        pergunta: "Qual a hipótese e qual cautela não pode ser esquecida?",
        resposta: "O padrão sugere **icterícia do leite materno**, relacionada a fatores que aumentam a circulação entero-hepática. Porém toda icterícia prolongada exige **bilirrubina fracionada** para não perder colestase, especialmente com colúria ou acolia.",
      },
    ],
    discussao: "A primeira é precoce e ligada à baixa ingesta; a segunda é tardia, em lactente saudável. Em nenhuma delas se suspende aleitamento de rotina.",
  }),
  caso({
    id: "caso-ped-disc-04",
    disciplinaId: "ped",
    subtemaId: "ped--infeccoes-respiratorias-na-infancia--crupe-laringotraqueobronquite",
    titulo: "Crupe grave com estridor em repouso",
    resumo: "Adrenalina atua em minutos, mas seu efeito transitório exige observação.",
    tags: ["crupe", "adrenalina", "dexametasona"],
    etapas: [
      {
        tipo: "exame_fisico",
        titulo: "Gravidade",
        corpo: "Criança de 3 anos com estridor intenso em repouso, tiragem de fúrcula e agitação.",
        pergunta: "Qual intervenção farmacológica produz alívio mais rápido?",
        resposta: "**Adrenalina nebulizada**, pela vasoconstrição da mucosa subglótica. Deve ser associada a **dexametasona**, que tem início mais lento e efeito prolongado.",
      },
      {
        tipo: "evolucao",
        titulo: "Após a melhora",
        corpo: "O estridor desaparece logo após a nebulização.",
        pergunta: "Por que a criança não deve receber alta imediata?",
        resposta: "O efeito da adrenalina é transitório. É necessário observar por cerca de **3 a 4 horas**, garantindo ausência de recorrência do estridor e estabilidade antes da alta.",
      },
    ],
    discussao: "Adrenalina não substitui corticoide. Agitação piora a obstrução, portanto minimizar manipulação e manter a criança com o cuidador também faz parte da conduta.",
  }),
  caso({
    id: "caso-ped-disc-05",
    disciplinaId: "ped",
    subtemaId: "ped--emergencias-pediatricas--convulsao-febril",
    titulo: "Orientação após convulsão febril simples",
    resumo: "Critérios diagnósticos e prognóstico que precisam ser explicados à família.",
    tags: ["convulsão febril", "recorrência", "epilepsia"],
    etapas: [
      {
        tipo: "historia",
        titulo: "Critérios",
        corpo: "Criança de 18 meses tem crise generalizada única de 4 minutos durante febre, recupera-se completamente e não apresenta sinais de infecção do SNC.",
        pergunta: "Quais elementos sustentam convulsão febril simples?",
        resposta: "Faixa de **6 meses a 5 anos**, febre sem infecção do SNC ou causa metabólica, crise **generalizada**, duração **menor que 15 minutos** e ausência de recorrência em 24 horas.",
      },
      {
        tipo: "desfecho",
        titulo: "Prognóstico",
        corpo: "Os pais perguntam se a crise voltará e se a criança terá epilepsia.",
        pergunta: "Como orientar?",
        resposta: "A recorrência ocorre em cerca de **um terço** das crianças, maior quando a primeira crise é precoce. Após crise simples, o risco de epilepsia permanece baixo, por volta de **1–2%**, e o prognóstico cognitivo é excelente.",
      },
    ],
    discussao: "Antitérmicos trazem conforto, mas não previnem de modo confiável novas crises. Tratamento anticonvulsivante crônico não é indicado após crise simples.",
  }),
  caso({
    id: "caso-inf-disc-41",
    disciplinaId: "inf",
    subtemaId: STORCH,
    titulo: "Toxoplasmose materna com baixa avidez",
    resumo: "Da suspeita de infecção recente à confirmação fetal e mudança terapêutica.",
    tags: ["toxoplasmose", "avidez", "PCR fetal"],
    etapas: [
      {
        tipo: "laboratorio",
        titulo: "Sorologia materna",
        corpo: "Gestante de 12 semanas apresenta IgG e IgM positivos para toxoplasmose, com avidez de IgG de 15%.",
        pergunta: "Como interpretar e tratar inicialmente?",
        resposta: "A **baixa avidez** no primeiro trimestre sustenta infecção recente. Inicia-se **espiramicina** para reduzir transmissão transplacentária enquanto se investiga o feto.",
      },
      {
        tipo: "exame_fisico",
        titulo: "Investigação fetal",
        corpo: "A gestação segue sem alterações ultrassonográficas.",
        pergunta: "Quando e como investigar infecção fetal?",
        resposta: "Fazer ultrassonografia seriada e **PCR para T. gondii no líquido amniótico**, em geral após **18 semanas** e pelo menos quatro semanas após a infecção materna suspeita, para melhorar a sensibilidade.",
      },
      {
        tipo: "conduta",
        titulo: "PCR positiva",
        corpo: "A PCR do líquido amniótico confirma infecção fetal.",
        pergunta: "Como muda o tratamento?",
        resposta: "Após o primeiro trimestre, troca-se para **pirimetamina + sulfadiazina + ácido folínico**, que tratam a infecção fetal. O ácido folínico reduz toxicidade medular da pirimetamina.",
      },
    ],
    discussao: "IgM isolado pode persistir; avidez, cronologia, sorologias confirmatórias e PCR fetal devem ser interpretadas em conjunto.",
  }),
  caso({
    id: "caso-inf-disc-42",
    disciplinaId: "inf",
    subtemaId: STORCH,
    titulo: "Recém-nascido sintomático exposto à sífilis",
    resumo: "Tratamento materno inadequado, investigação neonatal e penicilina por 10 dias.",
    tags: ["sífilis congênita", "VDRL", "penicilina"],
    etapas: [
      {
        tipo: "historia",
        titulo: "Exposição",
        corpo: "Mãe com VDRL 1:64 recebeu somente duas doses de penicilina benzatina; a última foi cinco dias antes do parto. O RN tem rinite serossanguinolenta, hepatoesplenomegalia, lesões palmoplantares e VDRL 1:128.",
        pergunta: "O tratamento materno foi adequado?",
        resposta: "**Não.** O esquema foi incompleto e terminou menos de 30 dias antes do parto. Além disso, o RN é sintomático, o que impõe investigação e tratamento completos.",
      },
      {
        tipo: "laboratorio",
        titulo: "Avaliação neonatal",
        corpo: "É necessário estadiar o acometimento.",
        pergunta: "Quais exames são prioritários?",
        resposta: "VDRL quantitativo em sangue periférico, hemograma/plaquetas, função hepática e **radiografia de ossos longos**; avaliar **líquor com VDRL, celularidade e proteína**, além de outros exames conforme manifestações (audição, visão e neuroimagem).",
      },
      {
        tipo: "conduta",
        titulo: "Tratamento",
        corpo: "O RN permanece clinicamente estável.",
        pergunta: "Qual é o esquema de escolha?",
        resposta: "**Penicilina G cristalina intravenosa por 10 dias** (ou esquema procaína quando apropriado ao protocolo). Uma dose isolada de benzatina é insuficiente para RN sintomático.",
      },
    ],
    discussao: "Título neonatal quatro vezes maior apoia infecção, mas sua ausência não exclui sífilis congênita. Aqui, sinais clínicos e tratamento materno inadequado já definem alto risco.",
  }),
  caso({
    id: "caso-inf-disc-43",
    disciplinaId: "inf",
    subtemaId: STORCH,
    titulo: "CMV congênito diagnosticado tardiamente",
    resumo: "Padrão de imagem, confirmação após 21 dias e benefício do tratamento precoce.",
    tags: ["CMV congênito", "surdez", "PCR"],
    etapas: [
      {
        tipo: "imagem",
        titulo: "Padrão neurológico",
        corpo: "Lactente de 2 meses tem microcefalia, calcificações periventriculares e surdez neurossensorial.",
        pergunta: "Qual o diagnóstico e o principal diferencial radiológico?",
        resposta: "O padrão favorece **CMV congênito**. Toxoplasmose é o principal diferencial, mas costuma produzir calcificações **difusas** e se associa à hidrocefalia/coriorretinite.",
      },
      {
        tipo: "laboratorio",
        titulo: "Confirmação tardia",
        corpo: "Não houve PCR de saliva ou urina nas primeiras três semanas.",
        pergunta: "Como ainda demonstrar origem congênita?",
        resposta: "Após 21 dias, PCR atual não distingue aquisição congênita de pós-natal. Pode-se testar a **amostra neonatal arquivada do teste do pezinho** por PCR, reconhecendo sensibilidade limitada; prontuários e amostras precoces também são decisivos.",
      },
      {
        tipo: "conduta",
        titulo: "Antiviral",
        corpo: "Os pais perguntam sobre o tratamento no período neonatal.",
        pergunta: "Qual benefício era esperado no RN sintomático?",
        resposta: "**Valganciclovir por seis meses**, iniciado precocemente em doença sintomática com SNC, pode melhorar desfechos auditivos e do neurodesenvolvimento, exigindo monitorização hematológica e hepática.",
      },
    ],
    discussao: "O limite de 21 dias é crucial: depois dele, uma amostra nova positiva confirma infecção, mas não necessariamente que ela era congênita.",
  }),
  caso({
    id: "caso-inf-disc-44",
    disciplinaId: "inf",
    subtemaId: STORCH,
    titulo: "Hidropisia fetal por parvovírus B19",
    resumo: "Anemia fetal grave, Doppler de ACM e transfusão intrauterina.",
    tags: ["parvovírus B19", "hidropisia", "transfusão intrauterina"],
    etapas: [
      {
        tipo: "imagem",
        titulo: "Fisiopatologia",
        corpo: "Feto de 22 semanas tem hidropisia e insuficiência cardíaca. PVS da artéria cerebral média é 1,7 MoM e IgM materna para parvovírus B19 é positiva.",
        pergunta: "Como a infecção produz hidropisia?",
        resposta: "O vírus destrói **precursores eritroides**, causando aplasia transitória e anemia fetal grave. A queda da viscosidade eleva o PVS da ACM; a insuficiência cardíaca de alto débito culmina em hidropisia.",
      },
      {
        tipo: "conduta",
        titulo: "Intervenção fetal",
        corpo: "O Doppler sugere anemia grave e há deterioração fetal.",
        pergunta: "Qual intervenção pode salvar o feto?",
        resposta: "Avaliação em centro de medicina fetal para **cordocentese e transfusão intrauterina**, indicada diante de anemia grave provável/confirmada, especialmente com PVS da ACM >1,5 MoM e hidropisia. O seguimento usa Doppler e ultrassom seriados.",
      },
      {
        tipo: "desfecho",
        titulo: "Prognóstico",
        corpo: "O feto responde à transfusão e a hidropisia regride.",
        pergunta: "Como é o prognóstico dos sobreviventes?",
        resposta: "Em geral é **favorável** após correção da anemia, embora hidropisia grave, prematuridade e complicações do procedimento possam elevar o risco neurológico; é necessário seguimento do desenvolvimento.",
      },
    ],
    discussao: "PVS da ACM é método não invasivo de rastreio de anemia fetal e reduz a necessidade de cordocenteses meramente diagnósticas.",
  }),
  caso({
    id: "caso-inf-disc-45",
    disciplinaId: "inf",
    subtemaId: STORCH,
    titulo: "Síndrome congênita do Zika",
    resumo: "Neuroimagem, malformações osteoarticulares e diagnóstico materno.",
    tags: ["Zika", "microcefalia", "artrogripose"],
    etapas: [
      {
        tipo: "imagem",
        titulo: "Espectro de imagem",
        corpo: "Gestante sintomática vive em área com circulação de arbovírus; o feto apresenta microcefalia progressiva.",
        pergunta: "Quais achados reforçam síndrome congênita do Zika?",
        resposta: "Microcefalia grave com desproporção craniofacial, **calcificações corticais/subcorticais**, ventriculomegalia, alterações de migração cortical, hipoplasia de corpo caloso/cerebelo e redução do volume encefálico.",
      },
      {
        tipo: "exame_fisico",
        titulo: "Sistema osteoarticular",
        corpo: "Também são vistos membros em posições fixas e pés deformados.",
        pergunta: "Quais malformações são típicas e qual o mecanismo provável?",
        resposta: "**Artrogripose** e **pé torto congênito** são frequentes. Predomina mecanismo **neurogênico**, com lesão de neurônios motores/fetal akinesia, mais do que teratogênese direta do osso.",
      },
      {
        tipo: "laboratorio",
        titulo: "Investigação materna",
        corpo: "A gestante procura atendimento poucos dias após o início do exantema.",
        pergunta: "Como organizar o rastreamento laboratorial?",
        resposta: "Coletar **teste molecular (RT-PCR)** nas janelas e amostras previstas pelo protocolo de vigilância e considerar sorologia conforme o tempo de sintomas. Interpretar com cautela pela reação cruzada com outros flavivírus e manter ultrassonografia fetal seriada.",
      },
    ],
    discussao: "Teste negativo fora da janela não exclui exposição. O diagnóstico integra epidemiologia, cronologia, laboratório e imagem fetal/neonatal.",
  }),
  caso({
    id: "caso-go-disc-01",
    disciplinaId: "go",
    subtemaId: "go--crescimento-e-obito-fetal--restricao-de-crescimento-fetal",
    titulo: "RCF ou feto constitucionalmente pequeno?",
    resumo: "Biometria seriada e Doppler distinguem baixo percentil de insuficiência placentária.",
    tags: ["RCF", "Doppler", "PIG"],
    etapas: [
      {
        tipo: "historia",
        titulo: "Suspeita clínica",
        corpo: "Gestante de 28 semanas, sem comorbidades, apresenta altura uterina abaixo do percentil 10.",
        pergunta: "Qual é a propedêutica inicial?",
        resposta: "Confirmar datação, realizar ultrassonografia com biometria e **peso fetal estimado**, circunferência abdominal, anatomia, placenta e líquido amniótico. Repetir biometria em intervalo adequado para avaliar **velocidade de crescimento**.",
      },
      {
        tipo: "imagem",
        titulo: "Dopplervelocimetria",
        corpo: "O peso fetal estimado está abaixo do percentil 10.",
        pergunta: "Como o Doppler ajuda no diagnóstico diferencial?",
        resposta: "Avaliar artérias **uterinas, umbilical e cerebral média**, com relação cerebroplacentária; nos quadros precoces/graves, ducto venoso. Feto pequeno com crescimento harmônico, líquido e Dopplers normais tende a ser constitucional; alterações placentárias/cerebrais sustentam **RCF** e orientam vigilância/parto.",
      },
    ],
    discussao: "Percentil baixo não é sinônimo automático de doença. O diagnóstico depende de contexto, trajetória de crescimento e sinais de insuficiência placentária.",
  }),
  caso({
    id: "caso-go-disc-02",
    disciplinaId: "go",
    subtemaId: "go--sindromes-hipertensivas-da-gestacao--pre-eclampsia-e-eclampsia",
    titulo: "Pré-eclâmpsia grave com 30 semanas",
    resumo: "Estabilização materna, vigilância rigorosa e critérios de interrupção imediata.",
    tags: ["pré-eclâmpsia", "sulfato de magnésio", "prematuridade"],
    etapas: [
      {
        tipo: "conduta",
        titulo: "Manejo inicial",
        corpo: "Paciente com 30 semanas e pré-eclâmpsia com sinais de gravidade está temporariamente estável em centro terciário.",
        pergunta: "Quais são os pilares do manejo?",
        resposta: "Internação, **sulfato de magnésio** para prevenção de eclâmpsia, tratamento urgente se PA persistir ≥160/110, corticoide antenatal, exames seriados maternos e vigilância fetal. Conduta expectante só cabe sob critérios estritos e capacidade de intervenção imediata.",
      },
      {
        tipo: "evolucao",
        titulo: "Critérios de parto",
        corpo: "Durante a internação surgem novos sinais clínicos.",
        pergunta: "O que determina interrupção independentemente da idade gestacional?",
        resposta: "Hipertensão grave refratária, eclâmpsia, edema pulmonar, HELLP/deterioração hepática ou renal, sintomas neurológicos persistentes, DPP, sangramento importante, sofrimento ou morte fetal e outras evidências de piora materno-fetal.",
      },
    ],
    discussao: "O objetivo da expectância é ganhar tempo com segurança, nunca prolongar a gestação diante de deterioração materna ou fetal.",
  }),
  caso({
    id: "caso-go-disc-03",
    disciplinaId: "go",
    subtemaId: "go--hemorragias-da-gestacao--segunda-metade-dpp-placenta-previa",
    titulo: "Placenta prévia versus DPP",
    resumo: "Dor, aspecto do sangramento e tônus uterino orientam o diagnóstico.",
    tags: ["placenta prévia", "DPP", "sangramento"],
    etapas: [
      {
        tipo: "exame_fisico",
        titulo: "Comparação clínica",
        corpo: "Duas gestantes no terceiro trimestre chegam com sangramento vaginal.",
        pergunta: "Como diferenciar placenta prévia de DPP à beira-leito?",
        resposta: "**Placenta prévia:** sangramento vermelho vivo, súbito, recorrente e geralmente **indolor**, útero flácido. **DPP:** dor abdominal, sangramento frequentemente escuro (que pode ser oculto), útero **hipertônico e doloroso**, com maior risco de sofrimento fetal.",
      },
      {
        tipo: "conduta",
        titulo: "Exame proibido",
        corpo: "A localização placentária ainda não foi confirmada por ultrassom.",
        pergunta: "Por que o toque vaginal digital está contraindicado?",
        resposta: "Na placenta prévia, o toque pode romper a implantação placentária sobre o colo e desencadear **hemorragia catastrófica**. Primeiro se exclui placenta prévia por ultrassonografia; exame especular cuidadoso pode ser usado em ambiente apropriado.",
      },
    ],
    discussao: "Sangramento aparente não mede a gravidade do DPP: grande volume pode permanecer retroplacentário.",
  }),
  caso({
    id: "caso-go-disc-04",
    disciplinaId: "go",
    subtemaId: "go--hemorragias-da-gestacao--primeira-metade-abortamento-ectopica-mola",
    titulo: "Gestação de localização desconhecida",
    resumo: "β-hCG seriado e ultrassom guiam observação, metotrexato ou cirurgia.",
    tags: ["gravidez ectópica", "GLD", "metotrexato"],
    etapas: [
      {
        tipo: "laboratorio",
        titulo: "Primeiras 48 horas",
        corpo: "Paciente estável, com atraso menstrual, β-hCG positivo e ultrassom transvaginal sem gestação intrauterina ou ectópica visível.",
        pergunta: "Como conduzir inicialmente?",
        resposta: "Tratar como **gestação de localização desconhecida**: repetir β-hCG em 48 horas, reavaliar sintomas e repetir ultrassom. A zona discriminatória e a curva auxiliam, mas um valor isolado não autoriza interromper gestação potencialmente viável.",
      },
      {
        tipo: "conduta",
        titulo: "Escolha terapêutica",
        corpo: "A evolução confirma ectópica não rota.",
        pergunta: "Quando considerar metotrexato e quando operar?",
        resposta: "**Metotrexato:** paciente estável, sem rotura, capaz de seguimento, sem contraindicações e com baixa carga trofoblástica. **Cirurgia:** instabilidade/hemoperitônio, rotura, contraindicação ou falha do fármaco, massa/carga elevada, atividade cardíaca embrionária em muitos protocolos ou impossibilidade de seguimento.",
      },
    ],
    discussao: "Uma elevação aparentemente adequada do β-hCG não exclui totalmente ectópica; clínica e ultrassom seriados permanecem essenciais.",
  }),
  caso({
    id: "caso-go-disc-05",
    disciplinaId: "go",
    subtemaId: "go--sindromes-hipertensivas-da-gestacao--pre-eclampsia-e-eclampsia",
    titulo: "HAS crônica, pré-eclâmpsia sobreposta e DPP",
    resumo: "Três diagnósticos convergem para estabilização e parto urgente.",
    tags: ["HAS crônica", "pré-eclâmpsia sobreposta", "DPP"],
    etapas: [
      {
        tipo: "historia",
        titulo: "Apresentação integrada",
        corpo: "Gestante de 32 semanas com hipertensão crônica chega com cefaleia, epigastralgia, PA 170/110, sangramento, útero hipertônico e sofrimento fetal agudo.",
        pergunta: "Qual a hipótese principal?",
        resposta: "**Pré-eclâmpsia sobreposta à hipertensão crônica, com sinais de gravidade, complicada por descolamento prematuro de placenta.** Hipertonia, dor/sangramento e sofrimento fetal sustentam DPP.",
      },
      {
        tipo: "conduta",
        titulo: "Decisão imediata",
        corpo: "A equipe prepara acesso, monitorização e avaliação rápida.",
        pergunta: "Como controlar a pressão e decidir o momento do parto?",
        resposta: "Tratar imediatamente a PA grave com agente de ação rápida, administrar **sulfato de magnésio**, estabilizar a mãe e proceder à **resolução urgente da gestação** pela via mais rápida e segura, pois há DPP e sofrimento fetal. A prematuridade não justifica expectância nesse cenário.",
      },
    ],
    discussao: "Hipertensão crônica isolada e controlada poderia permitir seguimento até idade gestacional planejada. O surgimento de pré-eclâmpsia grave/DPP muda completamente o risco e o tempo do parto.",
  }),
];
