/** Gera manifesto privado, com hash do recorte e do PDF de origem, para as pÃ¡ginas
 * neuropsiquiÃ¡tricas que faltavam no catÃ¡logo. NÃ£o publica e nÃ£o faz upload. */
import { createHash } from "node:crypto";
import { readFile, stat, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import sharp from "sharp";

const args = process.argv.slice(2);
const flag = (name: string) => { const i = args.indexOf(name); return i >= 0 ? args[i + 1] : undefined; };
const root = resolve(flag("--root") ?? "C:/Users/Adm/Desktop/MEDICINA/_private-corpus/batch-20260812-psiquiatria");
const incoming = resolve(flag("--incoming") ?? "C:/Users/Adm/Desktop/MEDICINA/_private-corpus/semana-20260809/incoming");
const out = resolve(flag("--out") ?? `${root}/manifest-neuropsiquiatria-completo-20260814.json`);

type Definition = {
  file: string; page: number; output: string; disciplina: string; tema: string;
  subtema: string; subtemaId: string; titulo: string; diagnostico: string;
  modalidade: string; fonte: string;
};

const definitions: Definition[] = [
  { file: "Psiquiatria_Clinica_MED_ATLAS_V3_2026.pdf", page: 92, output: "renders/psiquiatria-clinica-092.png", disciplina: "Psiquiatria", tema: "Psicoses", subtema: "Primeiro episódio psicótico e causas orgânicas", subtemaId: "psiq--psicoses--primeiro-episodio-psicotico", titulo: "Red flags e neuroimagem no primeiro episódio psicótico", diagnostico: "Psicose com possível etiologia orgânica", modalidade: "RM FLAIR e tabela de neuroimagem", fonte: "Psiquiatria Clínica MED ATLAS 2026" },
  { file: "Psiquiatria_Clinica_MED_ATLAS_V3_2026.pdf", page: 97, output: "renders/psiquiatria-clinica-097.png", disciplina: "Psiquiatria", tema: "Psicoses", subtema: "Primeiro episódio psicótico e causas orgânicas", subtemaId: "psiq--psicoses--primeiro-episodio-psicotico", titulo: "Quando a psicose é neurológica", diagnostico: "Diferencial neurológico da psicose", modalidade: "TC, RM e EEG", fonte: "Psiquiatria Clínica MED ATLAS 2026" },
  { file: "Psiquiatria_Clinica_MED_ATLAS_V3_2026.pdf", page: 99, output: "renders/psiquiatria-clinica-099.png", disciplina: "Psiquiatria", tema: "Psicoses", subtema: "Primeiro episódio psicótico e causas orgânicas", subtemaId: "psiq--psicoses--primeiro-episodio-psicotico", titulo: "Doença de pequenos vasos e neuropsiquiatria", diagnostico: "Comprometimento vascular com manifestações neuropsiquiátricas", modalidade: "RM FLAIR e neuroimagem", fonte: "Psiquiatria Clínica MED ATLAS 2026" },
  { file: "Psiquiatria_Clinica_MED_ATLAS_V3_2026.pdf", page: 100, output: "renders/psiquiatria-clinica-100.png", disciplina: "Psiquiatria", tema: "Emergências psiquiátricas", subtema: "Psicose secundária, delirium e EEG", subtemaId: "neuro--hipertensao-intracraniana-e-delirium--diagnostico-e-conduta", titulo: "Anti-NMDAR e delirium: EEG que muda a investigação", diagnostico: "Encefalopatia/delirium com investigação neurológica", modalidade: "Tabela de EEG e critérios de investigação", fonte: "Psiquiatria Clínica MED ATLAS 2026" },
  { file: "Psiquiatria_Clinica_MED_ATLAS_V3_2026.pdf", page: 102, output: "renders/psiquiatria-clinica-102.png", disciplina: "Psiquiatria", tema: "Psicoses", subtema: "Primeiro episódio psicótico e causas orgânicas", subtemaId: "psiq--psicoses--primeiro-episodio-psicotico", titulo: "Quando solicitar exames em psiquiatria", diagnostico: "Investigação de causa secundária", modalidade: "Tabela de indicação de exames", fonte: "Psiquiatria Clínica MED ATLAS 2026" },
  { file: "Sindromes_Demenciais_Guia_Integrado_Residencia_2026_MED_ATLAS_REAL_v2.pdf", page: 39, output: "renders/demencias-039.png", disciplina: "Neurologia", tema: "Síndromes demenciais", subtema: "Neuroimagem e causas tratáveis", subtemaId: "neuro--amnesias-e-sindromes-demenciais--diagnostico-e-conduta", titulo: "ARIA: leitura radiológica sem esquema sintético", diagnostico: "Alterações de imagem relacionadas a terapias antiamiloide", modalidade: "RM FLAIR e classificação radiológica", fonte: "Síndromes Demenciais MED ATLAS 2026" },
  { file: "Sindromes_Demenciais_Guia_Integrado_Residencia_2026_MED_ATLAS_REAL_v2.pdf", page: 68, output: "renders/demencias-068.png", disciplina: "Neurologia", tema: "Síndromes demenciais", subtema: "Neuroimagem e causas tratáveis", subtemaId: "neuro--amnesias-e-sindromes-demenciais--diagnostico-e-conduta", titulo: "Doença de Creutzfeldt-Jakob: critérios de probabilidade", diagnostico: "Doença de Creutzfeldt-Jakob", modalidade: "Critérios clínicos, EEG e biomarcadores", fonte: "Síndromes Demenciais MED ATLAS 2026" },
  { file: "Sindromes_Demenciais_Guia_Integrado_Residencia_2026_MED_ATLAS_REAL_v2.pdf", page: 107, output: "renders/demencias-107.png", disciplina: "Neurologia", tema: "Síndromes demenciais", subtema: "Neuroimagem e causas tratáveis", subtemaId: "neuro--amnesias-e-sindromes-demenciais--diagnostico-e-conduta", titulo: "Alzheimer: atrofia temporal medial", diagnostico: "Doença de Alzheimer provável", modalidade: "RM coronal", fonte: "Síndromes Demenciais MED ATLAS 2026" },
  { file: "Sindromes_Demenciais_Guia_Integrado_Residencia_2026_MED_ATLAS_REAL_v2.pdf", page: 110, output: "renders/demencias-110.png", disciplina: "Neurologia", tema: "Síndromes demenciais", subtema: "Neuroimagem e causas tratáveis", subtemaId: "neuro--amnesias-e-sindromes-demenciais--diagnostico-e-conduta", titulo: "Hidrocefalia de pressão normal", diagnostico: "Hidrocefalia de pressão normal", modalidade: "TC e RM com índice de Evans", fonte: "Síndromes Demenciais MED ATLAS 2026" },
  { file: "Sindromes_Demenciais_Guia_Integrado_Residencia_2026_MED_ATLAS_REAL_v2.pdf", page: 111, output: "renders/demencias-111.png", disciplina: "Neurologia", tema: "Síndromes demenciais", subtema: "Neuroimagem e causas tratáveis", subtemaId: "neuro--amnesias-e-sindromes-demenciais--diagnostico-e-conduta", titulo: "Doença de Creutzfeldt-Jakob: padrão de difusão", diagnostico: "Doença de Creutzfeldt-Jakob", modalidade: "RM com difusão", fonte: "Síndromes Demenciais MED ATLAS 2026" },
  { file: "Neuroanatomia_Clinica_Visual_Funcional_Patologias_Final.pdf", page: 55, output: "renders/neuroanatomia-055.png", disciplina: "Neurologia", tema: "Neuroanatomia clínica", subtema: "Localização neurológica", subtemaId: "neuro--neuroanatomia-clinica--localizacao-neurologica", titulo: "Sistema límbico e hipocampo", diagnostico: "Anatomia funcional da memória", modalidade: "RM e diagrama anatômico", fonte: "Neuroanatomia Clínica Visual MED ATLAS 2026" },
  { file: "Neuroanatomia_Clinica_Visual_Funcional_Patologias_Final.pdf", page: 56, output: "renders/neuroanatomia-056.png", disciplina: "Neurologia", tema: "Neuroanatomia clínica", subtema: "Localização neurológica", subtemaId: "neuro--neuroanatomia-clinica--localizacao-neurologica", titulo: "Hipocampo e localização temporal medial", diagnostico: "Estruturas temporais mediais", modalidade: "RM coronal", fonte: "Neuroanatomia Clínica Visual MED ATLAS 2026" },
  { file: "Neuroanatomia_Clinica_Visual_Funcional_Patologias_Final.pdf", page: 67, output: "renders/neuroanatomia-067.png", disciplina: "Neurologia", tema: "AVC isquêmico", subtema: "Diagnóstico e conduta", subtemaId: "neuro--avc-isquemico--diagnostico-e-conduta", titulo: "Vascularização cerebral e territórios", diagnostico: "Territórios vasculares cerebrais", modalidade: "Diagrama vascular e TC", fonte: "Neuroanatomia Clínica Visual MED ATLAS 2026" },
  { file: "Neuroanatomia_Clinica_Visual_Funcional_Patologias_Final.pdf", page: 75, output: "renders/neuroanatomia-075.png", disciplina: "Neurologia", tema: "Neuroanatomia clínica", subtema: "Localização neurológica", subtemaId: "neuro--neuroanatomia-clinica--localizacao-neurologica", titulo: "Cápsula interna, corpo caloso e substância branca", diagnostico: "Localização de lesões de substância branca", modalidade: "RM axial", fonte: "Neuroanatomia Clínica Visual MED ATLAS 2026" },
  { file: "Neuroanatomia_Clinica_Visual_Funcional_Patologias_Final.pdf", page: 78, output: "renders/neuroanatomia-078.png", disciplina: "Neurologia", tema: "Neuroanatomia clínica", subtema: "Localização neurológica", subtemaId: "neuro--neuroanatomia-clinica--localizacao-neurologica", titulo: "Via visual e campos visuais", diagnostico: "Lesão das vias visuais", modalidade: "Diagrama e RM", fonte: "Neuroanatomia Clínica Visual MED ATLAS 2026" },
  { file: "Neuroanatomia_Clinica_Visual_Funcional_Patologias_Final.pdf", page: 97, output: "renders/neuroanatomia-097.png", disciplina: "Neurologia", tema: "Neuroanatomia clínica", subtema: "Localização neurológica", subtemaId: "neuro--neuroanatomia-clinica--localizacao-neurologica", titulo: "Neuroimagem para neuroanatomia: cortes sagital e axial", diagnostico: "Correlação anatômica em RM", modalidade: "RM sagital e axial", fonte: "Neuroanatomia Clínica Visual MED ATLAS 2026" },
  { file: "Neuroanatomia_Clinica_Visual_Funcional_Patologias_Final.pdf", page: 99, output: "renders/neuroanatomia-099.png", disciplina: "Neurologia", tema: "Neuroanatomia clínica", subtema: "Localização neurológica", subtemaId: "neuro--neuroanatomia-clinica--localizacao-neurologica", titulo: "Neuroimagem para neuroanatomia: estruturas temporais", diagnostico: "Correlação anatômica em RM", modalidade: "RM sagital e coronal", fonte: "Neuroanatomia Clínica Visual MED ATLAS 2026" },
  { file: "Neuroanatomia_Clinica_Visual_Funcional_Patologias_Final.pdf", page: 101, output: "renders/neuroanatomia-101.png", disciplina: "Neurologia", tema: "Neuroanatomia clínica", subtema: "Localização neurológica", subtemaId: "neuro--neuroanatomia-clinica--localizacao-neurologica", titulo: "Neuroimagem: comparação de cortes", diagnostico: "Correlação anatômica em RM", modalidade: "RM sagital, axial e coronal", fonte: "Neuroanatomia Clínica Visual MED ATLAS 2026" },
  { file: "Neuroanatomia_Clinica_Visual_Funcional_Patologias_Final.pdf", page: 102, output: "renders/neuroanatomia-102.png", disciplina: "Neurologia", tema: "Neuroanatomia clínica", subtema: "Localização neurológica", subtemaId: "neuro--neuroanatomia-clinica--localizacao-neurologica", titulo: "Neuroimagem: estruturas e relações", diagnostico: "Correlação anatômica em RM", modalidade: "RM e esquema anatômico", fonte: "Neuroanatomia Clínica Visual MED ATLAS 2026" },
  { file: "Neuroanatomia_Clinica_Visual_Funcional_Patologias_Final.pdf", page: 103, output: "renders/neuroanatomia-103.png", disciplina: "Neurologia", tema: "Neuroanatomia clínica", subtema: "Localização neurológica", subtemaId: "neuro--neuroanatomia-clinica--localizacao-neurologica", titulo: "Estrutura, função, falha e patologia", diagnostico: "Integração anatômico-clínica", modalidade: "Tabela e neuroimagem", fonte: "Neuroanatomia Clínica Visual MED ATLAS 2026" },
];

const hash = (b: Buffer) => createHash("sha256").update(b).digest("hex");
async function main() {
  const rows = [];
  const pdfHashes = new Map<string, string>();
  for (const d of definitions) {
    const imagePath = resolve(root, d.output);
    const pdfPath = resolve(incoming, d.file);
    const image = await readFile(imagePath);
    const pdf = await readFile(pdfPath);
    const metadata = await sharp(image).metadata();
    const pdfSha = pdfHashes.get(d.file) ?? hash(pdf);
    pdfHashes.set(d.file, pdfSha);
    const s = await stat(imagePath);
    rows.push({ path: d.output, sha256: hash(image), bytes: s.size, width: metadata.width ?? 0, height: metadata.height ?? 0, page: d.page, destination: "private", canonical: true, visual_review: "approved", titulo: d.titulo, disciplina: d.disciplina, tema: d.tema, subtema: d.subtema, subtemaId: d.subtemaId, diagnostico: d.diagnostico, modalidade: d.modalidade, fonte: d.fonte, source_pdf: d.file, source_pdf_sha256: pdfSha, rights_status: "commercial_private", publicRepositoryAllowed: false, observacao: "Página renderizada seletivamente, conferida visualmente em 2026-08-14; manter somente na biblioteca autenticada. O recorte não transfere a licença do PDF nem das fontes nele citadas." });
  }
  await writeFile(out, JSON.stringify({ schemaVersion: 1, generatedAt: new Date().toISOString(), batch: "neuropsiquiatria-completo-20260814", visibility: "private", publicRepositoryAllowed: false, rows }, null, 2), "utf8");
  console.log(JSON.stringify({ out, rows: rows.length, pdfs: [...pdfHashes].map(([file, sha256]) => ({ file, sha256 })) }, null, 2));
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
